const { db, initDb } = require('./src/db');
initDb();

db.prepare('UPDATE modules SET content = ? WHERE id = ?').run(
  'The after action review, also called a post-incident review or lessons learned session, is the phase where incidents generate lasting improvement. Without structured reflection after incidents, organizations repeat the same mistakes and face the same incidents again and again. With it, each incident makes you measurably more secure.\n\nThe after action review should occur within days of an incident being resolved, while details are still fresh. It should include everyone who participated in the response, from the frontline analysts who detected the incident to the executives who made containment decisions. The goal is learning, not blame. A blame-focused review causes people to be defensive and withhold information. A learning-focused review surfaces the real root causes and systemic issues that need to be addressed.\n\nThe review should address a standard set of questions. What happened and when? What was the initial detection method and how long did it take to detect? What was the response timeline and where were the delays? What worked well in the response? What did not work as expected? What was the root cause of the incident? What could have prevented it? What changes would make future detection and response faster and more effective?\n\nRoot cause analysis goes deeper than identifying the immediate cause. A ransomware incident might have been caused immediately by a phishing email, but the root cause might be inadequate security awareness training, the absence of email filtering controls, or a culture where employees are afraid to report suspicious emails. Addressing root causes prevents recurrence. Addressing only immediate causes means the next incident exploits the same underlying weakness through a different vector.\n\nAction items from the review must be specific, assigned to named individuals, and tracked to completion. Vague recommendations like improve security awareness accomplish nothing. Specific action items like schedule quarterly phishing simulation for all staff by end of quarter with results reviewed monthly are actionable and measurable.\n\nMetrics from incidents help quantify improvement over time. Track mean time to detect, mean time to contain, mean time to recover, and total incident cost. Improvements in these metrics across incidents demonstrate that your investments in detection and response capabilities are paying off.\n\nShare lessons learned appropriately. Within your organization, sharing what happened and what you learned helps other teams avoid similar incidents. In some cases, sharing sanitized incident details with peers in your industry or with sector-specific information sharing organizations helps the broader community defend against the same threats.',
  101
);

db.prepare('UPDATE modules SET content = ? WHERE id = ?').run(
  'The AI threat landscape is evolving faster than any previous category of security threat. Capabilities that seemed speculative a few years ago are now in active use by attackers. Staying ahead of evolving AI threats requires continuous learning, adaptable defenses, and organizational practices that do not depend on any single technology or detection capability.\n\nFollow the AI security research community. Organizations like the AI Security Initiative, academic research groups studying adversarial AI, and security vendors publishing threat intelligence on AI-powered attacks all produce valuable information about emerging techniques. Setting up news alerts for AI security topics and following relevant researchers on professional platforms helps you stay current without requiring you to read everything.\n\nFocus on durable defenses rather than AI-specific countermeasures. The specific AI techniques attackers use will change continuously, but the underlying objectives remain constant. Attackers want to manipulate people into taking harmful actions, gain unauthorized access to systems, and exfiltrate valuable data. Defenses that address these objectives directly are more durable than defenses tuned to specific AI-generated content patterns.\n\nVerification procedures are among the most durable defenses against AI-powered social engineering. If your organization requires out-of-band verification for financial transactions, sensitive data requests, and access to critical systems regardless of how the request is delivered, AI-generated impersonation attacks become much less effective. The specific medium of the attack whether voice clone, deepfake video, or AI-generated email matters less when your procedures require verification anyway.\n\nUpdate your mental model of what attacks look like. AI-powered attacks are more polished, more personalized, and more convincing than what most security training historically prepared people for. Security awareness training needs to evolve to reflect that you can no longer rely on poor grammar or implausible scenarios as reliable indicators of phishing or fraud.\n\nInvest in threat intelligence specific to your sector. Attackers tend to develop and test AI-powered attack techniques against specific industries before generalizing them. Financial services organizations see AI fraud techniques before smaller organizations in other sectors. Following threat intelligence relevant to your industry gives you early warning of techniques that may not yet be widely discussed in general security media.\n\nThe goal is not to develop certainty about what is real and what is synthetic because that certainty may not always be achievable. The goal is to build systems, procedures, and habits that produce good security outcomes regardless of whether a specific communication or piece of media is authentic or AI-generated.',
  111
);

const r1 = db.prepare('SELECT LENGTH(content) as len, title FROM modules WHERE id = 101').get();
const r2 = db.prepare('SELECT LENGTH(content) as len, title FROM modules WHERE id = 111').get();
console.log('Module 101:', r1.len, 'chars -', r1.title);
console.log('Module 111:', r2.len, 'chars -', r2.title);
