const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS10(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='AI and Deepfake Threats'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    {
      title: "Module 1: How AI Is Changing the Threat Landscape",
      content: `Artificial intelligence is transforming the threat landscape in ways that make attacks faster, cheaper, more convincing, and more scalable than ever before. Understanding how attackers are using AI helps you recognize AI-powered attacks when you encounter them and defend against them more effectively.

AI makes phishing emails dramatically more convincing. Traditional phishing emails were often identifiable by poor grammar, generic greetings, and implausible scenarios. AI language models can generate phishing emails that are grammatically perfect, contextually appropriate, personalized to the target using publicly available information about them, and indistinguishable in writing quality from legitimate correspondence. The volume of high-quality phishing content that can be generated has increased by orders of magnitude while the skill required to create it has dropped to near zero.

AI enables highly targeted spear phishing at scale. Previously, crafting a convincing personalized phishing email required significant research time, which meant attackers reserved spear phishing for high-value targets. AI can automatically research targets by scraping their social media profiles, company websites, and public records, then generate personalized messages that reference real details about the target's role, colleagues, projects, and interests. This level of personalization can now be applied to thousands of targets simultaneously.

AI-powered vulnerability discovery and exploitation tools can identify weaknesses in software and generate working exploit code faster than human researchers. This compresses the window between vulnerability disclosure and active exploitation, reducing the time organizations have to patch before attacks begin.

AI is also being used defensively. Security tools increasingly use machine learning to detect anomalous behavior, identify malware based on behavioral patterns rather than signatures, and analyze vast volumes of log data to surface meaningful signals. The same capabilities that empower attackers are also being applied to defense.

The fundamental challenge posed by AI is that it removes the skill barrier for many types of attack. Activities that previously required significant expertise and time can now be automated and scaled. Attacks that were previously too expensive or difficult to execute become economically viable. Defense must adapt by focusing less on detecting specific attack patterns, which AI can modify endlessly, and more on behavioral detection and identity verification that is harder to fake even with AI assistance.`,
      category: "AI Threats", difficulty: "beginner", duration_minutes: 10, order_index: 1,
      quiz: [
        { question_text: "How does AI change the traditional indicators used to identify phishing emails?", choice_a: "AI eliminates the grammatical errors, generic greetings, and poor writing quality that were the most commonly taught indicators of phishing, making AI-generated phishing indistinguishable in writing quality from legitimate emails", choice_b: "AI makes phishing emails easier to identify because AI-generated text has a distinctive formal tone that differs from how humans write casual business communications", choice_c: "AI primarily affects the technical delivery of phishing emails by improving spoofing capabilities but does not significantly change the content quality of the messages themselves", correct_choice: "A", explanation: "Grammar and writing quality were never good security controls, but AI removes them completely. Now you cannot rely on spelling errors or awkward phrasing to identify phishing. Focus instead on verifying the sender, the request itself, and using independent confirmation." },
        { question_text: "What capability does AI give attackers when conducting spear phishing attacks at scale?", choice_a: "AI allows attackers to simultaneously generate thousands of highly personalized phishing messages incorporating accurate details about each target gathered automatically from public sources", choice_b: "AI allows attackers to send more emails per hour than human-operated campaigns through faster automation tools", choice_c: "AI gives attackers access to private email databases that were previously difficult to obtain through technical means", correct_choice: "A", explanation: "Traditional phishing was generic. Spear phishing required manual research per target. AI enables personalized spear phishing at mass scale by automatically researching targets from social media and public records and generating individually tailored messages, combining the effectiveness of spear phishing with the volume of mass phishing." },
        { question_text: "Beyond phishing, in what other ways are attackers currently using AI that affect everyday users?", choice_a: "AI is primarily used for offensive purposes in nation-state conflicts and does not significantly affect everyday users at this time", choice_b: "AI is used for voice cloning scams, generating fake customer service personas, creating synthetic social media accounts for influence operations, and generating fraudulent documents and images", choice_c: "AI attacks are limited to financial sector targets and large corporations with significant security budgets to defend against", correct_choice: "B", explanation: "AI-powered attacks affect everyone. Voice cloning scams target individuals with fake family emergency calls. Fake AI customer service personas collect personal information. AI-generated documents and profiles are used in romance scams, job fraud, and social engineering at every level." },
      ],
    },
    {
      title: "Module 2: Understanding Deepfakes",
      content: `Deepfakes are synthetic media in which a person's likeness, voice, or both have been replaced or manipulated using artificial intelligence. The technology has advanced to the point where deepfake videos and audio can be difficult or impossible to distinguish from authentic recordings with the naked eye and ear. Understanding what deepfakes are and how they are used maliciously is the first step in defending against them.

Video deepfakes replace a person's face in a video with someone else's face, or generate entirely synthetic video of a person doing or saying something they never actually did. The technology uses deep learning models trained on large amounts of video footage of the target person. The more footage available, the more convincing the result. Public figures with extensive video archives online are particularly easy to deepfake convincingly.

Audio deepfakes clone a person's voice to generate synthetic speech that sounds like them saying anything the attacker wants. Voice cloning requires relatively little source audio. A few minutes of audio, obtainable from a YouTube video, podcast, or voicemail greeting, can be sufficient to produce convincing voice clones. The resulting synthetic voice can read any text in a way that sounds authentically like the target person.

Real-time deepfakes modify video streams live, allowing a person in a video call to appear as someone else. This capability is increasingly accessible through consumer software. A fraudster conducting a video call while appearing to be a legitimate executive or job candidate is a real and growing threat.

The malicious applications of deepfakes span financial fraud, disinformation, reputation attacks, and social engineering. Financial fraud using executive voice clones has already resulted in significant losses at multiple organizations. Deepfake videos of public figures making inflammatory statements have been used to spread disinformation. Synthetic intimate imagery created without consent is used for harassment and extortion.

The social and organizational harms of deepfakes extend beyond the immediate victims of specific attacks. The existence of convincing synthetic media erodes trust in authentic recordings. When people know that any video or audio could be fake, the evidentiary value of genuine recordings diminishes. This erosion of trust in media is itself a harm that benefits bad actors.`,
      category: "Deepfakes", difficulty: "beginner", duration_minutes: 10, order_index: 2,
      quiz: [
        { question_text: "What is a deepfake and what makes current deepfake technology particularly concerning?", choice_a: "A type of malware disguised as legitimate software, concerning because it bypasses antivirus detection through polymorphic code", choice_b: "Synthetic audio or video where AI generates or replaces a real person's likeness and voice, concerning because quality has reached a point where many people cannot distinguish deepfakes from real content", choice_c: "Manipulated images created using traditional photo editing software available to anyone with basic skills", correct_choice: "B", explanation: "Deepfakes use machine learning to generate convincing synthetic media. The concern is not just that they exist but that quality has improved to the point where average viewers cannot reliably detect them, enabling impersonation, fraud, and disinformation that people are not equipped to question." },
        { question_text: "Which of the following represents a real-world threat from deepfake technology that has already caused harm?", choice_a: "Deepfakes are only a theoretical threat in political contexts where public figures might be impersonated in future elections", choice_b: "A finance employee receives a video call appearing to show their CFO instructing them to transfer funds, with the appearance and voice perfectly replicated using AI", choice_c: "Deepfakes can only be used to impersonate celebrities not ordinary employees or executives in organizational settings", correct_choice: "B", explanation: "Business-targeted deepfake fraud has already resulted in organizations losing millions of dollars. Attackers use video calls where AI generates a real-time fake of a company executive to authorize fraudulent financial transfers. This requires very little source material of the target to execute." },
        { question_text: "How much video or audio of a person does an attacker typically need to create a convincing voice or video deepfake?", choice_a: "Many hours of high-quality studio recordings are required to produce convincing results that could fool a careful listener", choice_b: "Modern AI voice cloning can produce convincing results from as little as a few seconds to a few minutes of audio, and video deepfakes require modest amounts of publicly available footage", choice_c: "Deepfakes require direct cooperation from the target who must provide recordings in a controlled environment", correct_choice: "B", explanation: "This is one of the most alarming aspects of the technology. Social media posts, interview clips, voicemails, and conference recordings provide all the material an attacker needs. Anyone with a public digital presence has likely provided enough material for a deepfake to be created." },
      ],
    },
    {
      title: "Module 3: Detecting Deepfakes",
      content: `Detecting deepfakes is an ongoing technical challenge because the technology used to create them and the technology used to detect them are locked in a continuous arms race. Detection methods that work today may be defeated by improved generation techniques tomorrow. Understanding current detection approaches while maintaining realistic expectations about their limitations is important for anyone who needs to evaluate potentially synthetic media.

Visual artifacts are the starting point for deepfake detection. Current deepfake generation technology has consistent weaknesses that manifest as visual anomalies. Watch for unnatural blinking patterns or eyes that do not blink at all. Look for inconsistencies around the hairline and face edges where the face replacement meets the background. Examine lighting and shadows on the face, which may not match the lighting in the rest of the scene. Watch for unusual skin texture that looks unnaturally smooth or exhibits strange artifacts when the subject moves. Look at teeth, ears, and jewelry which deepfake models frequently render imperfectly.

Audio artifacts in voice clones include unnatural prosody where the rhythm and emphasis of speech sounds slightly off, inconsistent breathing patterns, background noise that does not match the setting, and subtle digital artifacts particularly in consonant sounds. Comparing a suspected voice clone to known authentic recordings of the same person can help identify subtle differences in speaking style.

Contextual verification is often more reliable than technical detection. Rather than trying to determine whether a video is authentic, verify the claim the video is making through independent channels. If a video purports to show your CEO making a statement, verify with the CEO through a separate communication channel before acting on it. If a video makes an extraordinary claim about a public figure, check whether credible news organizations are reporting the same information.

Automated deepfake detection tools analyze media for statistical patterns associated with AI generation. These tools can process video at scale but are imperfect and are frequently defeated by improved generation techniques. They are most useful as one signal among many rather than as a definitive detector.

The most reliable defense against deepfake-enabled attacks is not technical detection but procedural verification. Establish verification protocols for high-stakes communications and transactions that do not rely solely on the authenticity of audio or video. Out-of-band verification, pre-established code words, and multi-person approval requirements for significant decisions all reduce the effectiveness of deepfake social engineering regardless of how convincing the synthetic media becomes.`,
      category: "Deepfakes", difficulty: "intermediate", duration_minutes: 10, order_index: 3,
      quiz: [
        { question_text: "What visual artifacts have historically indicated deepfake video, though these are becoming less reliable as technology improves?", choice_a: "Unnatural blinking patterns, facial boundary blurring, inconsistent lighting on the face, and unusual rendering artifacts around teeth, ears, and hair", choice_b: "Deepfake videos always have a visible watermark that identifies them as AI generated by the creation tool", choice_c: "Deepfake videos always have audio that does not match the lip movements because synchronization is technically impossible", correct_choice: "A", explanation: "Early deepfakes had obvious tells including blinking issues, facial boundary artifacts, and lighting inconsistencies. These are becoming harder to spot as quality improves. Do not rely on visual artifacts as your primary deepfake detection method since the technology improves faster than human perception." },
        { question_text: "What is the most reliable way to verify the identity of someone making an unexpected request via video call?", choice_a: "Ask them to smile or perform a specific spontaneous gesture since deepfakes cannot replicate unexpected movements in real time", choice_b: "End the call and contact the person through a completely separate channel using contact information you already have to confirm whether they actually made the request", choice_c: "Ask them a personal question that only the real person would know the answer to since AI cannot access private information", correct_choice: "B", explanation: "Hanging up and calling back through a trusted number you already have is the only reliable verification method. Live deepfakes can respond to prompts and answer questions using AI. The only defense is multi-channel verification using a contact method completely independent of the suspicious call." },
        { question_text: "What technical tool can organizations use to verify the integrity of video content at scale?", choice_a: "Automated deepfake detection software that analyzes video for statistical patterns associated with AI generation, used as one signal among multiple verification methods rather than a definitive detector", choice_b: "Blockchain-based video authentication that creates an unalterable record of the original video at creation time making any modification detectable", choice_c: "Watermarking tools that embed invisible identifiers at capture time that cannot be removed during deepfake generation", correct_choice: "A", explanation: "Automated detection tools are useful but imperfect and are frequently defeated by improved generation techniques. They should be one layer of a defense-in-depth approach that also includes procedural verification. No automated tool should be treated as definitive given the ongoing arms race." },
      ],
    },
    {
      title: "Module 4: AI-Powered Voice Cloning Scams",
      content: `AI-powered voice cloning scams represent one of the most emotionally manipulative forms of fraud. When you hear what sounds like the voice of someone you trust urgently asking for help, your instinct is to respond immediately. Scammers are exploiting this instinct using synthetic voices that are increasingly indistinguishable from real ones.

The grandparent scam has been updated with voice cloning technology. Traditional versions involved a scammer calling an elderly person and claiming to be their grandchild in trouble and needing money urgently. With voice cloning, the scammer can call using a synthetic version of the grandchild's actual voice, making the deception far more convincing. Similar attacks target parents, siblings, and spouses using cloned voices of their family members.

Executive fraud using voice clones has resulted in significant financial losses at organizations. In documented cases, employees received calls from what they believed to be their CEO or CFO instructing them to wire money urgently for a sensitive business reason. The voice was a clone generated from audio of the real executive available in public speeches, interviews, or earnings calls. Employees who trusted their ears followed the instructions and transferred funds before discovering the fraud.

The attack workflow is straightforward. The attacker finds audio of the target person online, which is widely available for anyone who has ever appeared in a podcast, video, interview, or voicemail greeting. They feed this audio into a voice cloning service, which generates a synthetic voice model. They then use that model to generate any audio they want the target person to appear to say. The call is placed with the synthetic voice delivering the scripted message.

Protection against voice cloning scams relies on verification procedures rather than trying to detect synthetic voices in real time. Establish a family code word that anyone claiming to be a family member in distress must provide before you send money. Organizations should require out-of-band verification for any financial request received by phone regardless of who the caller claims to be. Never send money based solely on a phone call regardless of how familiar the voice sounds.

Caller ID spoofing frequently accompanies voice cloning attacks, making the call appear to come from the genuine person's phone number. A familiar voice calling from a familiar number is the combination attackers use to overcome skepticism. Both elements can be faked.`,
      category: "Voice Cloning", difficulty: "intermediate", duration_minutes: 10, order_index: 4,
      quiz: [
        { question_text: "How does an AI voice cloning emergency scam typically work to manipulate victims?", choice_a: "The attacker clones the voice of a family member or trusted person using publicly available audio, then calls the target using that synthetic voice claiming the person is in distress and needs immediate financial help, exploiting emotional urgency to bypass critical thinking", choice_b: "The attacker sends a deepfake video of the family member rather than using voice cloning because video is significantly more convincing than audio alone for creating a sense of emergency", choice_c: "The attacker uses the cloned voice only to initiate contact and then transfers to a human operator to conduct the actual social engineering because AI cannot handle unexpected questions", correct_choice: "A", explanation: "The combination of a familiar voice and an emergency scenario is designed to trigger an emotional response that bypasses rational evaluation. The urgency prevents the target from taking time to verify. The familiar voice provides the credibility needed to make the scenario believable." },
        { question_text: "What organizational control specifically protects against voice clone fraud targeting employees?", choice_a: "Establishing pre-agreed verbal code words for high-stakes requests that the requester must provide before any sensitive action is taken, verifying identity regardless of how convincing the voice sounds", choice_b: "Training employees to analyze voice quality during calls and identify subtle artifacts that indicate synthetic speech rather than a real human voice", choice_c: "Requiring all financial requests to be submitted through an official ticketing system rather than by phone so voice-based requests are structurally excluded", correct_choice: "A", explanation: "Code words work because they are known only to the parties involved and cannot be derived from public audio of the target person. A voice clone can sound exactly like the real person but cannot know a privately agreed word. This control defeats voice clone fraud regardless of the sophistication of the synthesis." },
        { question_text: "Why is urgency a particularly effective element when combined with voice cloning in fraud attacks?", choice_a: "Urgency gives the target a justifiable reason to bypass normal verification procedures because time pressure makes verification appear impractical, while the familiar voice provides the credibility to make the urgency seem legitimate", choice_b: "Urgency is effective because it causes targets to focus on the technical details of the request rather than on whether the caller is who they claim to be", choice_c: "Urgency works because most organizations have policies allowing employees to skip approval processes in genuine emergencies, and attackers exploit these legitimate policy exceptions", correct_choice: "A", explanation: "Urgency and credibility working together is the core mechanism of voice clone fraud. The cloned familiar voice establishes credibility. The urgency scenario provides justification for bypassing verification. Each element amplifies the other. The defense is verification procedures that cannot be bypassed regardless of urgency." },
      ],
    },
    {
      title: "Module 5: AI-Generated Disinformation",
      content: `AI-generated disinformation uses artificial intelligence to create and distribute false or misleading information at a scale and speed that human-created disinformation cannot match. Understanding how AI is used to spread disinformation helps you evaluate the information you consume more critically and recognize manipulation when you encounter it.

AI language models can generate realistic-sounding news articles, social media posts, forum comments, product reviews, and other content types indistinguishably from human-written equivalents. This content can be produced in massive quantities, targeted to specific audiences, and distributed through networks of fake accounts with minimal human effort. The economic barrier to conducting large-scale disinformation campaigns has dropped dramatically.

Synthetic personas are AI-generated social media accounts with fake profile photos, consistent posting histories, and realistic engagement patterns. These accounts can be used to amplify specific narratives, create the appearance of grassroots support for positions or products, and manipulate trending algorithms to increase the visibility of disinformation. Detecting synthetic personas requires analyzing behavioral patterns over time rather than just examining individual posts.

Deepfake videos and audio are used in disinformation campaigns to create false records of things that never happened. Synthetic video of a political figure making a controversial statement, of a corporate executive announcing false information, or of an event that did not occur can spread rapidly before being debunked, and the debunking typically reaches far fewer people than the original false content.

Information verification has become a critical skill. When you encounter surprising or emotionally provocative information, slow down before sharing it. Check whether credible independent sources are reporting the same information. Reverse image search photographs to check whether they are authentic. Look for the original context of quotes. Consider whether the information is designed to provoke an emotional reaction, since emotional content is more likely to be shared without verification.

Prebunking, explaining how disinformation techniques work before people encounter specific examples, has been shown to be more effective than debunking after people have already been exposed to false content. Understanding that AI can generate convincing fake quotes, images, and videos makes you more likely to verify before accepting or sharing.`,
      category: "Disinformation", difficulty: "intermediate", duration_minutes: 10, order_index: 5,
      quiz: [
        { question_text: "What makes AI-generated disinformation more dangerous than traditional human-created disinformation?", choice_a: "AI enables the creation and distribution of high-quality false content at a scale, speed, and personalization level that human-created disinformation cannot match, dramatically lowering the cost and skill required", choice_b: "AI-generated disinformation is more dangerous because AI can target specific individuals with personalized false content while traditional disinformation only works at a population level", choice_c: "AI makes disinformation more dangerous primarily because it can generate false content in any language simultaneously enabling unprecedented cross-border influence operations", correct_choice: "A", explanation: "Scale and accessibility are the key changes. Large-scale disinformation campaigns previously required significant resources and infrastructure. AI makes them accessible to anyone with basic technical knowledge. The volume of plausible-sounding false content that can now be generated far exceeds human capacity to verify and debunk it." },
        { question_text: "How should you approach viral content that triggers a strong emotional reaction before deciding to share it?", choice_a: "Verify the content through independent credible sources before sharing, recognizing that emotionally provocative content is specifically designed to spread before people have time to verify it", choice_b: "Share the content immediately if you agree with its message because delaying sharing reduces its reach and impact on public discourse", choice_c: "Report the content to the platform's moderation team and wait for their determination before forming any opinion about its authenticity", correct_choice: "A", explanation: "Emotional provocation is a feature of disinformation design. Content that makes you angry, afraid, or excited spreads faster because people share before thinking. The verification step is deliberately bypassed by the emotional response. Slowing down to verify breaks the disinformation distribution mechanism." },
        { question_text: "What is a synthetic social media persona and how is it used in disinformation campaigns?", choice_a: "An AI-generated social media account with a fake profile photo, consistent posting history, and realistic engagement patterns used to amplify specific narratives and create false impressions of grassroots support", choice_b: "A real person's social media account that has been compromised and repurposed by attackers to spread disinformation using the original account's established follower base", choice_c: "A parody account that clearly identifies itself as satirical but uses realistic presentation to comment on current events in ways that may be mistaken for genuine reporting", correct_choice: "A", explanation: "Synthetic personas create the appearance of organic support for specific narratives. Networks of these accounts can make fringe positions appear mainstream, amplify specific content to trending status, and manufacture the social proof that makes people more likely to accept false information as credible." },
      ],
    },
    {
      title: "Module 6: AI in Social Engineering",
      content: `AI has dramatically lowered the barrier to conducting sophisticated social engineering attacks. Capabilities that previously required skilled human operators, significant research time, and expensive resources are now accessible to anyone through AI tools. Understanding how AI amplifies social engineering helps you recognize attacks that may be more polished and convincing than anything you have encountered before.

Automated reconnaissance uses AI to rapidly gather and synthesize information about targets from public sources. Social media profiles, company websites, press releases, LinkedIn profiles, and public records can be scraped and analyzed to build detailed target profiles in minutes. This profile informs the social engineering attack with accurate personal details that make the attacker appear knowledgeable and trustworthy.

AI-generated pretexts are more convincing than human-crafted ones because they can incorporate target-specific details naturally. An AI-generated spear phishing email might reference the target's recent conference attendance, their team's current project, their manager's name, and a plausible business scenario specific to their role, all derived from public information. The combination of these accurate details makes the email feel like it comes from someone who genuinely knows the target.

Conversational AI enables attackers to conduct extended interactions through chat, email, or messaging that remain convincing over time. A human social engineer might make mistakes in extended correspondence that reveal the deception. An AI can maintain consistent personas, remember previous parts of a conversation, and generate contextually appropriate responses indefinitely.

AI voice agents can conduct real-time phone conversations using synthetic voices. These agents can answer questions, respond to objections, and maintain a convincing conversation with targets who might detect inconsistencies that would expose a recorded message. Combining a cloned familiar voice with a conversational AI creates a highly effective vishing tool.

The defenses against AI-powered social engineering are the same as for traditional social engineering but need to be applied more consistently because AI-powered attacks are more convincing. Verify all unexpected requests through independent channels. Be suspicious of urgency regardless of how credible the source seems. Establish verification procedures for sensitive actions that cannot be bypassed even when requests seem legitimate.`,
      category: "Social Engineering", difficulty: "intermediate", duration_minutes: 10, order_index: 6,
      quiz: [
        { question_text: "How does AI change the research phase of a social engineering attack?", choice_a: "AI can automatically gather and synthesize information about targets from public sources in minutes, building detailed profiles that previously required hours of manual research and enabling personalized attacks at any scale", choice_b: "AI enables attackers to access private databases and internal systems to gather target information without the manual hacking that was previously required for detailed reconnaissance", choice_c: "AI changes social engineering research primarily by improving the quality of publicly available information about targets rather than changing how quickly that information can be gathered", correct_choice: "A", explanation: "Speed and scale of reconnaissance is the key change. A human researcher might spend hours profiling one target. AI can profile thousands simultaneously using publicly available information. This makes sophisticated personalized attacks economically viable at scales that were previously impractical." },
        { question_text: "What is a chatbot-based social engineering attack and how does it work against targets?", choice_a: "A conversational AI poses as a customer service representative, technical support agent, or other trusted persona to build rapport with targets over extended interactions and eventually extract sensitive information or manipulate them into harmful actions", choice_b: "A chatbot attack automatically generates phishing emails by having an AI converse with itself to produce increasingly convincing message templates for human attackers to send", choice_c: "A chatbot attack is a denial of service technique that floods customer service chatbots with automated messages to prevent legitimate customers from receiving support", correct_choice: "A", explanation: "AI-powered conversational attacks can maintain consistent personas through extended interactions that would expose human social engineers. They can answer questions, handle objections, and remember previous conversation context indefinitely. The target may never suspect they are communicating with an automated system." },
        { question_text: "What remains the most effective defense against AI-enhanced social engineering attacks regardless of the specific technology used?", choice_a: "Verification procedures that require independent confirmation of identity and authorization for sensitive actions, applied consistently regardless of how convincing the request seems or what medium it arrives through", choice_b: "AI-powered social engineering detection tools that analyze communication patterns and flag messages likely to be AI-generated before they reach potential targets", choice_c: "Restricting all employee communications to official monitored channels that are filtered by security tools preventing attackers from reaching employees through unofficial contact methods", correct_choice: "A", explanation: "Procedural verification is attacker-agnostic. It works regardless of whether the attack uses a human social engineer, a voice clone, a deepfake video, or an AI chatbot. The specific technology used becomes irrelevant when the procedure requires independent verification that cannot be satisfied by the attack itself." },
      ],
    },
    {
      title: "Module 7: Protecting Yourself From AI Scams",
      content: `AI has dramatically expanded the toolkit available to scammers, but the fundamental defenses remain the same as they have always been. The difference is that these defenses now need to be applied more consistently because AI-powered attacks are more convincing than what most people have encountered before.

Your public social media presence provides attackers with the raw material for personalized attacks. Voice recordings from videos enable cloning. Personal details enable personalization. Photos enable deepfake generation. Family relationships, workplace information, and life events all appear in social media profiles and are used to craft convincing scenarios. Privacy settings that limit your public exposure directly reduce the materials available for AI-powered attacks targeting you.

Family code words are one of the most effective low-tech defenses against voice cloning scams. Establish a word or phrase with your family that anyone claiming to be in distress must provide before you take any financial action. This defeats voice cloning regardless of how convincing the synthetic voice sounds because the code word cannot be derived from any public recording of the real person.

Slow down when requests feel urgent. Urgency is the primary manipulation mechanism in AI-powered social engineering. The pressure to act now before verifying is specifically engineered to prevent you from thinking critically. A genuine emergency will survive a brief delay while you call the person back through a trusted number. A scam cannot survive independent verification, which is why it depends on urgency to prevent it.

Verify through independent channels. When you receive a request for money, sensitive information, or access credentials through any channel including phone, email, video call, or text message, verify through a channel you already trust that is completely independent of the suspicious communication. Call the person on their actual phone number. Walk to their office. Use a previously established secure channel. Never verify by calling a number provided in the suspicious communication itself.

Understand that technical detection is not reliable. You cannot trust your ears or eyes to identify synthetic media. The technology improves faster than human perception can keep up. Your protection comes from processes and habits that produce good outcomes regardless of how convincing the attack appears, not from your ability to spot the fakes.`,
      category: "Personal Protection", difficulty: "beginner", duration_minutes: 10, order_index: 7,
      quiz: [
        { question_text: "How does your public social media presence affect your risk from AI-powered scams targeting you personally?", choice_a: "Public social media provides attackers with the audio, video, and personal information needed to create convincing voice clones, deepfakes, and highly personalized social engineering attacks targeting you or people close to you", choice_b: "Public social media presence has no meaningful impact on AI scam risk because attackers use data broker databases rather than social media for target research", choice_c: "Public social media increases scam risk only for public figures with large followings because attackers only target people whose compromise would generate significant attention", correct_choice: "A", explanation: "Anyone with a public social presence has generated sufficient raw material for AI-powered attacks. Voice recordings from videos enable cloning. Personal details enable personalization. Photos enable deepfake generation. Privacy settings that limit public exposure directly reduce the materials available for these attacks." },
        { question_text: "What is a family safe word and how does it protect against AI voice cloning scams?", choice_a: "A pre-agreed code word that any family member claiming to be in distress must provide to verify their identity, defeating voice cloning attacks because the code word cannot be derived from public recordings of the real person", choice_b: "A password used to access family accounts on shared devices protecting against account takeover attacks rather than voice cloning", choice_c: "A verbal trigger that activates a predetermined response protocol protecting against social engineering by ensuring family members respond consistently", correct_choice: "A", explanation: "Code words work because they are private information that is not in any recording, public document, or database that an attacker could access. A voice clone sounds exactly like the real person but cannot know a privately agreed word. The code word converts identity verification from a voice recognition problem to an information verification problem." },
        { question_text: "Why is it important to verify AI-related claims and content through multiple independent sources before acting or sharing?", choice_a: "AI can generate convincing false content including fake news articles, fabricated quotes, synthetic images, and misleading statistics, making independent verification essential before acting on or sharing any information that has significant consequences", choice_b: "Independent verification of AI content is important primarily for technical claims about AI capabilities because non-technical people may misunderstand AI limitations", choice_c: "Verifying AI-related content through multiple sources is only necessary for content that will be published or presented professionally because personal information consumption does not require the same rigor", correct_choice: "A", explanation: "The ease of generating convincing false content means that a single source is insufficient verification for any consequential information. Multiple independent credible sources that have separately verified information provide meaningful confirmation. A single viral post, regardless of how professional it appears, could be entirely AI-generated." },
      ],
    },
    {
      title: "Module 8: AI and Fraud Detection",
      content: `AI fraud detection systems are used by financial institutions, e-commerce platforms, and other organizations to identify fraudulent transactions and activities in real time. Understanding how these systems work helps you understand why certain legitimate activities trigger fraud alerts and why certain fraudulent activities sometimes get through.

Traditional fraud detection relied on rule-based systems that flagged transactions meeting specific criteria like transactions above a certain amount, transactions in foreign countries, or multiple transactions in rapid succession. These rules were effective against known fraud patterns but easily defeated by attackers who learned the rules and structured their activities to avoid triggering them.

Machine learning fraud detection analyzes patterns across millions of transactions to build models of what legitimate behavior looks like for each individual user and account. When a transaction deviates significantly from established patterns, the model flags it for review or blocks it automatically. This behavioral approach is much harder to defeat because it is personalized to each account rather than based on global rules.

Behavioral biometrics analyze how users interact with devices and applications rather than just what they do. Typing rhythm, mouse movement patterns, how a person holds their phone, and how they scroll through an application all create a behavioral signature that is difficult to replicate. Fraud detection systems that incorporate behavioral biometrics can identify account takeovers even when the attacker has valid credentials.

AI is used on the attacker side as well, creating an arms race in fraud detection. Fraud rings use AI to analyze which transaction patterns get through detection systems and optimize their attacks to stay within those patterns. They use AI to generate synthetic identities for account creation and to automate the testing of stolen credentials at scale.

You can support fraud detection systems by notifying your financial institutions promptly when your behavior is going to change. If you are traveling internationally, alert your bank. If you are making an unusually large purchase, be prepared to verify it through the bank's authentication channel. These communications help fraud detection systems calibrate their models and reduce both false positives that block your legitimate transactions and false negatives that allow fraudulent ones.`,
      category: "Fraud Detection", difficulty: "intermediate", duration_minutes: 10, order_index: 8,
      quiz: [
        { question_text: "How do banks use AI to detect fraudulent transactions more effectively than traditional rule-based systems?", choice_a: "AI builds behavioral models of normal transaction patterns for each individual account and flags transactions that deviate significantly from established patterns, enabling detection of fraud even when the attacker has valid credentials", choice_b: "Banks use AI exclusively to verify that customers are physically present at ATMs through facial recognition preventing card skimming attacks at automated terminals", choice_c: "Banks use AI to analyze the language of online communications with customers to detect scam victims who may be being coached by fraudsters to authorize transactions", correct_choice: "A", explanation: "Behavioral modeling is what makes modern fraud detection effective against sophisticated attacks. Rule-based systems that blocked transactions above certain amounts were easily defeated by attackers who understood the rules. Behavioral models are personalized to each account and harder to predict and evade." },
        { question_text: "What is the limitation of AI-based deepfake detection tools that organizations should understand when deploying them?", choice_a: "AI deepfake detection tools are expensive and slow requiring dedicated hardware that only large organizations with significant security budgets can afford to deploy at scale", choice_b: "AI deepfake detection tools can only analyze video and cannot process audio deepfakes leaving voice clone attacks completely undetected by these systems", choice_c: "AI deepfake detection tools are frequently defeated by improved generation techniques and should be used as one signal among multiple verification methods rather than as a definitive detector", correct_choice: "C", explanation: "Detection and generation are in an arms race. Improved generation techniques specifically target and defeat known detection methods. A detection tool effective today may be easily bypassed by next-generation synthesis. Relying solely on automated detection creates a single point of failure that will eventually be defeated." },
        { question_text: "Why should you respond to a bank's fraud alert system even when the flagged transaction seems like a false positive?", choice_a: "Responding to fraud alerts, even false positives, helps the AI system learn your legitimate behavior patterns and improve future accuracy for your specific account", choice_b: "Banks legally require acknowledgment of all fraud alerts within a specified timeframe and failure to respond may result in account restrictions", choice_c: "Not responding to fraud alerts automatically freezes your account for security reasons until you call the bank directly to confirm each flagged transaction", correct_choice: "A", explanation: "Your responses to fraud alerts are training data for your behavioral model. Confirming legitimate transactions and reporting fraudulent ones both improve the model's accuracy for your specific patterns. An uncalibrated model generates more false positives that block legitimate transactions." },
      ],
    },
    {
      title: "Module 9: Legal and Ethical Issues Around AI and Deepfakes",
      content: `The rapid advancement of AI and deepfake technology has outpaced the legal and ethical frameworks designed to govern it. Understanding the current legal landscape and ethical debates helps you navigate the use of AI tools responsibly and understand your rights when AI is used against you.

Consent is the central legal issue in most AI and deepfake contexts. Creating a realistic likeness of a real person without their consent is the foundation of most deepfake harms. Many jurisdictions have enacted or are developing laws specifically addressing non-consensual intimate deepfakes, which criminalize the creation and distribution of synthetic explicit imagery of real people without consent. Some jurisdictions have broader laws against using someone's likeness without consent for commercial purposes.

Defamation law applies to deepfakes that falsely portray real people doing or saying harmful things. A deepfake video that portrays a real person committing a crime they did not commit could constitute defamation. However, proving defamation requires establishing that the content is false, that it was published to third parties, that it caused harm, and in many jurisdictions that the creator acted with the requisite level of fault. The anonymity of internet distribution often makes identifying and holding creators accountable difficult.

Electoral integrity laws in many jurisdictions address the use of synthetic media in political campaigns. Using deepfakes to impersonate candidates or create false representations of their statements is either explicitly illegal or may constitute election interference under existing laws. Disclosure requirements for AI-generated political advertising are being enacted in multiple jurisdictions.

Intellectual property questions arise around training data and generated content. AI models trained on copyrighted material without licensing raise copyright infringement questions that courts are actively working through. The ownership of AI-generated content is unsettled in most jurisdictions. Using AI tools to generate content that closely mimics a specific artist's style raises both legal and ethical questions.

Ethically, the use of AI to create realistic synthetic media of real people without consent violates their autonomy and dignity even in cases that may not be clearly illegal. The potential for harm from synthetic media of real people is significant, and the ethical standard of obtaining consent before creating realistic representations of others should guide decisions even in legal gray areas.`,
      category: "AI Ethics", difficulty: "intermediate", duration_minutes: 10, order_index: 9,
      quiz: [
        { question_text: "What legal issues can arise when someone creates and distributes a deepfake of a real person without their consent?", choice_a: "Depending on jurisdiction and use, deepfakes can violate laws around defamation, fraud, non-consensual intimate imagery, and election interference, with criminal penalties applying in some cases", choice_b: "Deepfakes are protected as free speech in all jurisdictions regardless of content or context because they constitute a form of creative expression", choice_c: "Deepfakes only become illegal if the subject of the deepfake files a formal complaint within a specific timeframe after discovering the content", correct_choice: "A", explanation: "Legal frameworks for deepfakes are developing rapidly. Non-consensual intimate deepfakes are criminalized in a growing number of jurisdictions. Deepfakes used for financial fraud are covered by existing fraud laws. Defamatory deepfakes can support civil liability. Election-related deepfakes face specific prohibitions in some regions." },
        { question_text: "Why are content creators who use AI to generate realistic fake quotes attributed to real public figures creating legal and ethical risks?", choice_a: "Using AI tools for content creation is currently prohibited under most platform terms of service creating contractual liability for content creators", choice_b: "Fabricated quotes attributed to real people can constitute defamation if they damage reputation, and election-related fake quotes may violate specific electoral laws", choice_c: "AI-generated quotes are legal as long as they are clearly labeled as fictional in a disclaimer somewhere in the content", correct_choice: "B", explanation: "A disclaimer at the bottom of content does not prevent the fabricated quote from spreading without context. Realistic fake quotes attributed to real people spread as real quotes. When they damage someone's reputation or spread false information about their positions, they may meet the legal threshold for defamation." },
        { question_text: "What responsibility do organizations have regarding the ethical use of AI in their products and services?", choice_a: "Organizations should establish clear policies governing AI use, ensure transparency when AI is used in consequential decisions, and consider the potential for bias and harm in AI outputs before deploying them", choice_b: "Organizations have no ethical obligations beyond meeting current legal requirements for AI use because AI tools are simply software like any other business tool", choice_c: "Ethical AI use is solely a concern for AI developers not for organizations that purchase and deploy third-party AI products in their operations", correct_choice: "A", explanation: "Organizations deploying AI are responsible for how it affects people. This includes assessing misuse potential, auditing for discriminatory outcomes, and being transparent with users about AI use. Regulatory frameworks including the EU AI Act are formalizing these obligations into legal requirements." },
      ],
    },
    {
      title: "Module 10: Staying Ahead of Evolving AI Threats",
      content: `The AI threat landscape is evolving faster than any previous category of security threat. Capabilities that seemed speculative a few years ago are now in active use by attackers. Staying ahead of evolving AI threats requires continuous learning, adaptable defenses, and organizational practices that do not depend on any single technology or detection capability.

Follow the AI security research community. Organizations like the AI Security Initiative, academic research groups studying adversarial AI, and security vendors publishing threat intelligence on AI-powered attacks all produce valuable information about emerging techniques. Setting up news alerts for AI security topics and following relevant researchers on professional platforms helps you stay current without requiring you to read everything.

Focus on durable defenses rather than AI-specific countermeasures. The specific AI techniques attackers use will change continuously, but the underlying objectives remain constant. Attackers want to manipulate people into taking harmful actions, gain unauthorized access to systems, and exfiltrate valuable data. Defenses that address these objectives directly are more durable than defenses tuned to specific AI-generated content patterns.

Verification procedures are among the most durable defenses against AI-powered social engineering. If your organization requires out-of-band verification for financial transactions, sensitive data requests, and access to critical systems regardless of how the request is delivered, AI-generated impersonation attacks become much less effective. The specific medium of the attack whether voice clone, deepfake video, or AI-generated email matters less when your procedures require verification anyway.

Update your mental model of what attacks look like. AI-powered attacks are more polished, more personalized, and more convincing than what most security training historically prepared people for. Security awareness training needs to evolve to reflect that you can no longer rely on poor grammar or implausible scenarios as reliable indicators of phishing or fraud.

Invest in threat intelligence specific to your sector. Attackers tend to develop and test AI-powered attack techniques against specific industries before generalizing them. Financial services organizations see AI fraud techniques before smaller organizations in other sectors. Following threat intelligence relevant to your industry gives you early warning of techniques that may not yet be widely discussed in general security media.

The goal is not to develop certainty about what is real and what is synthetic, because that certainty may not always be achievable. The goal is to build systems, procedures, and habits that produce good security outcomes regardless of whether a specific communication or piece of media is authentic or AI-generated.`,
      category: "Personal Protection", difficulty: "beginner", duration_minutes: 8, order_index: 10,
      quiz: [
        { question_text: "What habit provides durable protection against AI-powered attacks even as the specific techniques continue to evolve?", choice_a: "Requiring independent verification through trusted channels for any request involving money, access to sensitive systems, or sensitive information, applied consistently regardless of how convincing the request appears", choice_b: "Installing the latest AI detection software on every device you own to identify synthetic content before acting on it", choice_c: "Avoiding all digital communication in favor of in-person interactions for all sensitive discussions to eliminate the attack surface entirely", correct_choice: "A", explanation: "Specific attack techniques change but verification does not. Hanging up and calling back, walking to a colleague's desk, or checking through a known trusted channel defeats social engineering regardless of whether it uses AI voice cloning, deepfake video, or traditional phone impersonation." },
        { question_text: "How should you approach a request that feels emotionally urgent and comes from someone who appears to be a person you trust?", choice_a: "Recognize that urgency combined with a trusted identity is a classic manipulation pattern and slow down to verify through an independent channel before taking any action regardless of the pressure", choice_b: "Act immediately since trusted contacts would only reach out urgently for genuine reasons that require fast responses without verification delays", choice_c: "Decline all urgent requests as a blanket policy since legitimate requests can always wait for standard verification procedures to complete", correct_choice: "A", explanation: "Urgency plus apparent trust is the core formula for AI-enhanced social engineering attacks including voice cloning emergency scams and deepfake executive fraud. Training yourself to slow down when these two elements appear together breaks the manipulation pattern regardless of the specific attack technique." },
        { question_text: "What is the most useful mindset shift for staying protected as AI attack capabilities continue to improve?", choice_a: "Shift from trusting content quality as a safety signal to trusting verification processes, since AI has made content quality an unreliable indicator of authenticity", choice_b: "Assume that any digital communication could be fabricated and refuse to act on any information received digitally as a blanket policy", choice_c: "Trust only communications that use end-to-end encryption since AI cannot intercept properly encrypted messages regardless of sophistication", correct_choice: "A", explanation: "Content used to signal trustworthiness through quality indicators like correct grammar, familiar voices, and professional appearance. AI has neutralized all of these as reliable signals. The reliable indicator is now the verification process. Did you confirm this through a trusted independent channel? That is the new quality check." },
      ],
    },
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS10 };
