const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS10(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='AI and Deepfake Threats'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    {
      title: "Module 1: How AI Is Changing the Threat Landscape",
      content: "Artificial intelligence is being used by attackers to automate, personalize, and scale attacks that previously required significant time and skill. Understanding how AI changes the threat landscape helps you recognize attacks that no longer carry the traditional warning signs.",
      category: "AI Threats", difficulty: "beginner", duration_minutes: 10, order_index: 1,
      quiz: [
        { question_text: "How does AI change the traditional indicators used to identify phishing emails?", choice_a: "AI makes phishing emails easier to spot because they are more formulaic", choice_b: "AI removes the grammatical errors, awkward phrasing, and generic greetings that previously helped people identify phishing, making content quality an unreliable detection method", choice_c: "AI only improves phishing targeting but does not affect the writing quality of attacks", correct_choice: "B", explanation: "Grammar and writing quality were never good security controls, but AI removes them completely. Now you cannot rely on spelling errors or awkward phrasing to identify phishing. Focus instead on verifying the sender, the request itself, and using independent confirmation." },
        { question_text: "What capability does AI give attackers when conducting spear phishing attacks at scale?", choice_a: "AI allows attackers to send more emails per hour than human-operated campaigns", choice_b: "AI can generate personalized, contextually relevant messages for each target using publicly available information, making mass attacks feel individually crafted", choice_c: "AI gives attackers access to email databases that were previously difficult to obtain", correct_choice: "B", explanation: "Traditional phishing was generic. Spear phishing required manual research per target. AI enables personalized spear phishing at mass scale by automatically researching targets from social media and public records and generating individually tailored messages, combining the effectiveness of spear phishing with the volume of mass phishing." },
        { question_text: "Beyond phishing, in what other ways are attackers using AI that affect everyday users?", choice_a: "AI is primarily used for offensive purposes in nation-state conflicts and does not affect everyday users", choice_b: "AI is used for voice cloning scams, generating fake customer service personas, creating fake social media accounts for influence operations, and generating fraudulent documents", choice_c: "AI attacks are limited to financial sector targets and large corporations", correct_choice: "B", explanation: "AI-powered attacks affect everyone. Voice cloning scams target individuals with fake family emergency calls. Fake AI customer service personas collect personal information. AI-generated documents and profiles are used in romance scams, job fraud, and social engineering at every level." },
      ],
    },
    {
      title: "Module 2: Understanding Deepfakes",
      content: "Deepfakes are synthetic media where a person's likeness, voice, or both are replaced or generated using AI. What started as a technology curiosity is now a serious security and fraud threat used in scams, disinformation, and business impersonation.",
      category: "Deepfakes", difficulty: "beginner", duration_minutes: 10, order_index: 2,
      quiz: [
        { question_text: "What is a deepfake and what makes current deepfake technology particularly concerning?", choice_a: "A type of malware disguised as legitimate software, concerning because it bypasses antivirus detection", choice_b: "Synthetic audio or video where AI generates or replaces a real person's likeness and voice, concerning because quality has reached a point where many people cannot distinguish deepfakes from real content", choice_c: "Manipulated images created using traditional photo editing software", correct_choice: "B", explanation: "Deepfakes use machine learning to generate convincing synthetic media. The concern is not just that they exist but that quality has improved to the point where average viewers cannot reliably detect them, enabling impersonation, fraud, and disinformation that people are not equipped to question." },
        { question_text: "Which of the following represents a real-world threat from deepfake technology?", choice_a: "Deepfakes are only a threat in political contexts where public figures are impersonated", choice_b: "A finance employee receives a video call appearing to show their CFO instructing them to transfer funds, with the CFO's appearance and voice perfectly replicated", choice_c: "Deepfakes can only be used to impersonate celebrities not ordinary employees", correct_choice: "B", explanation: "Business-targeted deepfake fraud has already resulted in organizations losing millions of dollars. Attackers use video calls where AI generates a real-time fake of a company executive to authorize fraudulent financial transfers. This requires very little source material of the target to execute." },
        { question_text: "How much video or audio of a person does an attacker typically need to create a convincing voice or video deepfake?", choice_a: "Many hours of high-quality studio recordings are required to produce convincing results", choice_b: "Modern AI voice cloning can produce convincing results from as little as a few seconds to a few minutes of audio, and video deepfakes require modest amounts of publicly available footage", choice_c: "Deepfakes require cooperation from the target who must provide recordings directly", correct_choice: "B", explanation: "This is one of the most alarming aspects of the technology. Social media posts, interview clips, voicemails, and conference recordings provide all the material an attacker needs. Anyone with a public digital presence has likely provided enough material for a deepfake to be created." },
      ],
    },
    {
      title: "Module 3: Detecting Deepfakes",
      content: "While no detection method is foolproof, understanding the technical and behavioral indicators of deepfakes helps you spot them more reliably. The most important defense is not technical detection but developing a verification habit.",
      category: "Deepfakes", difficulty: "intermediate", duration_minutes: 10, order_index: 3,
      quiz: [
        { question_text: "What visual artifacts have historically indicated deepfake video, though these are becoming less reliable?", choice_a: "Deepfake videos always have a watermark that identifies them as AI generated", choice_b: "Unnatural blinking patterns, facial boundary blurring, inconsistent lighting on the face, and unnatural hair and teeth rendering", choice_c: "Deepfake videos always have audio that does not match the lip movements", correct_choice: "B", explanation: "Early deepfakes had obvious tells including blinking issues, facial boundary artifacts, and lighting inconsistencies. These are becoming harder to spot as quality improves. Do not rely on visual artifacts as your primary deepfake detection method since the technology improves faster than human perception." },
        { question_text: "What is the most reliable way to verify the identity of someone making an unexpected request via video call?", choice_a: "Ask them to smile or perform a specific gesture since deepfakes cannot replicate spontaneous movement", choice_b: "End the call and contact the person through a completely separate channel using contact information you already have to confirm whether they actually made the request", choice_c: "Ask them a personal question only the real person would know", correct_choice: "B", explanation: "Hanging up and calling back through a trusted number you already have is the only reliable verification method. Live deepfakes can respond to prompts and answer questions using AI. The only defense is multi-channel verification using a contact method completely independent of the suspicious call." },
        { question_text: "What technical tool can organizations use to verify the integrity of communications from executives?", choice_a: "Video compression software that reduces file size by removing deepfake artifacts", choice_b: "Pre-established codewords known only to the parties involved that must be spoken to verify identity in high-stakes communications", choice_c: "Facial recognition software that cross-checks video against a database of known deepfakes", correct_choice: "B", explanation: "A codeword known only to the real parties provides a verification layer that AI cannot replicate without already knowing the word. Facial recognition compares against known fakes but cannot detect novel deepfakes. Codewords provide a simple, effective organizational control that does not depend on technology." },
      ],
    },
    {
      title: "Module 4: AI-Powered Voice Cloning Scams",
      content: "AI voice cloning can replicate anyone's voice from a small audio sample. This technology is being used in emergency scam calls, executive impersonation for fraud, and customer service fraud. Knowing how these scams work helps you avoid them.",
      category: "AI Threats", difficulty: "intermediate", duration_minutes: 10, order_index: 4,
      quiz: [
        { question_text: "How does an AI voice cloning emergency scam typically work?", choice_a: "Attackers call random phone numbers playing a recorded message about a fake prize", choice_b: "Attackers clone a family member's voice using social media recordings and call relatives claiming to be in an emergency needing immediate money to avoid asking questions", choice_c: "Attackers use voice cloning to impersonate bank staff and request account verification", correct_choice: "B", explanation: "Emergency scams using voice cloning exploit emotional responses. Hearing what sounds exactly like your child or grandchild in distress bypasses critical thinking. The urgency and the familiar voice combine to make victims act without verification. Always call the person back on a number you already have." },
        { question_text: "What organizational control specifically protects against voice-based executive impersonation fraud?", choice_a: "Requiring all financial requests to be submitted through an online form regardless of verbal approval", choice_b: "A pre-established verbal codeword that executives must speak during any voice or video request for financial action, known only to the executive and the finance team", choice_c: "Training employees to identify voice cloning by listening for audio artifacts and unnatural pauses", correct_choice: "B", explanation: "A codeword works because the attacker cannot know it without prior access to the real executive and the finance team's private communications. Audio artifacts are increasingly undetectable. The codeword is a shared secret that AI cannot replicate without knowing it in advance." },
        { question_text: "Why is urgency a particularly effective element when combined with voice cloning attacks?", choice_a: "Urgency makes the voice clone more convincing by mimicking emotional speech patterns", choice_b: "Urgency bypasses the victim's verification instincts by creating pressure to act immediately rather than take time to confirm through other channels", choice_c: "Urgency is less effective in voice scams than in written phishing because people are more cautious on phone calls", correct_choice: "B", explanation: "The combination of a familiar voice and extreme urgency is a powerful manipulation technique. Urgency specifically prevents the verification step that would defeat the attack. Training people to recognize that urgency is a manipulation signal and that real emergencies survive a one-minute callback helps break this pattern." },
      ],
    },
    {
      title: "Module 5: AI-Generated Disinformation",
      content: "AI is being used to generate fake news articles, fabricated quotes, synthetic social media personas, and manipulated images at a scale and speed that makes verification increasingly important. Understanding how AI-generated disinformation spreads helps you avoid amplifying it.",
      category: "Disinformation", difficulty: "intermediate", duration_minutes: 10, order_index: 5,
      quiz: [
        { question_text: "What makes AI-generated disinformation more dangerous than traditional manually created fake news?", choice_a: "AI-generated content is always more persuasive than human-written content", choice_b: "AI enables production of convincing disinformation at massive scale with no human effort per piece, flooding information environments faster than fact-checkers can respond", choice_c: "AI-generated disinformation is harder to detect because it uses more sophisticated language", correct_choice: "B", explanation: "Scale is the core advantage. A human disinformation operation requires significant labor per piece of content. AI can generate thousands of unique, coherent, and internally consistent fake articles, social media posts, and comments in the time it takes to write one manually, overwhelming verification capacity." },
        { question_text: "How should you approach viral content that triggers a strong emotional response before sharing it?", choice_a: "Share it immediately since its emotional impact suggests it is important news", choice_b: "Pause and verify the claim through established news sources and reverse image search tools before sharing since emotional triggers are a common disinformation technique", choice_c: "Only share it if the post has a high number of likes indicating community verification", correct_choice: "B", explanation: "Strong emotional reactions are specifically engineered by disinformation to short-circuit verification. Content designed to outrage, shock, or deeply sadden gets shared before people think critically. Pausing to verify through a second independent source before sharing prevents you from becoming a disinformation amplifier." },
        { question_text: "What is a synthetic social media persona and how is it used in influence operations?", choice_a: "A corporate social media account that uses AI to automate post scheduling", choice_b: "A fake AI-generated identity with a complete profile, profile picture, and posting history designed to appear as a real person and lend credibility to disinformation", choice_c: "A celebrity impersonation account that uses AI-generated content without disclosure", correct_choice: "B", explanation: "Influence operations use networks of synthetic personas that have been cultivated over months or years to appear legitimate. When these accounts coordinate to promote or amplify disinformation, it creates a false impression of widespread grassroots support for the content. Profile pictures, posting history, and follower counts are all fabricated." },
      ],
    },
    {
      title: "Module 6: AI in Social Engineering",
      content: "AI enables social engineers to research targets automatically, generate highly personalized pretexts, and conduct attacks at scales that were previously impossible. Recognizing AI-enhanced social engineering requires understanding what these attacks look like.",
      category: "Social Engineering", difficulty: "intermediate", duration_minutes: 10, order_index: 6,
      quiz: [
        { question_text: "How does AI change the research phase of a social engineering attack?", choice_a: "AI allows attackers to access private databases that were previously protected", choice_b: "AI automates the collection and synthesis of publicly available information about targets from social media, professional profiles, and public records, enabling personalized attacks at scale", choice_c: "AI makes social engineering research unnecessary since the attacks are automated", correct_choice: "B", explanation: "Attackers previously had to manually research each target. AI aggregates public information about you from dozens of sources and generates a detailed profile automatically, enabling personalized pretexts mentioning your role, recent projects, colleagues, and employer without any manual research by the attacker." },
        { question_text: "What is a chatbot-based social engineering attack and how does it differ from traditional phishing?", choice_a: "Chatbot attacks use automated messages but are otherwise identical to email phishing", choice_b: "AI chatbots can conduct extended interactive conversations that adapt to the target's responses, building rapport and trust over multiple exchanges before making the malicious request", choice_c: "Chatbot attacks exclusively target customer service platforms and do not affect individual employees", correct_choice: "B", explanation: "Traditional phishing is a single shot. AI chatbots engage in multi-turn conversations, answer questions convincingly, adapt when targets express skepticism, and build rapport over time. This makes the eventual malicious request feel like a natural conclusion of an established relationship rather than a cold attack." },
        { question_text: "What remains the most effective defense against AI-enhanced social engineering?", choice_a: "AI-powered email filters that detect AI-generated content before it reaches users", choice_b: "Independent verification of any unusual request through a trusted communication channel, regardless of how convincing the request seems", choice_c: "Refusing to engage with any communication that discusses sensitive business topics", correct_choice: "B", explanation: "AI improves the pretext but cannot defeat independent verification. If you hang up and call back on a number you already have, or walk to a colleague's desk to confirm a request, the social engineering chain is broken regardless of how convincing the AI-generated pretext was." },
      ],
    },
    {
      title: "Module 7: Protecting Yourself From AI Scams",
      content: "Individual protective habits significantly reduce your vulnerability to AI-powered scams. Understanding which personal behaviors make you a target and which reduce your risk helps you stay protected as attack techniques continue to evolve.",
      category: "Personal Protection", difficulty: "beginner", duration_minutes: 8, order_index: 7,
      quiz: [
        { question_text: "How does your public social media presence affect your risk of being targeted by AI-powered attacks?", choice_a: "Social media presence does not affect targeting since attackers use randomly generated victim lists", choice_b: "Public posts provide voice samples, video footage, personal details, and relationship information that attackers use to train deepfakes and craft personalized social engineering pretexts", choice_c: "Only social media with large follower counts is useful to attackers", correct_choice: "B", explanation: "Every public post, video, and audio clip is potential training data for attackers. Your posts reveal your relationships, employer, habits, and interests. Voice samples for cloning come from videos and voice messages. Reducing public sharing of sensitive personal information limits the material available for attacks against you." },
        { question_text: "What is a family safe word and how does it protect against AI voice cloning emergency scams?", choice_a: "A password used to lock shared family accounts on streaming services", choice_b: "A pre-established secret word that family members must use to verify their identity in an emergency call, which AI cannot know without prior knowledge of the specific word", choice_c: "A code word required to unlock parental controls on family devices", correct_choice: "B", explanation: "A family safe word is a simple, powerful defense. When you receive an emotional call from someone claiming to be a family member in an emergency, ask for the safe word. The AI cannot provide it. The real family member knows it. This single check defeats the entire attack." },
        { question_text: "Why is it important to verify AI-related claims and content with multiple independent sources?", choice_a: "Multiple sources reduce the reading time required to stay informed", choice_b: "AI-generated content can appear on many platforms simultaneously but independent verification sources are less likely to have all repeated the same fabricated claim", choice_c: "Major news outlets are immune to AI-generated content so they provide reliable verification", correct_choice: "B", explanation: "AI-generated disinformation can propagate rapidly across many outlets that repeat each other. Independent verification means checking sources that gather information independently. If a claim appears only in sources that are citing each other rather than independent reporting, the claim requires more skepticism." },
      ],
    },
    {
      title: "Module 8: AI and Fraud Detection",
      content: "The same AI technology being used by attackers is also being deployed defensively. Understanding how organizations use AI for fraud detection helps you understand the protections in place and their limitations.",
      category: "Defensive AI", difficulty: "intermediate", duration_minutes: 10, order_index: 8,
      quiz: [
        { question_text: "How do banks use AI to detect fraudulent transactions?", choice_a: "Banks use AI to review every transaction manually before it is processed", choice_b: "Banks use AI to learn normal spending patterns for each customer and flag transactions that deviate significantly from that baseline as potentially fraudulent", choice_c: "Banks use AI only to detect transactions that exceed a predetermined dollar threshold", correct_choice: "B", explanation: "Behavioral baseline modeling is the foundation of AI fraud detection. When a transaction occurs in an unusual location, at an unusual time, for an unusual amount, or at an unusual type of merchant compared to your history, AI flags it for review or declines it. This is why your bank calls when you travel." },
        { question_text: "What is the limitation of AI-based deepfake detection tools?", choice_a: "Deepfake detection AI requires very expensive hardware not available to most organizations", choice_b: "Deepfake detection models are trained on existing deepfakes and may not reliably detect novel techniques, making it an arms race where detection lags behind generation", choice_c: "Deepfake detection tools can only analyze pre-recorded video and cannot work in real time", correct_choice: "B", explanation: "Detection tools identify patterns learned from known deepfakes. When attackers improve their generation techniques, detection tools trained on older deepfakes fail. This technological arms race means detection tools are always somewhat behind generation capabilities." },
        { question_text: "Why should you respond to a bank's fraud alert system even when it seems like a false positive?", choice_a: "Banks charge fees if you do not respond to fraud alerts within a specified time window", choice_b: "Responding to alerts, even false positives, helps the AI system learn your legitimate behavior patterns and improve future accuracy", choice_c: "Not responding to fraud alerts automatically freezes your account for security reasons", correct_choice: "B", explanation: "When you confirm that a flagged transaction is legitimate, you provide feedback that helps the fraud detection system better understand your spending patterns. This reduces false positives over time and improves the system's ability to correctly identify real fraud when it occurs." },
      ],
    },
    {
      title: "Module 9: Legal and Ethical Issues Around AI and Deepfakes",
      content: "The legal landscape around AI-generated content and deepfakes is still evolving. Understanding what is currently regulated, what remains unregulated, and the ethical responsibilities around AI use helps you navigate this space responsibly.",
      category: "AI Ethics", difficulty: "intermediate", duration_minutes: 10, order_index: 9,
      quiz: [
        { question_text: "What legal issue arises when someone creates and distributes a deepfake of a real person without their consent?", choice_a: "Deepfakes are protected as free speech in all jurisdictions regardless of content or context", choice_b: "Depending on jurisdiction and use, deepfakes can violate laws around defamation, fraud, non-consensual intimate imagery, and election interference", choice_c: "Deepfakes only become illegal if the subject of the deepfake files a formal complaint", correct_choice: "B", explanation: "Legal frameworks for deepfakes are developing rapidly. Non-consensual intimate deepfakes are criminalized in a growing number of jurisdictions. Deepfakes used for financial fraud are covered by existing fraud laws. Defamatory deepfakes can support civil liability. Election-related deepfakes face specific prohibitions in some regions." },
        { question_text: "Why are content creators who use AI to generate realistic fake quotes from real public figures creating legal and ethical risks?", choice_a: "Using AI tools for content creation is currently prohibited under most platform terms of service", choice_b: "Fabricated quotes attributed to real people can constitute defamation if they damage reputation and election-related fake quotes may violate specific laws", choice_c: "AI-generated quotes are legal as long as they are clearly labeled as fictional in a disclaimer", correct_choice: "B", explanation: "A disclaimer at the bottom of content does not prevent the fabricated quote from spreading without context. Realistic fake quotes attributed to real people spread as real quotes. When they damage someone's reputation or spread false information about their positions, they may meet the legal threshold for defamation." },
        { question_text: "What responsibility do organizations have regarding the ethical use of AI in their products and services?", choice_a: "Organizations have no ethical obligations beyond meeting current legal requirements for AI use", choice_b: "Organizations should consider the potential for their AI systems to be misused, assess bias and fairness, and implement transparency measures so users know when they are interacting with AI", choice_c: "Ethical AI use is solely a concern for AI developers not for organizations that deploy AI products", correct_choice: "B", explanation: "Organizations deploying AI are responsible for how it affects people. This includes assessing misuse potential, auditing for discriminatory outcomes, and being transparent with users about AI use. Regulatory frameworks including the EU AI Act are formalizing these obligations into legal requirements." },
      ],
    },
    {
      title: "Module 10: Staying Ahead of Evolving AI Threats",
      content: "AI threats are evolving faster than most security training can track. Building habits of skepticism, verification, and continuous learning gives you defenses that remain effective even as specific attack techniques change.",
      category: "Personal Protection", difficulty: "beginner", duration_minutes: 8, order_index: 10,
      quiz: [
        { question_text: "What habit provides durable protection against AI-powered attacks even as specific techniques evolve?", choice_a: "Installing the latest AI detection software on every device you own", choice_b: "Developing a verification reflex that responds to any unusual request through an independent trusted channel regardless of how convincing the request appears", choice_c: "Avoiding all digital communication in favor of in-person interactions only", correct_choice: "B", explanation: "Specific attack techniques change but verification does not. Hanging up and calling back, walking to a colleague's desk, or checking through a known trusted channel defeats social engineering regardless of whether it uses AI voice cloning, deepfake video, or traditional phone impersonation." },
        { question_text: "How should you approach a request that feels emotionally urgent and comes from someone you trust?", choice_a: "Act immediately since trusted contacts would only reach out urgently for genuine reasons", choice_b: "Recognize that urgency combined with a trusted identity is a classic manipulation pattern and slow down to verify through an independent channel before acting", choice_c: "Decline all urgent requests as a policy since legitimate requests can always wait", correct_choice: "B", explanation: "Urgency plus apparent trust is the core formula for AI-enhanced social engineering attacks including voice cloning emergency scams and deepfake executive fraud. Training yourself to slow down when these two elements appear together breaks the manipulation pattern regardless of the specific attack technique." },
        { question_text: "What is the most useful mindset shift for staying protected as AI attack capabilities continue to improve?", choice_a: "Assume that any digital communication could be fabricated and refuse to act on any information received digitally", choice_b: "Shift from trusting content quality as a safety signal to trusting verification processes, since AI has made content quality an unreliable indicator", choice_c: "Trust only communications that use end to end encryption since AI cannot intercept encrypted messages", correct_choice: "B", explanation: "Content used to signal trustworthiness through quality indicators like correct grammar, familiar voices, and professional appearance. AI has neutralized all of these. The reliable signal is now the verification process. Did you confirm this through a trusted independent channel? That is the new quality check." },
      ],
    },
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS10 };
