const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS11(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='Password and Identity Management'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    {
      title: "Module 1: Why Passwords Fail",
      content: `Passwords have been the primary mechanism for authenticating identity online for decades, and they have been failing at that job for decades. Understanding why passwords fail so consistently is the foundation for building authentication systems and personal security habits that actually work.

The fundamental problem with passwords is that they exist at the intersection of two competing requirements. Passwords need to be hard for attackers to guess, which means they should be long, random, and unique. Passwords also need to be remembered by humans, which pushes people toward short, predictable, reused passwords. These two requirements are in direct conflict, and human memory consistently loses.

Password reuse is the most dangerous password behavior and also one of the most common. When you use the same password on multiple sites and one of those sites is breached, every account using that password is immediately at risk. Credential stuffing attacks automate the process of testing breached username and password combinations against hundreds of websites simultaneously. A single breach cascades into dozens of compromised accounts within hours.

Weak passwords are guessable through dictionary attacks that test common words, names, and patterns, and through brute force attacks that systematically test every possible combination. Despite decades of advice to the contrary, the most common passwords in breach databases are still variations of password, 123456, and similar trivially guessable strings. Password complexity requirements that require a mix of characters but allow short passwords are less effective than simply requiring length.

Password reset mechanisms are frequently the weakest link. Security questions with predictable answers, reset links sent to email accounts that may themselves be compromised, and SMS-based reset codes vulnerable to SIM swapping all create paths around even strong passwords.

Phishing attacks steal credentials directly by tricking users into entering them on fake sites. No password strength helps against phishing because the user willingly provides their credentials to the attacker. The password itself is irrelevant when the user hands it over.

Understanding these failure modes points toward solutions. Long unique randomly generated passwords stored in a password manager address the memorability problem. Multi-factor authentication provides protection even when passwords are stolen. Phishing-resistant authentication methods eliminate the credential theft attack entirely.`,
      category: "Password Security", difficulty: "beginner", duration_minutes: 8, order_index: 1,
      quiz: [
        { question_text: "What is a credential stuffing attack and why is password reuse the key enabler that makes it possible?", choice_a: "Credential stuffing automates testing of breached username and password combinations from one service against hundreds of other services, succeeding wherever the same password was reused across accounts", choice_b: "An attack where software fills in random password guesses at high speed until one works through brute force computation", choice_c: "An attack that targets password manager applications directly to extract all stored credentials at once", correct_choice: "A", explanation: "Credential stuffing works because people reuse passwords. When a less secure service is breached, attackers immediately test those credentials against banks, email, and social media. If you use the same password on multiple sites, a breach anywhere is a breach everywhere." },
        { question_text: "Why are passwords based on personal information like birthdays or pet names especially weak against targeted attacks?", choice_a: "Attackers use wordlists built from social media profiles and public records when targeting specific individuals, so personal information passwords are among the first guesses in a targeted attack", choice_b: "Personal information passwords are shorter than random passwords and length is the only factor that matters in determining password strength", choice_c: "Password strength checkers automatically penalize personal information regardless of length or complexity making them fail compliance checks", correct_choice: "A", explanation: "Targeted password attacks use information about the specific target. Your dog's name, wedding date, favorite team, and hometown are all in your social media profile and are among the first passwords tried. Random passwords are not guessable from personal research." },
        { question_text: "What is a rainbow table attack and what defense neutralizes it completely?", choice_a: "An attack using colorful phishing pages designed to look legitimate, neutralized by checking URLs carefully before clicking any links", choice_b: "An attack using precomputed hash values to quickly reverse password hashes, neutralized by salting each password hash with a unique random value before storing it", choice_c: "An attack using multiple simultaneous login attempts from different IP addresses, neutralized by account lockout policies and rate limiting", correct_choice: "B", explanation: "Rainbow tables are precomputed databases mapping password hashes back to plaintext. A salt is a unique random value added to each password before hashing, making precomputed tables useless since each hash is now unique even for the same password. This is why modern systems salt password hashes." },
      ],
    },
    {
      title: "Module 2: Strong Password Principles",
      content: `Strong password principles have evolved significantly as researchers have developed a better understanding of how attackers crack passwords and how humans actually behave. Modern guidance differs in important ways from older advice that focused on character complexity at the expense of length and memorability.

Length is the single most important factor in password strength. A longer password with a limited character set is generally stronger than a shorter password with maximum complexity. Every additional character multiplies the number of possible passwords an attacker must test to find yours. A 20-character password of random lowercase letters has more possible combinations than a shorter password using every character type.

Randomness matters as much as length. Human-chosen passwords are not random even when they appear to be. People use predictable patterns like starting with a capital letter, ending with a number or exclamation mark, substituting letters with visually similar numbers, and basing passwords on recognizable words or names. Attackers know these patterns and build them into their cracking tools. A truly random password is stronger than a longer but predictable one.

Passphrases offer a practical middle ground for passwords that must be remembered. A passphrase made of four or more random unrelated words is both memorable and extremely strong. The strength comes from length rather than complexity, and the randomness comes from the words being genuinely unrelated rather than forming a meaningful phrase the attacker might predict.

Uniqueness across accounts is non-negotiable. If you use the same password on multiple accounts and one account is breached, all accounts using that password are compromised. Every account should have its own unique password. This is only practical with a password manager.

Passwords should not be changed on a fixed schedule unless there is reason to believe they have been compromised. Frequent forced password changes without a specific reason cause people to make minimal changes like adding a number to an existing password, which is less secure than maintaining a strong password that is not being changed regularly.

Never use personal information in passwords. Birth dates, names, pet names, addresses, and similar information can be found through social media, data breaches, and public records, and are routinely incorporated into password cracking attacks targeted at specific individuals.`,
      category: "Password Security", difficulty: "beginner", duration_minutes: 8, order_index: 2,
      quiz: [
        { question_text: "Which of the following is the strongest password based on modern password security principles?", choice_a: "P@ssw0rd1! which includes uppercase, lowercase, numbers, and symbols meeting most complexity requirements", choice_b: "Mydog$Namei$Rex2019 which combines personal information with symbol substitutions for apparent complexity", choice_c: "correct-horse-battery-staple-seven-rain which is a long passphrase of random unrelated words", correct_choice: "C", explanation: "Length is the most important factor in password strength. A long passphrase of random words is both highly resistant to cracking and easier to remember than short complex strings. P@ssw0rd substitutions are well-known to attackers and are in every wordlist. Personal information like a dog's name is guessable from research." },
        { question_text: "Why do complexity requirements like mandatory symbols and numbers often backfire as a security policy?", choice_a: "Complex passwords cannot be stored in password managers and must be written down on paper creating a physical security risk", choice_b: "When forced to add complexity, users make predictable substitutions like replacing an a with the at symbol or adding an exclamation mark at the end, which attackers account for in their cracking wordlists", choice_c: "Symbol and number requirements reduce password entropy by limiting the character set available to users creating mathematically weaker passwords", correct_choice: "B", explanation: "Predictable complexity is not real complexity. When complexity rules force a change, users apply predictable patterns. Attackers know these patterns and include them in wordlists. Long random passphrases without complexity requirements often provide more real-world security than short complex strings." },
        { question_text: "How often should you change a password that has not been compromised and shows no signs of exposure?", choice_a: "Every 30 to 90 days as required by most organizational security policies to limit exposure windows", choice_b: "Every time your password manager prompts you to based on its automatic rotation schedule", choice_c: "Only when you have reason to believe it was compromised, since forced routine rotation leads to weaker passwords as users make minimal predictable changes", correct_choice: "C", explanation: "NIST updated its guidance to recommend against mandatory periodic password rotation that is not tied to evidence of compromise. Forced rotation causes users to make minimal predictable changes like incrementing a number, which produces weaker passwords over time. Change passwords when compromised, not on an arbitrary schedule." },
      ],
    },
    {
      title: "Module 3: Password Managers",
      content: `A password manager is the single most impactful tool most people can adopt to improve their personal security. It solves the fundamental tension between password strength and memorability by remembering passwords for you, eliminating the need to choose between strong unique passwords and passwords you can actually remember.

Password managers generate cryptographically random passwords of whatever length and character composition you specify. These passwords are strong by definition because they are genuinely random and not based on any pattern a human would choose. They are unique because the password manager generates a different one for every account. And they are stored encrypted so you never need to remember them.

The master password is the one password that protects your entire vault. Choose it carefully. It should be a long memorable passphrase that you have never used anywhere else and that you can remember without writing down. The master password is the only password you actually need to memorize. Everything else is handled by the password manager.

Most password managers include browser extensions that detect login forms on websites and automatically fill in the correct credentials. This auto-fill feature provides an additional security benefit beyond convenience. When a password manager auto-fills credentials, it matches the domain of the current page exactly. If you are on a phishing site that looks like your bank but has a slightly different domain, the password manager will not fill in your banking credentials because the domain does not match, effectively protecting you against some phishing attacks.

Password managers also enable password auditing features. They can identify passwords that have been reused across multiple accounts, passwords that are too weak or too old, and accounts whose passwords appear in known data breaches. These features turn periodic security reviews from a tedious manual process into an automated report.

Consider which password manager fits your needs. Some are cloud-based, syncing your vault across devices through an encrypted server. Some are local-only, storing your vault on your device without cloud sync. Cloud-based managers are more convenient for users with multiple devices. Local-only managers appeal to those who want to minimize trust in third-party servers. Both can be secure when used properly.

The risk of a compromised password manager vault is real but manageable. A strongly encrypted vault protected by a unique master password and MFA is extremely difficult to crack even if the encrypted data is obtained. The risk of using weak or reused passwords is far greater than the risk of using a well-configured password manager.`,
      category: "Password Tools", difficulty: "beginner", duration_minutes: 10, order_index: 3,
      quiz: [
        { question_text: "Why does using a password manager allow you to have a stronger overall security posture than trying to memorize passwords yourself?", choice_a: "A password manager generates and stores truly random unique passwords for every account, eliminating the password reuse and predictable patterns that result from human memory limitations", choice_b: "Password managers encrypt passwords using government-grade encryption that is stronger than the encryption used by websites to store passwords on their servers", choice_c: "Password managers automatically update your passwords every 30 days to maintain freshness and reduce exposure from any single credential", correct_choice: "A", explanation: "Human memory is the constraint that drives weak password practices. Password managers remove that constraint entirely. When you do not need to remember a password, you can use a random 30-character string for every site with no mental effort, completely defeating both guessing and credential stuffing attacks." },
        { question_text: "What should you do if a website says it does not support pasting passwords, preventing your password manager from filling in your credentials?", choice_a: "Create a simpler password that you can type manually for that site since the anti-paste restriction makes strong passwords impractical", choice_b: "Use your browser's built-in password manager instead since it handles anti-paste restrictions better than standalone password managers", choice_c: "Use your password manager's copy function to copy the password and manually paste or type it, and consider reporting the restriction as a security design flaw to the site", correct_choice: "C", explanation: "Anti-paste restrictions are a security antipattern. They prevent password manager use, which pushes users toward shorter, weaker, memorable passwords. This is the opposite of good security. The restriction should be reported and worked around using copy-paste. The site's design is the problem." },
        { question_text: "What is the most critical account to protect with the strongest available authentication when using a password manager?", choice_a: "Your primary email account because email is used as the recovery mechanism for virtually every other account you have, making its compromise a cascade failure for all dependent accounts", choice_b: "Your primary social media account because its compromise would allow attackers to impersonate you to all your contacts and connections", choice_c: "Your primary banking account because financial loss from account compromise is the most directly measurable harm from credential theft", correct_choice: "A", explanation: "Email is the master key. Password reset flows for nearly every service send reset links to email. A compromised email account enables takeover of every account that uses that email for recovery. The email account deserves the strongest available password and the strongest available MFA." },
      ],
    },
    {
      title: "Module 4: Multi-Factor Authentication",
      content: `Multi-factor authentication requires presenting two or more independent forms of evidence to prove your identity before being granted access. The independence of these factors is what makes MFA effective. An attacker who steals your password has only one factor and still cannot access your account if a second independent factor is required.

The three categories of authentication factors are something you know, something you have, and something you are. Passwords and PINs are something you know. Authenticator apps, hardware security keys, and physical tokens are something you have. Biometrics like fingerprints and facial recognition are something you are. Strong MFA combines factors from different categories. A password plus an authenticator app combines something you know with something you have.

SMS text message codes are the most widely deployed MFA method and also the weakest. Text messages can be intercepted through SIM swapping attacks where an attacker convinces your carrier to transfer your phone number to a SIM card they control. SS7 protocol vulnerabilities allow interception of SMS messages at the network level. Despite these weaknesses, SMS MFA is dramatically better than no MFA and should be used when stronger options are not available.

Time-based one-time password authenticator apps generate codes on your device using a shared secret and the current time. The codes are generated locally without any network transmission, which eliminates the SIM swapping and SS7 interception vulnerabilities that affect SMS. Authenticator apps are significantly more secure than SMS and should be preferred whenever available.

Hardware security keys are the strongest commonly available MFA method. They use public key cryptography and are phishing-resistant by design. When you authenticate with a hardware key, it verifies that the domain you are authenticating to is the real domain, not a phishing site. This eliminates the credential phishing attack that defeats password plus authenticator app MFA.

Push notification MFA sends a notification to your phone asking you to approve a login. This method is vulnerable to MFA fatigue attacks where an attacker who has your password repeatedly sends approval requests hoping you will approve one out of confusion or frustration. Number-matching push MFA, which requires you to enter a number displayed on the login screen into the authenticator app, significantly reduces this risk.

Enable MFA on every account that supports it, prioritizing accounts that would have the most severe consequences if compromised. Email accounts, password managers, financial accounts, and work accounts all warrant maximum MFA strength.`,
      category: "Authentication", difficulty: "intermediate", duration_minutes: 10, order_index: 4,
      quiz: [
        { question_text: "Why does multi-factor authentication remain effective even when your password has been stolen by an attacker?", choice_a: "MFA requires a second independent form of verification that the attacker typically cannot obtain even after stealing the password, meaning the stolen credential alone is insufficient to access the account", choice_b: "MFA automatically changes your password when it detects that your current password has appeared in a known data breach database", choice_c: "MFA works by encrypting your password with a key stored only on your device so a stolen password hash cannot be used without also physically compromising your device", correct_choice: "A", explanation: "Independence of factors is what makes MFA effective. The attacker has the first factor but lacks the second. For authenticator apps, they would also need physical access to your device. For hardware keys, they would need the physical key. The stolen password is useless without the factor the attacker does not have." },
        { question_text: "Which MFA method is most resistant to both phishing attacks and SIM swapping attacks?", choice_a: "SMS one-time codes because they are sent to your registered phone number which is tied to your verified identity through your carrier account", choice_b: "Time-based one-time password authenticator apps because they generate codes locally on your device without any network transmission that could be intercepted", choice_c: "Hardware security keys using public key cryptography because they verify the domain of the site they are authenticating to and will not respond to a phishing site with a different domain", correct_choice: "C", explanation: "Hardware keys provide phishing resistance that authenticator apps do not. When you authenticate with a hardware key it cryptographically verifies the domain. A phishing site with a different domain cannot obtain a valid response from your key. This is qualitatively different from authenticator app codes which can be relayed in real time from phishing sites." },
        { question_text: "What should you do if you receive an unexpected MFA code prompt or push notification that you did not initiate?", choice_a: "Deny the prompt and immediately change your password because an unsolicited MFA prompt means someone who has your password is actively attempting to log into your account right now", choice_b: "Approve the prompt and then change your password afterward to prevent future unauthorized access attempts from succeeding", choice_c: "Ignore the prompt because it is likely a technical error or test from your service provider and does not indicate any real security concern", correct_choice: "A", explanation: "Unsolicited MFA prompts are the alarm bell. They mean your password is already in an attacker's hands and they are attempting to use it right now. Denying the prompt stops this specific attempt. Changing your password immediately prevents the attacker from making additional attempts with the same credential." },
      ],
    },
    {
      title: "Module 5: Social Engineering Targeting Passwords",
      content: `Social engineering attacks targeting passwords are among the most effective because they bypass technical security controls entirely. Instead of cracking or stealing passwords through technical means, social engineers manipulate people into providing their credentials voluntarily. No password strength or complexity helps when the user hands the password to an attacker who asked nicely.

Phishing is the most common password-targeting social engineering attack. The attacker creates a convincing replica of a legitimate login page and directs victims to it through email links, SMS messages, or other means. When the victim enters their credentials, the attacker captures them. Modern phishing sites often proxy the real site in real time, immediately logging the victim into the real site after capturing their credentials so that nothing appears wrong and no suspicion is raised.

Pretexting builds a false scenario that makes a request for credentials seem legitimate. An attacker posing as IT support and calling to say they need your password to resolve a technical issue is pretexting. Attackers posing as HR to collect account information for a system migration, as vendors who need login details to perform integrations, or as security teams performing audits are all pretexting scenarios designed to elicit credentials.

Vishing, voice phishing, is used to gather credentials and other sensitive information through phone calls. Sophisticated vishing attacks use caller ID spoofing to make calls appear to come from legitimate numbers, use accurate personal information gathered from social media to build credibility, and create urgency that pressures targets to provide information before thinking critically.

Credential harvesting through fake customer support is a growing attack vector. Attackers monitor social media for people complaining about service issues and offer to help by asking them to verify their account by providing their credentials. The emotional state of a frustrated customer makes them more susceptible to this manipulation.

The defense against social engineering targeting passwords starts with the firm understanding that legitimate organizations never ask for your password. Help desks can reset passwords. IT teams can access systems through their own administrative accounts. No legitimate technical or security process requires you to share your password with another person. If someone asks for your password regardless of who they claim to be, the answer is always no.`,
      category: "Social Engineering", difficulty: "intermediate", duration_minutes: 10, order_index: 5,
      quiz: [
        { question_text: "A caller claims to be from IT support and says they need your password to fix an urgent account problem. What is the correct response?", choice_a: "Tell the caller you never share your password with anyone including IT staff, hang up, and call the IT helpdesk back using the number from your company directory to report the contact", choice_b: "Provide the password if the caller can verify their identity by telling you your employee ID and department name before you share anything", choice_c: "Ask the caller to send a support ticket number to your email first so you can verify the request is logged in the ticketing system", correct_choice: "A", explanation: "Legitimate IT teams do not need your password. They have administrative access to systems through their own accounts. Any request for your password is a social engineering attempt regardless of who the caller claims to be or how urgent the situation sounds. Hang up and verify through an independent channel." },
        { question_text: "What is MFA fatigue and how does it work as an attack technique against employees with MFA enabled?", choice_a: "An attacker who has stolen your password sends repeated MFA push notification requests hoping you will eventually approve one out of frustration, confusion, or the mistaken belief that approving will stop the notifications", choice_b: "MFA fatigue refers to users disabling MFA on their accounts after finding it too inconvenient, which attackers exploit by specifically targeting accounts where MFA has been recently removed", choice_c: "MFA fatigue is a technical vulnerability in authenticator apps that allows attackers to replay old authentication codes after extended periods of code generation", correct_choice: "A", explanation: "MFA fatigue exploits human psychology. Repeated push notifications are annoying. People approve them to make them stop. The attacker is counting on confusion or frustration to generate an accidental approval. Number-matching MFA defeats this by requiring active engagement with the login screen that the attacker cannot see." },
        { question_text: "How do attackers use fake IT helpdesk phone calls to defeat MFA protection on employee accounts?", choice_a: "Attackers call targets claiming to be IT support, tell them they need to approve an MFA push notification for a system update, and use the approved notification to complete their unauthorized login in real time", choice_b: "Attackers call targets and convince them to install a remote access tool that intercepts MFA codes as they are generated by the authenticator app on the device", choice_c: "Attackers call targets and persuade them to temporarily disable MFA citing a claimed incompatibility with a system upgrade that requires it to be turned off briefly", correct_choice: "A", explanation: "Real-time MFA interception through social engineering is an active attack technique. The attacker already has the password. They call the target, establish a pretextual reason for an MFA notification, then trigger the login while the target is on the phone. The target approves what they believe is a legitimate system notification." },
      ],
    },
    {
      title: "Module 6: Single Sign-On and Identity Providers",
      content: `Single sign-on systems allow users to authenticate once and access multiple applications without logging into each one separately. Identity providers are the systems that manage authentication and issue credentials that other applications trust. Understanding how SSO and identity providers work helps you use them safely and recognize when they may be targeted by attackers.

SSO works through a trusted relationship between an identity provider and service providers. When you try to access an application using SSO, the application redirects you to the identity provider for authentication. The identity provider verifies your identity and issues a token that tells the application you are authenticated. The application trusts this token because it trusts the identity provider. You never send your credentials directly to the application.

Common identity providers include corporate Active Directory systems federated through protocols like SAML or OIDC, consumer identity providers like Sign in with Google and Sign in with Apple, and purpose-built identity platforms. Each provides a different level of security and control.

The security concentration risk of SSO is its most important characteristic. When all your applications rely on a single identity provider for authentication, the security of the identity provider determines the security of all those applications. A compromised identity provider account provides access to every application that trusts it. This makes the identity provider account extraordinarily valuable to attackers and correspondingly important to protect with the strongest available security controls, including MFA.

Token theft is the primary attack against SSO systems. Rather than stealing credentials, attackers steal the authentication tokens that the identity provider issues. A stolen valid token can be used to access applications without any credentials at all. Token theft typically occurs through malware on the user's device, cross-site scripting vulnerabilities in applications, or man-in-the-middle attacks on insufficient HTTPS implementations.

Conditional access policies add additional validation to token-based authentication. Rather than accepting any valid token without question, conditional access evaluates additional signals like device health, network location, and behavior patterns before granting access. A valid token used from an unusual location or an unmanaged device may be challenged for additional verification.

SSO scope creep occurs when applications are connected to your identity provider over time and old connections are never removed. An application you connected years ago and no longer use may still have access through SSO. Periodically review which applications are connected to your identity provider and revoke access for any you no longer use.`,
      category: "Identity Management", difficulty: "intermediate", duration_minutes: 10, order_index: 6,
      quiz: [
        { question_text: "What is single sign-on and what is the main security advantage it provides for organizations?", choice_a: "SSO allows users to authenticate once with an identity provider and access multiple applications without re-authenticating for each one, enabling centralized enforcement of strong authentication policies across all connected applications", choice_b: "SSO automatically generates unique strong passwords for each application a user accesses and rotates them on a scheduled basis without requiring user involvement", choice_c: "SSO encrypts all communication between users and applications using keys managed by the identity provider, providing end-to-end encryption for all enterprise application traffic", correct_choice: "A", explanation: "The security advantage of SSO is centralization. Instead of managing authentication security for dozens of applications independently, you enforce strong authentication at the identity provider and all connected applications inherit that protection. MFA at the SSO layer protects every connected application simultaneously." },
        { question_text: "What is the biggest security risk associated with single sign-on that organizations must account for?", choice_a: "SSO creates a single high-value target where compromise of the identity provider account provides access to every application that trusts it, making the identity provider account significantly more valuable and dangerous than any individual application account", choice_b: "SSO is inherently insecure because identity providers must store all user credentials in a central location that represents an attractive target for attackers worldwide", choice_c: "SSO reduces security by allowing users to stay authenticated for extended periods without re-entering credentials, significantly increasing the risk of session hijacking attacks", correct_choice: "A", explanation: "Concentration of risk is the core SSO security concern. One compromised identity provider account unlocks every connected application. This concentration justifies applying the strongest available authentication controls to identity provider accounts. The blast radius of a compromised SSO account is far larger than any individual application account." },
        { question_text: "When you click Log in with Google or Log in with Apple on a third-party website, what is actually happening technically?", choice_a: "You are sharing your Google or Apple account credentials directly with the third-party website so they can verify your identity against those providers' user databases", choice_b: "The identity provider authenticates you and issues a token that tells the third-party application you are authenticated without sharing your password, while the application may receive specific authorized profile information", choice_c: "The third-party website receives your email address only and uses it to look up your account in its own user database without any ongoing access to your Google or Apple account", correct_choice: "B", explanation: "OAuth-based login does not share credentials with the third-party application. The identity provider handles authentication and issues a token. The application receives the token and the specific profile information you authorize, but never sees your password. This is more secure than creating another site-specific password that could be breached." },
      ],
    },
    {
      title: "Module 7: Privileged Access Management",
      content: `Privileged access management addresses the security of accounts and credentials that have elevated permissions in an organization's systems. Administrator accounts, root access, database credentials, and service accounts with broad permissions are all privileged accounts. They are the most valuable targets for attackers and the most damaging when compromised.

The principle of least privilege applied to privileged access means that even administrators should only have the elevated access they need for specific tasks, and only when they need it. Permanent standing administrative access is unnecessary for most administrative tasks and represents persistent elevated risk. Just-in-time privileged access provides elevated permissions only when requested for a specific task and revokes them automatically when the task is complete or a time limit is reached.

Privileged access workstations are dedicated devices used exclusively for administrative tasks. Because administrative activities access the most sensitive systems, they warrant the most secure computing environment. Using a shared general-purpose workstation for administrative tasks means that any compromise of that workstation, through a phishing email or malicious download, immediately has access to administrative capabilities.

Session recording for privileged access provides an audit trail of everything done during administrative sessions. Video recordings of remote desktop sessions, keystroke logs, and command histories help detect malicious insider activity and provide evidence for investigations. The knowledge that sessions are recorded also deters insider misuse.

Credential vaulting stores privileged credentials in a secure vault rather than in the minds of individual administrators or in documents and spreadsheets. Vaulted credentials can be checked out for specific tasks, with the vault automatically rotating the credential after it is returned. This means that even if a credential is somehow captured during use, it will be invalidated shortly after.

Service account management is frequently neglected compared to human account management. Service accounts are non-human accounts used by applications and automated processes. They often have significant permissions and may never be reviewed or rotated. Attackers specifically target service accounts because they are frequently overpermissioned and under-monitored. Inventory all service accounts, apply least privilege, enable logging on service account activity, and rotate service account credentials regularly.`,
      category: "Privileged Access", difficulty: "advanced", duration_minutes: 12, order_index: 7,
      quiz: [
        { question_text: "Why should administrators use separate accounts for privileged tasks rather than using their regular user accounts for everything?", choice_a: "Using a regular account for privileged tasks means that any compromise of the regular account through phishing or malware immediately grants the attacker administrative access, while separate privileged accounts limit exposure by restricting when elevated access is used", choice_b: "Regulatory frameworks require separate administrator accounts for compliance documentation purposes and the security benefit is secondary to the audit trail requirements", choice_c: "Separate privileged accounts are technically required because regular user accounts cannot perform administrative functions in modern operating systems and enterprise platforms", correct_choice: "A", explanation: "Privileged account separation limits blast radius. A regular user account is at risk from phishing, malicious downloads, and browsing activity. If that account also has administrative privileges, so does any attacker who compromises it. A separate privileged account used only for administrative tasks is exposed to far fewer threats." },
        { question_text: "What is just-in-time privileged access and why is it more secure than permanent standing administrative access?", choice_a: "Just-in-time access provides elevated permissions only for the duration of a specific authorized task and automatically revokes them afterward, eliminating the persistent elevated access that standing administrator accounts provide", choice_b: "Just-in-time access is a backup authentication method that provides emergency access when primary credentials are unavailable, used as a fallback rather than a primary access control mechanism", choice_c: "Just-in-time access is a monitoring feature that logs administrator actions in real time and alerts security teams when privileged operations occur outside of approved maintenance windows", correct_choice: "A", explanation: "Standing administrative access means privileged credentials exist and are usable at all times. Compromising an account with standing admin access gives the attacker those privileges immediately and indefinitely. JIT access means there is no standing privilege to compromise. Elevated access exists only during the specific window it is needed." },
        { question_text: "What is a privileged access workstation and what specific threat does it address in enterprise environments?", choice_a: "A PAW is a dedicated device used exclusively for administrative tasks that is hardened and isolated from general internet browsing and email, protecting privileged credentials from the threats that regular workstations face through routine use", choice_b: "A PAW is a virtual machine that runs inside a regular workstation providing isolation between privileged administrative work and regular user activities on the same physical device", choice_c: "A PAW is a network-isolated server that administrators connect to remotely to perform privileged tasks, protecting the server from external threats by keeping it off the public network", correct_choice: "A", explanation: "Administrative credentials are valuable. Performing administrative tasks from a workstation also used for email, browsing, and running general applications exposes those credentials to every threat those activities carry. A dedicated hardened workstation used only for administration reduces the attack surface for credential theft dramatically." },
      ],
    },
    {
      title: "Module 8: Account Recovery Security",
      content: `Account recovery mechanisms are the safety net for when users lose access to their accounts, but they are also a primary attack vector. If an attacker can trigger and complete your account recovery process, they gain access to your account without ever needing your password. Every account recovery option is a potential path for attackers to take over your account.

Email-based account recovery sends a reset link to a registered email address. This is secure only if the recovery email account is itself secure. If an attacker compromises your recovery email, they can use it to take over every account that uses it for recovery. Your recovery email account needs to be the most secure account you have, with a unique strong password and MFA enabled.

Security questions are a legacy account recovery mechanism that remain widely deployed despite being fundamentally insecure. The answers to common security questions like mother's maiden name, childhood pet, first school, and hometown are frequently discoverable through social media, public records, and data breaches. Using accurate answers to security questions provides minimal security. Using randomly generated false answers treated as passwords and stored in your password manager is the correct approach.

SMS-based recovery codes are vulnerable to SIM swapping, where an attacker transfers your phone number to a device they control by social engineering your carrier. With your phone number redirected, any SMS-based recovery process is compromised. For accounts with significant value, SMS should not be the sole recovery mechanism.

Backup codes are one-time use codes generated when you set up MFA that can be used to access your account if you lose your primary MFA device. These codes should be treated like extremely sensitive credentials. Store them in a secure location, ideally printed and kept physically secure or stored in your password manager. If backup codes are ever compromised, generate a new set immediately and invalidate the old ones.

Recovery phone numbers and alternate email addresses stored for account recovery purposes must be kept current. If the phone number or email address you registered for recovery years ago is no longer accessible to you, you may be permanently locked out of your account if you lose access through another means. Review and update recovery information annually.

Account recovery processes should be treated with the same skepticism as any other request that involves your credentials. Unsolicited messages claiming you need to verify your account or reset your password are phishing attacks. Initiate account recovery yourself by going directly to the service website rather than following links in unsolicited communications.`,
      category: "Account Security", difficulty: "intermediate", duration_minutes: 10, order_index: 8,
      quiz: [
        { question_text: "Why are traditional security questions a weak account recovery mechanism despite their widespread deployment?", choice_a: "The answers to common security questions like mother's maiden name, first pet, and childhood street are frequently discoverable through social media, public records, genealogy databases, and data breaches, making them effectively guessable for a determined attacker", choice_b: "Security questions are weak because users frequently forget the answers they provided when setting up their accounts, making them ineffective for legitimate recovery as well as for security", choice_c: "Security questions are cryptographically weak because the answer space is small and can be brute-forced by automated tools in a matter of seconds with modern hardware", correct_choice: "A", explanation: "Security questions were designed when personal information was less accessible. Today the information these questions ask about is frequently findable. Social media makes family names and pet names public. Genealogy databases expose maiden names. Data brokers compile personal histories. The questions provide minimal security against anyone who researches their target." },
        { question_text: "What is the safest approach to storing backup codes for MFA-protected accounts?", choice_a: "Store backup codes in your email account for convenient access if you lose your phone since your email is likely accessible from any device", choice_b: "Print backup codes and store them in a physically secure location like a safe, or store them in your password manager, since they provide full account access without the primary MFA factor", choice_c: "Screenshot backup codes and store them in your phone's photo library for easy access when you need them in an emergency", correct_choice: "B", explanation: "Backup codes are as powerful as your primary credentials combined with MFA. Storing them in email or photos creates an easily accessible bypass. Physical storage in a secure location means an attacker needs physical access to your safe, not just your compromised device or account." },
        { question_text: "Why should your account recovery email address have stronger security than the accounts it can recover?", choice_a: "If the recovery email address is less secure than the accounts it can recover, an attacker who compromises it can immediately reset passwords on all of those accounts, bypassing every other security measure you have in place", choice_b: "Recovery email addresses are shared with service providers and need more protection against provider data breaches that could expose the recovery address to third parties", choice_c: "Recovery email addresses are stored in plaintext by some services so they need additional encryption and protection beyond standard account security", correct_choice: "A", explanation: "Your recovery email is a master key. Securing your main accounts with strong passwords and MFA while using a weak recovery email address means an attacker who compromises the recovery email can reset everything. The recovery path is only as strong as its weakest link." },
      ],
    },
    {
      title: "Module 9: Identity Theft and Account Takeover",
      content: `Identity theft occurs when someone uses your personal information without your consent to commit fraud or other crimes. Account takeover is a specific form of identity theft where attackers gain control of your existing accounts. Both can have severe financial and personal consequences that take months or years to fully resolve.

New account fraud uses your stolen personal information to open new accounts in your name. These accounts are used to borrow money, make purchases, or commit other crimes. The victim discovers the fraud when debt collectors call, when unusual accounts appear on credit reports, or when legitimate credit applications are denied due to fraudulent accounts opened in their name.

Account takeover uses stolen or guessed credentials to access your existing accounts. Once inside, attackers change contact information to prevent you from recovering the account, drain financial accounts, make unauthorized purchases, steal sensitive information, or use your account as a platform for further attacks. Email account takeover is particularly damaging because email is used for recovery of so many other accounts.

The warning signs of identity theft include unexpected bills or collection notices for accounts you did not open, unfamiliar accounts appearing on your credit reports, credit applications being denied unexpectedly, missing mail, receiving correspondence about benefits you did not apply for, and notification from a company that your information was involved in a breach.

Credit freezes are the most effective prevention against new account fraud. A credit freeze prevents lenders from accessing your credit report, which means they will not extend new credit in your name even if an attacker has your Social Security number and other personal information. Freezes are free, can be placed and lifted as needed, and do not affect your existing accounts or credit score.

Regular credit monitoring through AnnualCreditReport.com and credit monitoring services detects fraudulent accounts early. Review your credit reports at least annually and investigate any unfamiliar accounts or inquiries immediately. The earlier you detect identity theft, the easier it is to resolve.

If your identity is stolen, report it to the Federal Trade Commission at IdentityTheft.gov, which generates a personalized recovery plan. Place fraud alerts or freezes at all three credit bureaus. File a police report. Contact affected financial institutions directly. Document everything with dates and names of representatives you speak with.`,
      category: "Identity Protection", difficulty: "intermediate", duration_minutes: 10, order_index: 9,
      quiz: [
        { question_text: "What is the difference between identity theft and account takeover as distinct types of attacks?", choice_a: "Account takeover targets specific existing accounts using stolen or guessed credentials, while identity theft uses your personal information to open new fraudulent accounts or commit fraud in your name without needing your existing account passwords", choice_b: "Identity theft affects government records while account takeover affects only private online accounts and never involves government systems or records", choice_c: "Identity theft and account takeover are the same attack described using different terminology by different security organizations", correct_choice: "A", explanation: "Account takeover hijacks your existing accounts. Identity theft uses your personal information to create new fraudulent accounts, loans, or records in your name without needing your existing account passwords. Both can occur together when a compromised account provides the personal information used for identity theft." },
        { question_text: "What should you do immediately if you discover that your information was included in a publicly disclosed data breach?", choice_a: "Wait to see if you notice unauthorized activity on your accounts before taking any action since many breaches do not result in actual fraud", choice_b: "Immediately change the password on the breached service and on any other service where you used the same password, enable MFA if not already active, and monitor for suspicious activity on affected accounts", choice_c: "Close your account on the breached service permanently because continued use after a breach creates ongoing risk regardless of what security measures you implement", correct_choice: "B", explanation: "Acting immediately limits damage. Change the breached password first, then audit every other account that used the same password and change those too. Enable MFA everywhere possible. Monitor financial accounts for unauthorized activity. Credential stuffing attacks begin within hours of a breach becoming available." },
        { question_text: "What is a credit freeze and when should you seriously consider using one to protect yourself?", choice_a: "A control that prevents credit reporting agencies from sharing your credit report with potential lenders, making it nearly impossible for someone to open new credit in your name, recommended when your personal information has been exposed in a breach or you have been a victim of identity theft", choice_b: "A feature that prevents your credit score from changing during a dispute investigation so you are not penalized while resolving fraudulent account issues", choice_c: "A service that alerts you in real time when someone applies for credit in your name so you can immediately contact the lender to deny the fraudulent application", correct_choice: "A", explanation: "A credit freeze is the strongest protection against new account fraud. With a freeze in place, a lender checking your credit for a new application gets a blocked response. Even if an attacker has all your personal information, they cannot open new credit accounts without your explicit unfreeze action. It is free at all major bureaus in the US." },
      ],
    },
    {
      title: "Module 10: Building a Personal Identity Security System",
      content: `Building a personal identity security system means putting in place the practices, tools, and habits that protect your accounts and personal information consistently over time. It is not a single action but an ongoing posture that becomes easier to maintain as the individual components become habits.

The foundation is a password manager. Start by choosing a reputable password manager and migrating your most important accounts to it first. Financial accounts, email accounts, and your primary work accounts should be migrated before lower-priority accounts. As you log into accounts over time, save each one to the password manager and have it generate a new strong unique password for that account. Over a few months you will have replaced most of your passwords without it feeling like a massive project.

Enable MFA on every account that supports it, starting with the highest-priority accounts. Your email account and password manager account are the most critical and should have the strongest available MFA. Work through your financial accounts, social media accounts, and other important accounts. Keep a record of your MFA setup and backup codes in a secure location.

Conduct a periodic account inventory. Set a calendar reminder every three to six months to review which accounts you have, which are still active, and which can be closed. Closed accounts cannot be breached. Dormant accounts with old passwords and no MFA are frequently compromised without the owner noticing.

Monitor your accounts for unauthorized activity. Enable login notifications on accounts that support them. Set up alerts on financial accounts for transactions above certain amounts. Check your credit reports at least annually. Use HaveIBeenPwned to check whether your email addresses have appeared in known data breaches.

Practice good digital hygiene around your personal information. Limit what you share on social media. Be thoughtful about which services you register with and what information they require. Use email aliases for services you do not trust with your primary email. Opt out of data broker profiles when possible.

Be skeptical of unexpected communications requesting account actions. Legitimate services do not send unsolicited messages asking you to verify your account, reset your password, or confirm your personal information by clicking a link. When in doubt, navigate directly to the service website rather than following any link.

Your personal identity security system does not need to be perfect on day one. Start with the highest impact actions, which are a password manager and MFA on your most important accounts, and build from there. Each improvement reduces your risk meaningfully.`,
      category: "Password Security", difficulty: "beginner", duration_minutes: 8, order_index: 10,
      quiz: [
        { question_text: "What is the correct priority order for improving personal account security when starting from scratch?", choice_a: "Set up a password manager first, then use it to create unique strong passwords everywhere, then enable MFA starting with the highest-value accounts like email and banking", choice_b: "Update passwords first across all accounts, then enable MFA everywhere, then set up a password manager to maintain the improved credentials", choice_c: "Enable MFA first on every account that supports it, then create a password manager account, then update all passwords to use the manager", correct_choice: "A", explanation: "A password manager is the foundation because it enables everything else. Without it, strong unique passwords are not sustainable. Once the manager is in place, update passwords starting with highest-value accounts, then enable MFA starting with email since it is the master key that can recover everything else." },
        { question_text: "How should you handle a service that does not support MFA when you need to maintain an account there?", choice_a: "Use a uniquely strong password generated by your password manager for that service, recognize it as higher risk, and avoid storing sensitive information in it or linking it as a recovery method for important accounts", choice_b: "Avoid using the service entirely since the absence of MFA is an unacceptable security risk that cannot be mitigated through any other means", choice_c: "Use the same password as your email since MFA on email compensates for the lack of MFA on this service through the recovery mechanism", correct_choice: "A", explanation: "Avoiding all services without MFA is not practical. The realistic approach is risk management. Give it a unique strong password from your password manager, minimize what sensitive information you store there, and do not link it as a recovery method for more important accounts. Recognize its elevated risk and treat it accordingly." },
        { question_text: "What ongoing habit keeps your personal identity security posture current and effective over time?", choice_a: "Conducting periodic reviews of your accounts including checking for unused accounts to close, verifying MFA is still active on important accounts, rotating any credentials that may have been exposed, and checking breach notifications for your email addresses", choice_b: "Changing all passwords on a fixed schedule like every January first regardless of whether there is any evidence of compromise or exposure", choice_c: "Performing a full security audit of every account every month to ensure nothing has changed without your knowledge or authorization", correct_choice: "A", explanation: "Sustainable security hygiene beats burst activity. Checking services like HaveIBeenPwned for breach notifications, reviewing which apps have access to your accounts periodically, and keeping your password manager current gives you ongoing visibility without an unmanageable monthly burden." },
      ],
    },
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS11 };
