const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS11(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='Password and Identity Management'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    {
      title: "Module 1: Why Passwords Fail",
      content: "Passwords are the most widely used authentication method and the most commonly exploited. Understanding why passwords fail and how attackers compromise them is the foundation for building better authentication habits.",
      category: "Password Security", difficulty: "beginner", duration_minutes: 8, order_index: 1,
      quiz: [
        { question_text: "What is a credential stuffing attack and why is password reuse the key enabler?", choice_a: "An attack where software fills in random password guesses at high speed until one works", choice_b: "An attack where breached username and password pairs from one service are automatically tested against hundreds of other services, succeeding wherever the same password was reused", choice_c: "An attack that targets password manager applications directly", correct_choice: "B", explanation: "Credential stuffing works because people reuse passwords. When a less secure service is breached, attackers immediately test those credentials against banks, email, and social media. If you use the same password on multiple sites, a breach anywhere is a breach everywhere." },
        { question_text: "Why are passwords based on personal information like birthdays or pet names especially weak?", choice_a: "Personal information passwords are shorter than random passwords and length is the only factor that matters", choice_b: "Attackers use wordlists built from social media profiles and public records when targeting specific individuals, so personal information passwords are among the first guesses", choice_c: "Password strength checkers penalize personal information regardless of length or complexity", correct_choice: "B", explanation: "Targeted password attacks use information about the specific target. Your dog's name, wedding date, favorite team, and hometown are all in your social media profile and are among the first passwords tried. Random passwords are not guessable from personal research." },
        { question_text: "What is a rainbow table attack and what defense neutralizes it?", choice_a: "An attack using colorful phishing pages, neutralized by checking URLs before clicking", choice_b: "An attack using precomputed hash values to quickly reverse password hashes, neutralized by salting each password hash with a unique random value before storing", choice_c: "An attack using multiple simultaneous login attempts, neutralized by account lockout policies", correct_choice: "B", explanation: "Rainbow tables are precomputed databases mapping password hashes back to plaintext. A salt is a unique random value added to each password before hashing, making precomputed tables useless since each hash is now unique even for the same password. This is why modern systems salt password hashes." },
      ],
    },
    {
      title: "Module 2: Strong Password Principles",
      content: "A strong password is one that cannot be guessed and cannot be cracked in a reasonable time frame. Understanding what makes a password strong and what does not helps you create credentials that actually protect your accounts.",
      category: "Password Security", difficulty: "beginner", duration_minutes: 8, order_index: 2,
      quiz: [
        { question_text: "Which of the following is the strongest password?", choice_a: "P@ssw0rd1!", choice_b: "Mydog$Namei$Rex2019", choice_c: "correct-horse-battery-staple-seven-rain", correct_choice: "C", explanation: "Length is the most important factor in password strength. A long passphrase of random words is both highly resistant to cracking and easier to remember than short complex strings. P@ssw0rd1 substitutions are well-known to attackers and are in every wordlist. Personal information like a dog's name is guessable from research." },
        { question_text: "Why do complexity requirements like mandatory symbols and numbers often backfire as a security policy?", choice_a: "Complex passwords cannot be stored in password managers and must be written down", choice_b: "When forced to add complexity, users make predictable substitutions like replacing an a with the at symbol or adding an exclamation mark at the end, which attackers account for in their wordlists", choice_c: "Symbol and number requirements reduce password entropy by limiting the character set", correct_choice: "B", explanation: "Predictable complexity is not complexity. When complexity rules force a change, users apply predictable patterns. Attackers know these patterns and include them in wordlists. Long random passphrases without complexity requirements often provide more real-world security than short complex strings." },
        { question_text: "How often should you change a password that has not been compromised?", choice_a: "Every 30 to 90 days as required by most security policies", choice_b: "Every time your password manager prompts you to", choice_c: "Only when you have reason to believe it was compromised, since forced routine rotation leads to weaker passwords as users make minimal predictable changes", correct_choice: "C", explanation: "NIST updated its guidance to recommend against mandatory periodic password rotation that is not tied to evidence of compromise. Forced rotation causes users to make minimal predictable changes like incrementing a number, which produces weaker passwords over time. Change passwords when compromised, not on an arbitrary schedule." },
      ],
    },
    {
      title: "Module 3: Password Managers",
      content: "A password manager is the single most impactful tool for improving your personal password security. It generates strong unique passwords for every site, stores them securely, and fills them in automatically, eliminating the tradeoff between security and convenience.",
      category: "Password Tools", difficulty: "beginner", duration_minutes: 10, order_index: 3,
      quiz: [
        { question_text: "Why does using a password manager allow you to have a stronger security posture than trying to memorize passwords?", choice_a: "Password managers encrypt passwords using government-grade encryption that is unbreakable", choice_b: "Password managers eliminate the memory constraint that forces people into weak predictable passwords and password reuse, allowing truly random unique passwords for every account", choice_c: "Password managers automatically change your passwords every 30 days to maintain freshness", correct_choice: "B", explanation: "Human memory is the constraint that drives weak password practices. Password managers remove that constraint entirely. When you do not need to remember a password, you can use a random 30-character string for every site with no mental effort, completely defeating both guessing and credential stuffing attacks." },
        { question_text: "What should you do if a website says it does not support pasting passwords, preventing your password manager from filling in your credentials?", choice_a: "Create a simpler password that you can type manually for that site", choice_b: "Use your browser's built-in password manager instead since it does not have pasting restrictions", choice_c: "Use your password manager's copy function to copy the password and manually paste or type it, and consider reporting the restriction as a security design flaw", correct_choice: "C", explanation: "Anti-paste restrictions are a security antipattern. They prevent password manager use, which pushes users toward shorter, weaker, memorable passwords. This is the opposite of good security. The restriction should be reported and worked around using copy-paste. The site's design is the problem." },
        { question_text: "What is the most critical account to protect with the strongest possible security measures?", choice_a: "Your bank account since it has the most direct financial impact", choice_b: "Your primary email account since it is used to reset passwords on every other account, making it the master key to your entire digital identity", choice_c: "Your social media accounts since they contain the most personal information", correct_choice: "B", explanation: "Your email is the recovery mechanism for every other account. If an attacker controls your email they can reset passwords on every service linked to it. Email is the highest-value target and should have the strongest unique password and mandatory multi-factor authentication." },
      ],
    },
    {
      title: "Module 4: Multi-Factor Authentication",
      content: "Multi-factor authentication requires something you know combined with something you have or something you are. It is the single most effective technical control for preventing account takeover even when passwords are stolen.",
      category: "MFA", difficulty: "beginner", duration_minutes: 10, order_index: 4,
      quiz: [
        { question_text: "Why does multi-factor authentication remain effective even when an attacker has your password?", choice_a: "MFA requires the attacker to also know your security questions which are harder to research", choice_b: "MFA requires a second factor that the attacker typically does not have, such as your physical phone or a hardware key, making the stolen password alone insufficient to log in", choice_c: "MFA locks your account after a stolen password is entered, preventing the attacker from trying again", correct_choice: "B", explanation: "MFA works because most attackers who have your password do not also have physical possession of your second factor. They may be across the world with your credentials but cannot produce the time-limited code from your authenticator app or the physical press of your hardware key." },
        { question_text: "Which MFA method is most resistant to phishing and SIM swapping attacks?", choice_a: "SMS text message codes since they are delivered to your registered phone number", choice_b: "Email-based one-time codes since they require access to your email account", choice_c: "Hardware security keys that use cryptographic challenge-response verification tied to the specific legitimate website domain", correct_choice: "C", explanation: "SMS codes are vulnerable to SIM swapping where attackers convince carriers to transfer your number. Phishing sites can relay OTP codes in real time. Hardware keys perform cryptographic verification that includes the domain, making them phishing-resistant. A fake login page cannot fool a hardware key because the domain does not match." },
        { question_text: "What should you do if you receive an MFA code prompt that you did not initiate?", choice_a: "Approve it since your phone receiving the prompt confirms it is a legitimate login", choice_b: "Treat it as evidence that your password has been compromised, do not approve the prompt, and immediately change your password", choice_c: "Wait to see if you receive multiple prompts before deciding whether to approve", correct_choice: "B", explanation: "An unsolicited MFA prompt means someone has your password and is attempting to log in. They are waiting for you to approve the request. Do not approve it. Change your password immediately since the prompt confirms the password has been compromised." },
      ],
    },
    {
      title: "Module 5: Social Engineering Targeting Passwords",
      content: "Technical controls like strong passwords and MFA can be defeated through social engineering. Attackers manipulate people into revealing credentials, approving MFA requests, or bypassing security procedures. Recognizing these tactics is as important as technical defenses.",
      category: "Social Engineering", difficulty: "intermediate", duration_minutes: 10, order_index: 5,
      quiz: [
        { question_text: "A caller claims to be from IT support and says they need your password to fix an urgent issue with your account. What is the correct response?", choice_a: "Provide it since IT staff legitimately need passwords to perform account maintenance", choice_b: "Provide it only if the caller can verify their identity by providing your employee ID", choice_c: "Refuse since legitimate IT support never needs your password because they have administrative access that does not require knowing your credentials", correct_choice: "C", explanation: "No legitimate IT department needs your password. Administrators have privileged access to perform maintenance without knowing your credentials. A request for your password is a definitive indicator of a social engineering attack regardless of how convincing the caller's identity seems." },
        { question_text: "What is MFA fatigue and how does it work as an attack technique?", choice_a: "The security risk created when users choose weak PINs for their MFA apps out of frustration with complex requirements", choice_b: "An attack where the attacker repeatedly sends MFA approval requests to the victim until they approve one just to stop the notifications", choice_c: "The tendency for users to disable MFA after finding it inconvenient over a long period", correct_choice: "B", explanation: "MFA fatigue attacks bombard the victim with push notification approval requests at all hours until the victim approves one to make it stop. The solution is to use MFA methods that require the user to enter a code rather than simply approve a push notification, or to use hardware keys that cannot be MFA-fatigued." },
        { question_text: "How do attackers use fake IT helpdesk calls to defeat MFA?", choice_a: "Attackers impersonate IT staff to convince users to disable MFA on their accounts for a supposed upgrade", choice_b: "Attackers call while simultaneously attempting to log in with stolen credentials, then ask the victim to read them the MFA code they just received to complete the supposed IT procedure", choice_c: "Attackers social engineer IT staff into resetting MFA for target accounts using internal employee information", correct_choice: "B", explanation: "Real-time MFA relay is a sophisticated attack. The attacker triggers a real MFA code to the victim's phone during a convincing helpdesk call, then asks the victim to read it back to complete a supposed account verification procedure. The code is then immediately used to complete the attacker's login." },
      ],
    },
    {
      title: "Module 6: Single Sign-On and Identity Providers",
      content: "Single sign-on allows users to authenticate once and access multiple systems without separate logins. Understanding how SSO works and its security implications helps you use it safely and recognize when it creates risk.",
      category: "Identity Management", difficulty: "intermediate", duration_minutes: 10, order_index: 6,
      quiz: [
        { question_text: "What is single sign-on and what is the main security advantage it provides for organizations?", choice_a: "A feature that allows one shared account to be used by multiple employees to reduce license costs", choice_b: "A system where users authenticate once to a central identity provider that grants them access to all connected applications, reducing password proliferation and centralizing authentication controls", choice_c: "A method that allows users to reset their own passwords without contacting IT support", correct_choice: "B", explanation: "SSO reduces password proliferation, which reduces the attack surface. Instead of dozens of separate passwords for dozens of applications, users have one strong credential centrally managed. Security controls like MFA, logging, and access revocation can be applied centrally rather than per-application." },
        { question_text: "What is the biggest security risk associated with single sign-on?", choice_a: "SSO is slower than individual logins which reduces employee productivity", choice_b: "Compromising the central SSO account gives the attacker access to every application connected to it, making the SSO credential an extremely high-value target", choice_c: "SSO systems are difficult to update, creating unpatched vulnerabilities over time", correct_choice: "B", explanation: "SSO is a single point of failure for identity. Compromising the SSO credential is more valuable to an attacker than compromising any individual application credential because it grants access to everything. This makes MFA on the SSO account mandatory and the SSO credential the most important password the user manages." },
        { question_text: "When you click Log in with Google or Log in with Apple on a third-party site, what are you actually doing?", choice_a: "Sharing your Google or Apple password with the third-party site for them to verify", choice_b: "Authorizing Google or Apple to share a limited token with the third-party site confirming your identity without exposing your actual credentials", choice_c: "Creating a copy of your Google or Apple account on the third-party site's servers", correct_choice: "B", explanation: "OAuth-based social login uses tokens not passwords. Google or Apple authenticates you and then tells the third-party site you are who you say you are without ever sharing your actual credentials. The third-party site gets a token proving identity, not your password." },
      ],
    },
    {
      title: "Module 7: Privileged Access Management",
      content: "Privileged accounts with administrative access are the highest-value targets in any organization. Managing and protecting them requires additional controls beyond standard user account security.",
      category: "Identity Management", difficulty: "advanced", duration_minutes: 10, order_index: 7,
      quiz: [
        { question_text: "Why should administrators use separate accounts for privileged tasks versus everyday computing?", choice_a: "Separate accounts are required by auditors but do not provide meaningful additional security", choice_b: "Everyday computing activities like browsing and email carry malware risk. If the browsing account is compromised, a separate admin account limits the blast radius to prevent immediate full environment takeover", choice_c: "Separate accounts help track hours spent on administrative versus regular work tasks", correct_choice: "B", explanation: "Browsing the web and reading email are the most common malware delivery vectors. If an admin account is used for everyday activity and malware runs in that session, it immediately has administrative access to everything. Separating accounts means compromised browsing credentials do not equal compromised infrastructure." },
        { question_text: "What is just-in-time privileged access and why is it more secure than persistent admin rights?", choice_a: "A schedule that grants admin rights during business hours and removes them at night to prevent after-hours attacks", choice_b: "A system where admin rights are granted only for the duration needed for a specific task and automatically revoked afterward, minimizing the window during which compromised admin credentials can be used", choice_c: "A training program that grants increasing privilege levels as administrators demonstrate competency", correct_choice: "B", explanation: "Persistent admin rights mean that if an admin account is compromised at any time, the attacker has full privileges indefinitely. Just-in-time access means the window of risk is limited to the brief period the rights are active. A compromised account outside that window has no special privileges." },
        { question_text: "What is a privileged access workstation and what threat does it mitigate?", choice_a: "A high-performance computer used for resource-intensive administrative tasks", choice_b: "A dedicated, hardened device used exclusively for administrative tasks, preventing the malware risks of everyday computing from existing in the same session as privileged credentials", choice_c: "A workstation with enhanced monitoring that records all administrative activity for audit purposes", correct_choice: "B", explanation: "A privileged access workstation is a hardened device with no internet browsing, no email, and minimal attack surface, used only for administrative tasks. It physically separates the high-risk environment of everyday computing from the high-value environment of privileged access, preventing the cross-contamination that separate accounts alone cannot fully prevent." },
      ],
    },
    {
      title: "Module 8: Account Recovery Security",
      content: "Account recovery mechanisms are often the weakest link in an otherwise strong authentication system. How you set up and protect your recovery options determines whether your other security measures can be bypassed.",
      category: "Identity Management", difficulty: "intermediate", duration_minutes: 8, order_index: 8,
      quiz: [
        { question_text: "Why are traditional security questions a weak account recovery mechanism?", choice_a: "Security questions require too much memory effort from users who struggle to remember the answers", choice_b: "The answers to security questions like mother's maiden name or high school are often findable through public records and social media, making them guessable or researchable by attackers", choice_c: "Security questions are vulnerable to brute force attacks because there are a limited number of possible answers", correct_choice: "B", explanation: "Security questions rely on information that is often public. Your mother's maiden name may be in a genealogy database. Your high school and hometown are on your social media profile. Treating security question answers as passwords by using random strings defeats this but is hard to manage without a password manager." },
        { question_text: "What is the safest approach to configuring backup codes for MFA?", choice_a: "Store backup codes in your email account for convenient access if you lose your phone", choice_b: "Print backup codes and store them in a physically secure location like a safe, since they provide full account access without the primary MFA factor", choice_c: "Screenshot backup codes and store them in your phone's photo library for easy access", correct_choice: "B", explanation: "Backup codes are as powerful as your primary credentials combined with MFA. Storing them in email or photos creates an easily accessible bypass. Physical storage in a secure location means an attacker needs physical access to your safe, not just your compromised device or account." },
        { question_text: "Why should your account recovery email address have stronger security than the accounts it can recover?", choice_a: "Recovery email addresses are shared with service providers and need more protection against provider data breaches", choice_b: "If the recovery email address is less secure than the accounts it can recover, an attacker who compromises it can immediately reset passwords on all of those accounts, bypassing every other security measure", choice_c: "Recovery email addresses are stored in plaintext by services so they need additional protection", correct_choice: "B", explanation: "Your recovery email is a master key. Securing your main accounts with strong passwords and MFA while using a weak recovery email address means an attacker who compromises the recovery email can reset everything. The recovery path is as strong as its weakest link." },
      ],
    },
    {
      title: "Module 9: Identity Theft and Account Takeover",
      content: "Identity theft occurs when an attacker uses your personal information to impersonate you for financial gain or other purposes. Account takeover is a related but distinct attack targeting specific online accounts. Understanding both helps you protect yourself and respond effectively if targeted.",
      category: "Identity Protection", difficulty: "intermediate", duration_minutes: 10, order_index: 9,
      quiz: [
        { question_text: "What is the difference between identity theft and account takeover?", choice_a: "Identity theft affects government records while account takeover affects only private accounts", choice_b: "Account takeover targets specific existing accounts while identity theft uses your personal information to open new accounts, take out loans, or commit fraud in your name", choice_c: "Identity theft and account takeover are the same attack described using different terminology", correct_choice: "B", explanation: "Account takeover hijacks your existing accounts. Identity theft uses your personal information to create new fraudulent accounts, loans, or records in your name without needing your existing account passwords. Both can occur together when a compromised account provides the personal information used for identity theft." },
        { question_text: "What should you do if you discover that your information was included in a publicly disclosed data breach?", choice_a: "Wait to see if you notice unauthorized activity on your accounts before taking action", choice_b: "Immediately change the password on the breached service and on any other service where you used the same password, enable MFA if not already active, and monitor for suspicious activity", choice_c: "Close your account on the breached service and never use it again", correct_choice: "B", explanation: "Acting immediately limits damage. Change the breached password first, then audit every other account that used the same password and change those too. Enable MFA everywhere possible. Monitor financial accounts for unauthorized activity. Credential stuffing attacks begin within hours of a breach becoming available." },
        { question_text: "What is a credit freeze and when should you consider using one?", choice_a: "A feature that prevents your credit score from changing during a dispute investigation", choice_b: "A control that prevents credit reporting agencies from sharing your credit report with potential lenders, making it nearly impossible for someone to open new credit in your name without your explicit unfreeze action", choice_c: "A service that alerts you when someone applies for credit in your name", correct_choice: "B", explanation: "A credit freeze is the strongest protection against new account fraud. With a freeze in place, a lender checking your credit for a new application gets a blocked response. Even if an attacker has all your personal information, they cannot open new credit accounts without your unfreeze action. It is free at all major bureaus in the US." },
      ],
    },
    {
      title: "Module 10: Building a Personal Identity Security System",
      content: "Effective personal identity security is not a single action but a layered system of tools and habits. This module ties together everything from the section into a practical personal security posture you can maintain.",
      category: "Password Security", difficulty: "beginner", duration_minutes: 8, order_index: 10,
      quiz: [
        { question_text: "What is the correct priority order for improving personal account security?", choice_a: "Update passwords first, then enable MFA, then set up a password manager", choice_b: "Set up a password manager first, then use it to create unique strong passwords everywhere, then enable MFA starting with the highest-value accounts like email and banking", choice_c: "Enable MFA first on every account, then create a password manager, then update all passwords", correct_choice: "B", explanation: "A password manager is the foundation because it enables everything else. Without it, strong unique passwords are not sustainable. Once the manager is in place, update passwords starting with highest-value accounts, then enable MFA starting with email since it is the master key that can recover everything else." },
        { question_text: "How should you handle a service that does not support MFA?", choice_a: "Avoid using the service entirely since no MFA is an unacceptable security risk", choice_b: "Use a uniquely strong password for that service, recognize it as higher risk, and avoid linking it to more sensitive accounts or storing sensitive information in it", choice_c: "Use the same password as your email since MFA on email compensates for the lack of MFA on this service", correct_choice: "B", explanation: "Avoiding all services without MFA is not practical. The realistic approach is risk management. Give it a unique strong password from your password manager, minimize what sensitive information you store there, and do not link it as a recovery method for more important accounts. Recognize its elevated risk and treat it accordingly." },
        { question_text: "What ongoing habit keeps your personal identity security posture current over time?", choice_a: "Changing all passwords on a fixed schedule like every January first", choice_b: "Checking breach notification services for your email addresses, reviewing account access logs periodically, and updating your password manager when you change passwords", choice_c: "Performing a full security audit of every account every month", correct_choice: "B", explanation: "Sustainable security hygiene beats burst activity. Checking services like HaveIBeenPwned for breach notifications, reviewing which apps have access to your accounts periodically, and keeping your password manager current gives you ongoing visibility without an unmanageable monthly burden." },
      ],
    },
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS11 };
