const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS1(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='Security Awareness'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    {
      title: "Module 1: Phishing Basics",
      content: "Phishing uses social engineering to trick people into clicking malicious links, opening attachments, or sharing sensitive data. Look for urgency, mismatched domains, and unexpected requests.",
      category: "Email Security", difficulty: "beginner", duration_minutes: 10, order_index: 1,
      quiz: [
        { question_text: "What does hovering over a link in an email before clicking it reveal?", choice_a: "The true destination URL so you can verify it goes where it claims", choice_b: "Whether the email was sent from a verified sender", choice_c: "The date the link was created", correct_choice: "A", explanation: "Hovering reveals the actual destination URL in your browser status bar without loading the page, letting you spot lookalike or malicious domains before clicking." },
        { question_text: "Which of these is a hallmark tactic used in phishing emails?", choice_a: "A polite greeting and professional signature", choice_b: "A newsletter you previously subscribed to", choice_c: "Urgent language threatening account suspension to pressure you into acting without thinking", correct_choice: "C", explanation: "Urgency is the most consistent phishing indicator. Attackers create artificial time pressure to bypass your critical thinking. Slowing down to verify is the correct response." },
        { question_text: "What should you do if you clicked a suspicious link before realizing it was phishing?", choice_a: "Close the browser tab and monitor for anything unusual over the next few days", choice_b: "Report it to IT immediately and change your passwords even if you did not enter credentials", choice_c: "Only act if the page asked you to log in", correct_choice: "B", explanation: "Even clicking without entering credentials can trigger drive-by downloads that install malware silently. Report it immediately so IT can assess and respond." },
      ],
    },
    {
      title: "Module 2: Credential Theft",
      content: "Credential theft attacks often use fake login pages, account alerts, and urgent prompts. Always verify the domain before entering passwords.",
      category: "Identity Protection", difficulty: "beginner", duration_minutes: 10, order_index: 2,
      quiz: [
        { question_text: "What is the safest way to reach a login page for your bank or email?", choice_a: "Click the link in the email notification from the service", choice_b: "Search for the site and use the first result", choice_c: "Type the address directly in the browser or use a saved bookmark you created yourself", correct_choice: "C", explanation: "Bookmarks and direct URL entry eliminate the risk of being redirected to a lookalike phishing page. Search results can be manipulated and email links can be fake." },
        { question_text: "A page looks identical to your bank website but something feels wrong. What should you verify first?", choice_a: "Whether the design matches what you remember", choice_b: "The full domain in the address bar to confirm it is the real site", choice_c: "Whether the page loaded quickly", correct_choice: "B", explanation: "Attackers can pixel-perfectly copy any website design. The URL domain is the only reliable indicator. Check that it is exactly right before entering any credentials." },
        { question_text: "Why does using the same password on multiple sites make a single breach catastrophic?", choice_a: "Attackers run automated credential stuffing attacks that try breached passwords against hundreds of other services immediately", choice_b: "Password reuse makes passwords easier for attackers to guess", choice_c: "Reused passwords expire faster than unique ones", correct_choice: "A", explanation: "Credential stuffing automates testing breached credentials across many services. One compromised site cascades to every other site where you reused that password." },
      ],
    },
    {
      title: "Module 3: Business Email Scams",
      content: "Business scams often imitate invoices, HR, payroll, or executive requests. Verify through trusted channels before taking action.",
      category: "Email Security", difficulty: "intermediate", duration_minutes: 12, order_index: 3,
      quiz: [
        { question_text: "You receive an urgent email appearing to be from your CEO requesting a wire transfer before close of business. What is the correct action?", choice_a: "Process it since the CEO name and signature look correct", choice_b: "Call the CEO back on a number you already have to verbally confirm before taking any financial action", choice_c: "Reply to the email asking for a purchase order number first", correct_choice: "B", explanation: "BEC attacks spoof executive addresses perfectly. Always verify financial requests through an independent channel you already have. Replying to the suspicious email reaches the attacker." },
        { question_text: "What makes a request to secretly handle a financial transaction a major red flag?", choice_a: "Legitimate business transactions do not require secrecy from colleagues, so a secrecy request is a manipulation tactic to prevent you from getting a second opinion", choice_b: "Financial transactions always require public announcement before processing", choice_c: "Secrets are only appropriate for surprise events not business transactions", correct_choice: "A", explanation: "Real executives understand that financial controls and transparency protect the organization. Requests for secrecy specifically prevent the verification steps that would expose the fraud." },
        { question_text: "A vendor sends an email saying their bank account details have changed. What should you do?", choice_a: "Update the details immediately to avoid disrupting payment schedules", choice_b: "Reply to the email asking them to confirm the change in writing", choice_c: "Call the vendor on a phone number from your existing records to verbally verify the change before updating anything", correct_choice: "C", explanation: "Bank detail change requests are a primary BEC vector. The confirmation must come through an independent channel. Calling a number from the suspicious email reaches the attacker." },
      ],
    },
    {
      title: "Module 4: Smishing and Mobile Safety",
      content: "Smishing uses text messages to create urgency and push users toward malicious links or fake delivery, payroll, or account pages.",
      category: "Mobile Security", difficulty: "beginner", duration_minutes: 8, order_index: 4,
      quiz: [
        { question_text: "You receive a text saying your package is held and to confirm details now. What is the safest action?", choice_a: "Tap the link since you are often expecting deliveries", choice_b: "Reply to the text with your address to confirm", choice_c: "Open the official carrier app or website directly to check your tracking", correct_choice: "C", explanation: "Always use official apps for delivery verification. Smishing links lead to credential harvesting pages designed to steal your information." },
        { question_text: "What makes smishing particularly effective compared to email phishing?", choice_a: "Mobile users tend to act quickly without scrutinizing shortened URLs or sender details", choice_b: "Phones cannot detect malicious links at all", choice_c: "SMS messages bypass all spam filters automatically", correct_choice: "A", explanation: "The mobile context encourages quick impulsive reactions, and shortened URLs on mobile hide the destination domain that would reveal the scam." },
        { question_text: "What is juice jacking and how do you protect against it?", choice_a: "A scam where attackers overcharge for phone repairs at unofficial repair shops", choice_b: "Malware delivery or data theft through compromised public USB charging ports, prevented by using your own charger with an AC outlet or a USB data blocker", choice_c: "A technique for stealing phone data through public Wi-Fi hotspots", correct_choice: "B", explanation: "Modified public USB charging ports can deliver malware or silently copy data while charging your device. Your own AC charger or a USB data blocker that passes power but blocks data pins eliminates this risk." },
      ],
    },
    {
      title: "Module 5: Vishing and Phone Based Scams",
      content: "Vishing uses voice calls and callback requests to pressure users into revealing credentials, MFA codes, or payment information.",
      category: "Voice Security", difficulty: "intermediate", duration_minutes: 10, order_index: 5,
      quiz: [
        { question_text: "A caller claims to be from IT and says they need your one-time MFA code to fix a problem with your account. What do you do?", choice_a: "Give them the code since IT legitimately needs access to fix account problems", choice_b: "Refuse immediately. No legitimate IT person or organization will ever ask you to read back a one-time code", choice_c: "Read them only the first three digits as a security compromise", correct_choice: "B", explanation: "One-time codes are yours alone to enter on the website. Any caller requesting you read one back is stealing your authentication code to take over your account." },
        { question_text: "A call comes in showing your company phone number on caller ID. What does this tell you about the call?", choice_a: "The call is definitely from within your organization since the number matches", choice_b: "The number may have routing issues which explains why it shows internally", choice_c: "Nothing definitive since caller ID can be spoofed to display any number regardless of where the call actually originates", correct_choice: "C", explanation: "Caller ID spoofing technology is freely available and widely used by scammers. The displayed number provides no reliable confirmation of the actual caller. Verify through a callback on a number you already have." },
        { question_text: "A caller claims to be from the IRS and says you will be arrested in two hours unless you pay immediately via gift cards. What is this?", choice_a: "A government impersonation scam. No legitimate government agency ever demands payment by gift card or threatens immediate arrest via phone", choice_b: "A legitimate collection method used when tax debts are severely overdue", choice_c: "A payment option only offered to taxpayers with no bank account", correct_choice: "A", explanation: "Gift card payment demands from supposed government agencies are a universally recognized fraud pattern. Real government agencies communicate primarily by mail, accept disputes, and never demand gift card payment." },
      ],
    },
    {
      title: "Module 6: MFA Fatigue and Push Attacks",
      content: "MFA fatigue attacks rely on repeated push prompts to trick users into approving a sign in they did not initiate.",
      category: "Authentication", difficulty: "intermediate", duration_minutes: 8, order_index: 6,
      quiz: [
        { question_text: "You receive ten MFA push notification requests in two minutes that you did not initiate. What is happening?", choice_a: "Your authenticator app has a technical glitch causing duplicate notifications", choice_b: "Your account is being synchronized across devices which triggers multiple prompts", choice_c: "An attacker has your password and is flooding you with push requests hoping you approve one out of frustration", correct_choice: "C", explanation: "Unsolicited MFA push notifications always mean someone else has your password and is actively attempting to log in. This is a MFA fatigue attack in progress." },
        { question_text: "What is the correct immediate response to an MFA fatigue attack?", choice_a: "Approve one notification to stop the flood then immediately change your password", choice_b: "Deny all requests, change your password immediately to stop the login attempts, and report the incident", choice_c: "Turn off push notifications and switch to SMS codes temporarily", correct_choice: "B", explanation: "Changing your password stops the attack at the source since the attacker can no longer log in with your old credentials. Approving any notification gives them full access before you can act." },
        { question_text: "What makes number-matching MFA more resistant to fatigue attacks than simple approve or deny push notifications?", choice_a: "Number matching requires matching a code displayed on the login screen to a code in your authenticator app, making blind approvals impossible", choice_b: "Number matching sends fewer notifications making the attack less effective", choice_c: "Number matching only works on registered devices that the attacker does not have", correct_choice: "A", explanation: "Simple push approval requires only a tap without verifying anything. Number matching requires you to read a specific code on the login page and confirm it in the app, preventing the reflexive approvals that MFA fatigue relies on." },
      ],
    },
    {
      title: "Module 7: USB Baiting and Physical Security",
      content: "Unknown USB drives, fake badges, and tailgating are physical security risks. Never connect unknown devices to company systems.",
      category: "Physical Security", difficulty: "beginner", duration_minutes: 8, order_index: 7,
      quiz: [
        { question_text: "You find a USB drive in the office parking lot labeled Salary Data. What should you do?", choice_a: "Plug it into your computer to find the owner so you can return it", choice_b: "Turn it over to IT or security without connecting it to any device", choice_c: "Take it home and check it on a personal device where it cannot harm work systems", correct_choice: "B", explanation: "USB baiting specifically uses enticing labels to exploit curiosity and helpfulness. Plugging in an unknown drive executes its payload instantly. Turn it over to IT without connecting it anywhere." },
        { question_text: "What is tailgating in physical security and why is it dangerous?", choice_a: "Following an authorized person through a secured door without using your own credentials, bypassing physical access controls entirely", choice_b: "Reading over a colleague shoulder to see sensitive information on their screen", choice_c: "Copying files to a USB drive while a security guard is distracted", correct_choice: "A", explanation: "Tailgating exploits the social norm of holding doors for people. An attacker with physical access can plant hardware, photograph screens, steal devices, and access unlocked workstations." },
        { question_text: "What is dumpster diving in the context of information security?", choice_a: "Searching through old emails and deleted files for forgotten passwords", choice_b: "Installing spyware on discarded computers found in recycling bins", choice_c: "Searching through physical trash and recycling for documents containing sensitive information like passwords, network diagrams, or customer data", correct_choice: "C", explanation: "Physical documents in the trash can expose valuable intelligence. Shred all documents with any sensitive content before disposal. This applies to any paper with names, systems, credentials, or organizational information." },
      ],
    },
    {
      title: "Module 8: Safe Browsing and QR Code Risks",
      content: "Malicious websites and QR codes can redirect users to phishing or malware pages. Verify destinations before visiting.",
      category: "Web Security", difficulty: "beginner", duration_minutes: 10, order_index: 8,
      quiz: [
        { question_text: "What does the padlock icon and HTTPS in your browser address bar actually confirm?", choice_a: "The connection between your browser and the server is encrypted, but it does not confirm the site is legitimate or not phishing", choice_b: "The website has been verified as legitimate by your browser vendor", choice_c: "Your antivirus has scanned the site and found no threats", correct_choice: "A", explanation: "HTTPS only confirms the connection is encrypted. Phishing sites routinely obtain valid TLS certificates and display the padlock too. Always verify the domain, not just the padlock." },
        { question_text: "A webpage displays a large security warning saying your computer is infected and provides a phone number to call for help. What should you do?", choice_a: "Call the number immediately since your browser detected the infection", choice_b: "Download the security tool the page offers to remove the infection quickly", choice_c: "Close the browser tab immediately. Legitimate security software never displays infection alerts in a webpage with a phone number to call", correct_choice: "C", explanation: "Browser-based security warnings with phone numbers are always fake tech support scams. Real antivirus software displays alerts in its own application interface, never in a webpage." },
        { question_text: "What should you check before tapping the URL that appears when your camera scans a QR code?", choice_a: "Whether the QR code is in a high-resolution format", choice_b: "That the domain in the URL preview matches the legitimate organization you expect and has not been replaced by a lookalike domain", choice_c: "Whether the QR code was printed recently", correct_choice: "B", explanation: "QR codes are just URLs your camera reads. Malicious stickers can be placed over legitimate QR codes. Always check the destination URL preview before tapping, just as you would hover over a link in email." },
      ],
    },
    {
      title: "Module 9: Password and Authentication Hygiene",
      content: "Use strong unique passwords, password managers, and MFA. Never reuse passwords or share one time codes.",
      category: "Authentication", difficulty: "beginner", duration_minutes: 10, order_index: 9,
      quiz: [
        { question_text: "What factor most determines password strength against brute-force attacks?", choice_a: "The inclusion of at least two special characters", choice_b: "Avoiding dictionary words by using random letter substitutions", choice_c: "Length, since each additional character multiplies the search space an attacker must cover exponentially", correct_choice: "C", explanation: "A 20-character passphrase is exponentially stronger than an 8-character complex password. Length matters more than complexity because the math of brute force grows exponentially with each character added." },
        { question_text: "Why is a password manager considered essential rather than a convenience tool?", choice_a: "Without a password manager it is impossible in practice to use long unique random passwords for every account, which is the foundation of credential security", choice_b: "Password managers are required by most workplace security policies", choice_c: "Password managers allow you to share credentials securely with colleagues", correct_choice: "A", explanation: "The human brain cannot memorize dozens of strong unique passwords. Password managers make strong unique credentials practical by generating and storing them, eliminating the password reuse that enables credential stuffing attacks." },
        { question_text: "Which MFA method provides the strongest protection against phishing attacks specifically?", choice_a: "SMS text message codes sent to your phone number", choice_b: "Hardware security keys or passkeys that cryptographically verify the site domain before authenticating", choice_c: "Email verification codes sent to your inbox", correct_choice: "B", explanation: "Hardware keys and passkeys verify the actual domain before authenticating. They will not authenticate to a fake phishing site even if the site looks identical, because the domain does not match what is registered with the key." },
      ],
    },
    {
      title: "Module 10: Ransomware Awareness",
      content: "Ransomware encrypts your files and demands payment for the decryption key. It most often arrives through phishing emails with malicious attachments or links.",
      category: "Malware", difficulty: "intermediate", duration_minutes: 12, order_index: 10,
      quiz: [
        { question_text: "An Office document you received by email asks you to click Enable Content to view it. What should you do?", choice_a: "Close the document immediately and report it to IT without enabling macros", choice_b: "Enable the content since the document needs macros to display properly", choice_c: "Enable macros but only read the document without saving any changes", correct_choice: "A", explanation: "Enabling macros in unexpected documents is the primary ransomware delivery mechanism. No legitimate document requires macros just to display its content. This prompt is a social engineering technique." },
        { question_text: "What does the 3-2-1 backup rule specify?", choice_a: "Back up at 3 AM, keep 2 weeks of history, use 1 cloud provider", choice_b: "Three password attempts, two recovery codes, one administrator account", choice_c: "Three copies of data, on two different media types, with one copy offsite or in cloud storage that ransomware on your local system cannot reach", correct_choice: "C", explanation: "The offsite or cloud component is critical for ransomware protection. Ransomware encrypts all accessible storage including attached drives. An isolated offline or cloud backup is the only recovery path without paying the ransom." },
        { question_text: "What is the single most important immediate action when you notice active ransomware encrypting files?", choice_a: "Pay the ransom quickly before the price increases", choice_b: "Disconnect the device from the network immediately to prevent the ransomware from spreading to other networked systems", choice_c: "Shut down the computer to stop the encryption process", correct_choice: "B", explanation: "Network disconnection stops lateral movement to other devices. In enterprise environments ransomware operators deploy across the network simultaneously. Isolating immediately limits how many systems are encrypted." },
      ],
    },
    {
      title: "Module 11: Insider Threats",
      content: "Insider threats come from current or former employees, contractors, or partners who misuse access. Signs include unusual data access, large file transfers, and out-of-hours system access.",
      category: "Human Factors", difficulty: "intermediate", duration_minutes: 12, order_index: 11,
      quiz: [
        { question_text: "Which type of insider threat is statistically the most common?", choice_a: "Malicious employees deliberately stealing data for financial gain", choice_b: "Negligent employees who cause incidents through carelessness, poor password practices, or falling for phishing rather than malicious intent", choice_c: "Former employees retaining access after leaving the organization", correct_choice: "B", explanation: "Negligent insiders vastly outnumber malicious ones. Employees who click phishing links, mishandle sensitive data, or violate security policies without harmful intent cause the majority of insider-related incidents." },
        { question_text: "An employee who is leaving the company next week suddenly begins accessing large volumes of files outside their normal work area. What does this suggest?", choice_a: "They are trying to catch up on work before their last day", choice_b: "They may be curious about how the company operates in other departments", choice_c: "This is a warning sign of potential data exfiltration. Unusual bulk data access combined with an upcoming departure is a primary insider threat indicator", correct_choice: "C", explanation: "The combination of impending departure and unusual broad data access is one of the most consistent behavioral patterns preceding insider data theft. Monitoring systems flag exactly this pattern for investigation." },
        { question_text: "What is the least privilege principle and how does it reduce insider threat risk?", choice_a: "Each employee should have access only to the data and systems needed for their specific job function, limiting what any single insider can steal or accidentally expose", choice_b: "Employees should have the least number of passwords possible to reduce security fatigue", choice_c: "Junior employees should have fewer system permissions than senior employees regardless of their role requirements", correct_choice: "A", explanation: "Least privilege limits blast radius. An employee who can only access data relevant to their role cannot steal or accidentally expose data they were never authorized to see, regardless of intent." },
      ],
    },
    {
      title: "Module 12: Social Engineering and Pretexting",
      content: "Social engineering manipulates people rather than exploiting software. Attackers build false context through pretexting to extract sensitive information or access.",
      category: "Human Factors", difficulty: "intermediate", duration_minutes: 12, order_index: 12,
      quiz: [
        { question_text: "What is pretexting in social engineering?", choice_a: "A legal warning message that must appear before a phishing site loads", choice_b: "An automated script attackers use to generate phishing emails", choice_c: "A fabricated backstory an attacker creates to establish false credibility before making a request for sensitive information or access", correct_choice: "C", explanation: "Pretexting involves creating a false context such as posing as IT support, a new vendor, an auditor, or a law enforcement officer to make the request seem legitimate and lower the target's defenses." },
        { question_text: "Which psychological principle do social engineers most consistently rely on across attack types?", choice_a: "Urgency combined with authority, creating pressure to comply with a request from a perceived authority figure before the target has time to verify", choice_b: "Curiosity about new technologies and systems", choice_c: "The desire to appear technically competent to colleagues", correct_choice: "A", explanation: "Urgency prevents verification. Authority suppresses the instinct to question. Together they reliably override normal critical thinking regardless of whether the specific scam is a tech support call, phishing email, or romance scam." },
        { question_text: "What is the most effective defense against a well-crafted social engineering attack?", choice_a: "Refusing to interact with anyone you do not personally recognize", choice_b: "Verifying unusual requests independently through a communication channel you already trust, regardless of how convincing the original request seems", choice_c: "Installing social engineering detection software that flags suspicious requests", correct_choice: "B", explanation: "Independent verification breaks the social engineering chain entirely. If you call back on a number you already have rather than one the attacker provided, impersonation is defeated regardless of how convincing the pretext was." },
      ],
    },
    {
      title: "Module 13: Safe Remote Work and VPN",
      content: "Remote work expands the attack surface significantly. Use your company VPN whenever accessing internal systems from outside the office.",
      category: "Network Security", difficulty: "intermediate", duration_minutes: 10, order_index: 13,
      quiz: [
        { question_text: "What is an evil twin Wi-Fi attack?", choice_a: "A rogue wireless access point broadcasting the same network name as a legitimate network to intercept the traffic of devices that connect to it", choice_b: "A malware attack that creates a backup copy of your files on a remote server", choice_c: "A phishing attack delivered through fake collaboration tool notifications", correct_choice: "A", explanation: "Evil twin attacks create fake Wi-Fi networks indistinguishable by name from legitimate ones. Devices that connect route all their traffic through the attacker's equipment, enabling man-in-the-middle interception." },
        { question_text: "Why is it important to use your corporate VPN when working from home rather than your home internet connection directly?", choice_a: "The corporate VPN is faster than your home internet connection", choice_b: "The corporate VPN prevents your employer from monitoring your personal browsing", choice_c: "The corporate VPN routes work traffic through your organization's security infrastructure and encrypts it from exposure on your home network", correct_choice: "C", explanation: "Corporate VPN ensures work traffic passes through organizational security controls, encrypts it across your home network, and provides access to internal resources as if you were physically in the office." },
        { question_text: "What does shoulder surfing mean and how do you protect against it when working in public?", choice_a: "A tactic where attackers observe your screen or keyboard from nearby to capture sensitive information, prevented by positioning against a wall or using a privacy screen filter", choice_b: "A network attack where traffic is captured from nearby Wi-Fi users", choice_c: "A social engineering technique where attackers pretend to need help while observing your login process", correct_choice: "A", explanation: "Shoulder surfing is physical observation of your screen or keyboard. In coffee shops, airports, and shared spaces, positioning yourself against a wall and using a privacy screen filter prevents unauthorized viewing of your work." },
      ],
    },
    {
      title: "Module 14: Data Classification and Handling",
      content: "Not all data carries the same risk. Most organizations classify data as public, internal, confidential, or restricted. Handle each level appropriately.",
      category: "Data Security", difficulty: "intermediate", duration_minutes: 10, order_index: 14,
      quiz: [
        { question_text: "Why should confidential data never be transmitted through personal email accounts?", choice_a: "Personal email accounts have smaller attachment size limits", choice_b: "Personal email is outside organizational security controls, creating an unmanaged copy of sensitive data with no access control, audit trail, or encryption guarantee", choice_c: "Personal email is slower and less reliable than corporate email systems", correct_choice: "B", explanation: "Using personal email for work data bypasses every security control the organization has implemented: encryption requirements, access logging, DLP tools, and data retention policies." },
        { question_text: "How should paper documents containing confidential customer information be disposed of?", choice_a: "Shredded using a cross-cut shredder before disposal to prevent reconstruction", choice_b: "Recycled in the standard paper recycling bin since the office handles disposal securely", choice_c: "Folded and placed in a sealed envelope before putting in the trash", correct_choice: "A", explanation: "Documents in recycling bins are accessible and dumpster diving specifically targets improperly disposed documents. Cross-cut shredding makes reconstruction practically impossible." },
        { question_text: "What is shadow IT and why does it create organizational security risk?", choice_a: "Unauthorized access to servers after business hours by disgruntled employees", choice_b: "Employees using personal devices on corporate networks without authorization", choice_c: "Using consumer apps and cloud services for work data without IT approval, placing sensitive data outside organizational security controls and compliance requirements", correct_choice: "C", explanation: "Shadow IT places organizational data in systems IT cannot apply security policies to, cannot audit, cannot ensure proper backup of, and cannot delete from when required by policy or regulation." },
      ],
    },
    {
      title: "Module 15: AI-Powered Attacks and Deepfakes",
      content: "AI is being used to craft convincing phishing emails, clone voices, and generate deepfake video of executives. Verify unexpected requests through independent channels.",
      category: "Emerging Threats", difficulty: "advanced", duration_minutes: 12, order_index: 15,
      quiz: [
        { question_text: "What specific capability does AI give attackers that makes phishing significantly more dangerous?", choice_a: "AI allows attackers to bypass email spam filters automatically", choice_b: "AI provides attackers with verified sender addresses that pass email authentication", choice_c: "AI generates grammatically perfect personalized messages at scale, removing the quality indicators that previously helped identify phishing", correct_choice: "C", explanation: "Traditional phishing was detectable by poor grammar, generic greetings, and awkward phrasing. AI removes these tells and enables personalized spear phishing at mass scale, making content quality an unreliable detection method." },
        { question_text: "How should you verify an unexpected financial request from someone whose voice sounds exactly like your CEO?", choice_a: "Contact the person through a completely separate communication channel using contact information you already have independently of the suspicious request", choice_b: "Ask them a personal question that only the real CEO would know", choice_c: "Request that they send a follow-up email to confirm the request in writing", correct_choice: "A", explanation: "AI voice cloning can replicate voices convincingly. Multi-channel verification using independently known contact information defeats cloning because the attacker would need to compromise multiple independent channels simultaneously." },
        { question_text: "What is a verbal code word and why does it provide protection that technology alone cannot?", choice_a: "A passphrase used to encrypt voice messages before sending them", choice_b: "A pre-established secret word known only to the real person that AI cloning cannot replicate without knowing the specific word in advance", choice_c: "A spoken password used to unlock voice-activated security systems", correct_choice: "B", explanation: "A code word agreed upon in advance provides a verification layer that requires prior knowledge of the specific word. AI cloning reproduces the voice but cannot reproduce information the attacker did not already have." },
      ],
    },
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS1 };
