const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS2(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='Computer Troubleshooting'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    {
      title: "CT Module 1: Diagnosing a Slow PC",
      content: "A slow computer is most often caused by high resource usage, too many startup programs, low disk space, or thermal throttling. Use Task Manager to identify the specific cause before trying fixes.",
      category: "Performance", difficulty: "beginner", duration_minutes: 10, order_index: 1,
      quiz: [
        { question_text: "What is the most effective first step when diagnosing an unexpectedly slow Windows computer?", choice_a: "Run a full antivirus scan to check for malware", choice_b: "Open Task Manager and check the Performance and Processes tabs to identify which specific process is consuming CPU, memory, or disk", choice_c: "Restart the computer and see if performance improves", correct_choice: "B", explanation: "Task Manager shows real-time resource consumption per process. Identifying the specific cause of high CPU, memory, or disk usage directs troubleshooting to the actual problem rather than applying random fixes." },
        { question_text: "What is thermal throttling and what symptom does it typically cause?", choice_a: "A processor automatically reducing its clock speed to prevent heat damage, causing slowness that appears only under sustained load while the computer feels normal during light tasks", choice_b: "A Windows feature that reduces screen brightness to save battery when temperatures rise", choice_c: "A storage drive reducing its read speed when approaching capacity limits", correct_choice: "A", explanation: "Thermal throttling is automatic self-protection. A computer that feels slow under load but responsive otherwise is often throttling due to inadequate cooling. Monitoring temperatures with HWMonitor confirms this." },
        { question_text: "How do startup programs affect a computer beyond just slowing boot time?", choice_a: "They only affect the first two minutes after boot and have no ongoing performance impact", choice_b: "They prevent the computer from installing Windows Updates automatically", choice_c: "They consume ongoing CPU, memory, and disk resources in the background throughout the entire session, not just during boot", correct_choice: "C", explanation: "Startup programs launch automatically and continue running as background processes. The combined resource consumption of multiple unnecessary startup items slows the entire computing session, not just the boot." },
      ],
    },
    {
      title: "CT Module 2: Blue Screen of Death Recovery",
      content: "BSODs are caused by driver failures, RAM errors, storage issues, or corrupted system files. Record the stop code, run sfc and DISM, and analyze memory dumps with WhoCrashed.",
      category: "System Recovery", difficulty: "intermediate", duration_minutes: 12, order_index: 2,
      quiz: [
        { question_text: "What is the most useful piece of information to capture when a Blue Screen of Death occurs?", choice_a: "The time the crash occurred for comparison with Event Viewer logs", choice_b: "Which application was running at the time of the crash", choice_c: "The stop code displayed on the screen which identifies the specific category of failure", correct_choice: "C", explanation: "The stop code is a specific error identifier. Searching it reveals targeted solutions and points toward driver, hardware, or system file categories. Without it you are troubleshooting blind." },
        { question_text: "What does the Windows command sfc /scannow do and when should you use it?", choice_a: "It scans for disk errors and repairs bad sectors on your hard drive", choice_b: "It checks protected Windows system files for corruption and repairs them from a cached copy, useful when BSODs are caused by corrupted system files", choice_c: "It scans installed applications for outdated versions that need updating", correct_choice: "B", explanation: "System File Checker addresses BSODs caused by corrupted system files from failed updates, power interruptions during writes, or storage issues. Run it after DISM to ensure it has a good source to restore from." },
        { question_text: "Which tool provides the most specific information about which driver caused a BSOD?", choice_a: "WhoCrashed or WinDbg, which analyze the memory dump file Windows saves during a crash and identify the specific driver responsible", choice_b: "Device Manager which shows which drivers have warning flags", choice_c: "Windows Update which logs which updates coincided with the crash", correct_choice: "A", explanation: "Memory dump analysis reads the crash data Windows saves and specifically identifies the driver or component that triggered the stop error. The stop code tells you the category; dump analysis tells you the exact cause." },
      ],
    },
    {
      title: "CT Module 3: Wi-Fi and Network Troubleshooting",
      content: "Start by isolating whether the problem affects one device or all devices, then work through DNS flushing, adapter resets, and router restarts systematically.",
      category: "Networking", difficulty: "beginner", duration_minutes: 10, order_index: 3,
      quiz: [
        { question_text: "What is the first diagnostic question that most efficiently narrows down a network problem?", choice_a: "Whether the problem affects one device or all devices, which determines whether the issue is device-specific or network-wide", choice_b: "Whether the router firmware needs an update", choice_c: "Whether the problem is with a specific website or all internet access", correct_choice: "A", explanation: "Scope isolation is the foundation of efficient troubleshooting. One affected device points to a driver, software, or configuration issue on that device. All devices affected points to the router, modem, or ISP." },
        { question_text: "A website that normally loads fine has been failing to connect for hours even though other sites work. What should you try first?", choice_a: "Reinstall the browser since it is likely corrupted", choice_b: "Restart the router to reset the connection to the ISP", choice_c: "Run ipconfig /flushdns to clear the local DNS cache which may contain a stale or corrupted entry for that domain", correct_choice: "C", explanation: "Site-specific failures while others work often indicate a corrupted DNS cache entry for that domain. Flushing the cache forces a fresh DNS lookup, resolving the connection failure without changing any network configuration." },
        { question_text: "Why might switching from 5 GHz Wi-Fi to 2.4 GHz improve connection reliability when you are far from the router?", choice_a: "The 2.4 GHz band is always faster than 5 GHz for streaming video", choice_b: "The 2.4 GHz band penetrates walls and extends range better than 5 GHz despite being slower, providing more stable connectivity at greater distances", choice_c: "The 5 GHz band interferes with Bluetooth which causes connectivity drops", correct_choice: "B", explanation: "Higher frequency radio waves attenuate faster through walls and over distance. At range, 5 GHz signal quality drops significantly while 2.4 GHz remains more stable. The speed trade-off is worth consistent connectivity." },
      ],
    },
    {
      title: "CT Module 4: Driver Problems and Updates",
      content: "Download drivers only from manufacturer websites. Use Device Manager yellow triangles to identify problems and Roll Back Driver to fix issues caused by recent updates.",
      category: "Hardware", difficulty: "intermediate", duration_minutes: 10, order_index: 4,
      quiz: [
        { question_text: "Where is the correct source for downloading driver updates for your hardware?", choice_a: "Any technology download site that ranks highly in search results", choice_b: "Third-party driver update utilities that automatically scan and update all drivers", choice_c: "The official website of the hardware manufacturer directly", correct_choice: "C", explanation: "Manufacturer official sites are the only trustworthy source. Third-party driver tools frequently install incorrect versions, bundle unwanted software, and have been used to distribute malware alongside drivers." },
        { question_text: "What does a yellow triangle warning icon in Device Manager indicate about a device?", choice_a: "The device is consuming too much power and needs to be replaced", choice_b: "Windows has identified a problem with that device's driver requiring attention such as a missing, corrupted, or incompatible driver", choice_c: "The device is working but in a reduced functionality mode due to power settings", correct_choice: "B", explanation: "The yellow warning triangle is Device Manager's way of flagging that something is wrong with the device's driver relationship with Windows. Right-clicking and viewing Properties reveals the specific error code." },
        { question_text: "When is the Roll Back Driver option the fastest fix for a hardware problem?", choice_a: "When a recent driver update introduced new problems, since rolling back restores the previous working driver version immediately", choice_b: "When the device has never had a driver installed and needs a starting point", choice_c: "When the driver is outdated and needs to be replaced with a newer version", correct_choice: "A", explanation: "If a device worked before a driver update and broke after it, Roll Back Driver is the fastest resolution. It restores the previous working version without requiring a download or research into which older version to install." },
      ],
    },
    {
      title: "CT Module 5: Storage and Disk Space Issues",
      content: "Use CrystalDiskInfo to check drive health and WinDirStat to find what is consuming space. Keep at least 10-15 percent free on the system drive for virtual memory.",
      category: "Storage", difficulty: "beginner", duration_minutes: 10, order_index: 5,
      quiz: [
        { question_text: "What does a Caution status in CrystalDiskInfo indicate and what should you do immediately?", choice_a: "The drive needs defragmenting to improve performance", choice_b: "The drive's own health monitoring has detected warning-level values indicating early failure signs. Back up your data immediately before the drive fails completely", choice_c: "The drive is running slightly warm and needs better ventilation", correct_choice: "B", explanation: "CrystalDiskInfo reads the drive's S.M.A.R.T. data. A Caution status means the drive itself has detected and logged health indicators associated with impending failure. Treat it as failing and prioritize data backup now." },
        { question_text: "Why does having less than 10 percent free space on the Windows system drive cause severe performance problems?", choice_a: "Windows requires free space for virtual memory paging when RAM fills up. Insufficient free space prevents paging, causing dramatic slowdowns during any memory-intensive task", choice_b: "Windows reads files more slowly when the drive is fragmented by many small free space gaps", choice_c: "Antivirus software scans slower when the drive has limited free space", correct_choice: "A", explanation: "Windows uses the system drive for virtual memory overflow when physical RAM is exhausted. A drive without sufficient free space for the page file causes constant allocation failures and severe performance degradation." },
        { question_text: "What is the Windows.old folder, how much space can it consume, and is it safe to delete?", choice_a: "A folder containing old program versions from automatic updates, consuming minimal space, always safe to delete", choice_b: "A critical system recovery folder that should never be deleted regardless of available space", choice_c: "A backup of your previous Windows installation created during upgrades that can consume tens of gigabytes, safe to delete after confirming the new version works correctly", correct_choice: "C", explanation: "Windows.old preserves the previous Windows installation for rollback. It can consume 20 gigabytes or more. Once you have used the new version successfully and do not need to roll back, deleting it through Disk Cleanup is safe." },
      ],
    },
    {
      title: "CT Module 6: Browser Problems and Resets",
      content: "Clear cache to fix display problems, use the browser task manager to find resource-heavy extensions, and perform a full reset to remove hijackers.",
      category: "Software", difficulty: "beginner", duration_minutes: 10, order_index: 6,
      quiz: [
        { question_text: "What specifically does clearing the browser cache fix?", choice_a: "Pages that display incorrectly, show outdated content, or have persistent errors caused by stale or corrupted locally stored resource copies", choice_b: "Slow internet speeds caused by too much data stored in the browser", choice_c: "Saved passwords that are no longer working correctly", correct_choice: "A", explanation: "The cache stores downloaded website resources for faster repeat loading. Outdated or corrupted cached versions of CSS, images, or scripts cause display problems. Clearing forces the browser to download fresh copies." },
        { question_text: "How do you determine which browser extension is causing performance or stability problems?", choice_a: "Disable all extensions and reinstall them one at a time to find the culprit", choice_b: "Check the browser settings page for extension error messages", choice_c: "Open the browser's built-in task manager to see resource usage per extension, or test performance in a private window with extensions disabled to confirm an extension is the cause", correct_choice: "C", explanation: "Browser task managers show exactly how much CPU and memory each extension consumes. Testing in a private window disables all extensions simultaneously, confirming whether an extension is the source of the problem." },
        { question_text: "What is a browser hijacker and how does it most commonly get installed?", choice_a: "A virus that steals saved passwords by reading the browser's password database directly", choice_b: "Malicious software that changes your homepage, new tab page, or default search engine without permission, typically bundled with free software via pre-checked installer checkboxes", choice_c: "A browser extension that redirects purchases to affiliate links without disclosure", correct_choice: "B", explanation: "Browser hijackers ride into systems through software bundle installers where additional software is pre-selected. Reading installer screens carefully and choosing custom installation allows you to uncheck and decline bundled additions." },
      ],
    },
    {
      title: "CT Module 7: Software Installation and Removal",
      content: "Download only from official sources, choose custom installation to avoid bundled software, and use proper uninstallers to avoid leaving registry remnants.",
      category: "Software", difficulty: "beginner", duration_minutes: 10, order_index: 7,
      quiz: [
        { question_text: "Why should you always choose Custom or Advanced installation rather than clicking through Express or Quick?", choice_a: "Custom installation is always completed faster than Express installation", choice_b: "Express installation uses more disk space because it installs redundant files", choice_c: "Custom installation reveals bundled software, toolbars, and browser modifications that are pre-selected in Express mode and installs silently if you do not manually uncheck them", correct_choice: "C", explanation: "Express installation hides additional software with pre-checked checkboxes. Custom installation shows each component individually. Browser hijackers and unwanted programs commonly arrive this way in free software installers." },
        { question_text: "Why does deleting an application folder leave problems behind compared to using the official uninstaller?", choice_a: "Deleted folders can be restored from the Recycle Bin causing the application to reappear", choice_b: "The official uninstaller removes registry entries, system files, startup entries, and other components installed throughout Windows that simply deleting the folder leaves scattered across the system", choice_c: "Windows prevents folder deletion for applications installed through official installers", correct_choice: "B", explanation: "Applications install components in the Registry, system folders, and startup entries throughout Windows. Only the official uninstaller knows where all these pieces are. Deleting the folder leaves invisible remnants that consume space and cause errors." },
        { question_text: "What security risk do applications you have installed but no longer use create?", choice_a: "Each unused application is an unmonitored attack surface with potentially unpatched vulnerabilities that can be exploited even if you never intentionally run it", choice_b: "Unused applications automatically send telemetry data to the developer consuming your bandwidth", choice_c: "Unused applications gradually corrupt each other's files causing eventual system instability", correct_choice: "A", explanation: "Unused applications sit unupdated and unmonitored. Their vulnerabilities are just as exploitable as those in applications you use daily. Removing unused software is one of the simplest ways to reduce attack surface." },
      ],
    },
    {
      title: "CT Module 8: Printer and Peripheral Troubleshooting",
      content: "Clear stuck print spooler jobs, download full driver packages from manufacturer sites, and print a self-test page to isolate whether the problem is the printer or the computer.",
      category: "Hardware", difficulty: "beginner", duration_minutes: 10, order_index: 8,
      quiz: [
        { question_text: "What is the Windows print spooler and why does clearing it resolve many common printing problems?", choice_a: "A hardware buffer inside the printer that stores jobs before printing, cleared by turning the printer off and on", choice_b: "A Windows service managing the print queue that becomes stuck when it cannot process a job, blocking all subsequent jobs. Stopping the service, clearing the queue folder, and restarting resolves this", choice_c: "A background process that downloads printer driver updates automatically", correct_choice: "B", explanation: "The print spooler is a Windows service managing the job queue. One unprocessable job blocks everything behind it. The manual reset procedure clears the jam by stopping the service, deleting queue files, and restarting fresh." },
        { question_text: "Why does printing from Notepad work when printing from Microsoft Word fails on the same printer?", choice_a: "Notepad files are smaller and more compatible with all printer types", choice_b: "Word uses more advanced printer features that require specific drivers not installed", choice_c: "The problem is application-specific, meaning Word's interaction with the printer driver has an issue while the basic driver function works. Reinstalling the Word printer driver or updating it resolves this", correct_choice: "C", explanation: "When printing works from one application but not another, the printer hardware and basic connectivity are fine. The problem is in how the specific application generates or sends print data. This isolates troubleshooting to the software layer." },
        { question_text: "What is the purpose of printing a self-test page from the printer itself using its buttons?", choice_a: "Testing that the printer hardware functions correctly independently of any computer connection, proving whether the problem is in the printer or on the computer side", choice_b: "Calibrating ink levels and print head alignment before important documents", choice_c: "Resetting the printer firmware to factory default settings", correct_choice: "A", explanation: "A self-test page prints without any computer involvement. If it prints correctly the printer hardware is working and the problem is on the computer. If it fails the problem is in the printer itself, directing troubleshooting appropriately." },
      ],
    },
    {
      title: "CT Module 9: Windows Update Problems",
      content: "Reset update components by stopping services, renaming SoftwareDistribution folder, and restarting. Always run DISM before sfc /scannow.",
      category: "System Maintenance", difficulty: "intermediate", duration_minutes: 12, order_index: 9,
      quiz: [
        { question_text: "What does the Windows Update component reset procedure accomplish?", choice_a: "It reinstalls Windows completely while keeping personal files", choice_b: "It rolls back all updates installed in the past 30 days", choice_c: "It stops update services, clears corrupted cache folders, and restarts services so Windows Update recreates them fresh, resolving most persistent update failures", correct_choice: "C", explanation: "The reset procedure stops the wuauserv and bits services, renames the SoftwareDistribution and catroot2 folders forcing fresh recreation, then restarts the services. This resolves corruption that prevents updates from downloading or installing." },
        { question_text: "Why should you run DISM before running sfc /scannow when troubleshooting Windows corruption?", choice_a: "DISM repairs the Windows component store that SFC uses as its repair source, ensuring SFC has a healthy reference to restore files from", choice_b: "DISM must run first to give SFC the administrator permissions it needs", choice_c: "Running SFC before DISM can permanently delete system files that DISM needs", correct_choice: "A", explanation: "SFC repairs system files by replacing them from the Windows component store. If the component store itself is corrupted, SFC cannot repair correctly. DISM fixes the component store first, making the subsequent SFC run effective." },
        { question_text: "When is briefly pausing Windows Updates appropriate versus when does it create unacceptable risk?", choice_a: "Pausing is always unacceptable since every update contains critical security fixes", choice_b: "Pausing for one to two weeks after major feature releases allows others to identify serious widespread issues before you install, while indefinitely deferring security updates significantly increases vulnerability", choice_c: "Pausing for several months is fine since most vulnerabilities are not actively exploited", correct_choice: "B", explanation: "A brief tactical pause after major releases is reasonable risk management. Indefinite deferral is dangerous because security patches address actively exploited vulnerabilities. The risk of remaining unpatched grows daily after patch release." },
      ],
    },
    {
      title: "CT Module 10: Data Backup and Recovery",
      content: "Follow the 3-2-1 rule: three copies, two media types, one offsite. Test restores regularly. Use file versioning to protect against ransomware overwriting backups.",
      category: "Data Protection", difficulty: "intermediate", duration_minutes: 12, order_index: 10,
      quiz: [
        { question_text: "Why is periodically testing your backup by actually restoring files as important as making the backup?", choice_a: "A backup that has never been verified may be corrupt, incomplete, or unrestorable, leaving you with false confidence instead of real data protection", choice_b: "Testing backups updates the backup software to the latest version automatically", choice_c: "Testing is required to maintain the encryption keys that protect backup files", correct_choice: "A", explanation: "Backup failures including media errors, misconfigured software, and incomplete captures are common. Discovering your backup cannot be restored during an actual disaster is catastrophic. Test restores before you need them." },
        { question_text: "Why is file versioning critical for ransomware protection in backup software?", choice_a: "Versioning makes backups run faster by only saving changed files", choice_b: "Versioning tracks which version of the backup application you are running", choice_c: "Versioning retains previous copies of files so you can restore the last known good version before ransomware encrypted them, preventing the encrypted version from overwriting your only backup", correct_choice: "C", explanation: "Without versioning, ransomware that encrypts files before the next backup run causes the backup to overwrite the last good version with the encrypted version. Versioning preserves the pre-encryption copy as a recoverable snapshot." },
        { question_text: "What does the offsite component of the 3-2-1 backup rule protect against that local backups cannot?", choice_a: "Physical disasters like fire, flood, and theft that would destroy both your original data and any local backup drives in the same location simultaneously", choice_b: "Software corruption that affects files stored locally but not files in cloud storage", choice_c: "Hardware compatibility issues that prevent local drives from being read on replacement hardware", correct_choice: "A", explanation: "No local backup survives a fire or flood. The offsite or cloud copy is the only protection against physical catastrophe affecting your location. This is the most commonly overlooked and most critical element of the 3-2-1 rule." },
      ],
    },
    {
      title: "CT Module 11: Overheating and Cooling Issues",
      content: "Use HWMonitor to track temperatures. Clean dust annually with compressed air. CPU temperatures consistently above 90C under load indicate a thermal problem.",
      category: "Hardware", difficulty: "beginner", duration_minutes: 10, order_index: 11,
      quiz: [
        { question_text: "What is the most common cause of a computer that worked fine for years but has recently started running hot?", choice_a: "The processor degrading and generating more heat as it ages", choice_b: "Newer software being less efficient and requiring more processing power", choice_c: "Dust accumulating in heatsinks and fan blades over time, acting as thermal insulation and blocking airflow", correct_choice: "C", explanation: "Dust is the number one cause of gradual thermal degradation in older computers. It accumulates slowly so the change is imperceptible until it reaches a threshold. Annual compressed air cleaning restores cooling to near-original effectiveness." },
        { question_text: "At what temperature range should you be concerned about CPU thermal throttling under full load?", choice_a: "Above 60 degrees Celsius since modern processors should not exceed this under any circumstances", choice_b: "When temperatures consistently exceed 90 degrees Celsius under sustained load, indicating inadequate cooling that will cause throttling and long-term damage", choice_c: "Above 75 degrees Celsius which always indicates a hardware fault requiring immediate replacement", correct_choice: "B", explanation: "Most modern processors operate safely up to about 85 to 90 degrees Celsius under full load. Consistent temperatures above 90 degrees under load indicate a thermal problem. Idle temperatures above 60 degrees also suggest cooling issues." },
        { question_text: "Why does using a laptop on a soft surface like a bed or couch cause overheating?", choice_a: "Soft surfaces block the bottom intake vents that laptop cooling systems use to draw cool air through the heatsink and fan assembly", choice_b: "Soft surfaces conduct heat into the laptop from the surrounding fabric", choice_c: "The uneven surface causes the laptop fans to spin at an angle reducing their efficiency", correct_choice: "A", explanation: "Laptop cooling depends on airflow through bottom vents. Soft surfaces conform to the laptop bottom and completely block these vents. Without airflow the cooling system cannot function and temperatures rise rapidly under any load." },
      ],
    },
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS2 };
