const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS3(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='Anti-Hacking Defense'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    { title: "AH Module 1: Setting Up a Firewall", content: "A firewall controls which network traffic reaches your device. Windows Defender Firewall uses network profiles (Public, Private, Domain) with different rule sets. Public profile is most restrictive.", category: "Network Defense", difficulty: "beginner", duration_minutes: 10, order_index: 1, quiz: [
      { question_text: "What does a stateful firewall do that a basic packet filter cannot?", choice_a: "It inspects the content of files being downloaded through the firewall", choice_b: "It tracks the state of network connections to allow expected response traffic while blocking unsolicited inbound connections", choice_c: "It automatically updates its rules from a cloud database", correct_choice: "B", explanation: "Stateful firewalls track connection state. Response packets matching an outbound connection are allowed. Unsolicited inbound packets with no matching outbound connection are blocked, protecting against direct internet attacks." },
      { question_text: "Why does Windows Defender Firewall configured to use different rules for different network profiles?", choice_a: "Different profiles use different amounts of memory", choice_b: "The Private profile allows connections from trusted devices on your home network which are not present on public networks", choice_c: "The Public profile blocks more inbound connections because you do not control or trust public networks and they may contain hostile devices", correct_choice: "C", explanation: "On your home network you know and trust the other devices. On a public network you share space with unknown potentially hostile devices. The Public profile reflects this by allowing fewer inbound connections." },
      { question_text: "An unfamiliar application requests permission to access the network through Windows Firewall. What should you do?", choice_a: "Deny the request, identify what the application is, and only create an exception if you recognize and trust it", choice_b: "Allow it since any application installed on your system was presumably authorized", choice_c: "Allow it temporarily and remove the rule after your current task is complete", correct_choice: "A", explanation: "Unknown applications requesting network access may be malware installed without your knowledge. The correct default is to deny, research, and only allow when you have confirmed the application is legitimate and the access is necessary." },
    ]},
    { title: "AH Module 2: Using a VPN Properly", content: "A VPN encrypts traffic between your device and the VPN server, protecting against local network interception. It does not protect against malware or account-based tracking.", category: "Privacy", difficulty: "intermediate", duration_minutes: 10, order_index: 2, quiz: [
      { question_text: "What does a VPN specifically protect and what threats does it not address?", choice_a: "A VPN protects against all cyber threats including malware, phishing, and account takeover", choice_b: "A VPN only protects browsing in the browser application and does not affect other application traffic", choice_c: "A VPN protects traffic from local network interception and hides your IP from sites you visit, but does not protect against malware on your device, phishing attacks, or tracking by services where you are logged in", correct_choice: "C", explanation: "A VPN is a network-level tool. It encrypts traffic in transit and masks your origin IP. It has no effect on malware already running on your device, social engineering attacks, or services that track you by account rather than IP." },
      { question_text: "Why does choosing a VPN provider with an independently audited no-log policy matter?", choice_a: "Audited providers offer faster connection speeds because they have optimized infrastructure", choice_b: "The VPN provider can see all your traffic since it is decrypted at their server, so their logging practices directly determine whether your privacy is actually protected", choice_c: "Audited providers are exempt from law enforcement requests for user data", correct_choice: "B", explanation: "VPN traffic is decrypted at the VPN server before being forwarded to the internet. The provider has full visibility. Only an independently verified no-log policy provides meaningful assurance they are not retaining records of your activity." },
      { question_text: "What is a DNS leak in VPN usage and why does it undermine privacy?", choice_a: "When VPN data is accidentally transmitted unencrypted due to a protocol error", choice_b: "When the VPN server IP address becomes publicly known reducing anonymity", choice_c: "When DNS queries bypass the VPN tunnel and go through your regular ISP DNS, revealing which domains you visit even though your traffic content travels through the VPN", correct_choice: "C", explanation: "DNS leaks expose your browsing activity at the domain level to your ISP despite the VPN. Even though the content of your traffic is encrypted through the VPN, the ISP can see every domain you look up through their DNS server." },
    ]},
    { title: "AH Module 3: Securing Your Home Router", content: "Change default admin credentials and Wi-Fi password, update firmware, disable WPS and remote management, use a guest network for IoT devices.", category: "Network Defense", difficulty: "beginner", duration_minutes: 10, order_index: 3, quiz: [
      { question_text: "Why are default router admin credentials a critical security vulnerability?", choice_a: "Every router model uses the same published default credentials that are documented in manuals and searchable online, making any router with unchanged defaults trivially accessible to attackers", choice_b: "Default credentials are designed to be easy to remember which makes them easy for attackers to guess", choice_c: "Router manufacturers use default credentials to maintain remote access for warranty support", correct_choice: "A", explanation: "Router manufacturers use the same default username and password across millions of identical devices. These are published in product manuals and aggregated in searchable databases. Any attacker who can reach your router admin interface can log in instantly." },
      { question_text: "Why should you disable WPS on your home router?", choice_a: "WPS slows down Wi-Fi connection speeds for all devices on the network", choice_b: "WPS consumes significant router processing resources that are better used for firewall functions", choice_c: "The WPS PIN method has a fundamental design flaw that allows the 8-digit PIN to be brute-forced in hours, giving attackers full Wi-Fi access regardless of your Wi-Fi password strength", correct_choice: "C", explanation: "WPS PIN validation checks the pin in two halves, effectively making it a 4-digit plus 3-digit check instead of 8-digit. This flaw reduces the effective brute-force space from 100 million to about 11,000 combinations." },
      { question_text: "Why should IoT devices be placed on a separate guest network rather than your main network?", choice_a: "IoT devices use incompatible network protocols that cause problems on regular home networks", choice_b: "Isolating IoT devices on a separate network segment prevents a compromised smart device from directly attacking your computers, phones, and sensitive data on the main network", choice_c: "Guest networks provide faster speeds more suitable for streaming devices like smart TVs", correct_choice: "B", explanation: "IoT devices frequently have poor security practices, slow update cycles, and long operational lives. Isolation means a compromised smart camera cannot pivot to attack your laptop. This is network segmentation applied at home scale." },
    ]},
    { title: "AH Module 4: Two Factor Authentication Setup", content: "Hardware keys are strongest, then authenticator apps, then SMS. Enable MFA on email first as it controls account recovery for all other services.", category: "Authentication", difficulty: "beginner", duration_minutes: 10, order_index: 4, quiz: [
      { question_text: "Why is an authenticator app more secure than SMS text messages for two-factor authentication?", choice_a: "Authenticator apps generate longer codes that are harder for attackers to guess", choice_b: "SMS codes can be intercepted through SIM swapping attacks where attackers transfer your phone number, while authenticator app codes are generated locally without any telecom network involvement", choice_c: "Authenticator apps work without any internet or cellular connection", correct_choice: "B", explanation: "SIM swapping convinces a carrier to transfer your phone number to an attacker's SIM, intercepting all your SMS codes. Authenticator app codes are generated locally using a shared secret and the current time, with no network transmission to intercept." },
      { question_text: "Why must backup codes for MFA-protected accounts be stored somewhere other than the device you are protecting?", choice_a: "Backup codes stored with the device are inaccessible when the device is lost or stolen, which is exactly when you would need them to regain account access", choice_b: "Backup codes stored on the device expire faster than those stored externally", choice_c: "Device storage corrupts backup codes over time making them unusable", correct_choice: "A", explanation: "Backup codes exist for the scenario where you cannot access your MFA device. If the backup codes are stored on the same device you lost, you are locked out with no recovery path. Store them in a password manager or secured physical location." },
      { question_text: "Why is your email account the single highest-priority account for enabling MFA?", choice_a: "Email accounts contain more personal messages than any other account type", choice_b: "Email providers process more login attempts making accounts statistically more likely to be targeted", choice_c: "Email is the password reset mechanism for most other accounts, meaning a compromised email account enables immediate takeover of banking, social media, and work accounts through password resets", correct_choice: "C", explanation: "Most online services offer email-based password reset. An attacker with your email can request resets for virtually every account you own. Protecting email with strong MFA protects the master recovery key to your entire digital identity." },
    ]},
    { title: "AH Module 5: Password Manager Setup and Use", content: "Choose a manager with end-to-end encryption like Bitwarden. Create a strong passphrase as master password. Enable MFA on the manager itself.", category: "Authentication", difficulty: "beginner", duration_minutes: 10, order_index: 5, quiz: [
      { question_text: "What is the most critical technical security requirement when selecting a password manager?", choice_a: "End-to-end encryption where only you can decrypt your vault and the provider cannot read your stored passwords even if their servers are breached", choice_b: "Cross-platform synchronization across all your devices and browsers", choice_c: "Integration with all major browsers for automatic form filling", correct_choice: "A", explanation: "End-to-end encryption means your vault data is encrypted before leaving your device using your master password as the key. Even a complete breach of the provider's servers yields only encrypted data useless without your master password." },
      { question_text: "What makes a passphrase of four or more random words an excellent master password?", choice_a: "Passphrases require no special characters which makes them easier for password managers to store", choice_b: "Passphrases are required by most enterprise security policies", choice_c: "Length provides exceptional security through exponentially larger search space while remaining memorable, unlike a random string of characters that is both weak if short and impossible to memorize if long", correct_choice: "C", explanation: "A four-word random passphrase has far more entropy than a typical 8-character complex password and is actually memorable. Length is the primary factor in password strength." },
      { question_text: "How does a password manager browser extension specifically protect against phishing sites?", choice_a: "The extension scans pages for phishing indicators and blocks access to suspicious sites", choice_b: "The extension matches saved credentials to exact domains and will not auto-fill on lookalike sites even if they appear visually identical", choice_c: "The extension encrypts your credentials before they are sent to the web server", correct_choice: "B", explanation: "Password manager extensions use domain matching not visual inspection. A fake site at paypa1.com will not receive your PayPal credentials even if it looks identical, because paypa1.com does not match the saved entry for paypal.com." },
    ]},
    { title: "AH Module 6: Recognizing and Removing Malware", content: "Signs of infection include unexplained slowness, disabled security tools, and unusual network activity. Use Malwarebytes for second-opinion scans and bootable scanners for rootkits.", category: "Malware Defense", difficulty: "intermediate", duration_minutes: 12, order_index: 6, quiz: [
      { question_text: "What is the key difference between how a virus spreads and how a trojan gets installed?", choice_a: "Viruses only affect Windows while trojans affect all operating systems", choice_b: "Trojans are more dangerous because they always include ransomware functionality", choice_c: "Viruses self-replicate by attaching to existing files, while trojans disguise malicious functionality as legitimate software relying entirely on the user being tricked into voluntarily installing them", correct_choice: "C", explanation: "Viruses spread autonomously by attaching copies to files. Trojans require user action, disguising themselves as useful software. The deception element makes trojans the primary delivery mechanism for most modern malware." },
      { question_text: "What is a rootkit and why is standard antivirus scanning insufficient to detect it?", choice_a: "A rootkit operates at the kernel or firmware level and intercepts the system calls security software uses to detect threats, making itself and other malware invisible to scanners running within the same compromised operating system", choice_b: "A rootkit that infects the root directory of your hard drive preventing the OS from loading", choice_c: "A rootkit is a collection of administrator tools that hackers use to manage compromised systems remotely", correct_choice: "A", explanation: "Rootkits subvert the operating system itself. Security software that runs within the compromised OS must use the same kernel functions the rootkit controls. The rootkit intercepts these calls and hides itself, requiring scanning from outside the OS." },
      { question_text: "Why is scanning from a bootable recovery environment more effective for serious infections than scanning from within Windows?", choice_a: "Recovery environment scanners have more recently updated malware definitions", choice_b: "Booting from a clean external environment scans the infected drive without the malware being active and able to use rootkit techniques to hide from the scanner", choice_c: "Recovery environments have access to more processing power than Windows does", correct_choice: "B", explanation: "When malware runs within the OS it can intercept and manipulate the same functions security scanners use. A bootable scanner like Kaspersky Rescue Disk operates outside the compromised OS, removing the malware's ability to hide itself." },
    ]},
    { title: "AH Module 7: Securing Your Browser", content: "Keep browser updated, block third-party cookies, use HTTPS-Only mode, audit extensions regularly, and use a content blocker like uBlock Origin to reduce malvertising exposure.", category: "Web Security", difficulty: "beginner", duration_minutes: 10, order_index: 7, quiz: [
      { question_text: "What is malvertising and why is an ad blocker effective against it?", choice_a: "Ads with misleading claims, blocked by ad blockers that verify advertising accuracy", choice_b: "Malicious code embedded in legitimate advertising networks affecting even reputable websites, effectively blocked by ad blockers that prevent third-party ad content from loading entirely", choice_c: "Ads that slow your browser by consuming excessive CPU and memory resources", correct_choice: "B", explanation: "Malvertising injects attack code into ad network inventory. Even major reputable sites serve ads from third-party networks they do not fully control. Ad blockers prevent these ad calls from loading, eliminating the attack vector entirely." },
      { question_text: "Why should you be cautious about browser extensions even when installing from official stores?", choice_a: "Official store extensions are slower because they undergo additional security verification before loading", choice_b: "Extensions charge monthly subscription fees that accumulate unnoticed", choice_c: "Extensions have broad access to all browser activity including page content and form data. Malicious extensions have been distributed through official stores after acquiring established popular extensions with existing user bases", correct_choice: "C", explanation: "Browser extensions are powerful code running on every page you visit. The pattern of purchasing legitimate popular extensions and pushing malicious updates to the existing trusted user base is a known attack vector." },
      { question_text: "What is the security benefit of enabling HTTPS-Only Mode or HTTPS-First Mode in your browser?", choice_a: "It prevents your browser from loading pages that lack HTTPS, ensuring all connections are encrypted and warning you before connecting to unencrypted sites", choice_b: "It speeds up page loading by prioritizing secure server connections over standard ones", choice_c: "It blocks all third-party scripts from running on HTTP pages", correct_choice: "A", explanation: "HTTPS-Only Mode prevents the browser from silently loading HTTP pages where traffic is unencrypted and visible to network observers. It forces an upgrade attempt or shows a warning, keeping you on encrypted connections by default." },
    ]},
    { title: "AH Module 8: Safe File Downloading", content: "Download only from official sources. Verify file hashes before opening. Never enable macros in Office documents from email or unknown sources.", category: "Malware Defense", difficulty: "beginner", duration_minutes: 10, order_index: 8, quiz: [
      { question_text: "Where is the only safe source for downloading software to minimize malware risk?", choice_a: "Any website that appears in the top five search results for the software name", choice_b: "Technology review sites that feature software recommendations", choice_c: "The official developer website or established repositories like the Microsoft Store, using bookmarks rather than search results to navigate there", correct_choice: "C", explanation: "Search results for popular software are routinely gamed by malicious sites. Attackers create convincing lookalike download sites. Using bookmarks to official sites eliminates the risk of search result manipulation leading you to a malicious download." },
      { question_text: "What does verifying a file hash confirm about a downloaded file?", choice_a: "It confirms the developer signed the file with their official certificate", choice_b: "It confirms the file is byte-for-byte identical to what the developer published, meaning it has not been modified or tampered with during distribution", choice_c: "It confirms the file does not contain any known malware signatures", correct_choice: "B", explanation: "A hash is a mathematical fingerprint of file contents. Even a single changed bit produces a completely different hash. Matching the hash on the download page confirms the file has not been tampered with in transit or on the download server." },
      { question_text: "An Office document you downloaded asks you to click Enable Content to view it properly. What is the correct response?", choice_a: "Close the document and report it. Legitimate documents do not require macros just to display content. This is the standard social engineering prompt used to deliver ransomware and trojans", choice_b: "Enable the content since the document needs macros to function as the developer intended", choice_c: "Enable macros but immediately save the document to a sandboxed folder for safety", correct_choice: "A", explanation: "The Enable Content prompt in Office documents is the primary delivery mechanism for macro-based malware including ransomware. No legitimate document requires macros merely to display its content. This prompt is always a warning sign." },
    ]},
    { title: "AH Module 9: Account Hardening Best Practices", content: "Use random false answers for security questions, review active sessions and connected apps, enable login notifications, and know your incident response steps before you need them.", category: "Account Security", difficulty: "intermediate", duration_minutes: 10, order_index: 9, quiz: [
      { question_text: "Why should you use random false answers to security questions rather than real answers?", choice_a: "Real security question answers are easy to forget over time", choice_b: "Real answers to questions like your mother's maiden name or first pet are often discoverable through social media, public records, and data brokers, making them ineffective as a second authentication factor", choice_c: "Security systems process fake answers faster than real ones", correct_choice: "B", explanation: "Security questions are effectively a second password. Using discoverable real information makes them weaker than no protection at all. Treat them as password fields and store the random false answers in your password manager." },
      { question_text: "What should you do when you receive an MFA prompt you did not initiate?", choice_a: "Deny the request immediately, change your password since someone clearly has it, and report the unauthorized login attempt to your security team", choice_b: "Approve it once to see what account is being accessed then change your password", choice_c: "Ignore it since it will expire automatically after a few minutes", correct_choice: "A", explanation: "An unsolicited MFA prompt means someone is actively trying to log in with your credentials. Denying stops this attempt. Changing your password removes their ability to try again. Reporting alerts the security team to an active attack." },
      { question_text: "Why is reviewing connected apps and revoking unused OAuth access part of account hardening?", choice_a: "Connected apps cause slower login times as the platform checks each one during authentication", choice_b: "Unused connected apps accumulate charges that appear on your billing statement", choice_c: "Each connected app retains access to your account data and can post or read on your behalf. Apps you no longer use are unmonitored risks that should be revoked to reduce your account's attack surface", correct_choice: "C", explanation: "OAuth connected apps retain ongoing access to your account. An app you authorized years ago and forgot about may have been acquired by a malicious actor, may have been breached, or may be collecting data you no longer consent to share." },
    ]},
    { title: "AH Module 10: Social Media Security", content: "Use strong unique passwords and MFA, review connected apps, configure privacy settings, and be wary of trends that ask for personal history details that match security questions.", category: "Account Security", difficulty: "beginner", duration_minutes: 10, order_index: 10, quiz: [
      { question_text: "Why are social media accounts particularly valuable targets for attackers?", choice_a: "They provide access to your entire contact network for impersonation and social engineering, contain personal information valuable for identity theft, and can be used for reputation damage and fraud", choice_b: "Social media passwords are typically weaker than other account passwords", choice_c: "Social media platforms have weaker authentication than banking or email platforms", correct_choice: "A", explanation: "Compromised social media accounts enable attacks on your entire network. Your contacts trust messages from you, making a compromised account an extremely effective social engineering platform. The personal data also feeds targeted attacks." },
      { question_text: "You notice your social media account sent messages to your contacts that you did not write. What should you do immediately?", choice_a: "Delete the sent messages and change your profile picture so contacts know the account was compromised", choice_b: "Report it to the platform as a bug since it might be a technical error", choice_c: "Change your password and MFA settings immediately, review and revoke connected apps, and notify your contacts that they may have received malicious messages from your compromised account", correct_choice: "C", explanation: "Account compromise requires immediate action on multiple fronts. Changing credentials stops ongoing access. Reviewing connected apps closes secondary access paths. Warning contacts prevents them from falling for scams sent in your name." },
      { question_text: "What is the privacy risk of participating in social media trends that ask you to share childhood memories or personal history details?", choice_a: "These trends are usually data harvesting operations where the real purpose is collecting answers to common security questions like first pet, childhood street, or mother's maiden name", choice_b: "These trends use excessive bandwidth that slows your device", choice_c: "These trends share your responses with advertisers who use them to target you", correct_choice: "A", explanation: "Security questions like first pet name, childhood street, and high school mascot are the most common trend formats. The entertaining framing disguises the actual purpose of collecting exactly the answers that unlock account recovery." },
    ]},
    { title: "AH Module 11: Encryption Basics for Everyone", content: "Encryption protects data at rest (BitLocker/FileVault) and in transit (HTTPS, end-to-end messaging). It does not protect against malware already running on your device.", category: "Data Security", difficulty: "intermediate", duration_minutes: 12, order_index: 11, quiz: [
      { question_text: "What does enabling BitLocker on your Windows computer protect against?", choice_a: "It prevents ransomware from encrypting your files", choice_b: "It blocks unauthorized applications from accessing your documents", choice_c: "It encrypts the entire drive so that someone with physical access to your laptop cannot read your files without your password, even if they remove the drive", correct_choice: "C", explanation: "Full disk encryption like BitLocker protects data at rest. Without it, removing the storage drive from a lost or stolen laptop and reading it in another computer bypasses Windows login entirely. With BitLocker the data is unreadable without the key." },
      { question_text: "What is the practical difference between transport encryption and end-to-end encryption in messaging?", choice_a: "Transport encryption is faster while end-to-end encryption is more secure but slower", choice_b: "Transport encryption protects messages between your device and the server but the server can read them. End-to-end encryption means only the sender and recipient can read messages and the service provider cannot", choice_c: "Transport encryption is used for text while end-to-end encryption is used for voice calls", correct_choice: "B", explanation: "Most messaging apps use transport encryption protecting messages in transit but storing them decryptably on servers. End-to-end encryption like Signal uses means the provider stores only encrypted data they cannot read." },
      { question_text: "Why does encryption not protect against malware already running on your device?", choice_a: "Malware running on your device accesses data before it is encrypted or after it is decrypted, when it is in its readable form, bypassing encryption entirely", choice_b: "Encryption software is incompatible with most antivirus programs preventing simultaneous protection", choice_c: "Encryption keys expire when malware is detected causing the encrypted data to become permanently inaccessible", correct_choice: "A", explanation: "Encryption protects data at rest and in transit. Malware runs on the live system where you work with decrypted data. It captures data in the moment you access it, before encryption applies or after decryption occurs." },
    ]},
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS3 };
