const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS4(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='Network Fundamentals'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    { title: "NF Module 1: How the Internet Works", content: "The internet routes packets through IP addresses using DNS to resolve domain names. End-to-end encryption protects traffic across all intermediate hops.", category: "Networking", difficulty: "beginner", duration_minutes: 10, order_index: 1, quiz: [
      { question_text: "What role does the Domain Name System play when you type a website address in your browser?", choice_a: "It verifies that the website has a valid security certificate before allowing connection", choice_b: "It translates the human-readable domain name into the IP address your browser needs to actually connect to the server", choice_c: "It checks whether you have permission to access the requested website", correct_choice: "B", explanation: "DNS is the internet's phone book. Your browser cannot connect to an IP address it does not know. DNS resolves the domain name you type into the numerical IP address that network routers use to direct your connection." },
      { question_text: "Why does end-to-end encryption provide protection even when your data passes through many routers and networks?", choice_a: "End-to-end encryption is applied at each router hop ensuring the data is re-encrypted with stronger keys as it travels", choice_b: "End-to-end encryption scrambles data on your device in a way that only the intended recipient can unscramble, so even if intermediate routers or networks capture the traffic they see only unreadable data", choice_c: "End-to-end encryption routes traffic through fewer hops reducing the number of systems that can intercept it", correct_choice: "B", explanation: "End-to-end encryption is applied before data leaves your device and removed only at the final destination. Every network, router, and provider the data passes through in between sees only encrypted ciphertext they cannot read." },
      { question_text: "What is a DDoS attack and why is it difficult for individual organizations to defend against large ones?", choice_a: "A DDoS attack installs malware on thousands of computers to steal data simultaneously", choice_b: "A DDoS attack uses a compromised user account to access data from many locations at once", choice_c: "A DDoS attack floods a target with traffic from many sources simultaneously overwhelming its capacity. Large volumetric attacks exceed what most organizations can absorb without upstream ISP or CDN mitigation", correct_choice: "C", explanation: "The distributed nature makes DDoS hard to block. Blocking individual source IPs is ineffective when traffic comes from thousands or millions of addresses. Mitigation requires infrastructure at the ISP or CDN level upstream of the target." },
    ]},
    { title: "NF Module 2: Understanding IP Addresses", content: "IPv4 addresses identify devices. Private addresses are used inside networks; public addresses are globally unique. NAT lets multiple devices share one public IP.", category: "Networking", difficulty: "beginner", duration_minutes: 10, order_index: 2, quiz: [
      { question_text: "What is the difference between a private IP address and a public IP address?", choice_a: "Private addresses are used within local networks and are not routable on the internet. Public addresses are globally unique and identify your network to the rest of the internet", choice_b: "Private addresses require a password to use while public addresses are freely accessible", choice_c: "Private addresses are assigned by your ISP while public addresses are self-assigned", correct_choice: "A", explanation: "Private addresses like 192.168.x.x are used inside local networks and can be reused in different networks. Public addresses are globally unique and are what the internet uses to route traffic to your location." },
      { question_text: "What is Network Address Translation and what problem does it solve?", choice_a: "A security feature that encrypts packets as they cross network boundaries", choice_b: "A method of converting domain names to IP addresses more efficiently than DNS", choice_c: "A technique that allows multiple devices with private IP addresses to share a single public IP address by the router tracking and translating connections", correct_choice: "C", explanation: "NAT solved IPv4 address exhaustion. Rather than every device needing a unique public IP, the router acts as a translator allowing all internal devices to share one public address while maintaining separate private addresses internally." },
      { question_text: "How does assigning a static IP or DHCP reservation to your home printer improve reliability?", choice_a: "A static IP makes the printer communicate faster with computers on the network", choice_b: "A static IP ensures the printer always has the same address so computers can always find it, preventing connection failures caused by address changes after DHCP lease renewal", choice_c: "A static IP protects the printer from attacks since only known addresses can connect", correct_choice: "B", explanation: "DHCP assigns addresses dynamically and they can change. If your computer has saved a printer at one address and the printer gets reassigned to another, the saved connection fails. A reservation or static IP prevents this." },
    ]},
    { title: "NF Module 3: Ports and Protocols", content: "Ports identify which service on a device should receive traffic. Common ports: 80 HTTP, 443 HTTPS, 22 SSH, 3389 RDP. RDP exposed to the internet is a top ransomware entry point.", category: "Networking", difficulty: "intermediate", duration_minutes: 10, order_index: 3, quiz: [
      { question_text: "What is the purpose of network ports in TCP/IP communication?", choice_a: "Ports identify the physical network adapter a packet should arrive on", choice_b: "Ports encrypt traffic between specific applications to prevent cross-application data exposure", choice_c: "Ports identify which specific application or service on a device should receive incoming network traffic, allowing multiple services to run simultaneously on one device", correct_choice: "C", explanation: "A single IP address identifies the device. The port number identifies which of many running applications should receive the traffic. Without ports, a web server and email server on the same machine could not coexist." },
      { question_text: "Why is RDP on port 3389 considered one of the highest-risk ports to expose to the internet?", choice_a: "RDP traffic is unencrypted making it easy to intercept credentials in transit", choice_b: "RDP has been a primary initial access vector for ransomware attacks through brute-force credential attacks and exploitation of known vulnerabilities in exposed systems", choice_c: "RDP uses more bandwidth than other remote access protocols making it easy to detect", correct_choice: "B", explanation: "Exposed RDP is constantly attacked by automated tools testing credential combinations and known exploits. Many major ransomware incidents began with compromised RDP. It should never be exposed directly to the internet without strong controls." },
      { question_text: "What does a port scan reveal about a target system and why do attackers perform them?", choice_a: "Port scans reveal the physical location of a server by measuring response timing", choice_b: "Port scans reveal the last login time on each discovered service to identify unused accounts", choice_c: "Port scans identify which network ports are open and what services are running, giving attackers a map of available attack surfaces and the specific service versions to look up known vulnerabilities for", correct_choice: "C", explanation: "Open ports reveal what services are running on a target. Service version banners often reveal specific software versions. Attackers cross-reference these against vulnerability databases to select applicable exploits." },
    ]},
    { title: "NF Module 4: Wi-Fi Security Standards", content: "WEP is broken and must never be used. WPA2-AES is the minimum acceptable standard. WPA3 prevents offline dictionary attacks. Disable WPS due to its PIN vulnerability.", category: "Wireless Security", difficulty: "beginner", duration_minutes: 10, order_index: 4, quiz: [
      { question_text: "Why is WEP considered completely insecure and never acceptable for use today?", choice_a: "WEP supports too few simultaneously connected devices for modern households", choice_b: "WEP has fundamental cryptographic weaknesses that allow its encryption key to be cracked using automated tools in minutes regardless of the key length or complexity used", choice_c: "WEP is incompatible with all devices manufactured after 2010", correct_choice: "B", explanation: "WEP's RC4 implementation has well-documented cryptographic flaws. Tools like Aircrack-ng can capture enough traffic to derive the key in minutes. Using WEP is effectively the same as using no encryption." },
      { question_text: "What specific security improvement does WPA3 provide over WPA2 for home Wi-Fi networks?", choice_a: "WPA3 uses Simultaneous Authentication of Equals which prevents offline dictionary attacks against captured handshakes and provides unique session encryption for each connection", choice_b: "WPA3 doubles the wireless range compared to WPA2 while maintaining the same security level", choice_c: "WPA3 requires a longer minimum password length than WPA2 making brute force harder", correct_choice: "A", explanation: "WPA2 handshakes can be captured and password-guessed offline indefinitely. WPA3 SAE prevents offline cracking because each authentication attempt requires active interaction with the access point, making brute force impractically slow." },
      { question_text: "Why does disabling WPS provide meaningful security improvement even if your Wi-Fi password is very strong?", choice_a: "WPS creates a secondary hidden network that bypasses your main network password entirely", choice_b: "WPS shares your Wi-Fi password with nearby devices automatically even without your action", choice_c: "The WPS PIN method has a design flaw allowing the 8-digit PIN to be brute-forced in a few hours, providing access to your network regardless of how strong your actual Wi-Fi passphrase is", correct_choice: "C", explanation: "WPS PIN authentication is independent of your Wi-Fi password. The PIN flaw exists at the protocol level. An attacker who cracks the WPS PIN gains full network access without ever needing to attack your Wi-Fi password." },
    ]},
    { title: "NF Module 5: Understanding Firewalls and NAT", content: "Stateful firewalls track connection state to allow response traffic while blocking unsolicited inbound connections. UPnP allows malware to open ports automatically.", category: "Network Defense", difficulty: "intermediate", duration_minutes: 10, order_index: 5, quiz: [
      { question_text: "How does your home router's stateful firewall protect internal devices from direct internet attacks?", choice_a: "The router encrypts all internal traffic so attackers cannot read it even if they intercept it", choice_b: "The router blocks all traffic from foreign countries where most attacks originate", choice_c: "The router only forwards response traffic to connections your devices initiated. Unsolicited inbound connection attempts from the internet have no matching state entry and are dropped", correct_choice: "C", explanation: "Stateful inspection tracks which connections your devices opened. An attacker attempting to connect directly to your computer sends traffic the router has no record of initiating, so it discards the packets before they reach your device." },
      { question_text: "What security risk does enabling UPnP on your router create?", choice_a: "UPnP consumes excessive router memory potentially causing instability", choice_b: "UPnP allows any device or software on your network including malware to automatically open ports on your router without your knowledge or approval", choice_c: "UPnP shares your router admin password with connected devices for configuration purposes", correct_choice: "B", explanation: "UPnP lets applications configure port forwarding automatically for convenience. Malware on an infected device can use UPnP to open ports creating persistent access paths from the internet to the infected machine without triggering any alerts." },
      { question_text: "What is a DMZ in network security and what type of systems are placed in it?", choice_a: "A DMZ is a network segment accessible from the internet but isolated from the internal network, used for servers that must accept public connections like web servers so a compromise there cannot directly reach internal systems", choice_b: "A DMZ is a restricted internal zone where only administrator accounts can operate", choice_c: "A DMZ is a high-speed network segment used for latency-sensitive applications like video conferencing", correct_choice: "A", explanation: "DMZ stands for demilitarized zone. Servers in the DMZ face the internet but firewall rules prevent them from initiating connections to the internal network. A compromised DMZ server cannot pivot to internal systems directly." },
    ]},
    { title: "NF Module 6: VPNs and Tunneling", content: "VPN tunnels encrypt all traffic to the VPN server. WireGuard and OpenVPN are strong modern protocols. Avoid PPTP. Split tunneling routes only work traffic through the VPN.", category: "Privacy", difficulty: "intermediate", duration_minutes: 10, order_index: 6, quiz: [
      { question_text: "What does a VPN tunnel do to your network traffic?", choice_a: "It encrypts all your traffic and routes it through a VPN server so that local network observers see only encrypted data going to the VPN server rather than your actual destinations and content", choice_b: "It compresses your traffic to make downloads faster through the encrypted channel", choice_c: "It routes your traffic through a government-monitored server that provides additional protection", correct_choice: "A", explanation: "The VPN tunnel wraps your traffic in encryption before it leaves your device. Anyone on your local network, your ISP, or anyone intercepting your traffic sees only encrypted data destined for the VPN server. Your actual destinations are hidden." },
      { question_text: "What is split tunneling in a corporate VPN context?", choice_a: "A security feature that automatically disconnects VPN when it detects the user is on a trusted network", choice_b: "A method of dividing VPN encryption keys between two servers for additional security", choice_c: "A configuration where work-related traffic routes through the corporate VPN while personal traffic goes directly to the internet, improving personal browsing performance while maintaining corporate security for work traffic", correct_choice: "C", explanation: "Split tunneling balances security and performance. Work traffic through the VPN gets corporate security controls. Personal traffic bypasses the VPN for better speed. Full tunneling sends all traffic through the VPN giving the organization visibility into everything." },
      { question_text: "How does Tor provide stronger anonymity than a VPN?", choice_a: "Tor is faster than VPN so traffic arrives before it can be logged", choice_b: "Tor routes traffic through three independent relays with layered encryption where each relay only knows the previous and next hop, so no single entity knows both the origin and destination", choice_c: "Tor encrypts traffic with military-grade encryption that VPNs are not permitted to use commercially", correct_choice: "B", explanation: "VPN providers know your identity and your destinations. Tor separates this knowledge across three relays using onion encryption. No single relay knows both who you are and where you are going. Even a compromised relay reveals only partial information." },
    ]},
    { title: "NF Module 7: DNS Security", content: "DNS cache poisoning injects false records to redirect traffic. DNS over HTTPS encrypts queries from ISP monitoring. Malware-blocking DNS providers like Cloudflare 1.1.1.2 block known malicious domains.", category: "Network Defense", difficulty: "intermediate", duration_minutes: 10, order_index: 7, quiz: [
      { question_text: "What is DNS cache poisoning and what harm can it cause?", choice_a: "A performance problem where too many DNS entries fill the cache slowing lookup times", choice_b: "An attack that injects false DNS records into a resolver's cache, redirecting users to attacker-controlled sites even when they type correct addresses", choice_c: "A misconfiguration that causes DNS queries to fail intermittently", correct_choice: "B", explanation: "Cache poisoning causes a resolver to serve false IP addresses to everyone who uses it. Users who type correct addresses are silently redirected to fake sites where their credentials are stolen, without any visible warning." },
      { question_text: "What does DNS over HTTPS protect that standard DNS does not?", choice_a: "DNS over HTTPS encrypts DNS queries so your ISP and local network cannot monitor which domains you are looking up, protecting your browsing activity from network-level surveillance", choice_b: "DNS over HTTPS verifies that website certificates match their DNS records preventing man-in-the-middle attacks", choice_c: "DNS over HTTPS speeds up DNS resolution by using faster HTTP2 connection multiplexing", correct_choice: "A", explanation: "Standard DNS queries are sent in plain text. Your ISP and anyone on your local network can see every domain you look up even if the subsequent connections are HTTPS encrypted. DoH encrypts the query, hiding this from network observers." },
      { question_text: "How does using a malware-blocking DNS provider like Cloudflare 1.1.1.2 or Quad9 add a security layer?", choice_a: "These providers encrypt all traffic not just DNS queries providing VPN-like protection", choice_b: "These providers verify website certificates before returning DNS responses", choice_c: "They refuse to resolve known malicious domains, so even malware that tries to contact command and control servers or phishing pages gets a failed lookup rather than a usable IP address", correct_choice: "C", explanation: "Malware-blocking DNS resolvers maintain lists of known malicious domains. When malware attempts to connect to its command server, the resolver returns an error instead of the real IP address. This limits malware functionality even on infected systems." },
    ]},
    { title: "NF Module 8: Network Monitoring Basics", content: "Network monitoring detects suspicious outbound connections, unusual traffic volumes, and unauthorized devices. Wireshark captures packets for detailed analysis. Persistent logs enable retrospective incident investigation.", category: "Network Defense", difficulty: "intermediate", duration_minutes: 12, order_index: 8, quiz: [
      { question_text: "Why does network monitoring improve security incident detection?", choice_a: "Network monitoring prevents attacks by blocking suspicious traffic before it reaches devices", choice_b: "Network monitoring automatically patches vulnerabilities when suspicious traffic is detected", choice_c: "Most security incidents generate distinctive network activity like unusual outbound connections, large data transfers, or scanning patterns. Monitoring converts invisible attacker activity into visible, actionable data", correct_choice: "C", explanation: "Attackers must communicate over the network to exfiltrate data, receive commands, and move laterally. Network monitoring detects these activities even when endpoint security has been evaded. Visibility is the prerequisite for response." },
      { question_text: "What is Wireshark and what kind of security analysis can it support?", choice_a: "An automated vulnerability scanner that tests your network for known weaknesses", choice_b: "A packet capture and analysis tool that shows the actual content of network traffic, useful for verifying encryption is working, diagnosing application problems, and investigating suspicious connections", choice_c: "A network performance monitoring tool that tracks bandwidth usage over time", correct_choice: "B", explanation: "Wireshark captures raw network packets and displays their contents. Security analysts use it to see exactly what data is being transmitted, verify that sensitive data is encrypted, and investigate anomalous connections identified by other monitoring." },
      { question_text: "Why is maintaining persistent network logs valuable even when no incident is currently occurring?", choice_a: "Persistent logs are required by most internet service provider agreements", choice_b: "Persistent logs allow real-time threat blocking by comparing current traffic against historical baselines", choice_c: "Security incidents are often detected days or weeks after initial compromise. Historical network logs allow investigators to reconstruct what happened during the compromise period and determine scope and impact", correct_choice: "C", explanation: "The gap between initial compromise and detection is often weeks. Without historical logs, investigators cannot determine what data was accessed, which systems were reached, or how the attacker moved. Logs retained before the incident enable retrospective analysis." },
    ]},
    { title: "NF Module 9: Common Network Attacks", content: "Man-in-the-middle attacks intercept traffic. ARP poisoning redirects local network traffic. DDoS amplification attacks use protocols that generate large responses from small queries.", category: "Threat Awareness", difficulty: "intermediate", duration_minutes: 12, order_index: 9, quiz: [
      { question_text: "What is a man-in-the-middle attack and how does HTTPS help defend against it?", choice_a: "An attacker positions themselves between two communicating parties to intercept and potentially modify traffic. HTTPS encryption makes intercepted data unreadable and certificate validation detects unauthorized intermediaries", choice_b: "An attack where a third party joins a two-person video call without invitation, defended against by using end-to-end encrypted calling apps", choice_c: "A social engineering attack where an attacker impersonates both parties in a business negotiation simultaneously", correct_choice: "A", explanation: "MITM attacks intercept traffic between you and your destination. HTTPS makes the intercepted data unreadable ciphertext. Certificate pinning and HSTS prevent attackers from substituting their own certificate to decrypt the traffic." },
      { question_text: "What is ARP poisoning and what type of attack does it enable?", choice_a: "A malware attack that corrupts the Windows ARP cache requiring a system reinstall", choice_b: "A network attack that floods the ARP cache with requests causing a denial of service", choice_c: "An attack that sends false ARP responses to redirect local network traffic through an attacker's device, enabling man-in-the-middle interception of all local network communications", correct_choice: "C", explanation: "ARP translates IP addresses to MAC addresses on local networks without authentication. An attacker can claim their MAC address is the router's address, causing all traffic to flow through their machine where it can be captured and modified." },
      { question_text: "How does a DNS amplification attack work and why is it effective for DDoS?", choice_a: "DNS amplification exploits recursive DNS servers to spread malware across networks automatically", choice_b: "DNS amplification sends small DNS queries with a spoofed source address set to the victim's IP, causing DNS servers to send large responses directly to the victim, amplifying traffic volume many times over", choice_c: "DNS amplification poisons DNS caches at multiple ISPs simultaneously to redirect all traffic", correct_choice: "B", explanation: "DNS responses are much larger than queries. By spoofing the victim's IP as the source, a small query causes a large response to be sent to the victim. Multiplied across thousands of DNS servers, this generates massive traffic the victim cannot absorb." },
    ]},
    { title: "NF Module 10: Securing Your Network at Home", content: "Secure your router, segment IoT devices to a guest network, use a security-focused DNS provider at the router level, and review connected devices regularly.", category: "Network Defense", difficulty: "beginner", duration_minutes: 10, order_index: 10, quiz: [
      { question_text: "What is the security benefit of reviewing connected devices in your router admin interface regularly?", choice_a: "It allows you to prioritize bandwidth for your most important devices", choice_b: "It lets you identify unfamiliar devices that may indicate unauthorized network access, a compromised IoT device, or a neighbor using your Wi-Fi", choice_c: "It helps the router firmware update more efficiently by knowing which devices are active", correct_choice: "B", explanation: "Every device on your network is a potential attack surface. Unfamiliar devices warrant investigation. An unknown device may be an unauthorized user, a forgotten old device, or an attacker who has gained Wi-Fi access." },
      { question_text: "Why does placing IoT devices on a separate guest network improve your home security posture?", choice_a: "Network segmentation means a compromised IoT device on the guest network cannot directly communicate with your computers and sensitive data on the main network", choice_b: "Guest networks transmit IoT traffic using a more secure encryption standard than the main network", choice_c: "Guest networks are monitored more closely by ISPs providing better protection for IoT devices", correct_choice: "A", explanation: "IoT devices have poor security track records. Isolating them means a compromised smart camera cannot pivot to attack your laptop. The guest network provides internet access for IoT functions while blocking lateral movement to sensitive devices." },
      { question_text: "Why should you use a security-focused DNS provider like Cloudflare 1.1.1.2 or Quad9 at the router level rather than configuring it per device?", choice_a: "Router-level DNS is faster than device-level DNS because it skips one network hop", choice_b: "Router DNS settings only apply to wired connections while device settings also cover wireless", choice_c: "Configuring DNS at the router level applies malware-blocking DNS protection to every device on the network including IoT devices that cannot be individually configured", correct_choice: "C", explanation: "Many IoT devices and smart appliances cannot have their DNS settings individually configured. Setting security DNS at the router level means the protection automatically applies to every device on the network without individual configuration." },
    ]},
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS4 };
