const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS5(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='Safe Internet Habits'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    { title: "SI Module 1: Safe Browsing Fundamentals", content: "Maintain healthy skepticism about unexpected online prompts. HTTPS encrypts the connection but does not confirm a site is legitimate. Use bookmarks for important sites.", category: "Web Security", difficulty: "beginner", duration_minutes: 10, order_index: 1, quiz: [
      { question_text: "What does the padlock icon in a browser address bar confirm?", choice_a: "The website owner has been verified as a legitimate business by the certificate authority", choice_b: "The website has no malware according to your browser vendor", choice_c: "The connection is encrypted, but not that the site is legitimate. Phishing sites routinely display padlocks too", correct_choice: "C", explanation: "HTTPS certificates are available to anyone including malicious site operators. The padlock only tells you the connection is encrypted. Always verify the actual domain matches what you expect before trusting any site." },
      { question_text: "Why is using bookmarks to navigate to important sites like your bank safer than searching each time?", choice_a: "Bookmarks load faster than search results because they skip the search engine step", choice_b: "Bookmarks go directly to the saved verified URL, while search results can be manipulated to show convincing malicious lookalike sites at the top", choice_c: "Bookmarks are encrypted in the browser preventing them from being tracked", correct_choice: "B", explanation: "Search result manipulation and paid advertising can place convincing malicious lookalike sites above legitimate results, particularly for banking and financial services. Bookmarks bypass this risk by going directly to the verified address." },
      { question_text: "When a download prompt appears unexpectedly on a website you did not deliberately choose to download something from, what should you do?", choice_a: "Decline or close the prompt. Legitimate sites do not initiate unsolicited downloads. This is likely a drive-by download attempt or malicious redirect", choice_b: "Accept the download since the site needs to install a component to display content properly", choice_c: "Accept it only if the file is under a few megabytes in size", correct_choice: "A", explanation: "Unsolicited download prompts are a primary malware distribution mechanism. Legitimate websites do not push downloads without explicit user action. Any unexpected download prompt should be refused and the site abandoned." },
    ]},
    { title: "SI Module 2: Online Privacy Basics", content: "Websites track you through cookies, fingerprinting, and tracking pixels. Block third-party cookies, use privacy search engines, and understand that private browsing only prevents local storage.", category: "Privacy", difficulty: "beginner", duration_minutes: 10, order_index: 2, quiz: [
      { question_text: "What is browser fingerprinting and why is it more persistent than cookie-based tracking?", choice_a: "A tracking technique that identifies you based on unique characteristics of your browser and device configuration, and unlike cookies it cannot be cleared or blocked through standard browser settings", choice_b: "A security feature that records your browser history to detect compromised accounts", choice_c: "A technique where advertisers save your photo from social media to identify your browser sessions", correct_choice: "A", explanation: "Browser fingerprinting combines your browser version, screen resolution, fonts, time zone, and dozens of other attributes into a unique identifier. Unlike cookies, fingerprints cannot be deleted and persist across private browsing sessions." },
      { question_text: "What does private browsing mode actually protect you from?", choice_a: "It protects you from all tracking including your ISP, employer network, and the websites you visit", choice_b: "It provides complete anonymity making your activity invisible to all parties", choice_c: "It prevents your local browser from saving history, cookies, and form data, but does not hide your activity from your ISP, employer, or the websites you visit", correct_choice: "C", explanation: "Private browsing is local only. It prevents the browser on that device from storing session data. Your ISP still sees your traffic, your employer's network still logs connections, and websites still identify you through your IP address and account logins." },
      { question_text: "How does using email aliases like those from SimpleLogin or Firefox Relay protect your privacy?", choice_a: "Email aliases encrypt your messages before they leave your device providing end-to-end protection", choice_b: "Aliases let you use unique forwarding addresses per service. When a service is breached or sells your address you can identify the source and delete just that alias without changing your real email address", choice_c: "Email aliases block advertising emails automatically without requiring you to unsubscribe", correct_choice: "B", explanation: "Each alias is a unique address that forwards to your real inbox. If you used an alias for one service and start receiving spam there, you know that service leaked your address. Delete the alias and the spam stops without affecting your real address." },
    ]},
    { title: "SI Module 3: Social Media Safety", content: "Review privacy settings periodically as platforms change their defaults. Avoid trends asking for personal history details that match common security questions.", category: "Social Media", difficulty: "beginner", duration_minutes: 10, order_index: 3, quiz: [
      { question_text: "Why should you review social media privacy settings periodically rather than setting them once?", choice_a: "Privacy settings expire annually and must be renewed to remain active", choice_b: "Platforms periodically change their default privacy settings, sometimes expanding what is publicly shared after policy updates, so settings that were correct last year may no longer reflect your preferences", choice_c: "Social media algorithms reset privacy preferences based on your activity patterns", correct_choice: "B", explanation: "Social platforms change their interfaces and defaults, sometimes broadening what is visible after policy changes or app updates. Settings you configured correctly when you joined may have been modified without clear notification." },
      { question_text: "What is the privacy risk of participating in popular social media trend formats that ask about your childhood or personal history?", choice_a: "These trends are designed to collect answers to common security questions like first pet, childhood street, and school mascot that are used in account recovery and identity verification systems", choice_b: "These trends harvest your responses to build advertising profiles without your knowledge", choice_c: "These trends expose your approximate age making you more vulnerable to age-targeted scams", correct_choice: "A", explanation: "The most viral trend formats ask exactly the questions that authentication systems use for account recovery. The entertaining framing disguises systematic security question harvesting." },
      { question_text: "A social media friend sends you a message with a link saying you need to see this about yourself. What is the likely situation?", choice_a: "It is a genuine concern from your friend about something they found online involving you", choice_b: "It is a platform notification that your friend tagged you in a post", choice_c: "Your friend's account has likely been compromised and is sending malicious links to their contact list. Verify with your friend through a separate channel before clicking", correct_choice: "C", explanation: "Compromised accounts are used to send malicious links to contact lists because friends are more likely to click links from people they trust. Verify through a phone call or separate message before clicking any unexpected link from a contact." },
    ]},
    { title: "SI Module 4: Safe Online Shopping", content: "Credit cards provide better fraud protection than debit cards. Refuse gift card and wire transfer payment demands. Use virtual card numbers to protect your real card from merchant breaches.", category: "Consumer Safety", difficulty: "beginner", duration_minutes: 10, order_index: 4, quiz: [
      { question_text: "Why do credit cards provide better fraud protection than debit cards for online shopping?", choice_a: "Credit cards have lower transaction fees that make fraud more expensive for merchants", choice_b: "Credit card fraud is covered by law enforcement while debit fraud requires civil litigation", choice_c: "Credit card chargebacks reverse fraudulent charges and the bank absorbs the loss while debit card fraud draws directly from your bank account and recovery is slower and less certain", correct_choice: "C", explanation: "Credit card chargebacks are a strong consumer protection mechanism. The card issuer disputes the charge with the merchant and provisionally credits your account. Debit fraud accesses your actual bank balance and recovery requires a bank investigation that can take weeks." },
      { question_text: "What payment methods should you absolutely refuse to use when shopping online regardless of the reason given?", choice_a: "Wire transfers, gift cards, Zelle, and cryptocurrency. These are irreversible payment methods favored by fraudsters precisely because chargebacks and recovery are impossible", choice_b: "Only debit cards since they lack chargeback protection", choice_c: "International credit cards since they charge higher foreign transaction fees", correct_choice: "A", explanation: "Irreversible payment methods are the universal signature of fraud. No legitimate retailer requires gift cards or wire transfers. When a seller insists on these methods the purchase is almost certainly fraudulent and your money will not be recoverable." },
      { question_text: "What is a virtual card number and how does it protect you when shopping online?", choice_a: "A temporary card number generated by your bank or card issuer for a specific transaction, which limits exposure if the merchant is breached since the number is not your real card", choice_b: "A card number stored only in your browser that cannot be intercepted in transit", choice_c: "A prepaid card number loaded with a specific amount limiting your maximum loss to that amount", correct_choice: "A", explanation: "Virtual card numbers are single-use or merchant-locked numbers linked to your real account. A merchant breach exposes only the virtual number which is useless elsewhere. Your real card number is never exposed to the merchant." },
    ]},
    { title: "SI Module 5: Email Safety and Spam", content: "Check the actual sender address, not just the display name. Never click unsubscribe in malicious spam. SPF, DKIM, and DMARC protect against domain spoofing.", category: "Email Security", difficulty: "beginner", duration_minutes: 10, order_index: 5, quiz: [
      { question_text: "What is the most important thing to verify when evaluating whether an email is legitimate?", choice_a: "The actual sending email address in the From field, not just the display name which can be set to anything", choice_b: "Whether the email contains a company logo and professional formatting", choice_c: "Whether the email was sent during normal business hours", correct_choice: "A", explanation: "Display names can be set to any text including your CEO's name or your bank's name. The actual email address in the From field is what reveals the truth. Always expand the sender field to see the full address, not just the display name." },
      { question_text: "Why should you never click an unsubscribe link in an email you did not sign up for?", choice_a: "Clicking unsubscribe in malicious spam confirms your email address is active and monitored, typically resulting in increased spam rather than reduced", choice_b: "Unsubscribe links in legitimate emails always work but in spam they should be avoided", choice_c: "Spam filter laws require all commercial emails to include unsubscribe links making them safe to use", correct_choice: "A", explanation: "Legitimate companies respect unsubscribe requests. In malicious spam, the unsubscribe link is a confirmation trap. Clicking it signals that your address is real and actively monitored, making it more valuable to spammers who then sell it or increase volume." },
      { question_text: "What are SPF, DKIM, and DMARC and what do they collectively protect against?", choice_a: "They are antivirus scanning protocols that check email attachments before delivery", choice_b: "They are browser security standards that verify email sender certificates", choice_c: "They are email authentication standards that allow receiving servers to verify that emails claiming to be from a domain were actually authorized by that domain, protecting against email spoofing", correct_choice: "C", explanation: "SPF specifies authorized sending servers, DKIM adds cryptographic signatures to messages, and DMARC tells receivers what to do with failures. Together they make it significantly harder for attackers to forge your domain in phishing campaigns." },
    ]},
    { title: "SI Module 6: Public Wi-Fi Safety", content: "Public Wi-Fi is untrusted. HTTPS encrypts content but not metadata. Use VPN consistently. Disable auto-connect to open networks. Verify the exact network name with staff.", category: "Network Security", difficulty: "beginner", duration_minutes: 10, order_index: 6, quiz: [
      { question_text: "Why does using HTTPS not fully protect you on public Wi-Fi without a VPN?", choice_a: "HTTPS only encrypts file downloads not regular browsing on public networks", choice_b: "HTTPS encrypts the content of your traffic but DNS queries still reveal which domains you visit, your destination IP addresses are visible, and the network operator can still monitor your activity patterns", choice_c: "HTTPS encryption is automatically disabled by most public Wi-Fi networks for compatibility", correct_choice: "B", explanation: "HTTPS encrypts content but metadata remains visible. Your DNS lookups reveal domains even over HTTPS. Your IP connections reveal destinations. A VPN encrypts all of this before it leaves your device, protecting both content and metadata." },
      { question_text: "What is an evil twin Wi-Fi attack and how do you protect against it?", choice_a: "A rogue access point using the same network name as a legitimate one to intercept traffic from devices that connect to it. Protect against it by verifying the exact network name with staff and using a VPN", choice_b: "A man-in-the-middle attack that duplicates websites to capture login credentials", choice_c: "A malware attack that creates a second wireless network adapter on infected devices", correct_choice: "A", explanation: "Evil twin networks are indistinguishable by name from legitimate ones. Always confirm the exact network name with staff. Using a VPN provides protection even if you connect to an evil twin since your traffic is encrypted before leaving your device." },
      { question_text: "Why should you disable auto-connect to open Wi-Fi networks on your mobile devices?", choice_a: "Auto-connect causes your device to automatically join networks with the same names as ones you have previously used, which attackers exploit by broadcasting familiar network names", choice_b: "Auto-connect drains battery faster by maintaining constant network scanning", choice_c: "Auto-connect slows down initial connection speeds by trying too many networks simultaneously", correct_choice: "A", explanation: "Your device broadcasts probe requests for networks it remembers. Attackers use these to identify what networks to name their evil twin. Your device then connects automatically to the attacker's network. Disabling auto-connect requires you to consciously choose a network." },
    ]},
    { title: "SI Module 7: Protecting Children Online", content: "Grooming is a gradual process predators use to build trust before exploitation. Create an open door policy so children report uncomfortable experiences without fear of punishment.", category: "Family Safety", difficulty: "beginner", duration_minutes: 12, order_index: 7, quiz: [
      { question_text: "What is grooming in the context of online child safety?", choice_a: "The process of teaching children appropriate behavior for video calls and online meetings", choice_b: "A parental control technique for gradually introducing children to internet access", choice_c: "A process where an online predator builds trust with a child over time before attempting exploitation, often involving moving conversations to less monitored platforms", correct_choice: "C", explanation: "Grooming is a deliberate, patient process. Predators establish trust by presenting as peers or mentors, isolating the child from trusted adults, and normalizing inappropriate contact gradually before exploitation attempts." },
      { question_text: "Why is having an open door policy where children can report uncomfortable online experiences without fear of punishment so important?", choice_a: "It reduces the time children spend online by making them more aware of risks", choice_b: "Children who fear punishment for online incidents are less likely to report grooming, harassment, or exploitation, allowing harmful situations to continue longer without adult intervention", choice_c: "Reporting requirements help platforms improve their safety systems faster", correct_choice: "B", explanation: "Children often fear losing device access or getting in trouble more than the harm they are experiencing. A non-punitive approach ensures they come to trusted adults at the earliest sign of trouble rather than suffering in silence." },
      { question_text: "What should you consider when a child wants to join a social media platform with a minimum age of 13?", choice_a: "The minimum age exists for real child safety and privacy reasons. Allowing early access means accepting the risks those policies were specifically designed to protect younger children from", choice_b: "If the child is mature enough to understand internet safety the minimum age is just a guideline", choice_c: "Age requirements are only suggestions since platforms cannot verify ages anyway", correct_choice: "A", explanation: "COPPA minimum ages exist because children under 13 have specific privacy and safety vulnerabilities those platforms are not designed to protect. Allowing early access bypasses these protections deliberately, accepting the associated risks." },
    ]},
    { title: "SI Module 8: Digital Footprint Awareness", content: "Your active footprint is what you post intentionally. Your passive footprint is data collected without direct action. Search your own name to understand your public exposure.", category: "Privacy", difficulty: "beginner", duration_minutes: 10, order_index: 8, quiz: [
      { question_text: "What is the difference between an active and passive digital footprint?", choice_a: "Active footprint consists of things you deliberately post online. Passive footprint is data collected without your direct action through tracking, browsing behavior, and data inference", choice_b: "Active footprint is data you can delete while passive footprint is permanent", choice_c: "Active footprint is public data while passive footprint is stored privately by companies", correct_choice: "A", explanation: "Your active footprint is what you choose to share. Your passive footprint is created automatically through tracking pixels, browsing behavior, app usage, and location data collected without your explicit participation. The passive footprint is typically much larger." },
      { question_text: "What is the most effective way to understand what information is publicly visible about you online?", choice_a: "Contact data broker companies directly and ask for a report of the data they hold", choice_b: "Regularly search for your own name and email addresses in search engines and check image search results to see what is publicly discoverable", choice_c: "Review your own social media profiles while logged in", correct_choice: "B", explanation: "Searching for yourself from a logged-out browser or incognito window shows what strangers and employers see. Search your name with and without quotes, include your location and employer, and check image results to get a realistic picture of your public profile." },
      { question_text: "How do data broker opt-out requests reduce your digital footprint and what is their limitation?", choice_a: "Opt-out requests permanently remove your data from all databases and prevent any future collection", choice_b: "Opt-out requests are legally binding in all countries and must be honored within 24 hours", choice_c: "Opt-out requests ask individual brokers to remove your data and many reputable ones comply, but the process must be repeated for hundreds of brokers and data can be re-collected over time", correct_choice: "C", explanation: "Most reputable data brokers honor opt-out requests but there are hundreds of them. Manual opt-outs are extremely tedious. Data can also be re-collected from public sources after removal. Services like DeleteMe automate and repeat the process but it requires ongoing effort." },
    ]},
    { title: "SI Module 9: Recognizing Online Scams", content: "Scams consistently use urgency combined with authority. Gift card payment demands are universally a fraud indicator. Verify independently before acting on any alarming request.", category: "Consumer Safety", difficulty: "beginner", duration_minutes: 10, order_index: 9, quiz: [
      { question_text: "What psychological mechanism do scammers most consistently rely on across different scam types?", choice_a: "Greed triggered by unexpected financial opportunities", choice_b: "Urgency combined with authority, creating pressure to act immediately without time to think critically or verify the request through other channels", choice_c: "Curiosity about surprising or alarming information about the target", correct_choice: "B", explanation: "Urgency prevents verification. Authority suppresses the instinct to question. Together they reliably override normal critical thinking regardless of whether the specific scam is a tech support call, phishing email, or romance scam." },
      { question_text: "You receive an unexpected call from someone who sounds exactly like your adult child saying they are in trouble and need money immediately by wire transfer. What should you do?", choice_a: "Send the money immediately since your child is in danger", choice_b: "Ask them their pet's name to verify their identity before sending", choice_c: "Hang up and call your child directly on their known phone number to verify. This is a common grandparent scam pattern using AI voice cloning or simple impersonation", correct_choice: "C", explanation: "Virtual kidnapping and emergency family scams specifically rely on panic preventing verification. Hanging up and calling the supposed victim on their real number takes seconds and immediately confirms whether the crisis is real." },
      { question_text: "What payment method demand is a universal indicator that a transaction is fraudulent?", choice_a: "Any request for payment by gift card, wire transfer, cryptocurrency, or Zelle as these are irreversible methods that no legitimate business requires for standard purchases", choice_b: "Requests for credit card payment since legitimate businesses prefer bank transfers", choice_c: "Any payment method that does not accept personal checks since checks provide a paper trail", correct_choice: "A", explanation: "Irreversible payment methods are the signature of fraud. Fraudsters demand them specifically because chargebacks and recovery are impossible. No legitimate retailer, government agency, or utility company requires gift cards or wire transfers for standard transactions." },
    ]},
    { title: "SI Module 10: Managing App Permissions", content: "Grant only permissions apps genuinely need for their stated function. Prefer While Using over Always for location. Audit permissions periodically and revoke unused app access.", category: "Privacy", difficulty: "beginner", duration_minutes: 10, order_index: 10, quiz: [
      { question_text: "A flashlight app requests access to your contacts, location, and microphone. What does this indicate?", choice_a: "The app is a premium version that includes additional features requiring these permissions", choice_b: "Modern flashlight apps require sensor data to adjust brightness automatically", choice_c: "The app is requesting far more access than a flashlight requires. This suggests data collection beyond its stated function and the permissions should be denied", correct_choice: "C", explanation: "A flashlight app needs camera flash access only. Requests for contacts, location, and microphone are completely unrelated to its function and indicate the app intends to collect data for other purposes like advertising or resale." },
      { question_text: "What is the privacy advantage of choosing while using the app instead of always for location permissions?", choice_a: "While using the app limits location access to when you are actively in the app, preventing it from continuously tracking your movements in the background when you are doing other things", choice_b: "While using the app setting uses less battery by disabling GPS between sessions", choice_c: "While using the app setting is more accurate than always-on location", correct_choice: "A", explanation: "Always-on location allows apps to record your location continuously building a comprehensive record of everywhere you go. While using the app grants the location function you need without enabling background tracking of your daily movements." },
      { question_text: "Why should you regularly audit and remove permissions from apps you rarely use?", choice_a: "Unused app permissions slow down your device by consuming background processing cycles", choice_b: "Apps you rarely use may have changed ownership, been acquired by a data broker, or had their privacy practices change. Revoking permissions limits ongoing data collection from apps providing you little value", choice_c: "Unused app permissions require annual renewal which costs additional storage space", correct_choice: "B", explanation: "App ownership changes without user notification. An app you trusted years ago may now be owned by a company with very different data practices. Regular permission audits ensure you are only granting ongoing access to apps you actively use and trust." },
    ]},
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS5 };
