const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS6(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='Device Security'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    { title: "DS Module 1: Securing Windows 10 and 11", content: "Use a standard user account for daily tasks. Enable Controlled Folder Access for ransomware protection. Enable BitLocker for full disk encryption.", category: "Operating Systems", difficulty: "beginner", duration_minutes: 10, order_index: 1, quiz: [
      { question_text: "Why is using a standard user account for daily computing rather than an administrator account an important security practice?", choice_a: "Malware that infects a standard user account cannot install persistently, modify system settings, or spread because it is constrained by the account's limited privileges", choice_b: "Standard accounts load Windows faster because they skip administrative startup checks", choice_c: "Standard accounts are required for connecting to corporate networks by most IT policies", correct_choice: "A", explanation: "Administrator malware automatically inherits administrator privileges and can do anything to the system. Standard account malware is constrained by what that account can do, cannot install drivers, cannot modify security settings, and is significantly easier to remediate." },
      { question_text: "What does Controlled Folder Access in Windows Security protect against?", choice_a: "It prevents unauthorized users from accessing specific folders when you share your computer", choice_b: "It blocks access to system folders from standard user accounts", choice_c: "It prevents ransomware and unauthorized applications from modifying files in protected folders by only allowing trusted applications to write to those locations", correct_choice: "C", explanation: "Controlled Folder Access blocks write access to protected folders from any application not on the trusted list. Ransomware attempting to encrypt files in your Documents folder is blocked even if it has user-level access to run." },
      { question_text: "What does enabling BitLocker encryption on your Windows system drive protect against?", choice_a: "It protects against malware attempting to modify system files", choice_b: "It ensures that physical theft of your laptop or removal of the drive from your computer does not result in readable access to your files without your password", choice_c: "It prevents ransomware from encrypting your personal files", correct_choice: "B", explanation: "BitLocker protects data at rest. Without it, a thief who removes your hard drive can read every file without needing your Windows login. With BitLocker the drive is unreadable ciphertext without the encryption key." },
    ]},
    { title: "DS Module 2: Securing Android Devices", content: "Install apps only from Google Play Store. Review Accessibility access permissions carefully. Enable Find My Device and keep OS updated.", category: "Mobile Security", difficulty: "beginner", duration_minutes: 10, order_index: 2, quiz: [
      { question_text: "Why is installing apps only from the Google Play Store recommended over sideloading from other sources?", choice_a: "Play Store apps are always free while sideloaded apps often have hidden costs", choice_b: "Play Store apps use less battery than apps from other sources", choice_c: "The Play Store uses Google Play Protect scanning and review processes that catch many malicious apps, while sideloaded apps bypass all these checks and have significantly higher rates of malicious content", correct_choice: "C", explanation: "Sideloaded APKs have no vetting. Play Protect scans Play Store apps continuously. While the Play Store is not perfect, sideloaded apps from unofficial sources are statistically far more likely to contain malware than those from the Play Store." },
      { question_text: "What security risk does rooting an Android device create?", choice_a: "Rooting voids the warranty causing the manufacturer to remotely disable security features", choice_b: "Rooting removes Android's application sandbox and security model allowing any app to access all data and system resources without permission prompts", choice_c: "Rooting installs unauthorized apps automatically from third-party repositories", correct_choice: "B", explanation: "Android's security is built on sandboxing and permission controls. Root access bypasses these, giving any app that obtains root the ability to access all other apps' data, system files, and hardware without restriction." },
      { question_text: "Why is reviewing apps with Accessibility access permission particularly important for Android security?", choice_a: "Accessibility apps consume more battery making devices slow and draining faster", choice_b: "Accessibility apps send usage statistics to Google that reduce your privacy", choice_c: "Accessibility access grants broad device control including reading screen content and simulating user actions, making it a high-value permission that malware specifically targets to bypass other security controls", correct_choice: "C", explanation: "Accessibility services can read everything on screen, simulate taps and swipes, and intercept input. Legitimate accessibility tools for people with disabilities need this. Malware that obtains accessibility access can steal credentials displayed on screen and control the device." },
    ]},
    { title: "DS Module 3: Securing iOS Devices", content: "iOS encrypts storage when a passcode is set. Enable Find My iPhone for remote wipe. Use While Using The App for location permissions. Install updates promptly.", category: "Mobile Security", difficulty: "beginner", duration_minutes: 10, order_index: 3, quiz: [
      { question_text: "What does iOS full disk encryption protect against and when is it automatically enabled?", choice_a: "It protects against malware accessing your files and is enabled when you install a security app", choice_b: "It protects against physical access to your data if the device is lost or stolen and is automatically enabled when you set a passcode", choice_c: "It protects against network interception of iCloud backups and is enabled when you activate iCloud", correct_choice: "B", explanation: "iOS encrypts device storage automatically when a passcode is configured. Without the passcode the encrypted storage is unreadable. A stolen iPhone without a passcode is data-secure unlike older devices or those without passcodes." },
      { question_text: "What is the security benefit of enabling Find My iPhone beyond just locating a lost device?", choice_a: "Find My iPhone enables remote lock and remote wipe, allowing you to protect your data from a stolen device even if you cannot physically recover it and enabling the device to report its last known location before the battery dies", choice_b: "Find My iPhone allows Apple to remotely install security updates on your device", choice_c: "Find My iPhone shares your location with Apple for improved mapping services", correct_choice: "A", explanation: "Remote wipe eliminates data on a stolen device preventing access to your information. The send last location feature records where the device was when the battery died, which often helps law enforcement locate the device." },
      { question_text: "What is iOS Lockdown Mode and for whom is it designed?", choice_a: "A parental control feature that prevents children from installing apps without parent approval", choice_b: "A feature that locks the device after a specified number of failed passcode attempts", choice_c: "An extreme security hardening mode that disables certain functionality to protect against sophisticated targeted attacks, designed specifically for journalists, activists, executives, and others at elevated risk of state-level attacks", correct_choice: "C", explanation: "Lockdown Mode makes significant usability trade-offs including disabling certain attachment types, web technologies, and connection methods. These trade-offs are appropriate for users facing sophisticated nation-state level attacks but impractical for general use." },
    ]},
    { title: "DS Module 4: Laptop Security Best Practices", content: "Full disk encryption is the definitive protection against physical theft. Configure screen lock to engage after 1-5 minutes. Use a privacy screen filter in public spaces.", category: "Physical Security", difficulty: "beginner", duration_minutes: 10, order_index: 4, quiz: [
      { question_text: "What is the most effective protection if your encrypted laptop is stolen?", choice_a: "Full disk encryption ensures the thief cannot read your files without the encryption key even if they remove the storage drive and connect it to another computer", choice_b: "A strong Windows password prevents access to the laptop since the thief cannot log in", choice_c: "Remote wipe through Find My Device will erase the laptop before the thief can access it", correct_choice: "A", explanation: "Full disk encryption is the definitive protection for physical theft. A strong login password can be bypassed by removing the drive. Remote wipe only works if the device connects to the internet. Encryption protects the data regardless of what the thief does with the hardware." },
      { question_text: "What is shoulder surfing and what are two effective countermeasures?", choice_a: "A network attack that captures Wi-Fi traffic from nearby users, countered by using a VPN and HTTPS", choice_b: "Physical theft of a laptop from behind the user while they are distracted, countered by laptop locks and staying in view of belongings", choice_c: "Observing your screen or keyboard from nearby to capture sensitive information, countered by positioning yourself against a wall and using a privacy screen filter", correct_choice: "C", explanation: "Shoulder surfing is low-tech but effective for capturing credentials, sensitive documents, and confidential work. Walls eliminate the angle of attack from behind. Privacy filters make the screen readable only from directly in front of you." },
      { question_text: "How should you configure screen timeout and lock settings on a laptop used in shared spaces?", choice_a: "Set a long timeout to avoid frequent interruptions to your workflow", choice_b: "Set the screen to lock after one to five minutes of inactivity so a brief absence does not expose your work to unauthorized access", choice_c: "Disable automatic locking since manually locking with the keyboard shortcut is sufficient", correct_choice: "B", explanation: "Brief absences to use the bathroom, get coffee, or speak with someone are enough time for someone to access an unlocked screen. A one to five minute timeout balances security with the minor inconvenience of re-authenticating after short breaks." },
    ]},
    { title: "DS Module 5: Smart Home and IoT Security", content: "Change default credentials immediately on all IoT devices. Place IoT devices on a guest network. Update firmware and disable features you do not use.", category: "IoT Security", difficulty: "beginner", duration_minutes: 10, order_index: 5, quiz: [
      { question_text: "Why are IoT devices considered particularly high-risk security components in a home network?", choice_a: "IoT devices broadcast their data publicly by default requiring manual privacy configuration", choice_b: "IoT devices are more frequently targeted by hackers because they are more valuable than computers", choice_c: "IoT devices often have weak default credentials, infrequent security updates, long operational lifespans, and limited user interfaces that make security configuration difficult", correct_choice: "C", explanation: "The combination of insecure defaults, rare updates, and long use periods means IoT devices accumulate unpatched vulnerabilities over years. Users rarely interact with their router's security settings let alone their smart thermostat's." },
      { question_text: "What is the most important first security step when setting up any new IoT device?", choice_a: "Register the device with the manufacturer to receive warranty support and security notices", choice_b: "Change the default username and password immediately to a strong unique credential before connecting the device to your network", choice_c: "Disable all features except the ones you specifically intend to use", correct_choice: "B", explanation: "Default credentials for IoT devices are published in manuals, support forums, and attacker databases. A device left with default credentials is effectively accessible to anyone who knows the model. Change credentials before connecting to any network." },
      { question_text: "What network configuration best reduces the risk from a compromised IoT device?", choice_a: "Assign each IoT device a static IP address so you can monitor its traffic more easily", choice_b: "Enable MAC address filtering on your router to restrict which devices can join", choice_c: "Place all IoT devices on a separate network segment such as a guest network that provides internet access but cannot communicate with your computers and sensitive devices on the main network", correct_choice: "C", explanation: "Network segmentation is the most effective mitigation for IoT risk. A compromised device on the guest network cannot pivot to attack your laptop or NAS. It may be used for internet-based attacks but your local sensitive data remains protected." },
    ]},
    { title: "DS Module 6: USB and External Storage Security", content: "Never connect found USB devices. Use USB data blockers at public charging ports. Properly wipe drives before disposal as deletion and formatting do not destroy data.", category: "Physical Security", difficulty: "intermediate", duration_minutes: 10, order_index: 6, quiz: [
      { question_text: "What is juice jacking and how does a USB data blocker protect against it?", choice_a: "A battery drain attack where charging cables transmit malware through the power pins", choice_b: "An attack using modified public USB charging ports to deliver malware or steal data while your device charges, blocked by a USB data blocker that passes power but physically disconnects the data pins", choice_c: "A credential theft attack targeting mobile banking apps when using public Wi-Fi", correct_choice: "B", explanation: "USB ports carry both power and data. Modified public charging ports use the data pins to attack connected devices. A USB data blocker is a passthrough device that physically breaks the data connections while still allowing the power pins to charge your device." },
      { question_text: "What is a USB Rubber Ducky and why is it dangerous?", choice_a: "A hardware device disguised as a USB flash drive that registers as a keyboard and automatically types malicious commands faster than any human could, bypassing application-based security controls", choice_b: "A USB device that automatically copies files from your computer to a hidden partition for data theft", choice_c: "A USB device used by security researchers to test physical security awareness by placing it in visible locations", correct_choice: "A", explanation: "The Rubber Ducky and similar HID attack tools are completely transparent to the operating system because they identify as keyboards, which are inherently trusted. They can execute complex attack sequences in seconds before any user response is possible." },
      { question_text: "How should you properly dispose of a hard drive that contains sensitive personal or business data?", choice_a: "Format the drive multiple times using the quick format option to ensure data is overwritten", choice_b: "Delete all files and empty the Recycle Bin before disposing of the drive", choice_c: "Use dedicated data wiping software that overwrites all sectors, or physically destroy the drive if the data sensitivity warrants it. Standard deletion and formatting leaves data recoverable with readily available tools", correct_choice: "C", explanation: "Deleting files and formatting only removes file system references. The actual data remains and is trivially recoverable with free tools. Proper wiping overwrites every sector with random data multiple times, or physical destruction of the platters ensures data cannot be recovered." },
    ]},
    { title: "DS Module 7: Software Updates and Patch Management", content: "The window between patch release and installation is when exploitation risk is highest. Browsers and plugins are the highest priority as they process untrusted content constantly.", category: "System Maintenance", difficulty: "beginner", duration_minutes: 10, order_index: 7, quiz: [
      { question_text: "Why is the period between a vulnerability being discovered and a patch being applied the most dangerous time?", choice_a: "Security researchers publicly announce vulnerabilities before patches exist giving attackers time to prepare", choice_b: "Antivirus software cannot detect unknown vulnerabilities making systems completely unprotected", choice_c: "Attackers actively scan for and exploit known unpatched vulnerabilities. The longer the delay between patch availability and installation, the greater the risk of exploitation", correct_choice: "C", explanation: "Attackers monitor security advisories and begin targeting known vulnerabilities as soon as they are public. The window between patch release and installation is when exploitation is most likely. Rapid patching closes this window." },
      { question_text: "Why should browsers, browser plugins, and PDF readers receive the highest update priority?", choice_a: "These applications are most frequently used making their updates most noticeable to users", choice_b: "Internet-facing applications that process untrusted content from the web are the most frequently targeted by attackers and the most likely to contain exploitable vulnerabilities", choice_c: "Browser updates are automatically applied without user action so they represent the least effort for the most gain", correct_choice: "B", explanation: "Applications that regularly process content from untrusted internet sources are the highest-value exploit targets. Browser vulnerabilities, PDF reader flaws, and plugin exploits are the most commonly used initial access vectors in real attacks." },
      { question_text: "What is the benefit of using a software inventory or update management tool for keeping applications current?", choice_a: "These tools negotiate better pricing for software licenses from developers", choice_b: "These tools automatically remove applications that have been unused for more than 30 days", choice_c: "They provide visibility into all installed software versions and can identify outdated applications that manual checking would easily miss, particularly less prominent utilities that do not have prominent update notifications", correct_choice: "C", explanation: "Manual update checking requires you to know every installed application and remember to check each one periodically. Inventory tools provide a comprehensive view and flag outdated versions including small utilities and plugins that rarely prompt for updates." },
    ]},
    { title: "DS Module 8: Screen Lock and Authentication", content: "Biometrics can be legally compelled in some jurisdictions while PINs generally cannot. Automatic screen lock is more reliable than manual locking. Windows Hello uses the TPM secure enclave.", category: "Authentication", difficulty: "intermediate", duration_minutes: 10, order_index: 8, quiz: [
      { question_text: "What is the security difference between biometric authentication and PIN-based authentication in legal contexts?", choice_a: "Biometric authentication such as fingerprints and face can be compelled by legal authority in some jurisdictions while a PIN representing knowledge generally cannot be compelled under the same circumstances", choice_b: "Biometrics are always more secure than PINs because they cannot be guessed or shared", choice_c: "PINs can be legally compelled in all jurisdictions while biometrics cannot be compelled anywhere", correct_choice: "A", explanation: "This is an important distinction for high-risk individuals. In the US and some other jurisdictions, courts have ruled that compelling a biometric is like compelling a physical action while compelling a PIN is like compelling testimony, affording different legal protections." },
      { question_text: "Why should you set your device screen to lock automatically after a short idle period rather than relying on manually locking it?", choice_a: "Automatic locking also saves battery life by reducing display-on time between active sessions", choice_b: "Manual locking is unreliable because brief distractions or emergencies cause people to forget, while automatic locking ensures the screen is always secured after a predictable idle period", choice_c: "Automatic locking syncs your lock state with other devices on the same account", correct_choice: "B", explanation: "Manual locking requires remembering in every situation including stressful, rushed, or distracted ones. Automatic timeout ensures that even if you forget, the device locks itself after a short predictable window, limiting the exposure from any unattended moment." },
      { question_text: "What makes Windows Hello with biometrics plus a PIN more secure than a password alone?", choice_a: "Windows Hello credentials are stored in the cloud making them inaccessible to local attackers", choice_b: "Windows Hello is required by Windows 11 for all accounts as a security baseline", choice_c: "Windows Hello uses the device's secure enclave to store credentials that cannot be extracted, requires physical presence for biometric authentication, and the PIN is device-specific and never transmitted over networks", correct_choice: "C", explanation: "Windows Hello credentials never leave the device and are protected by the TPM. Unlike passwords which can be phished, reused, or captured in transit, Hello credentials are bound to the specific device and require the physical device to authenticate." },
    ]},
    { title: "DS Module 9: Antivirus and Endpoint Protection", content: "Behavioral detection identifies threats by what they do, not signatures alone. Never disable antivirus at any application's request. EDR provides continuous monitoring beyond signature scanning.", category: "Malware Defense", difficulty: "intermediate", duration_minutes: 10, order_index: 9, quiz: [
      { question_text: "What is the difference between signature-based detection and behavioral detection in modern endpoint protection?", choice_a: "Signature detection only works on email attachments while behavioral detection works on all file types", choice_b: "Signature detection identifies known malware by matching against a database of known threat patterns, while behavioral detection identifies suspicious activity patterns that indicate malware even for previously unknown threats", choice_c: "Behavioral detection is less reliable than signature detection because it generates false positives", correct_choice: "B", explanation: "Signature detection is blind to new malware until signatures are updated. Behavioral detection watches for ransomware-like file encryption activity, credential dumping behavior, or suspicious process injection regardless of whether the specific malware is known." },
      { question_text: "Why should you never disable antivirus software at an application's request?", choice_a: "Antivirus software is required by law in most enterprise environments and disabling it creates legal liability", choice_b: "Disabling antivirus is unnecessarily disruptive since legitimate software can be installed with antivirus active", choice_c: "No legitimate software requires antivirus to be disabled for installation. Requests to disable security software are a manipulation technique used by malware to remove protection before executing its payload", correct_choice: "C", explanation: "If an installer cannot run with antivirus active, the antivirus is detecting something concerning about it. Legitimate installers are designed to coexist with security software. This request is the software telling you it cannot survive security scrutiny." },
      { question_text: "What is Endpoint Detection and Response and how does it differ from traditional antivirus?", choice_a: "EDR provides continuous monitoring, behavioral analysis, and forensic investigation capabilities that go far beyond signature scanning, enabling detection of advanced threats and detailed incident response with full activity timelines", choice_b: "EDR is antivirus software designed specifically for endpoint devices like laptops rather than servers", choice_c: "EDR is a cloud-based antivirus service that updates signatures faster than locally installed software", correct_choice: "A", explanation: "Traditional antivirus scans files on access. EDR continuously records system activity, correlates events across processes and time, identifies sophisticated attack patterns that span multiple actions, and provides investigators with complete attack timelines." },
    ]},
    { title: "DS Module 10: Device Disposal and Data Wiping", content: "Standard factory reset on unencrypted devices leaves data recoverable. Encrypt then reset for maximum security. Physically destroy storage for highly sensitive data.", category: "Data Security", difficulty: "intermediate", duration_minutes: 10, order_index: 10, quiz: [
      { question_text: "Why is performing a standard factory reset insufficient for securely wiping a device before disposal?", choice_a: "Factory resets only wipe user settings but leave the operating system files intact which contain browsing history", choice_b: "Factory resets require an internet connection to complete securely and may fail without one", choice_c: "Standard factory resets on older devices without encryption may leave data recoverable with forensic tools. A secure wipe requires encryption followed by factory reset or specialized data destruction software", correct_choice: "C", explanation: "On unencrypted devices, factory reset removes file system pointers but leaves data on storage media recoverable with widely available tools. Encrypting the device first then resetting ensures the reset removes the keys needed to interpret the stored data." },
      { question_text: "What is the recommended approach for disposing of a hard drive containing highly sensitive financial or medical records?", choice_a: "Physical destruction of the storage media by shredding, degaussing, or drilling through the platters ensures data cannot be recovered by any means", choice_b: "Formatting the drive three times with the full format option ensures complete data removal", choice_c: "Using a Department of Defense standard wipe tool that overwrites data seven times is sufficient for all sensitivity levels", correct_choice: "A", explanation: "For highly sensitive data, software-based wiping is adequate for most purposes but physical destruction provides absolute certainty. Hard drive shredders, degaussers, and professional data destruction services provide verifiable destruction certificates." },
      { question_text: "Before donating your old smartphone to a charity or giving it to a family member, what preparation is required?", choice_a: "Delete all apps manually before performing a factory reset to ensure app data is removed before the reset process", choice_b: "Remove the SIM card and memory card, sign out of all accounts, then perform a factory reset. On modern encrypted devices this effectively secures the data", choice_c: "Simply removing your accounts from the device is sufficient since apps store data in the cloud rather than on the device", correct_choice: "B", explanation: "The critical steps are signing out of all accounts to prevent the recipient from accessing your cloud data and services, and factory resetting to remove local data. On modern encrypted devices the reset removes the encryption key making remaining data unreadable." },
    ]},
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS6 };
