const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS7(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='Privacy Protection'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    { title: "PP Module 1: Understanding Data Brokers", content: "Data brokers aggregate personal information from public records, social media, and loyalty programs. Their profiles enable targeted social engineering. Opt out individually or use services like DeleteMe.", category: "Privacy", difficulty: "beginner", duration_minutes: 10, order_index: 1, quiz: [
      { question_text: "What types of personal information do data brokers typically aggregate and sell?", choice_a: "Name, address, phone number, relatives, estimated income, political affiliation, purchasing behavior, health interests, and location history gathered from public records, loyalty programs, and online tracking", choice_b: "Only information you have deliberately made public on social media profiles", choice_c: "Only financial records obtained from credit reporting agencies", correct_choice: "A", explanation: "Data brokers aggregate information from dozens of sources including public records, voter registrations, social media, loyalty programs, app data, and purchasing records. The resulting profiles are often more detailed than people expect and include sensitive inferences." },
      { question_text: "Why can data broker profiles create security risks beyond privacy concerns?", choice_a: "Data broker profiles are used to generate targeted advertising that can include malicious links", choice_b: "Data broker profiles reduce your credit score by increasing the number of entities that have accessed your information", choice_c: "Data broker profiles provide attackers with detailed personal information that can be used to answer security questions, build convincing pretexts for social engineering, and target spear phishing attacks", correct_choice: "C", explanation: "A detailed profile including your relatives names, previous addresses, employer, and daily patterns gives attackers precisely the information needed to build convincing impersonations and answer the security questions protecting your accounts." },
      { question_text: "What is the most practical approach to reducing your data broker profile?", choice_a: "Avoiding the internet entirely to prevent new data collection", choice_b: "Contacting each broker individually which takes hours but is free and effective for the brokers you reach", choice_c: "Using a data removal service like DeleteMe that automates opt-out requests across hundreds of brokers and repeats the process since data can be re-collected over time", correct_choice: "C", explanation: "Manual opt-outs are free but there are hundreds of brokers and the process must be repeated. Automated services handle this continuously. The choice depends on your time versus money trade-off and how important reducing your profile is to you." },
    ]},
    { title: "PP Module 2: Browser Privacy Settings", content: "Block third-party cookies to reduce cross-site tracking. Browser fingerprinting persists even after clearing cookies. Use DuckDuckGo or Brave Search for privacy-respecting searches.", category: "Privacy", difficulty: "beginner", duration_minutes: 10, order_index: 2, quiz: [
      { question_text: "What is the purpose of blocking third-party cookies in your browser settings?", choice_a: "Third-party cookies slow down page loading by requiring additional server connections", choice_b: "Third-party cookies are primarily used by advertising and analytics companies to track you across multiple different websites and blocking them significantly reduces cross-site behavioral tracking", choice_c: "Third-party cookies create security vulnerabilities that allow cross-site scripting attacks", correct_choice: "B", explanation: "First-party cookies serve legitimate purposes like keeping you logged in. Third-party cookies from external domains primarily serve cross-site tracking for advertising profiling. Blocking them has minimal impact on functionality while significantly reducing tracking." },
      { question_text: "What is browser fingerprinting and why can it track you even when you clear cookies?", choice_a: "Browser fingerprinting identifies you based on the unique combination of your browser version, screen resolution, installed fonts, time zone, and dozens of other device characteristics that persist regardless of cookie deletion", choice_b: "Browser fingerprinting is a security feature that records your activity to detect account compromise", choice_c: "Browser fingerprinting only works when you are logged into a Google or Facebook account", correct_choice: "A", explanation: "Unlike cookies which can be deleted, fingerprint characteristics are properties of your browser and hardware that remain constant. Clearing cookies starts a fresh tracking session but fingerprinting can re-identify you immediately on your next visit." },
      { question_text: "What privacy advantage does a search engine like DuckDuckGo offer compared to Google?", choice_a: "DuckDuckGo provides more accurate search results because it indexes more web pages", choice_b: "DuckDuckGo loads search results faster because it does not run advertising code", choice_c: "DuckDuckGo does not build user profiles based on search history or personalize results based on past behavior, preventing your searches from contributing to a detailed behavioral profile", correct_choice: "C", explanation: "Google's business model requires building detailed profiles from search activity to serve targeted advertising. DuckDuckGo's model does not involve user profiling. Searches are not linked to your identity or history." },
    ]},
    { title: "PP Module 3: Privacy on Social Media", content: "Review privacy settings periodically as platforms change defaults. Remove connected app access you no longer need. Location data in posts reveals your home and routine over time.", category: "Privacy", difficulty: "beginner", duration_minutes: 10, order_index: 3, quiz: [
      { question_text: "What does changing your social media post audience to Friends Only actually accomplish from a privacy standpoint?", choice_a: "It prevents the platform itself from accessing your posts for advertising purposes", choice_b: "It removes your posts from Google and other search engine indexes immediately", choice_c: "It limits post visibility to your accepted connections rather than making posts publicly searchable, though the platform still has full access to your content", correct_choice: "C", explanation: "Friends Only limits who among public internet users can see your posts. The platform itself retains full access to all your content regardless of audience settings. This is an important distinction when evaluating what privacy the setting actually provides." },
      { question_text: "Why is reviewing and removing connected third-party apps from your social media accounts an important privacy step?", choice_a: "Connected apps slow down your social media experience by running simultaneously in the background", choice_b: "Connected apps retain ongoing access to your profile data and posting ability. Apps you authorized years ago may have been acquired, breached, or changed their data practices without notification", choice_c: "Connected apps frequently post spam on your behalf to generate revenue for their developers", correct_choice: "B", explanation: "OAuth-connected apps maintain persistent access to your account. An app you trusted in 2018 may now be owned by a data broker or may have been compromised. Regular audits and removal of unused app connections reduces ongoing data exposure." },
      { question_text: "What privacy risk does location data in social media posts create beyond simply showing where you are?", choice_a: "Location data slows down post loading for your followers", choice_b: "Location data from posts is automatically shared with law enforcement in most countries", choice_c: "Aggregated location data from posts over time reveals your home address, workplace, daily routine, and regular locations creating a comprehensive movement profile that enables physical security risks and targeted attacks", correct_choice: "C", explanation: "Individual location tags seem harmless but aggregated over time they reveal your home, work, gym, church, and regular schedule. This pattern enables physical surveillance, burglary during known absences, and highly personalized social engineering attacks." },
    ]},
    { title: "PP Module 4: Secure Messaging Apps", content: "End-to-end encryption means only sender and recipient can read messages. Signal is the gold standard. SMS is not private. Metadata reveals communication patterns even when content is encrypted.", category: "Communications", difficulty: "intermediate", duration_minutes: 10, order_index: 4, quiz: [
      { question_text: "What does end-to-end encryption in messaging mean and why does it matter?", choice_a: "Messages are encrypted on your device before sending and can only be decrypted by the recipient's device, meaning the messaging platform, your carrier, and anyone intercepting the traffic cannot read the content", choice_b: "Messages are encrypted while stored on the messaging company's servers but decrypted for delivery", choice_c: "Encryption protects messages from hackers but the platform can still access them for moderation", correct_choice: "A", explanation: "End-to-end encryption means the encryption key never exists on the platform's servers. Only the communicating parties have the keys. The platform stores and transmits encrypted ciphertext it mathematically cannot decrypt." },
      { question_text: "Why is standard SMS not considered private even though it feels like a direct personal message?", choice_a: "SMS messages are stored publicly in government databases accessible to anyone with a records request", choice_b: "SMS messages are transmitted in plain text through multiple carrier systems and are accessible to carriers, potentially to law enforcement, and vulnerable to interception through SS7 protocol attacks", choice_c: "SMS is shared with your carrier's advertising partners to fund the free messaging service", correct_choice: "B", explanation: "SMS was designed for reliability not privacy. Messages pass through carrier infrastructure in a form carriers can read, are subject to government requests, and the SS7 protocol that routes them has known vulnerabilities that enable interception." },
      { question_text: "What is metadata in the context of messaging privacy and why does it matter even when messages are encrypted?", choice_a: "Metadata is the file attachments sent along with messages", choice_b: "Metadata is the actual text content of your messages stored separately from the encryption layer", choice_c: "Metadata is information about your communications such as who you contacted, when, and how frequently, without including the content. It can reveal your relationships, daily patterns, and associations even without message content", correct_choice: "C", explanation: "Metadata is communications intelligence. Knowing you called a specific doctor, lawyer, or political organization at a specific time reveals sensitive information about your health, legal situation, or beliefs without reading a single word of the message itself." },
    ]},
    { title: "PP Module 5: VPNs for Privacy", content: "VPNs shift trust from your ISP to the VPN provider. Choose providers with audited no-log policies in privacy-friendly jurisdictions. VPNs do not prevent account-based tracking or fingerprinting.", category: "Privacy", difficulty: "intermediate", duration_minutes: 10, order_index: 5, quiz: [
      { question_text: "What does using a VPN actually protect your privacy from?", choice_a: "It prevents all forms of tracking including account-based tracking and browser fingerprinting", choice_b: "It makes you completely anonymous on the internet so your activities cannot be attributed to you", choice_c: "It protects your traffic from ISP monitoring and hides your IP address from websites you visit, but the VPN provider itself can see your traffic and you remain trackable by services where you are logged in", correct_choice: "C", explanation: "A VPN shifts the privacy concern from your ISP to the VPN provider. It masks your IP from sites and prevents ISP traffic analysis. It does not prevent account-based tracking, fingerprinting, or the VPN provider themselves from monitoring your activity." },
      { question_text: "Why does the jurisdiction of a VPN provider matter for privacy?", choice_a: "VPN providers in certain countries have faster network infrastructure providing better performance", choice_b: "VPN providers must comply with the laws of their operating jurisdiction including data retention laws, court orders, and intelligence sharing agreements that may require them to provide user data", choice_c: "Some countries offer tax advantages to VPN companies making their services less expensive", correct_choice: "B", explanation: "A VPN provider based in a country with mandatory data retention laws may be legally required to log and retain your activity even if they claim a no-log policy. Jurisdiction determines what legal compulsion the provider faces." },
      { question_text: "What advantage does Tor provide over a VPN for users requiring strong anonymity?", choice_a: "Tor routes traffic through three independent relays where each relay knows only the previous and next hop, so no single entity knows both your identity and your destination simultaneously", choice_b: "Tor is significantly faster than commercial VPN services making it suitable for all everyday use", choice_c: "Tor is operated by government agencies providing legal protection that commercial VPNs cannot offer", correct_choice: "A", explanation: "VPN providers know your IP and your destinations. Tor separates this knowledge. The entry relay knows you but not your destination. The exit relay knows the destination but not you. No single relay has the complete picture." },
    ]},
    { title: "PP Module 6: Email Privacy", content: "Standard email is stored in readable form on servers and accessible to providers and law enforcement. ProtonMail provides end-to-end encryption for messages between ProtonMail users. Email aliases protect your real address.", category: "Privacy", difficulty: "intermediate", duration_minutes: 10, order_index: 6, quiz: [
      { question_text: "Why is standard email not considered a private communication method?", choice_a: "Standard email is monitored by government agencies in all countries by default", choice_b: "Email messages are stored in readable form on servers, transit through multiple systems, and are accessible to email providers, system administrators, and potentially law enforcement, by design not by accident", choice_c: "Email requires too many security approvals before delivery making it vulnerable to interception", correct_choice: "B", explanation: "Email was designed in the 1970s for reliability and interoperability, not privacy. Messages are stored on and pass through multiple servers in a form their operators can read. This is a fundamental architectural characteristic, not a security flaw that can be patched." },
      { question_text: "What security and privacy benefit does ProtonMail specifically provide for messages between ProtonMail users?", choice_a: "End-to-end encryption for messages between ProtonMail accounts meaning Proton's servers store only ciphertext they cannot decrypt even under legal compulsion", choice_b: "Automatic deletion of messages after 24 hours preventing long-term data storage exposure", choice_c: "Messages are stored in Switzerland benefiting from Swiss privacy laws regardless of where the recipient is located", correct_choice: "A", explanation: "ProtonMail's end-to-end encryption means messages are encrypted on the sender's device using the recipient's public key. Only the recipient's device can decrypt it. Proton's servers never have access to the plaintext even for court orders directed at Proton." },
      { question_text: "What is an email alias and how does it protect your real email address?", choice_a: "An alias is a nickname for your email account displayed to recipients instead of your real address", choice_b: "An alias is a backup email address used when your primary account is experiencing problems", choice_c: "An email alias is a forwarding address that delivers to your real inbox while hiding your actual email address. Each service gets a unique alias so you can identify and disable any source of spam without changing your real address", correct_choice: "C", explanation: "Aliases create disposable unique addresses per service. If you used an alias for one service and start receiving spam there, you know that service leaked your address. Disable that alias and the spam stops without affecting your real email address or other services." },
    ]},
    { title: "PP Module 7: Location Privacy", content: "Location can be determined without GPS through Wi-Fi positioning, cell towers, and Bluetooth beacons. Always-on location access enables comprehensive movement profiling. Prefer While Using The App.", category: "Privacy", difficulty: "intermediate", duration_minutes: 10, order_index: 7, quiz: [
      { question_text: "Can apps determine your location even when GPS is disabled? How?", choice_a: "Yes, through Wi-Fi network positioning using known access point locations, cell tower triangulation, and Bluetooth beacon data, all of which can determine location without GPS", choice_b: "No, GPS is the only accurate positioning technology available to mobile apps", choice_c: "Only approximately through IP address geolocation which is accurate only to the city level", correct_choice: "A", explanation: "Multiple positioning technologies work without GPS. Wi-Fi positioning databases map known access points to physical locations. Cell towers triangulate positions from signal strength. Bluetooth beacons provide indoor positioning. Apps can use all of these with appropriate permissions." },
      { question_text: "What long-term privacy risk does always-on location access for apps create?", choice_a: "Always-on location drains battery significantly increasing device replacement frequency", choice_b: "Always-on location causes GPS satellite overcrowding reducing positioning accuracy for emergency services", choice_c: "Always-on location enables apps to continuously build a comprehensive record of everywhere you go including your home, workplace, religious attendance, medical visits, and daily movement patterns", correct_choice: "C", explanation: "Continuous location data reveals the most intimate details of your life. Your home address, where you work, which doctor and church you visit, your daily schedule, and your social connections are all inferrable from movement patterns over time." },
      { question_text: "What is the most privacy-protective location permission setting for an app that occasionally needs your location?", choice_a: "Deny all location access and manually input your location when the app needs it", choice_b: "Allow only while using the app so location is accessible during active use but the app cannot track your location in the background", choice_c: "Grant precise location only while using the app rather than approximate location to ensure the feature works correctly", correct_choice: "B", explanation: "While using the app grants location access only when you are actively interacting with the app. The moment you switch away or close it, location access stops. This provides necessary functionality without enabling the background tracking that creates the most significant privacy risks." },
    ]},
    { title: "PP Module 8: Financial Privacy", content: "Place credit freezes at all three bureaus to prevent new account fraud. Use virtual card numbers for online shopping. Review statements monthly for unauthorized charges.", category: "Financial Security", difficulty: "intermediate", duration_minutes: 10, order_index: 8, quiz: [
      { question_text: "What does placing a credit freeze accomplish and when should you use it?", choice_a: "A credit freeze reduces your interest rates by signaling to lenders that you are a low-risk borrower", choice_b: "A credit freeze limits how many credit inquiries lenders can make per year", choice_c: "A credit freeze prevents new credit accounts from being opened in your name by blocking lenders from accessing your credit report, making it the most effective protection against new account identity theft", correct_choice: "C", explanation: "When a lender cannot pull your credit report they will not open new credit in your name. A freeze does not affect existing accounts. Freeze all three bureaus. Unfreeze temporarily when you apply for credit then refreeze." },
      { question_text: "Why does using credit cards rather than debit cards for purchases provide better financial privacy protection?", choice_a: "Credit card transactions are encrypted more strongly than debit card transactions", choice_b: "Credit card fraud triggers chargebacks where the bank disputes the charge and credits your account during investigation, while debit fraud directly removes funds from your bank account with slower and less certain recovery", choice_c: "Credit card companies sell less customer data to third parties than debit card issuing banks", correct_choice: "B", explanation: "The fundamental difference is where the money is while a dispute is resolved. Credit card fraud disputes leave your money in your account. Debit fraud drains your actual bank balance immediately, potentially causing cascading financial problems while you wait for investigation." },
      { question_text: "Why should you access your bank account using mobile data rather than public Wi-Fi?", choice_a: "Mobile data travels through your carrier's encrypted infrastructure rather than a potentially monitored or compromised shared public Wi-Fi network, reducing exposure to man-in-the-middle attacks and network-level surveillance", choice_b: "Mobile banking apps require a cellular connection to verify your identity through the carrier", choice_c: "Public Wi-Fi networks cannot process the encryption required for banking applications", correct_choice: "A", explanation: "Public Wi-Fi networks are shared untrusted environments. Sophisticated attackers can conduct certificate spoofing and session attacks. Your carrier's cellular network is a managed private infrastructure with different security characteristics than a coffee shop router." },
    ]},
    { title: "PP Module 9: Identity Protection and Monitoring", content: "Use random false answers for security questions stored in your password manager. Place credit freezes at all three bureaus. Use IdentityTheft.gov if your identity is stolen.", category: "Identity Security", difficulty: "intermediate", duration_minutes: 10, order_index: 9, quiz: [
      { question_text: "What is the difference between a fraud alert and a credit freeze for identity protection?", choice_a: "They are the same protection offered by different bureaus under different names", choice_b: "A fraud alert adds a notice asking lenders to verify identity before extending credit while a freeze is more absolute and blocks lenders from accessing your report entirely", choice_c: "A fraud alert only covers existing accounts while a freeze prevents both existing and new account fraud", correct_choice: "B", explanation: "A fraud alert is advisory, suggesting lenders take extra verification steps. A freeze is enforceable and prevents report access entirely. Freezes are stronger protection but require active management when you need to apply for legitimate credit." },
      { question_text: "Why should you use random false answers to security questions rather than accurate personal information?", choice_a: "False answers are easier to remember than real ones since they are more distinctive", choice_b: "Real answers to common security questions like mother's maiden name, first pet, and childhood street are frequently discoverable through social media, public records, and data brokers, making them effectively public knowledge that provides no protection", choice_c: "Security systems process incorrect answers faster than correct ones reducing login time", correct_choice: "B", explanation: "Security questions were designed when personal information was less accessible. Today these answers are findable through social media posts, genealogy databases, and data broker profiles. Treating them as passwords with randomly generated false answers stored in your password manager is the correct approach." },
      { question_text: "What should you do if you discover your identity has been stolen?", choice_a: "Contact only your bank since financial institutions coordinate all identity theft recovery", choice_b: "Wait a few weeks to see if the problem resolves through normal fraud detection processes", choice_c: "File a report with the FTC at IdentityTheft.gov for a recovery plan, place freezes at all three credit bureaus, contact affected institutions, and file a police report if applicable", correct_choice: "C", explanation: "Identity theft recovery requires coordinated action across multiple organizations. IdentityTheft.gov generates a personalized recovery plan. Freezes prevent new fraud while you recover. Affected institutions need notification. Police reports help with disputing fraudulent accounts." },
    ]},
    { title: "PP Module 10: Privacy Auditing Your Digital Life", content: "A privacy audit inventories all accounts and permissions, removes unused accounts, updates passwords and MFA, reviews app permissions, submits data broker opt-outs, and checks breach exposure.", category: "Privacy", difficulty: "intermediate", duration_minutes: 12, order_index: 10, quiz: [
      { question_text: "What is the first step in conducting a personal privacy audit?", choice_a: "Create a comprehensive inventory of all accounts, apps, services, and devices you use before attempting to secure or delete anything", choice_b: "Delete all social media accounts immediately to reduce your exposure as quickly as possible", choice_c: "Change all your passwords to strong unique ones before assessing what needs to be audited", correct_choice: "A", explanation: "You cannot secure what you do not know exists. The inventory step ensures no forgotten accounts with old passwords, unused apps with persistent permissions, or obsolete services with stored payment information are overlooked in the review." },
      { question_text: "Why is deleting unused accounts an important part of a privacy audit?", choice_a: "Inactive accounts automatically share your data with advertising partners after a period of inactivity", choice_b: "Unused accounts hold historical personal data, may have outdated weak passwords, lack MFA, and can be compromised without your knowledge to impersonate you or expose your data", choice_c: "Deleted accounts reduce the number of data broker opt-outs required since brokers source from active accounts", correct_choice: "B", explanation: "Every dormant account is an unmonitored risk. Old passwords you changed elsewhere remain in use there. No MFA was ever added. A compromise of an account you forgot existed can expose years of historical data and be used to impersonate you." },
      { question_text: "What does checking your email addresses at HaveIBeenPwned.com tell you and what should you do with the results?", choice_a: "It shows you which email addresses have the most followers on social platforms", choice_b: "It shows which companies have shared your email with advertisers", choice_c: "It shows which data breaches have exposed your credentials, allowing you to immediately change passwords for the affected services and any other services where you used the same password", correct_choice: "C", explanation: "HaveIBeenPwned maintains a database of billions of credentials from known breaches. Finding your email there tells you which services were compromised and which passwords are now in attacker databases. Change those passwords immediately and check for reuse." },
    ]},
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS7 };
