const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS8(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='Cloud Security'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    {
      title: "Module 1: What Is Cloud Computing",
      content: `Cloud computing has changed how individuals and organizations store data, run applications, and deliver services. Instead of maintaining physical servers in a building, cloud computing lets you access computing resources over the internet on demand. Understanding what the cloud is and how it works is the foundation of using it safely.

The three main cloud service models are Infrastructure as a Service, Platform as a Service, and Software as a Service. Infrastructure as a Service provides raw computing resources like virtual machines, storage, and networking. You manage the operating system and everything above it. Platform as a Service provides a managed environment for developers to build and deploy applications without managing the underlying infrastructure. Software as a Service delivers fully managed applications over the internet. Email services, document editors, and video conferencing tools are all common examples.

Deployment models matter for security. A public cloud is operated by a third-party provider and shared across many customers. A private cloud is dedicated to a single organization. A hybrid cloud combines both. A multi-cloud strategy uses services from multiple providers. Each model comes with different security responsibilities and risk profiles.

The shared responsibility model is one of the most important concepts in cloud security. Cloud providers are responsible for securing the underlying infrastructure, physical data centers, and core services. You are responsible for securing everything you put in the cloud, including your data, user accounts, application configurations, and access controls. Misunderstanding this boundary is one of the most common causes of cloud security breaches.

Cloud computing offers real advantages including scalability, redundancy, and access to enterprise-grade infrastructure without large upfront costs. But it also introduces risks. Data stored in the cloud is accessible over the internet, which means misconfigured permissions or weak credentials can expose it to anyone. Cloud environments can become complex quickly, making it easy to lose track of what is running and who has access to it.

Before moving anything to the cloud, understand what data you are handling, who needs access to it, and what the provider is and is not responsible for securing. These three questions will guide every other cloud security decision you make.`,
      category: "Cloud Fundamentals", difficulty: "beginner", duration_minutes: 10, order_index: 1,
      quiz: [
        { question_text: "What does the shared responsibility model mean in cloud security?", choice_a: "The cloud provider handles security for the infrastructure while customers are responsible for securing their data, accounts, and configurations", choice_b: "The cloud provider handles all security so customers do not need to worry about it", choice_c: "Customers are responsible for all security including the physical data center", correct_choice: "A", explanation: "In the shared responsibility model the provider secures the underlying infrastructure while customers are responsible for their data, identity management, access controls, and application security depending on whether they use IaaS, PaaS, or SaaS." },
        { question_text: "Which of the following is always the customer's responsibility regardless of cloud service type?", choice_a: "Physical server maintenance and hardware replacement", choice_b: "Hypervisor patching and network switch configuration", choice_c: "Protecting their own data and managing who has access to it", correct_choice: "C", explanation: "Data ownership and access control are always the customer's responsibility across all cloud service models. Even in fully managed SaaS the customer controls who can log in and what data they store." },
        { question_text: "What is the primary security risk of misunderstanding the shared responsibility model?", choice_a: "Cloud providers charge higher fees when customers report security incidents", choice_b: "Customers assume the provider is securing things the customer is actually responsible for, leaving critical gaps unaddressed", choice_c: "Duplicate security controls slow down cloud performance unnecessarily", correct_choice: "B", explanation: "Misconfigured public cloud storage buckets are among the most common causes of data breaches because customers incorrectly assumed the provider handled access controls. Understanding the boundary prevents these gaps." },
      ],
    },
    {
      title: "Module 2: Identity and Access in the Cloud",
      content: `Identity and access management is the single most important security control in a cloud environment. Unlike a traditional office where physical access to a building provides a layer of protection, cloud resources are accessible from anywhere in the world with just a username and password. This makes controlling who can access what, and how they authenticate, absolutely critical.

Identity and access management systems let you define who can access cloud resources and what actions they are allowed to perform. Every cloud provider offers some form of IAM. Amazon Web Services has IAM roles and policies. Microsoft Azure uses Azure Active Directory. Google Cloud uses Cloud IAM. Despite different names and interfaces, the underlying concepts are consistent across providers.

The principle of least privilege is the foundational rule of cloud IAM. Every user, application, and service should have only the permissions needed to perform its specific function and nothing more. An application that only reads from a database should not have permission to delete records. A developer who works on one project should not automatically have access to all company cloud resources. Overpermissioning is one of the most common cloud security mistakes and one of the most dangerous.

Role-based access control assigns permissions to roles rather than to individual users. Users are then assigned roles based on their job function. This makes managing access at scale much more practical. When someone changes jobs, you change their role assignment rather than manually adjusting dozens of individual permissions.

Multi-factor authentication must be enabled for all cloud accounts, especially any account with administrative permissions. A compromised admin account in a cloud environment can result in the deletion of all data, the creation of unauthorized resources that generate massive costs, or the exfiltration of everything stored in the environment. MFA is the single most effective control against credential compromise.

Service accounts and API keys require the same rigor as human accounts. Hardcoded credentials in application code, publicly exposed API keys in code repositories, and service accounts with excessive permissions are all common attack vectors. Rotate credentials regularly, store them in dedicated secrets management services rather than in code, and audit service account permissions the same way you audit human accounts.

Review access permissions regularly. People change roles, leave organizations, and projects end. Access that was appropriate six months ago may no longer be. Scheduled access reviews catch permission creep before it becomes a security incident.`,
      category: "Identity Security", difficulty: "beginner", duration_minutes: 10, order_index: 2,
      quiz: [
        { question_text: "What is the principle of least privilege and why is it critical in cloud environments?", choice_a: "Each user and service should have only the minimum permissions required for their specific function, limiting the damage that can result from a compromised account", choice_b: "All users should have the same permissions to keep management simple and reduce administrative overhead", choice_c: "Administrators should have no special privileges to reduce the risk of insider threats", correct_choice: "A", explanation: "Least privilege limits blast radius. If an attacker gains access to an account with minimal permissions, the damage is contained. Overprivileged accounts in the cloud can lead to entire environment takeovers." },
        { question_text: "Why should cloud service accounts and API keys never be hardcoded into application source code?", choice_a: "Hardcoded credentials make applications run slower due to parsing overhead", choice_b: "Source code is often shared, version controlled, or accidentally published, exposing credentials to anyone who can read the code", choice_c: "Cloud providers automatically revoke credentials found in source code repositories", correct_choice: "B", explanation: "Hardcoded credentials in source code are regularly discovered in public GitHub repositories. Attackers actively scan for cloud API keys and can rack up massive charges or steal data within minutes of discovery." },
        { question_text: "What is multi-factor authentication and why is it especially important for cloud console access?", choice_a: "A method of encrypting cloud data using multiple encryption keys simultaneously for defense in depth", choice_b: "A login process requiring a second form of verification beyond a password, preventing account takeover even if the password is stolen", choice_c: "A cloud backup strategy that stores data in multiple geographic regions for redundancy", correct_choice: "B", explanation: "Cloud management consoles control your entire environment. Without MFA, a stolen password gives an attacker complete control. With MFA, the attacker also needs the second factor, which they typically do not have." },
      ],
    },
    {
      title: "Module 3: Cloud Storage Security",
      content: `Cloud storage services like Amazon S3, Google Cloud Storage, and Azure Blob Storage make it easy to store and share data at scale. They are also one of the most common sources of data breaches when misconfigured. Understanding how to secure cloud storage correctly is essential for anyone who handles data in cloud environments.

The most dangerous misconfiguration in cloud storage is making buckets or containers publicly accessible when they should be private. A publicly accessible storage bucket means anyone on the internet can read, and sometimes write, the files inside it. Billions of records have been exposed this way. The default setting in most cloud providers has shifted toward private, but legacy configurations and human error still cause public exposure regularly.

Always verify the access control settings on any storage resource you create. Set bucket policies and access control lists explicitly rather than relying on defaults. Enable the block public access settings available in most cloud storage services as a preventive control that overrides any accidental public permission grants.

Encryption protects data even if access controls fail. Cloud storage services offer server-side encryption that automatically encrypts data before writing it to disk. Enable this for all storage resources. For highly sensitive data, consider client-side encryption where you encrypt the data before uploading it, meaning the provider holds only ciphertext they cannot read.

Versioning maintains a history of every change made to stored objects. If ransomware encrypts your cloud storage or someone accidentally deletes critical files, versioning lets you recover previous versions. Enable versioning on any storage containing important data.

Access logging records who accessed what files and when. Enable access logs on cloud storage resources containing sensitive data. These logs are invaluable during incident investigations and help you detect unusual access patterns early.

Object lifecycle policies automatically move or delete data based on age or access patterns. Use these to ensure data is not retained longer than necessary. Data you no longer need is data that cannot be breached.

Regularly audit your cloud storage resources using the access analyzer tools available in most cloud platforms. These tools automatically flag resources that are publicly accessible or shared with external accounts and give you a clear list of things to review and remediate.`,
      category: "Data Security", difficulty: "intermediate", duration_minutes: 10, order_index: 3,
      quiz: [
        { question_text: "How should you determine who can access a cloud storage bucket containing customer data?", choice_a: "Leave the default settings since cloud providers configure them securely by default in all cases", choice_b: "Make it public so customers can access it without authentication to reduce friction", choice_c: "Explicitly define access policies allowing only the specific identities and services that require access", correct_choice: "C", explanation: "Explicit deny-by-default access policies are the correct approach. Never rely on default settings and never make buckets containing sensitive data public. Define exactly who and what can access the bucket and nothing else." },
        { question_text: "What is server-side encryption in cloud storage and what threat does it mitigate?", choice_a: "Encryption applied to data as it is stored, protecting it from being readable if the underlying storage infrastructure is physically accessed or compromised", choice_b: "Encryption that protects data as it travels across the internet between your device and the cloud storage endpoint", choice_c: "A method of compressing data to reduce storage costs while maintaining readability", correct_choice: "A", explanation: "Server-side encryption protects data at rest. If an attacker gains unauthorized access to the raw storage infrastructure, they see only encrypted data they cannot read without the keys." },
        { question_text: "Why is versioning an important security feature for cloud storage buckets?", choice_a: "Versioning allows multiple users to edit the same file simultaneously without conflicts", choice_b: "Versioning preserves previous copies of files, allowing recovery after accidental deletion, ransomware encryption, or malicious modification", choice_c: "Versioning reduces storage costs by compressing older file versions automatically over time", correct_choice: "B", explanation: "Versioning maintains a history of file changes. If ransomware encrypts your cloud files or an insider maliciously deletes data, versioning lets you restore to a clean previous state without paying a ransom or losing data permanently." },
      ],
    },
    {
      title: "Module 4: Securing Cloud Networks",
      content: `Cloud networks differ from traditional office networks in important ways. Instead of physical switches, routers, and cables, cloud networks are software-defined. You configure them through management consoles and APIs, which gives tremendous flexibility but also means a single misconfiguration can expose your entire infrastructure to the internet.

Virtual Private Clouds are the foundational network construct in most cloud platforms. A VPC is a logically isolated section of the cloud where you launch resources. Within a VPC you define subnets, which are ranges of IP addresses. Resources in a public subnet can communicate directly with the internet. Resources in a private subnet can only communicate internally or through controlled exit points. Databases, internal application servers, and anything that does not need direct internet access should always be in private subnets.

Security groups act as virtual firewalls attached to individual cloud resources. They control inbound and outbound traffic based on rules you define. Every security group rule should be as specific as possible. Instead of allowing all traffic from any IP address, specify exactly which ports and protocols are needed and restrict source addresses to known ranges wherever possible. The most dangerous security group configuration is allowing inbound access on all ports from all IP addresses, which effectively removes all network-level protection.

Network access control lists provide an additional layer of traffic filtering at the subnet level. Unlike security groups which are stateful and automatically allow return traffic, NACLs are stateless and evaluate every packet independently. Use NACLs as a secondary defense layer for critical subnets.

VPN connections and private connectivity options like AWS Direct Connect or Azure ExpressLink provide encrypted dedicated connections between your on-premises infrastructure and cloud environments. Use these instead of exposing management interfaces over the public internet.

Flow logs capture information about network traffic moving through your cloud infrastructure. Enable flow logs on your VPCs and subnets. When a security incident occurs, flow logs tell you which IP addresses communicated with your resources, on which ports, and how much data moved. Without them you are investigating blind.

Cloud Web Application Firewalls protect internet-facing applications from common attacks including SQL injection, cross-site scripting, and bot traffic. Deploy WAF rules in front of any public-facing web application.`,
      category: "Network Security", difficulty: "intermediate", duration_minutes: 10, order_index: 4,
      quiz: [
        { question_text: "What is a Virtual Private Cloud and what security benefit does it provide?", choice_a: "A logically isolated section of the cloud where you launch resources, providing network isolation that prevents your resources from being directly accessible to other customers or the public internet by default", choice_b: "A dedicated physical server reserved exclusively for one customer providing hardware-level isolation", choice_c: "A virtual firewall service that inspects and filters all traffic entering and leaving your cloud environment", correct_choice: "A", explanation: "VPCs provide logical network isolation. Resources in a VPC are not directly accessible from the internet or from other customers by default. You control network access through subnets, security groups, and routing rules." },
        { question_text: "What is the correct approach to configuring security groups for cloud resources?", choice_a: "Allow all inbound traffic by default and create deny rules for known malicious IP addresses", choice_b: "Use a single security group for all resources to simplify management and ensure consistent rules", choice_c: "Allow only the specific ports and source addresses required for each resource's function and deny everything else", correct_choice: "C", explanation: "Security groups should implement least privilege at the network level. Each resource should only accept traffic on the ports it actually uses from the sources that legitimately need to reach it. The most dangerous configuration allows all traffic from all sources on all ports." },
        { question_text: "Why should production and development cloud environments be in separate accounts or projects?", choice_a: "Keeping them separate reduces cloud costs because providers charge less for development workloads", choice_b: "Separating environments prevents misconfigurations or security incidents in development from affecting production systems and limits the blast radius of any compromise", choice_c: "Regulatory requirements mandate separate cloud accounts for production and non-production workloads in all industries", correct_choice: "B", explanation: "Environment separation is a fundamental blast radius control. A developer accidentally exposing credentials in a development environment should not result in a production breach. Separate accounts with separate permissions ensure that development activity cannot affect production." },
      ],
    },
    {
      title: "Module 5: Cloud Monitoring and Logging",
      content: `You cannot protect what you cannot see. Cloud monitoring and logging give you visibility into what is happening across your cloud environment so you can detect threats, investigate incidents, and demonstrate compliance. Without them, attackers can operate in your environment for months without detection.

Cloud providers offer native logging services that capture activity across your entire account. AWS CloudTrail records every API call made in your account including who made it, from which IP address, and what the outcome was. Azure Monitor and Google Cloud Audit Logs provide equivalent functionality. Enable these services in every region you operate in and store the logs in a separate storage account with restricted access so that an attacker who compromises your environment cannot erase the evidence of their activity.

Security information and event management systems aggregate logs from multiple sources and apply rules to detect suspicious patterns. Many organizations use cloud-native SIEM services or third-party tools that integrate with cloud logging. Key events to alert on include root account or global admin logins, new IAM users or roles being created, security group rules being changed to allow public access, large volumes of data being downloaded or exported, and failed authentication attempts followed by a successful one.

Cloud Security Posture Management tools continuously scan your cloud environment for misconfigurations and compliance violations. They check things like whether storage buckets are publicly accessible, whether encryption is enabled, whether MFA is enforced, and whether network rules follow least privilege. CSPM tools turn what would be a manual audit into an automated continuous process.

Infrastructure as Code tools like Terraform and CloudFormation let you define cloud resources in configuration files. When you use IaC, you can scan your configuration files for security issues before deployment, review changes through pull requests, and maintain a complete history of every change to your infrastructure. This is a significant improvement over manually clicking through a management console.

Anomaly detection services use machine learning to identify unusual behavior in your cloud environment. AWS GuardDuty, Azure Defender, and Google Security Command Center all provide this capability. They detect things like unusual API call patterns, connections to known malicious IP addresses, and credential use from unexpected geographic locations.

Set up billing alerts as an early warning system. Unexpected spikes in cloud spending often indicate that an attacker is using your account to mine cryptocurrency or run other workloads. A billing alert costs nothing and can catch a compromise before it results in a massive unexpected bill.`,
      category: "Monitoring", difficulty: "intermediate", duration_minutes: 10, order_index: 5,
      quiz: [
        { question_text: "What type of cloud activity should immediately trigger a security alert?", choice_a: "A new IAM administrator account being created, security group rules being changed to allow public access, or large volumes of data being exported outside normal business operations", choice_b: "Users logging in during business hours from their registered office locations using verified credentials", choice_c: "Automated backup jobs running on their scheduled intervals and completing within expected time windows", correct_choice: "A", explanation: "High-privilege account creation, security configuration changes, and unusual data movement are all high-fidelity indicators of potential compromise or insider threat. These should trigger immediate review regardless of the time of day or who appears to be responsible." },
        { question_text: "Why should cloud logs be stored in a separate account or write-once storage?", choice_a: "Storing logs separately improves query performance because log analysis tools work faster on isolated datasets", choice_b: "Storing logs in the same account an attacker has compromised allows them to delete or modify logs to cover their tracks, destroying the forensic evidence needed to investigate the incident", choice_c: "Regulatory frameworks require log storage in geographically separate locations to ensure availability during regional outages", correct_choice: "B", explanation: "Log integrity is critical for forensic investigation. An attacker who compromises your cloud account and can also delete your logs can erase the evidence of their activity. Immutable or separate-account log storage ensures that investigation remains possible even after a full account compromise." },
        { question_text: "What information do cloud access logs typically capture that makes them valuable for security investigations?", choice_a: "Cloud logs capture only failed authentication attempts because successful logins are considered normal activity", choice_b: "Cloud logs capture the full content of all data accessed so investigators can see exactly what was viewed", choice_c: "Cloud logs capture who made each API call, from which IP address, at what time, what action was requested, and whether it succeeded, creating a complete audit trail", correct_choice: "C", explanation: "The who, what, when, and from where captured in cloud logs allows investigators to reconstruct the timeline of an attack, identify which resources were accessed, and determine the scope of a breach. Without logs, investigation relies on incomplete information." },
      ],
    },
    {
      title: "Module 6: Cloud Compliance and Data Residency",
      content: `Cloud compliance and data residency are concerns that affect organizations in virtually every industry. Regulations dictate how certain types of data must be handled, where it can be stored, and who can access it. Understanding these requirements before moving data to the cloud prevents costly compliance failures and legal exposure.

Data residency refers to the physical location where data is stored. Many regulations require that certain categories of data remain within specific geographic boundaries. European personal data governed by the General Data Protection Regulation must generally remain within the European Economic Area or be transferred only to countries with equivalent protections. Healthcare data in the United States is subject to HIPAA requirements. Financial data has its own regulatory frameworks depending on jurisdiction. Cloud providers offer regions and availability zones in different countries, and most allow you to specify exactly where your data will be stored.

The shared responsibility model has compliance implications. Cloud providers can certify their infrastructure against standards like SOC 2, ISO 27001, PCI DSS, and FedRAMP. But their certifications cover the infrastructure layer only. You are responsible for ensuring your applications, data handling practices, access controls, and configurations meet the same standards. Storing data in a HIPAA-certified data center does not make your application HIPAA-compliant if you have not implemented the required access controls and audit logging.

Data classification is the starting point for compliance. You need to know what data you have, where it is stored, who can access it, and how sensitive it is before you can implement appropriate controls. Most compliance frameworks require a data inventory and classification scheme.

Audit trails are a compliance requirement across virtually every regulatory framework. The logging capabilities discussed in the previous module directly support compliance by providing evidence that access controls are working, changes to systems are tracked, and unauthorized access attempts are detected and investigated.

Right to erasure provisions in regulations like GDPR require that you be able to delete all data associated with a specific individual on request. Before storing personal data in the cloud, ensure your architecture allows you to identify and delete data by individual, including any backups or replicated copies.

Compliance is not a one-time project. Regulations change, your cloud environment changes, and the data you handle changes. Treat compliance as an ongoing program with regular reviews, not a checkbox that stays checked forever.`,
      category: "Compliance", difficulty: "intermediate", duration_minutes: 10, order_index: 6,
      quiz: [
        { question_text: "What is data residency and why does it matter for organizations using cloud services?", choice_a: "Data residency refers to the physical location where data is stored, which matters because some regulations require specific categories of data to remain within certain geographic boundaries", choice_b: "Data residency refers to how long data can be stored in the cloud before it must be deleted due to cost considerations", choice_c: "Data residency refers to the number of copies of data maintained by the cloud provider for redundancy purposes", correct_choice: "A", explanation: "Regulations like GDPR impose geographic restrictions on where certain personal data can be stored and processed. Organizations must understand which regulations apply to their data and configure their cloud environments to store regulated data only in compliant regions." },
        { question_text: "How should an organization approach a cloud provider's compliance certifications when evaluating their own compliance posture?", choice_a: "Provider certifications fully cover the organization because the provider's infrastructure is the foundation of everything the organization runs", choice_b: "Provider certifications are irrelevant because each layer must be independently certified regardless of the infrastructure beneath it", choice_c: "Provider certifications cover the infrastructure layer only, and the organization must separately implement controls for their applications, data handling, and access management", correct_choice: "C", explanation: "The shared responsibility model applies directly to compliance. A certified infrastructure is a necessary foundation but not sufficient. The organization must implement appropriate controls for their applications, data handling, access management, and audit logging to be compliant themselves." },
        { question_text: "What is a cloud provider's Business Associate Agreement and when is it required?", choice_a: "A performance guarantee committing the provider to specific uptime levels required for all enterprise cloud customers", choice_b: "A legal agreement required when an organization processes protected health information using a cloud provider, establishing that the provider will appropriately safeguard that information as required by HIPAA", choice_c: "A data processing addendum required by GDPR for all cloud providers operating in Europe", correct_choice: "B", explanation: "HIPAA requires covered entities to have a BAA with any business associate that handles protected health information on their behalf. Without a BAA, using a cloud provider to process PHI is a HIPAA violation regardless of the technical security controls in place." },
      ],
    },
    {
      title: "Module 7: Securing Cloud Applications",
      content: `Applications running in the cloud face the same threats as applications running anywhere else, plus additional risks specific to the cloud environment. Securing cloud applications requires attention to how applications are built, deployed, configured, and monitored.

The OWASP Top Ten is the starting point for application security regardless of where an application runs. Injection attacks, broken authentication, security misconfigurations, and insecure dependencies are all as relevant in cloud applications as in traditional ones. The difference is that cloud applications are often exposed to the entire internet by default, increasing the urgency of addressing these vulnerabilities.

Infrastructure as Code should be used to define application environments. IaC makes deployments repeatable, reviewable, and auditable. It prevents configuration drift where live environments gradually diverge from their documented state through manual changes. Every change goes through version control and can be reviewed before it is applied.

Container security has become central to cloud application security as containerized workloads have become standard. Container images should be scanned for known vulnerabilities before deployment. Base images should be minimal, using only what the application needs. Containers should run as non-root users. Container registries should be private and access controlled. Kubernetes and other orchestration platforms have their own security configurations that must be hardened explicitly.

Secrets management is critical for cloud applications. Database passwords, API keys, encryption keys, and other credentials must never be hardcoded in application code or stored in environment variables that are logged or exposed. Use dedicated secrets management services like AWS Secrets Manager, Azure Key Vault, or HashiCorp Vault. These services store secrets encrypted, control access through IAM policies, and provide audit logs of every secret access.

Dependency management requires ongoing attention. Third-party libraries and packages introduce vulnerabilities that may not be discovered until after they are in production. Use dependency scanning tools in your build pipeline to detect known vulnerabilities in the packages your application uses. Subscribe to security advisories for your key dependencies and have a process for applying patches quickly when critical vulnerabilities are disclosed.

Web Application Firewalls, rate limiting, and DDoS protection should be deployed in front of any internet-facing application. These controls reduce the volume of malicious traffic that reaches your application and provide a layer of defense against common automated attacks.`,
      category: "Application Security", difficulty: "intermediate", duration_minutes: 10, order_index: 7,
      quiz: [
        { question_text: "What is a container and what security consideration does containerization introduce?", choice_a: "A container is a lightweight isolated runtime environment that shares the host operating system kernel, meaning a kernel vulnerability can potentially affect all containers on the same host", choice_b: "A container is a virtual machine variant that provides complete hardware emulation and introduces hypervisor vulnerability concerns", choice_c: "A container is a cloud storage format that introduces security considerations around encryption of stored data", correct_choice: "A", explanation: "Containers share the host kernel, which distinguishes them from virtual machines. This shared kernel means a container escape vulnerability could allow a compromised container to affect the host and other containers. Container images must be kept updated and minimal." },
        { question_text: "Why should secrets like database passwords never be stored in environment variables that are logged?", choice_a: "Environment variables are automatically encrypted by container runtimes so logging them actually exposes the encrypted values", choice_b: "Environment variables are not accessible to application code so using them to store secrets prevents the application from using those credentials", choice_c: "Logged environment variables expose secrets in log files that may be stored and accessed by many systems, turning a log access incident into a credential compromise", correct_choice: "C", explanation: "Logging environment variables is a common misconfiguration. Application frameworks, debugging tools, and crash reporters frequently log environment variables. A secret in an environment variable that gets logged is effectively stored in plaintext in every system that receives those logs." },
        { question_text: "What is a Web Application Firewall and what threat does it primarily address?", choice_a: "A network firewall designed for cloud environments that controls access between virtual machines within the same VPC", choice_b: "A service that inspects HTTP traffic and blocks common application-layer attacks like SQL injection, cross-site scripting, and malicious bots before they reach your application", choice_c: "A distributed denial of service mitigation service that absorbs large volumes of traffic during attacks", correct_choice: "B", explanation: "WAFs operate at the application layer analyzing the content of HTTP requests. They block attacks targeting application vulnerabilities that network firewalls cannot see because those firewalls only examine network-layer information like IP addresses and ports." },
      ],
    },
    {
      title: "Module 8: Cloud Incident Response",
      content: `Cloud incidents are different from traditional incidents in important ways. Resources can be created and destroyed in seconds. Logs may be stored in separate services that require specific access to retrieve. The blast radius of a compromised cloud account can be enormous. And the shared responsibility model means the cloud provider handles some aspects of incident response while you handle others.

Preparation is the most important phase of cloud incident response. Before an incident occurs, you need to know what logging is enabled and where those logs are stored, who has authority to take containment actions like revoking credentials or isolating resources, what your escalation path is for different types of incidents, and how to contact your cloud provider for support. Document all of this in an incident response plan and test it with tabletop exercises before you need it.

When a cloud incident occurs, the first priority is containment. In a traditional environment containment might mean disconnecting a server from the network. In the cloud it means revoking compromised credentials immediately, disabling or deleting unauthorized IAM users or roles, modifying security group rules to isolate affected resources, and snapshotting affected systems before making any changes so you preserve forensic evidence.

Credential compromise is the most common type of cloud incident. If you suspect credentials have been compromised, revoke them immediately. Do not wait to confirm the compromise before acting. The cost of revoking valid credentials and reissuing them is far lower than the cost of allowing an attacker continued access while you investigate.

Cloud provider support varies by service tier. Enterprise support contracts typically include access to security incident response teams who can assist with investigation and containment. Know what support tier you have and how to engage it before you are in the middle of an incident.

Forensic investigation in the cloud relies heavily on logs. CloudTrail, VPC flow logs, application logs, and authentication logs together paint a picture of what happened. Preserve these logs by moving copies to isolated storage before taking any remediation actions, since some remediation steps may affect log availability.

After an incident is contained and resolved, conduct a thorough after action review. Identify what detection and prevention controls failed, what worked well in your response, and what changes to make to prevent recurrence. Cloud incidents often reveal gaps in monitoring, overly permissive IAM configurations, or missing automated alerting that, once addressed, significantly reduce future risk.`,
      category: "Incident Response", difficulty: "advanced", duration_minutes: 12, order_index: 8,
      quiz: [
        { question_text: "What is the first action you should take when you detect that a cloud account has been compromised?", choice_a: "Revoke or rotate the compromised credentials immediately to stop the attacker's active access while preserving evidence for investigation", choice_b: "Delete all resources in the compromised account to remove the attacker's access as quickly as possible", choice_c: "Wait until business hours to contact your cloud provider's support team for guidance", correct_choice: "A", explanation: "Revoking credentials stops active access immediately without destroying evidence. Deleting resources destroys the evidence needed to understand what the attacker did and what data was accessed, making investigation and notification decisions impossible." },
        { question_text: "Why is forensic investigation more challenging in cloud environments than in traditional on-premises environments?", choice_a: "Cloud providers do not provide any logging capabilities for security investigations by default", choice_b: "Cloud resources are often ephemeral and auto-scaling can terminate instances that may contain forensic evidence before it is captured", choice_c: "Cloud forensics requires specialized hardware tools not available to most organizations", correct_choice: "B", explanation: "Auto-scaling groups, spot instances, and ephemeral containers may be terminated automatically by cloud orchestration. Organizations must configure forensic isolation procedures to snapshot and preserve resources before they are terminated." },
        { question_text: "What should an organization do with a compromised cloud instance to balance stopping the attack while preserving evidence?", choice_a: "Isolate the instance by removing it from load balancers and tightening security group rules while taking a snapshot before terminating it", choice_b: "Immediately terminate the instance to remove the threat as quickly as possible without any delay", choice_c: "Leave the instance running without taking any action to observe the full extent of the attacker's behavior", correct_choice: "A", explanation: "Isolation stops the attacker from causing further damage or exfiltrating more data while preserving the instance state for forensic analysis. A snapshot captures the memory and disk state before termination, enabling investigation of what tools the attacker used." },
      ],
    },
    {
      title: "Module 9: Zero Trust in the Cloud",
      content: `Zero Trust is a security model built on the principle that no user, device, or network connection should be trusted by default, regardless of whether it originates inside or outside the traditional network perimeter. In cloud environments, where the concept of a network perimeter barely exists, Zero Trust is not just a best practice but a practical necessity.

The traditional security model assumed that anything inside the corporate network could be trusted. Once an attacker or malicious insider was inside the perimeter, they often had relatively free movement. Zero Trust eliminates this assumption. Every request for access must be authenticated, authorized, and continuously validated regardless of where it comes from.

The core principles of Zero Trust are verify explicitly, use least privilege access, and assume breach. Verify explicitly means authenticating and authorizing every access request based on all available data points including identity, location, device health, and behavioral signals. Use least privilege means granting only the minimum access required for each specific function. Assume breach means designing systems with the expectation that a breach will occur and minimizing the blast radius when it does.

Identity is the primary control plane in a Zero Trust architecture. Strong authentication including MFA is required for every user and every service. Conditional access policies can require additional verification when access comes from unfamiliar locations or devices. Continuous authentication re-evaluates trust during sessions rather than only at login.

Microsegmentation is a Zero Trust network strategy that divides your cloud environment into small isolated zones, each with its own access controls. Instead of flat networks where any resource can communicate with any other, microsegmentation ensures that a compromised workload can only reach the specific resources it needs and nothing else. This dramatically limits lateral movement by attackers who gain a foothold in your environment.

Device health verification is a component of Zero Trust that evaluates whether the device making an access request meets your security requirements before granting access. Devices running outdated operating systems, missing security patches, or lacking endpoint protection can be denied access or given reduced permissions.

Implementing Zero Trust in a cloud environment is a journey rather than a single project. Start by identifying your most sensitive resources and implementing strong identity verification and least privilege access for those. Gradually extend the model outward. Every step toward Zero Trust reduces your attack surface and limits the damage any single compromise can cause.`,
      category: "Cloud Fundamentals", difficulty: "advanced", duration_minutes: 10, order_index: 9,
      quiz: [
        { question_text: "What does the zero trust principle of never trust, always verify mean in practice?", choice_a: "Every access request must be authenticated and authorized based on verified identity, device health, and context regardless of whether the request comes from inside or outside the network boundary", choice_b: "No users or systems should ever be granted access to cloud resources under any circumstances whatsoever", choice_c: "Cloud resources should verify their own security configuration before allowing any connections", correct_choice: "A", explanation: "Zero trust eliminates the assumption that anything inside a network perimeter is trustworthy. Every request from every user and device must prove its identity and authorization regardless of network location, because cloud resources have no meaningful network perimeter." },
        { question_text: "How does continuous verification differ from traditional perimeter-based security?", choice_a: "Continuous verification checks security only when a user first logs in rather than during their entire session", choice_b: "Traditional security checks credentials once at login and trusts the session, while continuous verification monitors behavior throughout the session and can revoke access if anomalies appear", choice_c: "Continuous verification only applies to external users accessing cloud resources from outside the office network", correct_choice: "B", explanation: "Traditional security trusts any established session. Continuous verification monitors signals like user behavior, device health, and access patterns throughout the session and can automatically challenge or terminate suspicious sessions even after initial authentication." },
        { question_text: "What role does device health play in a zero trust access decision?", choice_a: "Device health is irrelevant since zero trust relies entirely on user identity verification through strong credentials", choice_b: "Device health checks verify that the connecting device meets security requirements like patch level and endpoint protection before granting access to cloud resources", choice_c: "Device health monitoring only applies to mobile devices not laptops or desktop computers", correct_choice: "B", explanation: "A valid user on a compromised device is still a security risk. Zero trust access policies incorporate device health signals including patch compliance, endpoint protection status, and disk encryption to ensure that clean credentials on a compromised device cannot grant access." },
      ],
    },
    {
      title: "Module 10: Cloud Cost and Shadow IT Risk",
      content: `Shadow IT and uncontrolled cloud spending are two interconnected risks that organizations frequently underestimate. Shadow IT refers to cloud services, applications, and resources that employees create or use without the knowledge or approval of the IT or security team. Cloud cost overruns occur when cloud usage grows faster than it is monitored and controlled.

Shadow IT in the cloud is easy to create and hard to detect. An employee can sign up for a cloud storage service, spin up a virtual machine on a personal credit card, or connect a third-party application to corporate systems in minutes without any approval process. These resources operate outside of your security controls, often store company data without appropriate protections, and may not be discovered until the employee leaves or a breach occurs.

The risk of shadow IT goes beyond security. Data stored in unapproved cloud services may violate compliance requirements. Applications built outside of standard processes may lack proper access controls. And when the employee who created a shadow IT resource leaves, that resource may continue running undetected and accumulating cost.

Cloud cost management and shadow IT detection often go hand in hand. Cloud Access Security Brokers discover cloud services being used across your organization by analyzing network traffic and logs. CASB tools give you visibility into what cloud services your employees are using, how much data is moving to those services, and whether those services meet your security standards.

Tagging policies enforce consistent labeling of cloud resources with metadata like owner, project, cost center, and environment. Tags make it possible to attribute costs, identify orphaned resources, and quickly determine who is responsible for any given resource. Enforce tagging requirements through cloud policies that prevent the creation of untagged resources.

Budget alerts and cost anomaly detection automatically notify you when spending exceeds thresholds or when unusual patterns emerge. A sudden spike in compute costs often indicates either a security incident where someone is using your account for unauthorized workloads, or an accidental misconfiguration that is creating resources unintentionally.

The solution to shadow IT is not simply prohibition. People create shadow IT because approved tools do not meet their needs or approved processes are too slow. Work with your team to understand what they are trying to accomplish and provide approved alternatives that meet those needs while maintaining appropriate security controls.`,
      category: "Cloud Fundamentals", difficulty: "beginner", duration_minutes: 8, order_index: 10,
      quiz: [
        { question_text: "What is shadow cloud IT and why is it a security concern?", choice_a: "Cloud services used by competitors to gain market advantage against the organization", choice_b: "Employees using personal or unsanctioned cloud services for work data, placing sensitive information outside organizational security controls and monitoring", choice_c: "The hidden costs of cloud services that appear unexpectedly on monthly billing statements", correct_choice: "B", explanation: "Shadow cloud IT places organizational data in services IT cannot apply security policies to, cannot audit, cannot ensure proper backup of, and cannot revoke access from when an employee leaves. It creates uncontrolled copies of sensitive data." },
        { question_text: "Which of the following is an example of shadow cloud IT creating a real security risk?", choice_a: "Using the company-approved cloud storage service from a personal laptop while working remotely", choice_b: "An employee uploading a client contract to a personal file sharing account to work on it from home without IT approval", choice_c: "Accessing company email through the official mobile app on a personal phone enrolled in MDM", correct_choice: "B", explanation: "Uploading a client contract to a personal account creates an uncontrolled copy outside organizational security. The organization cannot revoke that access, enforce retention policies, or audit who views the document." },
        { question_text: "What is the most effective organizational approach to reducing shadow cloud IT?", choice_a: "Blocking all internet access to prevent employees from using unauthorized cloud services entirely", choice_b: "Providing approved tools that meet employee needs combined with clear policies explaining why unauthorized services create risk", choice_c: "Monitoring employee internet usage and terminating anyone found using unapproved services as a deterrent", correct_choice: "B", explanation: "Employees use shadow IT because approved tools do not meet their needs. Providing good approved alternatives removes the incentive while clear policies and training address the behavior. Blocking alone drives usage underground without solving the underlying problem." },
      ],
    },
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS8 };
