const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS8(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='Cloud Security'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    {
      title: "Module 1: What Is Cloud Computing",
      content: "Cloud computing delivers computing resources over the internet including storage, servers, databases, and software. Understanding the shared responsibility model is the foundation of cloud security because security obligations are split between the provider and the customer.",
      category: "Cloud Fundamentals", difficulty: "beginner", duration_minutes: 10, order_index: 1,
      quiz: [
        { question_text: "What does the shared responsibility model mean in cloud security?", choice_a: "The cloud provider handles all security so customers do not need to worry about it", choice_b: "Security responsibilities are divided between the cloud provider and the customer depending on the service type", choice_c: "Customers are responsible for all security including the physical data center", correct_choice: "B", explanation: "In the shared responsibility model the provider secures the underlying infrastructure while customers are responsible for their data, identity management, access controls, and application security depending on whether they use IaaS, PaaS, or SaaS." },
        { question_text: "Which of the following is always the customer's responsibility regardless of cloud service type?", choice_a: "Physical server maintenance and hardware replacement", choice_b: "Hypervisor patching and network switch configuration", choice_c: "Protecting their own data and managing who has access to it", correct_choice: "C", explanation: "Data ownership and access control are always the customer's responsibility across all cloud service models. Even in fully managed SaaS the customer controls who can log in and what data they store." },
        { question_text: "What is the primary security risk of storing sensitive data in a public cloud bucket with default settings?", choice_a: "The data will be automatically deleted after 30 days", choice_b: "Default settings on many cloud storage services are publicly accessible, exposing the data to anyone on the internet", choice_c: "Cloud providers can read your data to improve their services", correct_choice: "B", explanation: "Misconfigured public cloud storage buckets are among the most common causes of data breaches. Default settings on services like AWS S3 have historically allowed public access and many organizations have leaked sensitive data this way." },
      ],
    },
    {
      title: "Module 2: Identity and Access in the Cloud",
      content: "Identity is the new perimeter in cloud environments. Controlling who can access cloud resources and what they can do is more important than network perimeter controls because cloud resources are accessible from anywhere.",
      category: "Identity Security", difficulty: "beginner", duration_minutes: 10, order_index: 2,
      quiz: [
        { question_text: "What is the principle of least privilege and why is it critical in cloud environments?", choice_a: "Users should receive only the permissions they need for their specific role, preventing any compromised account from causing more damage than necessary", choice_b: "All users should have the same permissions to keep management simple", choice_c: "Administrators should have no special privileges to reduce insider threat risk", correct_choice: "A", explanation: "Least privilege limits the blast radius of any compromise. If an attacker gains access to an account with minimal permissions, the damage is contained. Overprivileged accounts in the cloud can lead to entire environment takeovers." },
        { question_text: "Why should cloud service accounts and API keys never be hardcoded into application source code?", choice_a: "Hardcoded credentials make applications run slower", choice_b: "Source code is often shared, version controlled, or accidentally published, exposing credentials to anyone who can read the code", choice_c: "Cloud providers automatically revoke credentials found in source code", correct_choice: "B", explanation: "Hardcoded credentials in source code are regularly discovered in public GitHub repositories. Attackers actively scan for cloud API keys and can rack up massive charges or steal data within minutes of discovery." },
        { question_text: "What is multi-factor authentication and why is it especially important for cloud console access?", choice_a: "A method of encrypting cloud data using multiple encryption keys simultaneously", choice_b: "A login process requiring a second form of verification beyond a password, preventing account takeover even if the password is stolen", choice_c: "A cloud backup strategy that stores data in multiple geographic regions", correct_choice: "B", explanation: "Cloud management consoles control your entire environment. Without MFA, a stolen password gives an attacker complete control. With MFA, the attacker also needs the second factor, which they typically do not have." },
      ],
    },
    {
      title: "Module 3: Cloud Storage Security",
      content: "Cloud storage misconfigurations are responsible for a significant portion of major data breaches. Understanding how to properly configure access controls on cloud buckets and file storage is essential for anyone who manages cloud resources.",
      category: "Data Security", difficulty: "intermediate", duration_minutes: 10, order_index: 3,
      quiz: [
        { question_text: "How should you determine who can access a cloud storage bucket containing customer data?", choice_a: "Leave the default settings since cloud providers configure them securely by default", choice_b: "Make it public so customers can access it without authentication", choice_c: "Explicitly define access policies allowing only the specific identities and services that require access", correct_choice: "C", explanation: "Explicit deny-by-default access policies are the correct approach. Never rely on default settings and never make buckets containing sensitive data public. Define exactly who and what can access the bucket and nothing else." },
        { question_text: "What is server-side encryption in cloud storage and what threat does it mitigate?", choice_a: "Encryption applied to data as it is stored, protecting it from being readable if the underlying storage infrastructure is physically accessed or compromised", choice_b: "Encryption that protects data as it travels across the internet between your device and the cloud", choice_c: "A method of compressing data to reduce storage costs", correct_choice: "A", explanation: "Server-side encryption protects data at rest. If an attacker gains unauthorized access to the raw storage infrastructure, they see only encrypted data they cannot read without the keys." },
        { question_text: "Why is versioning an important security feature for cloud storage buckets?", choice_a: "Versioning allows multiple users to edit the same file simultaneously", choice_b: "Versioning preserves previous copies of files, allowing recovery after accidental deletion, ransomware encryption, or malicious modification", choice_c: "Versioning reduces storage costs by compressing older file versions automatically", correct_choice: "B", explanation: "Versioning maintains a history of file changes. If ransomware encrypts your cloud files or an insider maliciously deletes data, versioning lets you restore to a clean previous state without paying a ransom or losing data permanently." },
      ],
    },
    {
      title: "Module 4: Securing Cloud Networks",
      content: "Cloud providers offer virtual networking tools that replicate traditional network security controls. Virtual private clouds, security groups, and network access control lists let you isolate resources and control traffic flow.",
      category: "Network Security", difficulty: "intermediate", duration_minutes: 12, order_index: 4,
      quiz: [
        { question_text: "What is a Virtual Private Cloud and what security benefit does it provide?", choice_a: "A paid upgrade that makes your cloud resources faster than shared infrastructure", choice_b: "An isolated virtual network environment within the public cloud that keeps your resources logically separated from other customers' resources", choice_c: "A VPN service provided by cloud vendors to encrypt internet traffic", correct_choice: "B", explanation: "A VPC creates a logically isolated section of the cloud where you control IP addressing, subnets, routing, and gateways. Resources in your VPC are not reachable from outside unless you explicitly allow it." },
        { question_text: "What is the correct approach to configuring security groups for a cloud database server?", choice_a: "Allow inbound traffic from all IP addresses so the application can connect from anywhere", choice_b: "Allow inbound traffic only from the specific application servers or IP ranges that need to query the database", choice_c: "Disable security groups since the database is already behind the application layer", correct_choice: "B", explanation: "Database servers should never be exposed to the public internet. Security groups should restrict inbound database port access to only the application servers or specific CIDR ranges that legitimately need to connect." },
        { question_text: "Why should production and development cloud environments be kept in separate accounts or VPCs?", choice_a: "Separate environments reduce your cloud bill by using different pricing tiers", choice_b: "A compromise of a development environment with weaker controls cannot propagate to production, and production data never reaches development systems", choice_c: "Cloud providers require separate accounts for development and production use", correct_choice: "B", explanation: "Development environments typically have more permissive access controls and may be accessed by contractors or testers. Isolation ensures that a development compromise cannot become a production breach and that real customer data stays out of development systems." },
      ],
    },
    {
      title: "Module 5: Cloud Monitoring and Logging",
      content: "You cannot secure what you cannot see. Cloud environments generate extensive logs that provide visibility into who is accessing what, from where, and when. Monitoring these logs is essential for detecting threats and investigating incidents.",
      category: "Security Monitoring", difficulty: "intermediate", duration_minutes: 10, order_index: 5,
      quiz: [
        { question_text: "What type of cloud activity should immediately trigger a security alert?", choice_a: "A user logging in during normal business hours from their usual location", choice_b: "A root or administrator account logging in from an unfamiliar IP address at an unusual time", choice_c: "Automated backup jobs running on their scheduled interval", correct_choice: "B", explanation: "Root and administrator account logins from unexpected locations or times are high-priority indicators of compromise. These accounts have full environment access and their activity should be closely monitored." },
        { question_text: "What information do cloud access logs typically capture that makes them valuable for security investigations?", choice_a: "Only the content of files that were accessed", choice_b: "Who performed what action on which resource at what time and from which IP address", choice_c: "The performance metrics of cloud services during business hours", correct_choice: "B", explanation: "Access logs capture the who, what, where, and when of every API call and resource access. This information is essential for reconstructing what an attacker did during an incident and for proving compliance with regulations." },
        { question_text: "Why should cloud logs be stored in a separate account or write-protected location from the resources they monitor?", choice_a: "To reduce storage costs by using lower-tier storage for log data", choice_b: "An attacker who compromises your main environment can delete logs to cover their tracks if logs are stored in the same location", choice_c: "Cloud providers require logs to be stored separately for compliance reasons", correct_choice: "B", explanation: "Attackers routinely delete logs to cover their activity. Storing logs in a separate account that the compromised environment cannot write to or delete from ensures log integrity and preserves your ability to investigate the incident." },
      ],
    },
    {
      title: "Module 6: Cloud Compliance and Data Residency",
      content: "Regulated industries must ensure their cloud usage meets compliance requirements. Data residency laws in many countries require that certain types of data be stored and processed within specific geographic boundaries.",
      category: "Compliance", difficulty: "intermediate", duration_minutes: 10, order_index: 6,
      quiz: [
        { question_text: "What is data residency and why does it matter for organizations using cloud services?", choice_a: "A cloud pricing model based on how long data is stored", choice_b: "The requirement that certain data be stored and processed within specific geographic regions due to local laws and regulations", choice_c: "A method for backing up cloud data to multiple physical locations", correct_choice: "B", explanation: "Many jurisdictions including the EU under GDPR require that personal data about their residents be processed within certain regions. Organizations must configure cloud regions appropriately and verify their cloud provider can meet these requirements." },
        { question_text: "How should an organization approach a cloud provider's compliance certifications when evaluating them for handling sensitive data?", choice_a: "Assume that any major cloud provider automatically meets all compliance requirements for all industries", choice_b: "Verify that the provider holds the specific certifications relevant to your industry and that those certifications cover the specific services you plan to use", choice_c: "Only review compliance certifications if a regulator specifically requests proof", correct_choice: "B", explanation: "Provider certifications apply to specific services and regions and may not cover every service in their catalog. Organizations must verify that the specific services they use in the specific regions they operate in are covered by the required certifications." },
        { question_text: "What is a cloud provider's Business Associate Agreement and when is it required?", choice_a: "A contract defining the pricing terms for cloud services over a multi-year period", choice_b: "A legal agreement required when healthcare organizations share patient health information with a cloud provider that must meet HIPAA obligations", choice_c: "An agreement granting the cloud provider permission to use your data for machine learning", correct_choice: "B", explanation: "Under HIPAA, cloud providers that process protected health information must sign a BAA accepting obligations for the data's security and privacy. Without a BAA, using cloud services for patient data is a HIPAA violation." },
      ],
    },
    {
      title: "Module 7: Securing Cloud Applications",
      content: "Applications deployed in the cloud face the same vulnerabilities as traditional applications plus cloud-specific risks. Secure development practices, dependency management, and runtime protection are all essential.",
      category: "Application Security", difficulty: "advanced", duration_minutes: 12, order_index: 7,
      quiz: [
        { question_text: "What is a container and what security consideration does containerization introduce?", choice_a: "A virtual machine that runs a complete operating system, introducing the same security surface as a physical server", choice_b: "A lightweight package that runs application code in an isolated environment, requiring that container images be scanned for vulnerabilities and kept updated", choice_c: "A cloud storage format for archiving application data", correct_choice: "B", explanation: "Containers package application code with its dependencies. Security requires scanning container images for known vulnerabilities before deployment, using minimal base images, running containers as non-root users, and keeping images updated when vulnerabilities are discovered." },
        { question_text: "Why should secrets like database passwords never be stored in container environment variables in production?", choice_a: "Environment variables reduce application performance in containerized environments", choice_b: "Environment variables can be exposed through application errors, logs, and container inspection commands, making secrets management services a safer alternative", choice_c: "Containers automatically delete environment variables after deployment", correct_choice: "B", explanation: "Environment variables are a common leak vector. Application errors sometimes dump environment data, logs may capture them, and anyone with container inspect access can read them. Dedicated secrets managers with access control and audit logging are the correct approach." },
        { question_text: "What is a Web Application Firewall and what threat does it address for cloud-hosted applications?", choice_a: "A hardware device installed in your data center to filter malicious network packets", choice_b: "A service that inspects HTTP traffic to detect and block common web attack patterns like SQL injection and cross-site scripting before they reach your application", choice_c: "A cloud service that encrypts all traffic between users and your application", correct_choice: "B", explanation: "A WAF sits in front of your application and filters malicious requests. It can block SQL injection, XSS, bot traffic, and other OWASP Top 10 attacks even when those vulnerabilities exist in the application code itself." },
      ],
    },
    {
      title: "Module 8: Cloud Incident Response",
      content: "Responding to security incidents in cloud environments requires understanding cloud-specific tools and the ephemeral nature of cloud resources. Acting quickly while preserving evidence is the core challenge.",
      category: "Incident Response", difficulty: "advanced", duration_minutes: 12, order_index: 8,
      quiz: [
        { question_text: "What is the first action you should take when you detect that a cloud account has been compromised?", choice_a: "Delete all resources in the compromised account to remove the attacker's access", choice_b: "Revoke or rotate the compromised credentials immediately to stop the attacker's active access while preserving evidence for investigation", choice_c: "Wait until business hours to contact your cloud provider's support team", correct_choice: "B", explanation: "Revoking credentials stops active access immediately without destroying evidence. Deleting resources destroys the evidence needed to understand what the attacker did and what data was accessed, making investigation and notification decisions impossible." },
        { question_text: "Why is forensic investigation more challenging in cloud environments than in traditional on-premises environments?", choice_a: "Cloud providers do not provide any logging capabilities for security investigations", choice_b: "Cloud resources are often ephemeral and auto-scaling can terminate instances that may contain forensic evidence before it is captured", choice_c: "Cloud forensics requires specialized hardware tools not available to most organizations", correct_choice: "B", explanation: "Auto-scaling groups, spot instances, and ephemeral containers may be terminated automatically by cloud orchestration. Organizations must configure forensic isolation procedures to snapshot and preserve resources before they are terminated." },
        { question_text: "What should an organization do with a compromised cloud instance to balance stopping the attack while preserving evidence?", choice_a: "Immediately terminate the instance to remove the threat as quickly as possible", choice_b: "Leave the instance running without taking any action to observe the attacker's behavior", choice_c: "Isolate the instance by removing it from load balancers and tightening security group rules while taking a snapshot before terminating it", correct_choice: "C", explanation: "Isolation stops the attacker from causing further damage or exfiltrating more data while preserving the instance state for forensic analysis. A snapshot captures the memory and disk state before termination, enabling investigation of what tools the attacker used and what data they accessed." },
      ],
    },
    {
      title: "Module 9: Zero Trust in the Cloud",
      content: "Zero trust is a security model based on the principle of never trust, always verify. In cloud environments where traditional network perimeters do not exist, zero trust provides a framework for securing access to resources.",
      category: "Cloud Fundamentals", difficulty: "advanced", duration_minutes: 10, order_index: 9,
      quiz: [
        { question_text: "What does the zero trust principle of never trust, always verify mean in practice?", choice_a: "No users or systems should ever be granted access to cloud resources under any circumstances", choice_b: "Every access request must be authenticated and authorized regardless of whether it comes from inside or outside the network", choice_c: "Cloud resources should verify their own security configuration before allowing connections", correct_choice: "B", explanation: "Zero trust eliminates the assumption that anything inside a network perimeter is trustworthy. Every request from every user and device must prove its identity and authorization regardless of network location, because cloud resources have no meaningful network perimeter." },
        { question_text: "How does continuous verification differ from traditional perimeter-based security?", choice_a: "Continuous verification checks security only when a user first logs in rather than during their entire session", choice_b: "Traditional security checks credentials once at login and trusts the session, while continuous verification monitors behavior throughout the session and can revoke access if anomalies appear", choice_c: "Continuous verification only applies to external users accessing cloud resources from outside the office", correct_choice: "B", explanation: "Traditional security trusts any established session. Continuous verification monitors signals like user behavior, device health, and access patterns throughout the session and can automatically challenge or terminate suspicious sessions even after initial authentication." },
        { question_text: "What role does device health play in a zero trust access decision?", choice_a: "Device health is irrelevant since zero trust relies entirely on user identity verification", choice_b: "Device health checks verify that the connecting device meets security requirements like patch level and endpoint protection before granting access", choice_c: "Device health monitoring only applies to mobile devices not laptops or desktops", correct_choice: "B", explanation: "A valid user on a compromised device is still a security risk. Zero trust access policies incorporate device health signals including patch compliance, endpoint protection status, and disk encryption to ensure that clean credentials on a compromised device cannot grant access." },
      ],
    },
    {
      title: "Module 10: Cloud Cost and Shadow IT Risk",
      content: "Unauthorized cloud usage by employees creates security and compliance risks that IT departments often do not discover until a breach or audit. Understanding shadow cloud IT and how to address it protects the organization.",
      category: "Cloud Fundamentals", difficulty: "beginner", duration_minutes: 8, order_index: 10,
      quiz: [
        { question_text: "What is shadow cloud IT and why is it a security concern?", choice_a: "Cloud services used by competitors to gain market advantage", choice_b: "Employees using personal or unsanctioned cloud services for work data, placing sensitive information outside organizational security controls", choice_c: "The hidden costs of cloud services that appear on monthly billing statements", correct_choice: "B", explanation: "Shadow cloud IT places organizational data in services IT cannot apply security policies to, cannot audit, cannot ensure proper backup of, and cannot revoke access from when an employee leaves. It creates uncontrolled copies of sensitive data." },
        { question_text: "Which of the following is an example of shadow cloud IT creating a real security risk?", choice_a: "Using the company-approved cloud storage service from a personal laptop", choice_b: "An employee uploading a client contract to a personal file sharing account to work on it from home", choice_c: "Accessing company email through the official mobile app on a personal phone", correct_choice: "B", explanation: "Uploading a client contract to a personal account creates an uncontrolled copy outside organizational security. The organization cannot revoke that access, enforce retention policies, or audit who views the document." },
        { question_text: "What is the most effective organizational approach to reducing shadow cloud IT?", choice_a: "Blocking all internet access to prevent employees from using unauthorized cloud services", choice_b: "Providing approved tools that meet employee needs, combined with clear policies and training explaining why unauthorized services create risk", choice_c: "Monitoring employee internet usage and terminating anyone found using unapproved services", correct_choice: "B", explanation: "Employees use shadow IT because approved tools do not meet their needs. Providing good approved alternatives removes the incentive while clear policies and training address the behavior. Blocking alone drives usage underground and damages trust without solving the problem." },
      ],
    },
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS8 };
