const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS9(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='Incident Response'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    {
      title: "Module 1: What Is an Incident",
      content: "A security incident is any event that threatens the confidentiality, integrity, or availability of information or systems. Knowing what constitutes an incident and how to recognize one early is the first step in an effective response.",
      category: "IR Fundamentals", difficulty: "beginner", duration_minutes: 8, order_index: 1,
      quiz: [
        { question_text: "Which of the following best describes a security incident?", choice_a: "Any event that triggers an antivirus alert regardless of severity", choice_b: "An event that threatens the confidentiality, integrity, or availability of systems or data and requires a response", choice_c: "Only events that result in confirmed data exfiltration", correct_choice: "B", explanation: "A security incident includes any event that threatens the CIA triad. This includes breaches, ransomware, unauthorized access, and availability attacks. Not every alert is an incident, but events that threaten these three pillars require a structured response." },
        { question_text: "What is the difference between a security event and a security incident?", choice_a: "Events are external threats while incidents are internal threats", choice_b: "An event is any observable occurrence in a system, while an incident is an event that has been assessed as having a negative security impact requiring response", choice_c: "Incidents are events that have been fully investigated and closed", correct_choice: "B", explanation: "Security events are raw observations like a failed login or firewall block. An incident is an event that analysis shows has real security impact. The triage and assessment process converts events into incidents requiring formal response." },
        { question_text: "Why is early detection of security incidents important beyond just minimizing damage?", choice_a: "Early detection automatically prevents all data loss", choice_b: "Early detection reduces the attacker's dwell time, limiting how much reconnaissance and damage they can perform before being stopped", choice_c: "Early detection is required to qualify for cybersecurity insurance claims", correct_choice: "B", explanation: "The longer an attacker has access, the more damage they cause. Studies consistently show that shorter dwell times correlate with significantly less data stolen and lower recovery costs. Early detection is the single most impactful factor in incident outcomes." },
      ],
    },
    {
      title: "Module 2: The Incident Response Lifecycle",
      content: "Effective incident response follows a structured lifecycle. The NIST framework defines six phases: preparation, detection and analysis, containment, eradication, recovery, and post-incident activity. Understanding each phase helps organizations respond consistently.",
      category: "IR Fundamentals", difficulty: "beginner", duration_minutes: 10, order_index: 2,
      quiz: [
        { question_text: "What is the primary goal of the containment phase in incident response?", choice_a: "Permanently remove all malware and close every vulnerability found during the investigation", choice_b: "Stop the incident from spreading or causing more damage while the investigation continues", choice_c: "Restore all affected systems to their pre-incident state as quickly as possible", correct_choice: "B", explanation: "Containment limits the blast radius. The goal is not yet to fix everything but to stop the bleeding. This often means isolating affected systems, revoking compromised credentials, or blocking attacker infrastructure while the full scope of the incident is determined." },
        { question_text: "Why must eradication happen before recovery in the incident response lifecycle?", choice_a: "Eradication is optional if the systems appear to be functioning normally again", choice_b: "If systems are restored before the attacker's access and persistence mechanisms are fully removed, they will immediately recompromise the recovered systems", choice_c: "Eradication generates the documentation needed to start the recovery process", correct_choice: "B", explanation: "Attackers often install multiple backdoors and persistence mechanisms. Recovering systems without eradicating every foothold means the attacker retains access and your recovery effort immediately restores their access. Thorough eradication must precede any recovery work." },
        { question_text: "What is the purpose of the post-incident activity phase and why do organizations often skip it?", choice_a: "It is used to assign blame and discipline employees who made mistakes during the incident", choice_b: "It captures lessons learned to improve future detection, response, and prevention, but organizations skip it because they are eager to return to normal operations", choice_c: "It is required only for incidents involving regulatory notification obligations", correct_choice: "B", explanation: "Post-incident review captures what worked, what failed, and what gaps allowed the incident to occur. Organizations skip it because recovery feels like closure, but the review is where real security improvement happens. Skipping it means making the same mistakes in the next incident." },
      ],
    },
    {
      title: "Module 3: Building an Incident Response Plan",
      content: "An incident response plan defines roles, communication procedures, and decision-making processes before an incident occurs. Organizations with documented plans respond faster and more effectively than those making it up as they go.",
      category: "IR Fundamentals", difficulty: "intermediate", duration_minutes: 10, order_index: 3,
      quiz: [
        { question_text: "What is the most critical element to establish in an incident response plan before an incident occurs?", choice_a: "A detailed technical playbook for every possible type of attack", choice_b: "Clear roles and decision-making authority so everyone knows who can make what decisions without waiting for approval chains during a fast-moving incident", choice_c: "A list of all software installed on every company system", correct_choice: "B", explanation: "Decision authority is the most critical element because incidents move fast. If responders must navigate approval chains during an active breach, attackers gain ground. Pre-defined authority means the right people can act immediately without organizational delays." },
        { question_text: "Why should an incident response plan include out-of-band communication methods?", choice_a: "Out-of-band communications are faster than email during normal operations", choice_b: "If an attacker has compromised your email or internal systems, using those same systems to coordinate your response tells the attacker your plans", choice_c: "Regulatory requirements mandate the use of external communication channels during incidents", correct_choice: "B", explanation: "Sophisticated attackers monitor compromised systems including email. Coordinating your response through a compromised channel gives the attacker visibility into your actions. Out-of-band channels like personal phones, encrypted messaging apps, or pre-established conference lines prevent this." },
        { question_text: "How often should an incident response plan be tested and updated?", choice_a: "Only when a real incident reveals a gap in the existing plan", choice_b: "Once when initially created since the fundamental steps do not change significantly over time", choice_c: "At least annually through tabletop exercises or simulations, and whenever the environment, personnel, or threat landscape changes significantly", correct_choice: "C", explanation: "Plans become stale. Personnel change, systems change, and new attack techniques emerge. Regular testing through tabletop exercises reveals gaps before a real incident does. Updating after exercises and significant environment changes keeps the plan aligned with reality." },
      ],
    },
    {
      title: "Module 4: Detection and Triage",
      content: "Most incidents are not immediately obvious. Detection relies on log analysis, alert monitoring, user reports, and threat intelligence. Effective triage separates real incidents from false positives without missing genuine threats.",
      category: "Detection", difficulty: "intermediate", duration_minutes: 10, order_index: 4,
      quiz: [
        { question_text: "What is alert fatigue and why is it a serious security problem?", choice_a: "Physical exhaustion experienced by security analysts working long shifts during incident response", choice_b: "The condition where analysts receive so many alerts that they start missing real threats because the volume of false positives has trained them to dismiss alerts quickly", choice_c: "A technical condition where security tools slow down from processing too many events simultaneously", correct_choice: "B", explanation: "Alert fatigue is one of the most dangerous conditions in security operations. When every shift produces thousands of low-quality alerts, analysts become desensitized and real threats are buried in noise. Tuning detection rules and focusing on high-fidelity alerts is essential." },
        { question_text: "A user reports that their computer is running slowly and showing strange pop-ups. How should this be triaged?", choice_a: "Advise them to restart their computer since performance issues are usually not security related", choice_b: "Treat it as a potential malware infection, isolate the system, and begin investigation before the situation spreads", choice_c: "Have them install additional antivirus software and monitor for a week before escalating", correct_choice: "B", explanation: "Performance issues and unexpected pop-ups are classic indicators of malware infection. Treating this as a potential incident and isolating the system prevents lateral movement. The cost of an unnecessary isolation is low compared to the cost of letting malware spread." },
        { question_text: "What information should be gathered during initial triage to determine if an event is a real incident?", choice_a: "Only the user's name and what application they were using at the time", choice_b: "The scope of affected systems, what data may be at risk, how the attacker may have gained access, and whether the activity is ongoing", choice_c: "The dollar value of the data at risk so leadership can decide whether a response is worth the cost", correct_choice: "B", explanation: "Initial triage must establish scope, data risk, attack vector, and whether the threat is active. These four factors determine the severity of the incident and drive the right containment and escalation decisions. Without them, response efforts may focus in the wrong area." },
      ],
    },
    {
      title: "Module 5: Containment Strategies",
      content: "Containment stops an active incident from spreading while preserving the ability to investigate what happened. Choosing the right containment strategy depends on the type of incident, the systems involved, and the business impact of taking those systems offline.",
      category: "Containment", difficulty: "intermediate", duration_minutes: 10, order_index: 5,
      quiz: [
        { question_text: "What is the tradeoff between aggressive containment and a slower monitored containment approach?", choice_a: "Aggressive containment is always the right choice since speed is the most important factor in all incidents", choice_b: "Aggressive containment stops damage quickly but may alert the attacker and destroy evidence, while monitored containment gathers intelligence but allows damage to continue", choice_c: "Monitored containment is always preferred since it provides better evidence for prosecution", correct_choice: "B", explanation: "The right containment strategy depends on context. For ransomware spreading across a network, aggressive isolation is correct. For a nation-state actor performing reconnaissance, monitored containment may allow intelligence gathering before the attacker realizes they have been detected." },
        { question_text: "Why is network isolation a common first containment step for a suspected malware infection?", choice_a: "Network isolation speeds up malware scanning tools by removing internet access", choice_b: "Network isolation prevents the malware from communicating with attacker infrastructure, spreading laterally, and exfiltrating additional data while investigation proceeds", choice_c: "Network isolation automatically triggers incident notification to regulatory bodies", correct_choice: "B", explanation: "Modern malware relies on network connectivity to receive commands, spread to other systems, and exfiltrate data. Network isolation cuts these capabilities immediately while preserving the system state for forensic analysis." },
        { question_text: "What does preserving evidence during containment mean and why does it matter?", choice_a: "Taking screenshots of error messages before rebooting affected systems", choice_b: "Capturing system memory, disk images, and logs before making changes that could overwrite forensic artifacts needed to understand the attack and prove what happened", choice_c: "Backing up user files so they are not lost during the recovery process", correct_choice: "B", explanation: "Forensic evidence is volatile. Rebooting clears memory, overwriting files destroys artifacts, and logs roll over. Capturing disk images and memory dumps before containment actions preserves the evidence trail needed for investigation, legal proceedings, and regulatory notifications." },
      ],
    },
    {
      title: "Module 6: Eradication and Recovery",
      content: "Eradication removes every trace of the attacker from affected systems. Recovery restores systems to normal operation. Both must be done thoroughly and in the right order to avoid reinfection.",
      category: "Recovery", difficulty: "intermediate", duration_minutes: 10, order_index: 6,
      quiz: [
        { question_text: "Why is simply running antivirus after an incident insufficient for complete eradication?", choice_a: "Antivirus tools are too slow to remove malware from large enterprise systems", choice_b: "Sophisticated attackers use living-off-the-land techniques and persistence mechanisms that antivirus tools do not detect, requiring manual investigation to find every foothold", choice_c: "Antivirus tools cannot remove malware while the system is running", correct_choice: "B", explanation: "Modern attackers use legitimate system tools to avoid antivirus detection and plant multiple persistence mechanisms. A clean antivirus scan does not mean a clean system. Thorough eradication requires investigating scheduled tasks, startup entries, user accounts, and configuration changes made by the attacker." },
        { question_text: "What is the safest approach to recovering a system that was fully compromised by an attacker?", choice_a: "Run a full antivirus scan and monitoring for suspicious activity for 30 days after cleaning", choice_b: "Rebuild the system from a known-good baseline image rather than trying to clean the existing installation", choice_c: "Restore the system from the most recent backup regardless of when the attacker first gained access", correct_choice: "B", explanation: "Rebuilding from a known-good baseline is the only way to guarantee the system is clean. Cleaning an existing installation risks missing hidden persistence mechanisms. Restoring from a backup risks restoring to a point where the attacker was already present." },
        { question_text: "What must be verified before returning recovered systems to production?", choice_a: "That the systems are running at their previous performance levels", choice_b: "That the vulnerability or misconfiguration that allowed the incident has been remediated so the same attack cannot immediately succeed again", choice_c: "That all user data from before the incident has been fully restored", correct_choice: "B", explanation: "Returning systems to production without fixing the root cause is pointless. The attacker knows exactly how they got in and will try again. Every recovery must include closing the initial access vector before systems go back online." },
      ],
    },
    {
      title: "Module 7: Communication During Incidents",
      content: "Who you tell, what you tell them, and when you tell them during a security incident has legal, regulatory, and reputational consequences. Internal communication keeps the response coordinated while external communication manages obligations and trust.",
      category: "Communication", difficulty: "intermediate", duration_minutes: 10, order_index: 7,
      quiz: [
        { question_text: "Why should incident communications be kept to a need-to-know basis during an active investigation?", choice_a: "To avoid causing panic among employees who may overreact to security news", choice_b: "Broad internal disclosure can alert an insider threat actor that they have been discovered or create rumors that reach the attacker before containment is complete", choice_c: "Legal requirements prohibit discussing active security incidents with non-security staff", correct_choice: "B", explanation: "If an insider is involved or an attacker has compromised internal communications, broad disclosure tips them off. Need-to-know communication keeps the investigation compartmentalized and maintains the element of surprise that containment actions depend on." },
        { question_text: "What triggers mandatory external breach notification requirements for most organizations?", choice_a: "Any security incident detected by the organization regardless of data exposure", choice_b: "Confirmed unauthorized access to personal data belonging to individuals who are protected by applicable laws and regulations", choice_c: "Incidents that result in financial losses exceeding a specific dollar threshold", correct_choice: "B", explanation: "Breach notification laws like GDPR, HIPAA, and state breach laws are triggered by confirmed unauthorized access to protected personal data. Not every incident triggers notification. Legal counsel should be involved immediately to assess whether notification obligations apply." },
        { question_text: "What is the role of legal counsel in incident response communication?", choice_a: "Legal counsel only becomes involved after recovery when preparing reports for regulators", choice_b: "Legal counsel should be involved immediately to assess notification obligations, manage attorney-client privilege over investigation communications, and guide public statements", choice_c: "Legal counsel is only needed if the organization plans to pursue criminal charges against the attacker", correct_choice: "B", explanation: "Early legal involvement is critical. Attorneys assess regulatory notification timelines, which are often measured in 72 hours or less. Attorney-client privilege over investigation reports may protect sensitive findings. Legal review of public statements prevents admissions that could be used in litigation." },
      ],
    },
    {
      title: "Module 8: Ransomware Response",
      content: "Ransomware is one of the most disruptive types of security incidents. Responding effectively requires preparation before the attack and deliberate decision-making during it. Paying the ransom does not guarantee recovery and funds future attacks.",
      category: "Ransomware", difficulty: "advanced", duration_minutes: 12, order_index: 8,
      quiz: [
        { question_text: "What is the most effective preparation against ransomware before an attack occurs?", choice_a: "Purchasing ransomware-specific cyber insurance that will cover the ransom payment", choice_b: "Maintaining tested offline backups that ransomware cannot reach and encrypt, enabling recovery without paying the ransom", choice_c: "Installing dedicated ransomware detection software on every endpoint", correct_choice: "B", explanation: "Tested offline backups are the single most effective ransomware control. If attackers encrypt your systems, backups let you restore without paying. The backups must be offline or immutable because modern ransomware specifically seeks out and encrypts accessible backups before triggering the main attack." },
        { question_text: "If an organization decides to pay a ransomware demand, what risks remain even after paying?", choice_a: "No risks remain since the attacker will provide the decryption key once paid", choice_b: "Attackers may provide broken decryptors, have already sold the data, demand additional payment, or have left backdoors for future attacks", choice_c: "The only remaining risk is the reputational damage from the payment becoming public", correct_choice: "B", explanation: "Payment is not a guarantee of recovery. Studies show a significant percentage of organizations that pay do not fully recover their data. Attackers may have already sold the data before encrypting it, making payment irrelevant to data exposure. Paying also marks the organization as a target willing to pay." },
        { question_text: "What should be the first technical action when ransomware is detected actively encrypting files on a network?", choice_a: "Immediately pay the ransom to stop the encryption before more files are lost", choice_b: "Isolate affected systems from the network immediately to stop lateral spread while identifying how many systems are affected", choice_c: "Run a full backup of all remaining unaffected systems before taking any other action", correct_choice: "B", explanation: "Immediate network isolation stops ransomware from spreading to additional systems and from communicating with attacker infrastructure. Speed is critical because every second of network connectivity allows more encryption and potential spread. Isolation is the containment action that limits total damage." },
      ],
    },
    {
      title: "Module 9: Digital Forensics Basics",
      content: "Digital forensics is the process of collecting, preserving, and analyzing digital evidence. Even without specialized training, understanding forensic basics helps responders avoid destroying evidence and work effectively with professional investigators.",
      category: "Forensics", difficulty: "advanced", duration_minutes: 12, order_index: 9,
      quiz: [
        { question_text: "What is the order of volatility and why does it matter in digital forensics?", choice_a: "A ranking of how severe different types of security incidents are", choice_b: "The sequence in which digital evidence is lost, with memory and network connections disappearing first, guiding investigators to collect the most perishable evidence before less volatile evidence like disk data", choice_c: "A legal framework determining which evidence courts consider most reliable", correct_choice: "B", explanation: "Memory contains running processes, encryption keys, and attacker tools that disappear the moment the system is rebooted. Network connection state disappears quickly. Disk data is more persistent. Forensic collection follows volatility order to capture what will be lost soonest." },
        { question_text: "What does maintaining a chain of custody mean for digital evidence?", choice_a: "Encrypting digital evidence so only authorized personnel can access it during investigation", choice_b: "Documenting who collected evidence, how it was collected, where it has been, and who has accessed it so evidence integrity can be proven", choice_c: "Storing digital evidence in a physically secure location during the investigation", correct_choice: "B", explanation: "Chain of custody documentation proves evidence has not been tampered with. Without it, digital evidence may be inadmissible in legal proceedings. Every person who handles evidence, every system it passes through, and every analysis performed must be documented." },
        { question_text: "Why should responders avoid running programs on a suspected compromised system before forensic imaging?", choice_a: "Running programs slows down the forensic imaging process", choice_b: "Running programs modifies timestamps, may overwrite deleted files that contain evidence, and can trigger malware to destroy evidence when it detects investigation tools", choice_c: "Running unauthorized programs on company systems may violate acceptable use policies", correct_choice: "B", explanation: "Every action on a system modifies it. Running programs updates access timestamps, which can obscure the attacker's activity timeline. Some malware has anti-forensic capabilities that trigger data destruction when they detect certain investigation tools running." },
      ],
    },
    {
      title: "Module 10: After Action Review",
      content: "The after action review, also called a lessons learned review, is where organizations extract value from incidents. It is not about assigning blame but about identifying what can be improved in detection, response, prevention, and the overall security posture.",
      category: "IR Fundamentals", difficulty: "intermediate", duration_minutes: 8, order_index: 10,
      quiz: [
        { question_text: "What is the primary purpose of a post-incident after action review?", choice_a: "To identify which employees failed to follow security policies so they can be disciplined", choice_b: "To systematically identify gaps in detection, response, and prevention so they can be addressed before the next incident", choice_c: "To create documentation for cyber insurance claims related to the incident", correct_choice: "B", explanation: "After action reviews are forward-looking improvement exercises, not blame sessions. The goal is to understand what gaps allowed the incident to occur and what slowed the response, then fix those gaps. Organizations that treat them as blame sessions get sanitized results that do not drive improvement." },
        { question_text: "Which of the following is a valuable output of an after action review?", choice_a: "A list of employees whose mistakes contributed to the incident", choice_b: "Specific, actionable improvements to detection rules, response playbooks, training, and security controls with assigned owners and deadlines", choice_c: "A detailed timeline of the incident for the organization's annual report", correct_choice: "B", explanation: "Actionable improvement items with owners and deadlines are what make after action reviews valuable. Vague findings like improve security awareness result in nothing. Specific items like add detection rule for this specific behavior by this date and owner create accountability and measurable improvement." },
        { question_text: "How should an organization treat the metrics from security incidents over time?", choice_a: "Keep incident metrics confidential since they reveal security weaknesses to potential attackers", choice_b: "Track metrics like mean time to detect and mean time to respond over time to measure whether the security program is improving", choice_c: "Only collect metrics for incidents that result in regulatory notification obligations", correct_choice: "B", explanation: "Mean time to detect and mean time to respond are the most important security operation metrics. Tracking them over time shows whether investment in detection and response capabilities is working. Organizations that do not measure cannot demonstrate improvement or justify security investment." },
      ],
    },
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS9 };
