const { upsertModule, upsertModuleQuiz } = require("../schema");

function seedS9(db) {
  const sec = db.prepare("SELECT id FROM sections WHERE name='Incident Response'").get();
  if (!sec) return;
  const sid = sec.id;

  const modules = [
    {
      title: "Module 1: What Is an Incident",
      content: `A security incident is any event that threatens the confidentiality, integrity, or availability of your information systems or data. Understanding what qualifies as an incident, and how to recognize one when it occurs, is the starting point for effective incident response.

Not every security alert is an incident. Security tools generate enormous volumes of alerts, the vast majority of which are false positives or low-priority events. An incident is a confirmed or suspected security event that requires a coordinated response. The difference between an event and an incident is context, severity, and impact. A single failed login attempt is an event. Ten thousand failed login attempts against your admin accounts in five minutes is an incident.

Common types of security incidents include unauthorized access to systems or data, malware infections, ransomware attacks, data breaches where sensitive information is exfiltrated, denial of service attacks, insider threats, and supply chain compromises. Each type requires a somewhat different response, but the overall process for managing incidents follows consistent phases regardless of type.

Recognizing incidents requires both technical detection capabilities and human judgment. Technical detection comes from security monitoring tools, antivirus alerts, intrusion detection systems, and log analysis. Human recognition comes from employees who notice something wrong with their systems, receive suspicious communications, or observe unusual behavior by colleagues. Both channels matter, and employees need to know how to report suspected incidents quickly without fear of blame.

The cost of late detection is enormous. Studies consistently show that the longer an attacker remains in an environment undetected, the more damage they can cause and the more expensive recovery becomes. The average time to detect a breach has historically been measured in months. Every day of undetected presence allows an attacker to move laterally, escalate privileges, exfiltrate more data, and establish additional persistence mechanisms.

Early detection requires investment in monitoring, alerting, and the human capacity to investigate alerts. It also requires a culture where employees feel comfortable reporting suspected incidents immediately without worrying about being blamed for causing them. An employee who reports clicking a suspicious link within minutes of doing so gives your security team a chance to contain the incident before it spreads. An employee who waits days out of embarrassment gives the attacker days of undetected access.

Establish clear criteria for what constitutes an incident in your organization and make sure everyone knows what to do when they suspect one has occurred.`,
      category: "IR Fundamentals", difficulty: "beginner", duration_minutes: 8, order_index: 1,
      quiz: [
        { question_text: "Which of the following best describes a security incident?", choice_a: "A confirmed or suspected security event that threatens the confidentiality, integrity, or availability of systems or data and requires a coordinated response", choice_b: "Any event that triggers an antivirus alert regardless of severity or context", choice_c: "Only events that result in confirmed data exfiltration and affect more than one system", correct_choice: "A", explanation: "A security incident includes any event that threatens the CIA triad. This includes breaches, ransomware, unauthorized access, and availability attacks. Not every alert is an incident, but events that threaten these three pillars require a structured response." },
        { question_text: "What is the difference between a security event and a security incident?", choice_a: "Events are external threats while incidents are internal threats caused by employees or insiders", choice_b: "An event is any observable occurrence in a system, while an incident is an event that has been assessed as having a negative security impact requiring a coordinated response", choice_c: "Incidents are events that have been fully investigated, documented, and formally closed in the ticketing system", correct_choice: "B", explanation: "Security events are raw observations like a failed login or firewall block. An incident is an event that analysis shows has real security impact. The triage and assessment process converts events into incidents requiring formal response." },
        { question_text: "Why is early detection of security incidents important beyond just minimizing immediate damage?", choice_a: "Early detection automatically prevents all data loss through built-in security tool containment features", choice_b: "Early detection reduces the attacker's dwell time, limiting lateral movement, privilege escalation, and data exfiltration before the attacker is stopped", choice_c: "Early detection is required to qualify for cybersecurity insurance claims under most policies", correct_choice: "B", explanation: "The longer an attacker has access, the more damage they cause. Studies consistently show that shorter dwell times correlate with significantly less data stolen and lower recovery costs. Early detection is the single most impactful factor in incident outcomes." },
      ],
    },
    {
      title: "Module 2: The Incident Response Lifecycle",
      content: `The incident response lifecycle provides a structured framework for managing security incidents from initial detection through final resolution and lessons learned. Having a defined process prevents the chaos and ad-hoc decision making that makes incidents worse and recovery harder.

The most widely used incident response framework comes from the National Institute of Standards and Technology. The NIST framework defines four phases: preparation, detection and analysis, containment eradication and recovery, and post-incident activity. These phases are not strictly sequential but cycle continuously as incidents evolve and new information emerges.

Preparation is the most important phase because it happens before any incident occurs. Preparation includes building and training an incident response team, developing and documenting incident response plans and playbooks, deploying detection and logging tools, establishing communication channels and escalation paths, and conducting tabletop exercises to test your plans. Organizations that invest in preparation respond faster, make better decisions under pressure, and recover more completely than those who improvise.

Detection and analysis involves identifying that an incident has occurred, determining its scope and severity, and gathering the information needed to respond effectively. This phase involves correlating alerts from multiple sources, analyzing logs and forensic artifacts, and making decisions about how serious the incident is and what resources to mobilize.

Containment stops the incident from spreading while you plan eradication and recovery. Containment strategies vary by incident type. For a malware infection, containment might mean isolating affected systems from the network. For a compromised account, it means revoking credentials and terminating active sessions. The goal is to limit damage while preserving forensic evidence.

Eradication removes the threat from your environment. This means removing malware, closing the vulnerability that was exploited, revoking unauthorized access, and verifying that no additional compromises occurred. Eradication must be thorough because attackers frequently establish multiple persistence mechanisms.

Recovery restores affected systems and services to normal operation. Recovery is more than just restoring from backup. It includes verifying the integrity of restored systems, monitoring for signs of re-compromise, and gradually returning systems to production with enhanced monitoring.

Post-incident activity is where lasting improvement happens. The after action review identifies what went wrong, what went right, and what specific changes to make to prevent recurrence and improve future response.`,
      category: "IR Fundamentals", difficulty: "beginner", duration_minutes: 10, order_index: 2,
      quiz: [
        { question_text: "What is the primary goal of the containment phase in incident response?", choice_a: "Stop the incident from spreading or causing more damage while the investigation continues and forensic evidence is preserved", choice_b: "Permanently remove all malware and close every vulnerability found during the investigation as quickly as possible", choice_c: "Restore all affected systems to their pre-incident state as quickly as possible to minimize business disruption", correct_choice: "A", explanation: "Containment limits the blast radius. The goal is not yet to fix everything but to stop the bleeding. This often means isolating affected systems, revoking compromised credentials, or blocking attacker infrastructure while the full scope of the incident is determined." },
        { question_text: "Why must eradication happen before recovery in the incident response lifecycle?", choice_a: "Eradication is optional if the systems appear to be functioning normally again after containment", choice_b: "If systems are restored before the attacker's access and all persistence mechanisms are fully removed, the attacker immediately recompromises the recovered systems", choice_c: "Eradication generates the documentation required to formally begin the recovery process under compliance frameworks", correct_choice: "B", explanation: "Attackers often install multiple backdoors and persistence mechanisms. Recovering systems without eradicating every foothold means the attacker retains access and your recovery effort immediately restores their access. Thorough eradication must precede any recovery work." },
        { question_text: "What is the purpose of the post-incident activity phase and why do organizations often skip it?", choice_a: "It is used to assign blame and discipline employees whose mistakes contributed to the incident", choice_b: "It captures lessons learned to improve future detection, response, and prevention, but organizations skip it because returning to normal operations feels like closure", choice_c: "It is required only for incidents involving regulatory notification obligations under applicable law", correct_choice: "B", explanation: "Post-incident review captures what worked, what failed, and what gaps allowed the incident to occur. Organizations skip it because recovery feels like closure, but the review is where real security improvement happens. Skipping it means making the same mistakes in the next incident." },
      ],
    },
    {
      title: "Module 3: Building an Incident Response Plan",
      content: `An incident response plan is a documented, tested set of procedures that guides your organization through detecting, containing, eradicating, and recovering from security incidents. Without a plan, incident response defaults to improvisation under pressure, which consistently produces worse outcomes than even a mediocre written plan.

The incident response plan should begin with clear definitions. What constitutes an incident at your organization? What are the severity levels and what determines which level applies? Who is on the incident response team and what are their roles? Who has authority to make major decisions like taking systems offline or notifying customers? These questions need answers before an incident occurs, not during one.

Playbooks are the operational heart of an incident response plan. A playbook is a step-by-step guide for responding to a specific type of incident. Common playbooks cover ransomware, data breach, account compromise, malware infection, DDoS attack, and insider threat. Each playbook walks through detection indicators, immediate containment steps, investigation procedures, eradication steps, recovery procedures, and notification requirements. Playbooks reduce decision fatigue during stressful incidents and ensure consistent responses regardless of which team member is leading the response.

Communication plans specify who needs to be notified at each stage of an incident and through what channels. Internal communication includes executives, legal counsel, human resources, and affected business units. External communication may include customers, partners, regulators, and law enforcement depending on the nature of the incident. Pre-drafted communication templates save critical time when you are in the middle of an incident and need to notify stakeholders quickly.

Legal and regulatory notification requirements must be incorporated into your plan. Many jurisdictions require notification of affected individuals and regulators within specific timeframes after a data breach. GDPR requires notification to regulators within 72 hours of becoming aware of a breach. HIPAA has its own notification timeline. Knowing your obligations before an incident occurs ensures you meet them without scrambling to understand the requirements while simultaneously managing the incident.

The plan must be tested. A plan that has never been tested is a plan of unknown reliability. Tabletop exercises simulate incident scenarios and walk the team through the plan in a discussion format. Full simulation exercises actually execute response procedures in a test environment. Test at least annually and after any significant changes to your environment or the threat landscape.`,
      category: "IR Fundamentals", difficulty: "intermediate", duration_minutes: 10, order_index: 3,
      quiz: [
        { question_text: "What is the most critical element to establish in an incident response plan before an incident occurs?", choice_a: "Clear roles, decision-making authority, and escalation paths so everyone knows who can make what decisions during a fast-moving incident without waiting for approval chains", choice_b: "A detailed technical playbook for every possible type of attack with specific remediation steps for each", choice_c: "A complete inventory of all software installed on every company system for forensic reference", correct_choice: "A", explanation: "Decision authority is the most critical element because incidents move fast. If responders must navigate approval chains during an active breach, attackers gain ground. Pre-defined authority means the right people can act immediately without organizational delays." },
        { question_text: "Why should an incident response plan include out-of-band communication methods?", choice_a: "Out-of-band communications are faster than email during normal operations so they speed up response times", choice_b: "If an attacker has compromised your email or internal systems, using those same systems to coordinate your response tells the attacker your plans", choice_c: "Regulatory requirements mandate the use of external communication channels during security incidents", correct_choice: "B", explanation: "Sophisticated attackers monitor compromised systems including email. Coordinating your response through a compromised channel gives the attacker visibility into your actions. Out-of-band channels like personal phones or pre-established conference lines prevent this." },
        { question_text: "How often should an incident response plan be tested and updated?", choice_a: "Only when a real incident reveals a specific gap in the existing plan through direct experience", choice_b: "Once when initially created since the fundamental steps do not change significantly over time", choice_c: "At least annually through tabletop exercises or simulations and whenever the environment, personnel, or threat landscape changes significantly", correct_choice: "C", explanation: "Plans become stale. Personnel change, systems change, and new attack techniques emerge. Regular testing through tabletop exercises reveals gaps before a real incident does. Updating after exercises and significant environment changes keeps the plan aligned with reality." },
      ],
    },
    {
      title: "Module 4: Detection and Triage",
      content: `Detection and triage are the skills that separate organizations that catch incidents early from those that discover breaches months after they began. Detection is finding that something is wrong. Triage is determining how serious it is and what to do about it first.

Detection relies on a layered approach combining automated tools and human observation. No single detection tool catches everything, which is why defense in depth applies to detection just as it applies to prevention. Antivirus and endpoint detection tools catch known malware and suspicious behavior on individual devices. Network monitoring catches unusual traffic patterns and connections to known malicious infrastructure. Log analysis identifies anomalous patterns in authentication, access, and system activity. Threat intelligence feeds provide indicators of compromise associated with known threat actors and campaigns.

Alert fatigue is the enemy of effective detection. When security tools generate thousands of alerts per day, analysts become desensitized and start dismissing alerts without proper investigation. Tuning your detection tools to reduce false positives is as important as deploying them in the first place. Prioritize high-fidelity alerts that indicate genuine threats and suppress or deprioritize alerts that consistently turn out to be benign.

Threat hunting is the proactive search for threats that have evaded automated detection. Rather than waiting for alerts, threat hunters actively look for indicators of compromise and attacker techniques in your environment. Threat hunting catches sophisticated attackers who specifically design their tools and techniques to avoid triggering common detection rules.

Triage involves quickly assessing the severity and scope of a potential incident to determine the appropriate response level. Key questions during triage include: What systems are affected? What data may be at risk? Is the incident still ongoing? How did the attacker gain access? Are there signs of lateral movement to other systems? The answers determine whether this is a minor event that one analyst can handle or a major incident requiring the full team.

Severity classification helps allocate resources appropriately. A common approach uses four or five levels from informational events that require no immediate action up to critical incidents that require all hands immediately. Define your severity levels clearly with specific criteria for each level so triage decisions are consistent across different analysts and time periods.

Time is critical during triage. Every minute spent debating whether something is an incident is a minute the attacker may be using to move deeper into your environment. When in doubt, treat it as an incident and scale back the response if investigation reveals it was a false alarm. The cost of an unnecessary response is far lower than the cost of delayed response to a real incident.`,
      category: "Detection", difficulty: "intermediate", duration_minutes: 10, order_index: 4,
      quiz: [
        { question_text: "What is alert fatigue and why is it a serious security problem?", choice_a: "Alert fatigue occurs when security tools generate so many alerts that analysts become desensitized and begin dismissing alerts without proper investigation, causing real threats to be missed", choice_b: "Alert fatigue is a hardware problem caused by security monitoring systems running too many simultaneous queries that degrades system performance", choice_c: "Alert fatigue refers to psychological burnout experienced by security analysts after responding to major incidents resulting in high staff turnover", correct_choice: "A", explanation: "High alert volumes with low signal quality cause analysts to treat all alerts as noise. When a genuine high-priority alert arrives it receives the same cursory review as the hundreds of false positives that preceded it. Tuning detection to reduce false positives is as important as detection capability itself." },
        { question_text: "A user reports that their computer is running slowly and showing pop-up messages they did not install. What is the correct initial triage question?", choice_a: "Have any other users reported similar symptoms, and has the affected user recently opened email attachments, clicked unusual links, or installed any new software?", choice_b: "What is the make and model of the affected computer because hardware failures are more common than malware and should be ruled out first", choice_c: "Has the user recently changed their password because account compromise is the most likely cause of unusual system behavior", correct_choice: "A", explanation: "Understanding whether the issue is isolated or widespread, and identifying recent user actions that might explain it, immediately narrows the investigation. A single affected user after clicking a link suggests malware. Multiple users with the same symptoms suggests a broader compromise." },
        { question_text: "What information should be gathered during initial triage to determine incident severity?", choice_a: "A complete inventory of all software installed on affected systems to identify potential vulnerability sources", choice_b: "The affected system count, nature of the threat, what data may be at risk, whether the incident is ongoing, and how the attacker gained access if known", choice_c: "The financial cost estimate for remediation so that appropriate budget can be approved before response activities begin", correct_choice: "B", explanation: "Severity determination requires understanding scope and impact. How many systems are affected determines resource needs. Whether the incident is ongoing affects urgency. Data at risk determines notification requirements. Access method affects containment strategy." },
      ],
    },
    {
      title: "Module 5: Containment Strategies",
      content: `Containment is the phase where you stop an active incident from getting worse. The goal is not to fix everything immediately but to limit damage while you gather enough information to eradicate the threat properly. Moving too fast in containment can destroy forensic evidence. Moving too slow allows the attacker to cause more damage.

Short-term containment actions are immediate steps taken to stop the bleeding without permanently altering affected systems. These include isolating affected systems from the network by disconnecting them or placing them in a quarantine VLAN, blocking malicious IP addresses at the firewall, revoking compromised credentials, and disabling affected user accounts. These actions are reversible and preserve the state of affected systems for forensic analysis.

Evidence preservation must happen in parallel with containment. Before making significant changes to affected systems, capture forensic images of disk contents and take memory dumps if possible. Preserve log files from affected systems and any network devices that may have recorded relevant traffic. Evidence collected before remediation is far more useful than evidence collected after, because remediation actions inevitably alter the state of systems.

Long-term containment strategies may be needed when immediate full eradication is not possible. If you cannot immediately remove malware from a production system without causing unacceptable downtime, you might keep the system running in a highly monitored isolated state while you prepare a clean replacement. This is acceptable when the alternative is extended outage, but it requires careful monitoring to ensure the contained threat does not spread.

Network segmentation during containment prevents lateral movement. If an attacker has compromised one system, they will attempt to use that access to reach other systems. Isolating the compromised segment limits their ability to do so. In cloud environments this means modifying security groups to restrict outbound connections from affected resources.

Communication during containment is critical. The incident response team needs to coordinate actions to avoid stepping on each other. Executives need enough information to make decisions about business continuity without being buried in technical details. Affected users may need to know why their access has been revoked or their systems taken offline. Establish a clear communication cadence during active containment and assign someone specifically to handle internal and external communications so that the technical team can focus on response.`,
      category: "Containment", difficulty: "intermediate", duration_minutes: 10, order_index: 5,
      quiz: [
        { question_text: "What is the tradeoff between aggressive containment and a slower deliberate approach during an incident?", choice_a: "Aggressive containment stops damage faster but risks destroying forensic evidence and missing additional compromises if done without preserving evidence first", choice_b: "Aggressive containment is always the correct approach because the cost of additional damage always outweighs the value of forensic evidence", choice_c: "Deliberate containment is always the correct approach because forensic evidence is required for legal proceedings in every incident", correct_choice: "A", explanation: "The right balance depends on the specific incident. Active ransomware spreading to new systems requires aggressive containment immediately. An attacker who has been in an environment for months warrants more deliberate containment that preserves evidence to understand the full scope." },
        { question_text: "Why is network isolation a common first containment step for malware infections?", choice_a: "Network isolation prevents the malware from communicating with its command and control infrastructure and spreading to other systems while preserving the state of the infected system for analysis", choice_b: "Network isolation allows security tools to run more effectively because they do not have to process legitimate network traffic while scanning", choice_c: "Network isolation is required by most cyber insurance policies as a mandatory first step that must be documented before coverage applies", correct_choice: "A", explanation: "Malware that cannot reach its command and control cannot receive new instructions, exfiltrate data, or spread to new systems. Isolation cuts the attacker's operational capability immediately while keeping the system available for forensic investigation." },
        { question_text: "What does preserving evidence during containment mean and why does it matter?", choice_a: "Taking forensic disk images and memory captures of affected systems before making changes, because remediation actions alter system state and can destroy the artifacts needed to understand what happened", choice_b: "Keeping all affected systems running in their compromised state until a full forensic investigation is complete regardless of how long that takes", choice_c: "Documenting the incident in a ticketing system before taking any containment actions so there is a written record of the initial discovery", correct_choice: "A", explanation: "Digital forensic evidence is fragile. Rebooting a system clears memory. Cleaning malware removes artifacts. Evidence captured before remediation is reliable and complete. Evidence gathered after remediation may be partial, altered, or missing entirely." },
      ],
    },
    {
      title: "Module 6: Eradication and Recovery",
      content: `Eradication removes the threat from your environment completely. Recovery restores your systems and services to normal operation. These two phases are closely linked but distinct, and rushing through eradication to get to recovery is one of the most common mistakes organizations make during incident response.

Eradication must be thorough. Attackers routinely establish multiple persistence mechanisms to ensure they can regain access even if their primary access method is discovered and removed. Common persistence techniques include creating new user accounts, installing scheduled tasks or cron jobs that re-run malicious code, modifying startup scripts, installing rootkits that survive operating system reinstalls, and establishing command and control connections through legitimate-looking outbound traffic. Your eradication process must identify and remove all of these, not just the most obvious one.

The safest eradication approach for severely compromised systems is complete rebuild from a known good baseline. Rather than attempting to clean an infected system, you provision a new clean instance, restore data from a verified clean backup, and verify the new system is operating correctly before decommissioning the compromised one. This approach takes more time than attempting to clean the existing system but provides much higher confidence that the threat is fully removed.

Vulnerability remediation is an essential component of eradication. The attacker exploited something to gain access. If you remove the attacker without fixing the vulnerability, you have simply reset the clock. Identify the initial access vector, whether it was a phishing email, an unpatched vulnerability, a weak password, or a misconfigured service, and address it as part of eradication.

Recovery involves restoring systems and services carefully rather than simply bringing everything back online as quickly as possible. Prioritize systems based on business criticality. Restore from the most recent verified clean backup. Monitor restored systems more intensively than normal for the first days and weeks after recovery to detect any signs of re-compromise that might indicate the eradication was incomplete.

Credential rotation is required after any incident involving account compromise. Change passwords for all accounts that may have been accessed during the incident, even if there is no specific evidence those accounts were compromised. If the attacker had access to your environment for any significant period, assume they may have harvested credentials. Rotate service account credentials, API keys, and any other secrets that were accessible in the compromised environment.`,
      category: "Eradication", difficulty: "advanced", duration_minutes: 12, order_index: 6,
      quiz: [
        { question_text: "Why is simply running antivirus after an incident insufficient for complete eradication?", choice_a: "Antivirus can only detect known malware signatures and will miss novel malware, may not detect all persistence mechanisms, and cannot remove rootkits that hide themselves from the operating system", choice_b: "Antivirus tools are too slow to run during an active incident because they require a full system scan that takes hours to complete", choice_c: "Antivirus removes the malware but does not address the vulnerability that was exploited, leaving the system vulnerable to the same attack", correct_choice: "A", explanation: "Sophisticated attackers install multiple persistence mechanisms. Antivirus may find and remove the obvious malware while missing a backdoor user account, a scheduled task that reinstalls the malware, or a rootkit designed to hide from security tools. Complete eradication requires understanding all attacker actions." },
        { question_text: "What is the safest approach to recovering a system that was severely compromised by an attacker who had extended access?", choice_a: "Provision a completely clean replacement system from a known-good baseline and restore only verified clean data to it rather than attempting to clean the compromised system", choice_b: "Run a comprehensive antivirus scan and remove all detected threats, then monitor the system intensively for two weeks to verify the attacker is no longer present", choice_c: "Restore the system from the most recent backup taken before the compromise began and verify the backup was not itself affected", correct_choice: "A", explanation: "An attacker with extended access may have modified system files, created hidden accounts, installed rootkits, and established persistence mechanisms that survive antivirus scanning. A clean rebuild from a known-good baseline provides higher confidence than any cleaning process applied to a compromised system." },
        { question_text: "What must be verified before returning recovered systems to production?", choice_a: "The total cost of recovery must be approved by finance and the incident must be closed in the ticketing system before systems can be returned", choice_b: "The restored systems must be verified as clean through security scans, the initial access vulnerability must be confirmed as remediated, and enhanced monitoring must be in place", choice_c: "Legal counsel must review and approve all remediation actions taken during eradication before affected systems can return to production", correct_choice: "B", explanation: "Recovery is not complete when systems are back online. Verification that the threat is fully removed, that the attack vector is closed, and that monitoring is in place to detect re-compromise are all required before normal operations resume." },
      ],
    },
    {
      title: "Module 7: Communication During Incidents",
      content: `Effective communication during a security incident is as important as effective technical response. Poor communication causes confusion, delays decisions, creates legal liability, and can allow the attacker to adapt their approach if they are monitoring your systems. Good communication keeps the right people informed with the right information at the right time.

Internal communication during an incident needs to be controlled carefully. The incident response team needs detailed technical information to coordinate their response. Executives need enough information to make business continuity decisions without being overwhelmed by technical detail. Legal counsel needs to be involved early to protect privileged communications and advise on notification obligations. Human resources may need to be involved if the incident involves insider threat. Affected employees may need limited information about why their systems are unavailable or why their access has been revoked.

Out-of-band communication channels are critical when your primary systems may be compromised. If an attacker has access to your email, using email to coordinate your incident response tells the attacker your plans. Establish alternative communication channels before an incident occurs. Personal mobile phones, encrypted messaging apps on personal devices, and pre-established conference bridge numbers are all options. The channel should be completely independent of the systems that may be compromised.

External communication requires careful management. Regulatory notification obligations have specific content requirements and timelines that must be met. Customer communications need to be accurate, clear, and focused on what affected parties need to do to protect themselves. Media communications, if necessary, should go through a single designated spokesperson to ensure consistent messaging. Law enforcement engagement requires careful consideration of what information to share and when.

Timing of external communication involves competing pressures. Notifying too early before the scope is fully understood leads to inaccurate communications that require correction. Notifying too late risks regulatory violations and damages trust. Work with legal counsel to understand the specific notification timelines that apply to your situation and plan communications accordingly.

Documentation during the incident serves multiple purposes. It supports the investigation by creating a timeline of actions taken. It creates records that may be required for regulatory compliance. It provides the foundation for the after action review. Assign someone specifically to document the timeline of events, actions taken, and decisions made during the response rather than relying on individual memories reconstructed after the fact.`,
      category: "Communication", difficulty: "intermediate", duration_minutes: 10, order_index: 7,
      quiz: [
        { question_text: "Why should incident communications be kept to a need-to-know basis during an active incident?", choice_a: "If an attacker has insider access or is monitoring communications, broad incident discussions reveal the scope of detection and response actions, potentially allowing the attacker to adapt their approach before containment is complete", choice_b: "Limiting communication protects the organization legally by ensuring only authorized statements about the incident are made", choice_c: "Wide distribution of incident details wastes response team time as non-essential personnel ask questions that distract from active response work", correct_choice: "A", explanation: "Need-to-know communication during an active incident protects response operations. An attacker who learns they have been detected may accelerate data exfiltration, delete logs, or activate additional persistence before containment is complete." },
        { question_text: "What triggers mandatory external breach notification requirements in most regulatory frameworks?", choice_a: "Any security incident involving more than ten affected user accounts automatically triggers mandatory notification regardless of data type", choice_b: "Mandatory notification is triggered only when an organization publicly acknowledges a breach", choice_c: "Mandatory notification is triggered by incidents involving specific categories of protected data such as personal information or health records, with timelines varying by regulation", correct_choice: "C", explanation: "Notification requirements are tied to data types and applicable regulations rather than incident size. GDPR requires notification within 72 hours for breaches involving personal data. HIPAA has specific requirements for health information. Many US states have their own breach notification laws." },
        { question_text: "What is the role of legal counsel in incident response communications?", choice_a: "Legal counsel drafts all external communications to ensure they are factually accurate and comprehensive for affected parties", choice_b: "Legal counsel reviews external communications, advises on notification obligations, guides decisions about law enforcement engagement, and helps ensure communications do not create additional legal liability", choice_c: "Legal counsel's role is limited to reviewing final breach notification letters before they are sent to regulatory bodies", correct_choice: "B", explanation: "Legal involvement in incident response goes beyond reviewing notification letters. Legal counsel advises on privilege protections for investigation documents, guides decisions about law enforcement cooperation, reviews all external statements, and helps navigate the complex intersection of security operations and legal obligations." },
      ],
    },
    {
      title: "Module 8: Ransomware Response",
      content: `Ransomware has become one of the most disruptive and financially damaging forms of cyberattack. Understanding how ransomware works and how to respond when it strikes is essential knowledge for anyone responsible for systems or data.

Ransomware encrypts your files and demands payment, usually in cryptocurrency, in exchange for the decryption key. Modern ransomware attacks often involve double extortion, where the attackers exfiltrate data before encrypting it and threaten to publish it publicly if the ransom is not paid. Some attacks involve triple extortion, adding threats to notify your customers or attack your customers directly.

Ransomware typically enters environments through phishing emails containing malicious attachments or links, exploitation of unpatched vulnerabilities in internet-facing systems, compromised remote desktop protocol credentials, or malicious downloads. Once inside, ransomware operators often spend weeks or months in an environment before triggering encryption, during which time they establish persistence, escalate privileges, move laterally to reach the most valuable data, and disable backup systems.

When ransomware activates, the first response is containment. Isolate affected systems immediately to prevent the encryption from spreading to additional systems and network shares. Disconnect affected systems from the network but do not power them off, as memory may contain forensic information about the ransomware and potentially the encryption keys.

Do not pay the ransom without exhausting all other options. Payment funds criminal operations and does not guarantee recovery. A significant percentage of organizations that pay ransoms do not receive working decryption keys, or receive keys that only partially decrypt their data. In some jurisdictions, paying ransoms to sanctioned entities may itself be illegal.

Before considering payment, check whether free decryption tools exist for the specific ransomware variant. The No More Ransom project maintains a database of free decryptors for many ransomware families. Ransomware identification tools can help determine which variant you are dealing with.

The best defense against ransomware is immutable offline backups. Backups that ransomware cannot reach or modify are your recovery path when all else fails. Test your backups regularly. Know your recovery time objective and ensure your backup strategy can meet it.`,
      category: "Ransomware", difficulty: "advanced", duration_minutes: 12, order_index: 8,
      quiz: [
        { question_text: "What is the most effective preparation against ransomware before an attack occurs?", choice_a: "Maintaining tested offline or cloud-isolated immutable backups of all critical data combined with network segmentation to limit lateral spread", choice_b: "Installing the latest version of antivirus software with ransomware-specific protection modules on all endpoints", choice_c: "Training all employees to recognize phishing emails because phishing is the only delivery mechanism for ransomware", correct_choice: "A", explanation: "Backups are the only reliable recovery mechanism when other defenses fail. Antivirus misses novel variants. Phishing training reduces but cannot eliminate human error. Immutable backups that ransomware cannot reach ensure recovery is possible regardless of which delivery method is used." },
        { question_text: "If an organization decides to pay a ransomware demand, what risks remain even after paying?", choice_a: "No risks remain since attackers have a business incentive to provide working decryption keys to maintain their reputation", choice_b: "Attackers may provide broken decryptors, have already sold the stolen data, demand additional payment, or have left backdoors for future attacks against the same target", choice_c: "The only remaining risk is the reputational damage from the payment becoming known to the public", correct_choice: "B", explanation: "Payment is not a guarantee of recovery. Studies show a significant percentage of organizations that pay do not fully recover their data. Attackers may have already sold the data before encrypting it, making payment irrelevant to data exposure. Paying also marks the organization as a target willing to pay again." },
        { question_text: "What should be the first technical action when ransomware is detected actively encrypting files on a network?", choice_a: "Isolate affected systems from the network immediately to stop lateral spread while identifying how many systems are affected", choice_b: "Immediately pay the ransom to stop the encryption before more files are irretrievably lost", choice_c: "Run a full backup of all remaining unaffected systems before taking any other containment action", correct_choice: "A", explanation: "Immediate network isolation stops ransomware from spreading to additional systems and from communicating with attacker infrastructure. Speed is critical because every second of network connectivity allows more encryption and potential spread. Isolation is the containment action that limits total damage." },
      ],
    },
    {
      title: "Module 9: Digital Forensics Basics",
      content: `Digital forensics is the process of collecting, preserving, and analyzing digital evidence in a way that maintains its integrity and makes it usable in investigations and, if necessary, legal proceedings. Even if you never need to present evidence in court, forensic principles improve the quality of your incident investigations and help you understand exactly what happened during a breach.

The most fundamental principle of digital forensics is evidence preservation. Digital evidence is fragile and can be easily altered or destroyed. The act of booting a compromised system, running programs on it, or even just letting it continue operating changes the evidence. Proper forensic practice involves capturing the state of systems before making any changes. This means taking forensic disk images that capture every bit of data on a drive, taking memory captures that preserve the contents of RAM including running processes and network connections, and preserving log files before any remediation actions alter or delete them.

Chain of custody documentation records every person who handled evidence, what they did with it, and when. This documentation is what allows evidence to be trusted in legal proceedings. Even in internal investigations, maintaining chain of custody discipline instills good habits and produces more reliable evidence.

Disk imaging creates a bit-for-bit copy of a storage device that can be analyzed without touching the original. Forensic analysis is always performed on the image, never on the original evidence. This ensures the original evidence remains unaltered and can be used for verification or future analysis.

Memory forensics analyzes the contents of a system's RAM at a point in time. Memory contains information that is not stored on disk, including encryption keys, running processes and their network connections, recently executed commands, and credentials. Memory captures are extremely valuable in malware investigations because sophisticated malware often operates entirely in memory to avoid leaving traces on disk.

Log analysis is the most practical forensic skill for most security professionals. System logs, application logs, authentication logs, and network logs together create a timeline of what happened. Learning to correlate events across multiple log sources, identify the timestamps of key attacker actions, and trace the path an attacker took through your environment is a skill that pays dividends in every investigation.`,
      category: "Forensics", difficulty: "advanced", duration_minutes: 12, order_index: 9,
      quiz: [
        { question_text: "What is the order of volatility and why does it matter in digital forensics?", choice_a: "The sequence in which digital evidence is lost, with memory and network connections disappearing first, guiding investigators to collect the most perishable evidence before less volatile evidence like disk data", choice_b: "A ranking of how severe different types of security incidents are for purposes of prioritizing response resources", choice_c: "A legal framework determining which evidence courts consider most reliable and admissible in proceedings", correct_choice: "A", explanation: "Memory contains running processes, encryption keys, and attacker tools that disappear the moment the system is rebooted. Network connection state disappears quickly. Disk data is more persistent. Forensic collection follows volatility order to capture what will be lost soonest." },
        { question_text: "What does maintaining a chain of custody mean for digital evidence?", choice_a: "Encrypting digital evidence so only authorized personnel can access it during the investigation period", choice_b: "Documenting who collected evidence, how it was collected, where it has been, and who has accessed it so evidence integrity can be proven without question", choice_c: "Storing digital evidence in a physically secure location accessible only to the lead investigator", correct_choice: "B", explanation: "Chain of custody documentation proves evidence has not been tampered with. Without it, digital evidence may be inadmissible in legal proceedings. Every person who handles evidence, every system it passes through, and every analysis performed must be documented." },
        { question_text: "Why should responders avoid running programs on a suspected compromised system before forensic imaging?", choice_a: "Running programs slows down the forensic imaging process by consuming system resources simultaneously", choice_b: "Running programs modifies timestamps, may overwrite deleted files that contain evidence, and can trigger malware to destroy evidence when it detects investigation tools running", choice_c: "Running unauthorized programs on company systems may violate acceptable use policies and create legal complications", correct_choice: "B", explanation: "Every action on a system modifies it. Running programs updates access timestamps, which can obscure the attacker's activity timeline. Some malware has anti-forensic capabilities that trigger data destruction when they detect certain investigation tools running." },
      ],
    },
    {
      title: "Module 10: After Action Review",
      content: `The after action review, also called a post-incident review or lessons learned session, is the phase where incidents generate lasting improvement. Without structured reflection after incidents, organizations repeat the same mistakes and face the same incidents again and again. With it, each incident makes you measurably more secure.

The after action review should occur within days of an incident being resolved, while details are still fresh. It should include everyone who participated in the response, from the frontline analysts who detected the incident to the executives who made containment decisions. The goal is learning, not blame. A blame-focused review causes people to be defensive and withhold information. A learning-focused review surfaces the real root causes and systemic issues that need to be addressed.

The review should address a standard set of questions. What happened and when? What was the initial detection method and how long did it take to detect? What was the response timeline and where were the delays? What worked well in the response? What did not work as expected? What was the root cause of the incident? What could have prevented it? What changes would make future detection and response faster and more effective?

Root cause analysis goes deeper than identifying the immediate cause. A ransomware incident might have been caused immediately by a phishing email, but the root cause might be inadequate security awareness training, the absence of email filtering controls, or a culture where employees are afraid to report suspicious emails. Addressing root causes prevents recurrence. Addressing only immediate causes means the next incident exploits the same underlying weakness through a different vector.

Action items from the review must be specific, assigned to named individuals, and tracked to completion. Vague recommendations like improve security awareness accomplish nothing. Specific action items like schedule quarterly phishing simulation for all staff by end of quarter with results reviewed monthly are actionable and measurable.

Metrics from incidents help quantify improvement over time. Track mean time to detect, mean time to contain, mean time to recover, and total incident cost. Improvements in these metrics across incidents demonstrate that your investments in detection and response capabilities are paying off.

Share lessons learned appropriately. Within your organization, sharing what happened and what you learned helps other teams avoid similar incidents. In some cases, sharing sanitized incident details with peers in your industry or with sector-specific information sharing organizations helps the broader community defend against the same threats.`,
      category: "IR Fundamentals", difficulty: "intermediate", duration_minutes: 8, order_index: 10,
      quiz: [
        { question_text: "What is the primary purpose of a post-incident after action review?", choice_a: "To systematically identify gaps in detection, response, and prevention so they can be addressed before the next incident occurs", choice_b: "To identify which employees failed to follow security policies so they can receive appropriate disciplinary action", choice_c: "To create documentation for cyber insurance claims and regulatory reports related to the incident", correct_choice: "A", explanation: "After action reviews are forward-looking improvement exercises, not blame sessions. The goal is to understand what gaps allowed the incident to occur and what slowed the response, then fix those gaps. Organizations that treat them as blame sessions get sanitized results that do not drive improvement." },
        { question_text: "Which of the following is a valuable output of an after action review?", choice_a: "A list of employees whose mistakes contributed to the incident for accountability purposes", choice_b: "Specific actionable improvements to detection rules, response playbooks, training, and security controls with assigned owners and deadlines", choice_c: "A detailed timeline of the incident formatted for the organization's annual security report", correct_choice: "B", explanation: "Actionable improvement items with owners and deadlines are what make after action reviews valuable. Vague findings like improve security awareness result in nothing. Specific items like add detection rule for this specific behavior by this date and owner create accountability and measurable improvement." },
        { question_text: "How should an organization treat the metrics from security incidents over time?", choice_a: "Keep incident metrics confidential since they reveal security weaknesses to potential attackers and competitors", choice_b: "Track metrics like mean time to detect and mean time to respond over time to measure whether the security program is actually improving", choice_c: "Only collect metrics for incidents that result in mandatory regulatory notification obligations", correct_choice: "B", explanation: "Mean time to detect and mean time to respond are the most important security operation metrics. Tracking them over time shows whether investment in detection and response capabilities is working. Organizations that do not measure cannot demonstrate improvement or justify security investment." },
      ],
    },
  ];

  for (const m of modules) {
    const { quiz, ...extras } = m;
    extras.section_id = sid;
    const mid = upsertModule(db, m.title, m.content, extras);
    upsertModuleQuiz(db, mid, quiz);
  }
}

module.exports = { seedS9 };
