const { upsertSimulation, upsertQuestion } = require("../schema");

function seedSimulations(db) {
  const simulations = [
    {
      title: "Invoice Due Today",
      prompt: "You receive an email saying an invoice is overdue and must be paid today.",
      explanation: "This scam uses urgency, a fake billing portal, and pressure to push the user into clicking before checking the sender.",
      sender_name: "Accounts Payable", sender_email: "billing@securevend0r-payments.com",
      subject: "Urgent: Invoice Due Today", sent_at: "Today, 9:14 AM",
      body_text: `Hello,\n\nOur records show your invoice is now overdue and requires immediate payment to avoid service disruption.\n\nPlease review the attached invoice and confirm payment today.\n\nPayment Portal:\nsecurevendor-billing-login.com\n\nThank you,\nAccounts Payable Team`,
      link_label: "Review invoice and submit payment", link_url: "securevendor-billing-login.com",
      attachment_name: "Invoice_88421.pdf", is_phishing: 1, landing_page_type: "bank",
      difficulty: "easy", scenario_type: "phishing", channel: "email",
      question: { question_text: "What is the safest action?", choice_a: "Click the link and pay to avoid late fees", choice_b: "Reply directly and ask them to resend payment details", choice_c: "Verify using a known contact method, then report if suspicious", correct_choice: "C", red_flags: "Urgency, lookalike domain, unexpected payment request" },
    },
    {
      title: "Mailbox Quota Warning",
      prompt: "An email claims your mailbox is full and asks you to verify your account.",
      explanation: "Mailbox quota scams often try to collect credentials through a fake sign in page that looks familiar.",
      sender_name: "Microsoft 365 Notifications", sender_email: "support@micros0ft-mailhelp.com",
      subject: "Mailbox Storage Limit Reached", sent_at: "Today, 10:42 AM",
      body_text: `Your mailbox has reached 99 percent capacity.\n\nTo avoid message delivery failure, verify your mailbox and increase storage immediately.\n\nUse the secure verification page below.\n\nRegards,\nMail Admin`,
      link_label: "Verify mailbox now", link_url: "microsoft365-verify-now.com",
      attachment_name: "", is_phishing: 1, landing_page_type: "microsoft",
      difficulty: "medium", scenario_type: "phishing", channel: "email",
      question: { question_text: "Which red flag is the strongest indicator of phishing here?", choice_a: "The message mentions storage limits", choice_b: "The sender domain does not match the real Microsoft domain", choice_c: "The message was sent in the morning", correct_choice: "B", red_flags: "Lookalike domain, urgency, credential harvest attempt" },
    },
    {
      title: "Team Meeting Notes",
      prompt: "A coworker shares meeting notes from a scheduled team session.",
      explanation: "This is a legitimate internal message. The sender is familiar, the context is expected, and there is no pressure or suspicious domain mismatch.",
      sender_name: "Jordan Lee", sender_email: "jordan.lee@company.com",
      subject: "Notes from Today's Project Meeting", sent_at: "Today, 4:05 PM",
      body_text: `Hi team,\n\nHere are the notes from today's project meeting.\n\nPlease review the summary and let me know if I missed anything. I also attached the action item list for this week.\n\nThanks,\nJordan`,
      link_label: "Open shared notes", link_url: "sharepoint.company.com/project-notes",
      attachment_name: "Action_Items.docx", is_phishing: 0, landing_page_type: "none",
      difficulty: "easy", scenario_type: "legitimate", channel: "email",
      question: { question_text: "What is the best assessment of this email?", choice_a: "It appears to be a normal internal message", choice_b: "It is clearly a credential harvesting attack", choice_c: "It is suspicious because it includes meeting notes", correct_choice: "A", red_flags: "No major red flags, expected context, familiar sender" },
    },
    {
      title: "Package Delivery Hold",
      prompt: "A text message says your package is on hold and asks you to confirm delivery details.",
      explanation: "Smishing works because many users are expecting a package and react quickly on mobile without verifying the sender or link.",
      sender_name: "Delivery Alerts", sender_email: "SMS Short Code 88421",
      subject: "Package On Hold", sent_at: "Today, 2:17 PM",
      body_text: `Your parcel is on hold due to an address verification issue.\n\nConfirm delivery details now to avoid return:\nparcel-redelivery-alerts.net/track`,
      link_label: "Confirm delivery details", link_url: "parcel-redelivery-alerts.net/track",
      attachment_name: "", is_phishing: 1, landing_page_type: "bank",
      difficulty: "easy", scenario_type: "smishing", channel: "sms",
      question: { question_text: "What is the most suspicious part of this text message?", choice_a: "It mentions a package", choice_b: "It pushes you to use an odd delivery domain right away", choice_c: "It was received on a phone", correct_choice: "B", red_flags: "Unexpected package notice, suspicious tracking domain, urgency" },
    },
    {
      title: "Payroll Update Text",
      prompt: "A mobile text claims payroll details must be updated today.",
      explanation: "Payroll themed smishing tries to use urgency and HR language to drive users to fake sign in pages.",
      sender_name: "Payroll Alert", sender_email: "SMS Short Code 74120",
      subject: "Payroll Profile Update Required", sent_at: "Today, 12:31 PM",
      body_text: `Payroll notice: Your direct deposit profile needs review before today's processing cut off.\n\nUpdate now:\ncompany-payrollverify.net`,
      link_label: "Update payroll profile", link_url: "company-payrollverify.net",
      attachment_name: "", is_phishing: 1, landing_page_type: "internal",
      difficulty: "medium", scenario_type: "smishing", channel: "sms",
      question: { question_text: "Why is this text suspicious?", choice_a: "Payroll messages always come by email only", choice_b: "It creates urgency and uses an unusual payroll domain", choice_c: "It mentions direct deposit", correct_choice: "B", red_flags: "Urgency, odd payroll domain, pressure to act quickly" },
    },
    {
      title: "MFA Push Bombing",
      prompt: "You receive repeated login approval prompts that you did not initiate.",
      explanation: "MFA fatigue attacks rely on repetition and confusion. Attackers hope the user eventually approves a prompt just to stop the alerts.",
      sender_name: "Identity Service", sender_email: "Push Notification",
      subject: "Sign in approval request", sent_at: "Today, 6:44 PM",
      body_text: `A sign in attempt is requesting approval from a device in another location.\n\nYou have received 5 approval prompts in the last 2 minutes.\n\nApprove sign in?`,
      link_label: "", link_url: "", attachment_name: "", is_phishing: 1, landing_page_type: "none",
      difficulty: "hard", scenario_type: "mfa_fatigue", channel: "push",
      question: { question_text: "What is the safest response?", choice_a: "Approve one prompt so the alerts stop", choice_b: "Ignore or deny the prompts and report the suspicious activity", choice_c: "Wait and approve later if they continue", correct_choice: "B", red_flags: "Unexpected MFA prompts, repeated approvals, unknown sign in attempt" },
    },
    {
      title: "Legitimate MFA Prompt",
      prompt: "You receive a single sign in approval after you just logged into a work application.",
      explanation: "This is a normal MFA event because it matches an action you just initiated and there is no abnormal context.",
      sender_name: "Identity Service", sender_email: "Push Notification",
      subject: "Approve sign in", sent_at: "Today, 8:04 AM",
      body_text: `A sign in approval is requested for your work account from your usual device in your normal location.\n\nApprove sign in?`,
      link_label: "", link_url: "", attachment_name: "", is_phishing: 0, landing_page_type: "none",
      difficulty: "easy", scenario_type: "authentication", channel: "push",
      question: { question_text: "Why is this more likely to be legitimate?", choice_a: "It matches an action you just initiated", choice_b: "All MFA prompts are suspicious", choice_c: "Push notifications are always safe", correct_choice: "A", red_flags: "Expected context, known device, matching user action" },
    },
    {
      title: "Help Desk Callback Scam",
      prompt: "You receive a voicemail style security notice asking you to call a number immediately.",
      explanation: "Vishing often uses fake support teams, urgent warnings, and callback numbers to create pressure and collect credentials or codes.",
      sender_name: "Security Operations", sender_email: "Voicemail Notification",
      subject: "Urgent security callback required", sent_at: "Today, 1:51 PM",
      body_text: `This is an urgent security notification.\n\nWe detected suspicious activity on your account. Call the security desk immediately at 1 800 555 0199 and have your verification code ready for validation.`,
      link_label: "", link_url: "", attachment_name: "Voicemail_Transcript.txt",
      is_phishing: 1, landing_page_type: "none", difficulty: "hard",
      scenario_type: "vishing", channel: "voice",
      question: { question_text: "What is the main red flag in this scenario?", choice_a: "It asks for a call back using pressure and asks you to have a code ready", choice_b: "It was left during the day", choice_c: "It references security activity", correct_choice: "A", red_flags: "Urgent callback, fake support, request for verification code" },
    },
    {
      title: "Dropped USB Drive",
      prompt: "A labeled USB drive is found in the office parking lot.",
      explanation: "USB baiting relies on curiosity and trust. Unknown removable media should never be inserted into a company system.",
      sender_name: "Physical Security Scenario", sender_email: "Office Environment",
      subject: "Found USB drive labeled Executive Salaries", sent_at: "Today, 7:55 AM",
      body_text: `You find a USB drive in the parking lot labeled Executive Salaries and Staff Bonuses.\n\nIt looks important and may belong to leadership.\n\nWhat should you do next?`,
      link_label: "", link_url: "", attachment_name: "Unknown USB Device",
      is_phishing: 1, landing_page_type: "none", difficulty: "medium",
      scenario_type: "usb_baiting", channel: "physical",
      question: { question_text: "What is the safest action?", choice_a: "Plug it into a company computer to identify the owner", choice_b: "Take it home and inspect it on a personal device", choice_c: "Turn it over to security or IT without plugging it in", correct_choice: "C", red_flags: "Unknown media, curiosity bait, physical social engineering" },
    },
    {
      title: "Benefits Open Enrollment Reminder",
      prompt: "HR sends a standard reminder about open enrollment with a normal internal portal link.",
      explanation: "This is a legitimate HR reminder. The domain matches the company environment and the request fits an expected process.",
      sender_name: "HR Operations", sender_email: "hr@company.com",
      subject: "Open Enrollment Reminder", sent_at: "Today, 8:35 AM",
      body_text: `Hello,\n\nOpen enrollment closes Friday at 5 PM.\n\nPlease use the employee portal to review your current selections and confirm your choices if needed.\n\nEmployee Portal:\nportal.company.com/benefits\n\nThank you,\nHR Operations`,
      link_label: "Open employee portal", link_url: "portal.company.com/benefits",
      attachment_name: "", is_phishing: 0, landing_page_type: "none",
      difficulty: "medium", scenario_type: "legitimate", channel: "email",
      question: { question_text: "What makes this email more likely to be legitimate?", choice_a: "It includes an internal company domain and expected HR context", choice_b: "All benefits emails are phishing", choice_c: "Every link is automatically suspicious", correct_choice: "A", red_flags: "Expected process, internal domain, no abnormal pressure" },
    },
    {
      title: "CEO Wire Transfer Request",
      prompt: "You receive an urgent email appearing to be from your CEO asking you to wire funds to a new vendor account before end of day.",
      explanation: "CEO fraud uses executive impersonation to pressure finance staff into bypassing normal approval workflows.",
      sender_name: "CEO - Michael Hargrove", sender_email: "m.hargrove@company-corp.net",
      subject: "Urgent: Wire Transfer Needed Today", sent_at: "Today, 11:07 AM",
      body_text: `Hi,\n\nI need you to process a wire transfer today for a new strategic vendor we are bringing on. This is time sensitive and needs to go out before 3 PM.\n\nAmount: $47,500\nAccount: First Merchant Bank\nRouting: 091000019\nAccount: 4472910038\n\nPlease handle this quietly for now as the deal is not public yet. I will explain more tomorrow.\n\nThanks,\nMichael`,
      link_label: "", link_url: "", attachment_name: "", is_phishing: 1, landing_page_type: "none",
      difficulty: "hard", scenario_type: "phishing", channel: "email",
      question: { question_text: "What should you do when you receive this email?", choice_a: "Process the transfer since it came from the CEO", choice_b: "Reply to the email to confirm the details before sending", choice_c: "Call the CEO directly using a known number to verify before taking any action", correct_choice: "C", red_flags: "Lookalike domain, secrecy request, urgency, bypasses approval process" },
    },
    {
      title: "Fake IT Helpdesk Call",
      prompt: "You receive a call from someone claiming to be IT support who says your computer has been sending error logs and they need remote access to fix it.",
      explanation: "Fake IT helpdesk calls use authority and technical language to create urgency. Granting remote access gives attackers full control of your system.",
      sender_name: "IT Support Desk", sender_email: "Inbound Phone Call",
      subject: "Remote Access Requested by IT", sent_at: "Today, 2:33 PM",
      body_text: `You receive a phone call.\n\nCaller: Hi, this is Derek from the IT support desk. We are seeing error reports coming from your machine and need to connect remotely to run a diagnostic before it causes data loss.\n\nCan you open your browser and go to remote-it-support-access.com so I can connect? It will only take a few minutes.\n\nThe caller has your name, department, and employee ID ready.`,
      link_label: "remote-it-support-access.com", link_url: "remote-it-support-access.com",
      attachment_name: "", is_phishing: 1, landing_page_type: "none",
      difficulty: "hard", scenario_type: "vishing", channel: "voice",
      question: { question_text: "What is the correct response to this call?", choice_a: "Go to the website and allow the connection since IT called you", choice_b: "Give them your employee ID to verify your identity", choice_c: "Hang up and contact IT through your company's official support portal or number", correct_choice: "C", red_flags: "Unsolicited remote access request, unofficial URL, urgency, social proof with personal details" },
    },
    {
      title: "QR Code at Conference",
      prompt: "A poster at a security conference invites you to scan a QR code to download free resources and enter a prize draw.",
      explanation: "QR code phishing called quishing is increasing because users rarely see the destination URL before being redirected.",
      sender_name: "Conference Organizer", sender_email: "Physical Poster",
      subject: "Scan for Free Security Resources", sent_at: "Today, 10:15 AM",
      body_text: `You notice a professional-looking poster at the conference registration area.\n\nIt reads:\nFREE Security Awareness Resources + Win a $500 Gift Card\n\nScan the QR code below to download your resource pack and enter the prize draw.\n\nThe QR code is printed neatly and the poster looks official.`,
      link_label: "QR destination: conf-resources-2024.net/download", link_url: "conf-resources-2024.net/download",
      attachment_name: "", is_phishing: 1, landing_page_type: "microsoft",
      difficulty: "medium", scenario_type: "phishing", channel: "physical",
      question: { question_text: "What is the safest way to handle this QR code?", choice_a: "Scan it since it is at a security conference and looks legitimate", choice_b: "Use a QR scanner that previews the URL before opening, then verify the domain", choice_c: "Share it with colleagues since free resources are always welcome", correct_choice: "B", red_flags: "Unknown domain, prize incentive, physical QR with no way to verify origin" },
    },
    {
      title: "LinkedIn Spear Phishing",
      prompt: "You receive a LinkedIn message from a recruiter offering a high salary role and asking you to complete a skills assessment via a link.",
      explanation: "Spear phishing via LinkedIn is highly effective because attackers research targets and use real company names.",
      sender_name: "Sarah Mitchell - Talent Acquisition", sender_email: "LinkedIn Message",
      subject: "Exclusive Opportunity - Senior Security Role", sent_at: "Today, 9:52 AM",
      body_text: `Hi,\n\nI came across your profile and was really impressed by your background in security awareness. We have an exclusive senior role opening that I think would be a great fit.\n\nCompensation: $145,000 base + equity\nLocation: Remote\n\nTo move things forward quickly, our team uses a pre-screening platform. Please complete the 10 minute skills assessment here:\n\ntalent-screening-portal.net/assess\n\nLooking forward to connecting.\n\nSarah Mitchell\nSenior Talent Acquisition\nCyberCore Technologies`,
      link_label: "Complete skills assessment", link_url: "talent-screening-portal.net/assess",
      attachment_name: "", is_phishing: 1, landing_page_type: "microsoft",
      difficulty: "hard", scenario_type: "phishing", channel: "email",
      question: { question_text: "What makes this message a likely spear phishing attempt?", choice_a: "Recruiters never contact people on LinkedIn", choice_b: "The assessment link uses a third party domain unrelated to the company named", choice_c: "The salary offered is too high to be real", correct_choice: "B", red_flags: "Third party assessment domain, urgency, compelling offer, unverified recruiter identity" },
    },
    {
      title: "Fake Software Update Popup",
      prompt: "While browsing the web you see a popup warning that your browser is critically out of date and you must update immediately to continue.",
      explanation: "Fake update popups are a common malware delivery method. The downloaded file installs malware, ransomware, or a remote access tool.",
      sender_name: "Browser Alert", sender_email: "In-browser Popup",
      subject: "Critical Browser Update Required", sent_at: "Today, 3:18 PM",
      body_text: `A large popup appears on your screen while browsing:\n\nWARNING: Your browser is critically out of date and your connection is not secure.\n\nYou must update immediately to continue browsing safely.\n\n[DOWNLOAD BROWSER UPDATE NOW]\n\nThe popup is difficult to close and keeps reappearing.`,
      link_label: "Download browser update", link_url: "browser-update-secure-patch.com/install",
      attachment_name: "BrowserUpdate_v112.exe", is_phishing: 1, landing_page_type: "none",
      difficulty: "medium", scenario_type: "phishing", channel: "email",
      question: { question_text: "What should you do when you see this popup?", choice_a: "Click download since an outdated browser is a real security risk", choice_b: "Close the tab and update your browser only through its official built-in update menu", choice_c: "Restart your computer and try the site again", correct_choice: "B", red_flags: "Unsolicited popup, third party download domain, pressure to act immediately, executable file" },
    },
    {
      title: "Deepfake Voice Authorization",
      prompt: "Your company's finance manager receives a voice message that sounds exactly like the CFO authorizing an urgent international transfer.",
      explanation: "AI voice cloning can replicate a person's voice from just a few minutes of public audio. Attackers use cloned voices to authorize financial transactions.",
      sender_name: "CFO - Voice Message", sender_email: "Voicemail System",
      subject: "Voice Authorization for Transfer", sent_at: "Today, 4:47 PM",
      body_text: `You listen to a voicemail on the shared finance line.\n\nThe voice sounds exactly like your CFO and says:\n\nHi, it is Richard. I am in back to back meetings all afternoon and cannot take calls. I need you to process an international wire of $92,000 to our overseas partner account. The details are in the email I just sent. Please process before 5 PM and do not loop in anyone else as I am handling the partner relationship directly. Thanks.\n\nThe voice tone, cadence, and name match your CFO perfectly.`,
      link_label: "", link_url: "", attachment_name: "Wire_Instructions.pdf",
      is_phishing: 1, landing_page_type: "none", difficulty: "hard",
      scenario_type: "vishing", channel: "voice",
      question: { question_text: "How should the finance manager respond to this voicemail?", choice_a: "Process the transfer since the voice is clearly the CFO", choice_b: "Send a confirmation email to the CFO before acting", choice_c: "Call the CFO back on their known direct number to verify before taking any action", correct_choice: "C", red_flags: "Secrecy request, urgency, voice only verification, large dollar amount" },
    },
    {
      title: "Google Login Clone",
      prompt: "You click a shared document link and are asked to sign in to your Google account on a page that looks exactly like the real Google login.",
      explanation: "Adversary in the middle phishing pages perfectly replicate login portals and can even bypass MFA by relaying credentials in real time.",
      sender_name: "Document Share Notification", sender_email: "notifications@gdrive-docshare.com",
      subject: "Someone shared a document with you", sent_at: "Today, 1:22 PM",
      body_text: `You received a shared document notification.\n\nAlex Thompson has shared a file with you:\nQ4 Budget Review - Final.xlsx\n\nClick below to open the document.\n\nThe link takes you to a page that looks identical to Google Sign In.\n\nThe URL in your browser reads: accounts.google.gdrive-docshare.com`,
      link_label: "Open shared document", link_url: "accounts.google.gdrive-docshare.com",
      attachment_name: "", is_phishing: 1, landing_page_type: "microsoft",
      difficulty: "hard", scenario_type: "phishing", channel: "email",
      question: { question_text: "What exposes this as a phishing page despite the convincing appearance?", choice_a: "Google never sends document share notifications", choice_b: "The URL domain is gdrive-docshare.com, not google.com", choice_c: "The file type is suspicious", correct_choice: "B", red_flags: "Subdomain spoofing, lookalike URL, credential harvest on realistic login clone" },
    },
    {
      title: "Legitimate IT Security Bulletin",
      prompt: "Your IT security team sends a company-wide bulletin about a new password policy requiring all staff to update passwords within 14 days.",
      explanation: "This is a legitimate IT communication using an internal sender address, directing users to the official portal, with a reasonable timeframe.",
      sender_name: "IT Security Team", sender_email: "security@company.com",
      subject: "Action Required: Password Policy Update", sent_at: "Today, 9:00 AM",
      body_text: `Hello,\n\nAs part of our annual security review, all staff are required to update their network passwords within the next 14 days.\n\nPlease log in to the employee portal using your current credentials and follow the prompts to set a new password.\n\nEmployee Portal: portal.company.com/password-update\n\nIf you have questions, contact the help desk at ext. 4400 or helpdesk@company.com.\n\nThank you,\nIT Security Team`,
      link_label: "Go to employee portal", link_url: "portal.company.com/password-update",
      attachment_name: "", is_phishing: 0, landing_page_type: "none",
      difficulty: "medium", scenario_type: "legitimate", channel: "email",
      question: { question_text: "Why is this email likely legitimate rather than a phishing attempt?", choice_a: "It uses an internal company domain, provides an alternative contact, and does not demand immediate action", choice_b: "All password reset emails are safe", choice_c: "The email was sent in the morning which is normal for IT", correct_choice: "A", red_flags: "Internal domain, reasonable timeframe, alternative contact provided, no credential request in email" },
    },
  ];

  for (const sim of simulations) {
    const { question, ...simData } = sim;
    const simulationId = upsertSimulation(db, simData);
    upsertQuestion(db, simulationId, question);
  }
}

module.exports = { seedSimulations };
